export const MENTION_CORPUS: readonly string[] = [
  '',
  '@',
  '@a',
  '@ada',
  '@ada.lovelace',
  '@ada-lovelace',
  '@ada_lovelace',
  '@scope/name',
  'hello @',
  'hello @ada',
  'hello  @ada',
  'hello\t@ada',
  'hello@ada',
  'hello @ada ',
  'hello @ada then more',
  'email me at ada@example.com',
  '@ada @grace',
  '@ada @',
  'line one\n@ada',
  'line one\nhello @ada',
  'line one\n@',
  '@ada\nline two',
  'a\n\n@grace',
  'punctuation, @grace',
  '(@grace',
  '@ada!',
  '@漢字',
  'plain text with no trigger',
  '   ',
  '\n',
  '/slash not a mention',
  '@ada/beta.v2-rc_1',
];
