//! Typed Rust access to AGI Workforce's canonical model registry.
//!
//! Model identity, capabilities, routes, harness status, and Auto policy are
//! generated from `packages/ai/model-registry`. Rust applications consume this
//! crate instead of maintaining provider/model tables or token-threshold
//! routing rules of their own.

use std::cmp::Ordering;
use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[path = "generated/model_registry.rs"]
mod generated;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TrustMode {
    Local,
    OnDevice,
    Byok,
    ManagedCloud,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RoutingProfile {
    Economy,
    Balanced,
    Premium,
}

impl RoutingProfile {
    fn as_key(self) -> &'static str {
        match self {
            Self::Economy => "economy",
            Self::Balanced => "balanced",
            Self::Premium => "premium",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RoutingTaskType {
    SimpleChat,
    General,
    Coding,
    Reasoning,
    CreativeWriting,
    Multimodal,
    LongContext,
    Research,
    Agentic,
    ComputerUse,
    ImageGeneration,
}

impl RoutingTaskType {
    fn as_key(self) -> &'static str {
        match self {
            Self::SimpleChat => "simple_chat",
            Self::General => "general",
            Self::Coding => "coding",
            Self::Reasoning => "reasoning",
            Self::CreativeWriting => "creative_writing",
            Self::Multimodal => "multimodal",
            Self::LongContext => "long_context",
            Self::Research => "research",
            Self::Agentic => "agentic",
            Self::ComputerUse => "computer-use",
            Self::ImageGeneration => "image_generation",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IntrinsicCapability {
    TextInput,
    ImageInput,
    AudioInput,
    VideoInput,
    TextOutput,
    ImageOutput,
    AudioOutput,
    VideoOutput,
    Streaming,
    StructuredOutput,
    FunctionCalling,
    Reasoning,
    ImageEditing,
    Realtime,
    Reranking,
    ToolSchemaSupport,
}

impl IntrinsicCapability {
    fn as_key(self) -> &'static str {
        match self {
            Self::TextInput => "textInput",
            Self::ImageInput => "imageInput",
            Self::AudioInput => "audioInput",
            Self::VideoInput => "videoInput",
            Self::TextOutput => "textOutput",
            Self::ImageOutput => "imageOutput",
            Self::AudioOutput => "audioOutput",
            Self::VideoOutput => "videoOutput",
            Self::Streaming => "streaming",
            Self::StructuredOutput => "structuredOutput",
            Self::FunctionCalling => "functionCalling",
            Self::Reasoning => "reasoning",
            Self::ImageEditing => "imageEditing",
            Self::Realtime => "realtime",
            Self::Reranking => "reranking",
            Self::ToolSchemaSupport => "toolSchemaSupport",
        }
    }
}

#[derive(Debug, Clone)]
pub struct AutoRoutingRequest<'a> {
    pub selection: Option<&'a str>,
    pub task_type: RoutingTaskType,
    pub subscription_tier: Option<&'a str>,
    pub trust_mode: TrustMode,
    pub current_model_key: Option<&'a str>,
    pub previous_task_type: Option<RoutingTaskType>,
    pub required_capabilities: &'a [IntrinsicCapability],
    /// Runtime-specific harness adapters that the caller can actually execute.
    /// `None` means the caller accepts every registry-declared harness.
    pub allowed_harnesses: Option<&'a [&'a str]>,
    /// Canonical surface/mode admission profile generated by the registry.
    pub runtime_profile_id: Option<&'a str>,
    pub us_only: bool,
    pub estimated_input_tokens: Option<u64>,
    pub estimated_output_tokens: Option<u64>,
}

impl Default for AutoRoutingRequest<'_> {
    fn default() -> Self {
        Self {
            selection: None,
            task_type: RoutingTaskType::General,
            subscription_tier: None,
            // Fail closed when a caller forgets to declare its trust boundary.
            trust_mode: TrustMode::Local,
            current_model_key: None,
            previous_task_type: None,
            required_capabilities: &[],
            allowed_harnesses: None,
            runtime_profile_id: None,
            us_only: false,
            estimated_input_tokens: None,
            estimated_output_tokens: None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RouteCacheClass {
    ProviderImplicitPromptCache,
    ProviderExplicitPromptCache,
    GatewayPromptCache,
    GatewayResponseCache,
    NoProviderCache,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RouteCommercialStatus {
    AgiDirect,
    CustomerByok,
    AuthorizedMarketplace,
    FreeCommercial,
    ExperimentalOnly,
    Blocked,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RoutePricing {
    pub input_per_million: Option<f64>,
    pub output_per_million: Option<f64>,
    pub cache_read_per_million: Option<f64>,
    pub cache_write_per_million: Option<f64>,
    pub cache_write_1h_per_million: Option<f64>,
    pub cache_class: RouteCacheClass,
    pub commercial_status: RouteCommercialStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RouteReason {
    Explicit,
    Continuity,
    PreferredSlot,
    FallbackSlot,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnavailableCode {
    UnknownSelection,
    UnknownTask,
    UnknownRuntimeProfile,
    RuntimeProfileUnavailable,
    RuntimeProfileMismatch,
    ExplicitModelIneligible,
    NoEligibleRoute,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AutoFallbackRoute {
    pub model_key: String,
    pub provider: String,
    pub provider_model_id: String,
    pub route_id: String,
    pub harness_id: String,
}

/// The concrete provider model a routing slot resolves to.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SlotModel {
    pub slot: String,
    pub model_key: String,
    pub provider: String,
    pub provider_model_id: String,
    pub route_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SelectedAutoRoute {
    pub requested_selection: String,
    pub requested_profile: Option<RoutingProfile>,
    pub effective_profile: Option<RoutingProfile>,
    pub task_type: RoutingTaskType,
    pub model_key: String,
    pub provider: String,
    pub provider_model_id: String,
    pub route_id: String,
    pub harness_id: String,
    pub fallbacks: Vec<AutoFallbackRoute>,
    pub reason: RouteReason,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnavailableAutoRoute {
    pub code: UnavailableCode,
    pub requested_selection: String,
    pub requested_profile: Option<RoutingProfile>,
    pub effective_profile: Option<RoutingProfile>,
    pub task_type: RoutingTaskType,
    pub reasons: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutoRouteDecision {
    Selected(SelectedAutoRoute),
    Unavailable(UnavailableAutoRoute),
}

#[derive(Debug, Error)]
pub enum RegistryError {
    #[error("generated model registry is invalid: {0}")]
    InvalidGeneratedRegistry(String),
}

#[derive(Debug, Deserialize)]
struct Registry {
    models: HashMap<String, RegistryModel>,
    #[serde(rename = "providerModelKeys")]
    provider_model_keys: HashMap<String, Vec<String>>,
    routes: HashMap<String, RegistryRoute>,
    harnesses: HashMap<String, RegistryHarness>,
    #[serde(rename = "runtimeProfiles")]
    runtime_profiles: HashMap<String, RegistryRuntimeProfile>,
    capabilities: HashMap<String, HashMap<String, Option<bool>>>,
    limits: HashMap<String, RegistryLimits>,
    policies: RegistryPolicies,
}

#[derive(Debug, Deserialize)]
struct RegistryModel {
    identity: RegistryIdentity,
    lifecycle: RegistryLifecycle,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryIdentity {
    provider: String,
}

#[derive(Debug, Deserialize)]
struct RegistryLifecycle {
    availability: String,
    deprecated: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryRoute {
    model_key: String,
    provider: String,
    provider_model_id: String,
    harness_id: String,
    trust_modes: Vec<TrustMode>,
    availability: String,
    selectable: bool,
    is_default: bool,
    cache_class: RouteCacheClass,
    commercial_status: RouteCommercialStatus,
    pricing: RegistryRoutePricing,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryRoutePricing {
    #[serde(default)]
    input_per_million: Option<f64>,
    #[serde(default)]
    output_per_million: Option<f64>,
    #[serde(default)]
    cache_read_per_million: Option<f64>,
    #[serde(default)]
    cache_write_per_million: Option<f64>,
    #[serde(default)]
    cache_write_1h_per_million: Option<f64>,
}

#[derive(Debug, Deserialize)]
struct RegistryHarness {
    #[serde(default)]
    features: HashMap<String, RegistryHarnessFeature>,
}

#[derive(Debug, Deserialize)]
struct RegistryHarnessFeature {
    implementation: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryRuntimeProfile {
    family: String,
    surface: String,
    execution_mode: String,
    trust_mode: TrustMode,
    status: String,
    #[serde(default)]
    features: HashMap<String, RegistryHarnessFeature>,
    allowed_harness_ids: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeProfile {
    pub id: String,
    pub family: String,
    pub surface: String,
    pub execution_mode: String,
    pub trust_mode: TrustMode,
    pub status: String,
    pub features: HashMap<String, String>,
    pub allowed_harness_ids: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryLimits {
    context_tokens: Option<u64>,
}

#[derive(Debug, Deserialize)]
struct RegistryPolicies {
    auto: AutoPolicy,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoPolicy {
    default_alias: String,
    fallback_slot: String,
    profile_order: Vec<RoutingProfile>,
    /// Complexity band per classified task for the self-routing `auto` alias.
    /// Unlisted tasks fall back to the alias's static profile.
    #[serde(default)]
    auto_profile_by_task: HashMap<String, RoutingProfile>,
    tier_maximum_profiles: HashMap<String, RoutingProfile>,
    tier_allowed_slots: HashMap<String, Vec<String>>,
    provider_policies: ProviderPolicies,
    aliases: HashMap<String, AutoAlias>,
    continuity: ContinuityPolicy,
    tasks: HashMap<String, AutoTaskPolicy>,
    slots: HashMap<String, AutoSlot>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProviderPolicies {
    us_only: ProviderExclusionPolicy,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProviderExclusionPolicy {
    allowed_tiers: Vec<String>,
    excluded_providers: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoAlias {
    profile: RoutingProfile,
    /// Single self-routing `auto`: derive the requested profile from the
    /// classified task instead of using `profile`. Absent → false (static).
    #[serde(default)]
    compute_profile: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContinuityPolicy {
    prefer_current_model_when_eligible: bool,
    prefer_current_route_for_cache: bool,
    reevaluate_on_task_change: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoTaskPolicy {
    required_capabilities: Vec<String>,
    required_harness_features: Vec<String>,
    minimum_context_tokens: Option<u64>,
    preferred_slots: HashMap<String, Vec<String>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoSlot {
    model_key: String,
}

static REGISTRY: OnceLock<Result<Registry, String>> = OnceLock::new();

fn registry() -> Result<&'static Registry, RegistryError> {
    match REGISTRY.get_or_init(|| {
        serde_json::from_str(generated::MODEL_REGISTRY_JSON).map_err(|error| error.to_string())
    }) {
        Ok(registry) => Ok(registry),
        Err(message) => Err(RegistryError::InvalidGeneratedRegistry(message.clone())),
    }
}

/// Return whether `selection` names an Auto routing profile rather than a
/// concrete provider model. Matching is case-insensitive because CLI/config
/// inputs are normalized the same way by [`resolve_auto_route`].
pub fn is_auto_routing_selection(selection: &str) -> bool {
    let Ok(registry) = registry() else {
        return false;
    };
    registry
        .policies
        .auto
        .aliases
        .contains_key(&selection.to_ascii_lowercase())
}

/// Return canonical model keys for a provider in registry-defined order.
/// Provider membership is generated from model identities, so Rust consumers
/// do not need to maintain provider-specific model tables.
pub fn model_keys_for_provider(provider: &str) -> Result<Option<Vec<String>>, RegistryError> {
    let registry = registry()?;
    Ok(registry.provider_model_keys.get(provider).cloned())
}

/// Resolve a routing slot to the concrete provider model the generated
/// registry assigns it.
///
/// Surfaces that call a single canonical model for a modality, voice
/// transcription is the first, read the slot instead of re-deriving the model
/// from per-surface tier heuristics that drift apart.
pub fn slot_model(slot: &str) -> Result<Option<SlotModel>, RegistryError> {
    let registry = registry()?;
    let Some(model_key) = registry
        .policies
        .auto
        .slots
        .get(slot)
        .map(|entry| entry.model_key.as_str())
    else {
        return Ok(None);
    };
    let Some(model) = registry.models.get(model_key) else {
        return Ok(None);
    };
    let route = registry
        .routes
        .iter()
        .filter(|(_, route)| {
            route.model_key == model_key && route.provider == model.identity.provider
        })
        .min_by(|(left, _), (right, _)| left.cmp(right));
    let Some((route_id, route)) = route else {
        return Ok(None);
    };
    Ok(Some(SlotModel {
        slot: slot.to_owned(),
        model_key: model_key.to_owned(),
        provider: route.provider.clone(),
        provider_model_id: route.provider_model_id.clone(),
        route_id: route_id.clone(),
    }))
}

/// Return the generated admission profile for a concrete surface/mode runtime.
pub fn runtime_profile(id: &str) -> Result<Option<RuntimeProfile>, RegistryError> {
    let registry = registry()?;
    Ok(registry
        .runtime_profiles
        .get(id)
        .map(|profile| RuntimeProfile {
            id: id.to_owned(),
            family: profile.family.clone(),
            surface: profile.surface.clone(),
            execution_mode: profile.execution_mode.clone(),
            trust_mode: profile.trust_mode,
            status: profile.status.clone(),
            features: profile
                .features
                .iter()
                .map(|(feature, state)| (feature.clone(), state.implementation.clone()))
                .collect(),
            allowed_harness_ids: profile.allowed_harness_ids.clone(),
        }))
}

struct Eligibility<'a> {
    route_id: Option<&'a str>,
    route: Option<&'a RegistryRoute>,
    ranked_routes: Vec<RankedRoute<'a>>,
    reasons: Vec<String>,
}

struct RankedRoute<'a> {
    route_id: &'a str,
    route: &'a RegistryRoute,
    expected_cents: f64,
}

const DEFAULT_AFFORDABILITY_OUTPUT_TOKENS: u64 = 1_000;
const TOKENS_PER_PRICED_MILLION: f64 = 1_000_000.0;
const CENTS_PER_USD: f64 = 100.0;

pub fn route_pricing(route_id: &str) -> Result<Option<RoutePricing>, RegistryError> {
    let registry = registry()?;
    Ok(registry.routes.get(route_id).map(|route| RoutePricing {
        input_per_million: route.pricing.input_per_million,
        output_per_million: route.pricing.output_per_million,
        cache_read_per_million: route.pricing.cache_read_per_million,
        cache_write_per_million: route.pricing.cache_write_per_million,
        cache_write_1h_per_million: route.pricing.cache_write_1h_per_million,
        cache_class: route.cache_class,
        commercial_status: route.commercial_status,
    }))
}

fn route_expected_cents(route: &RegistryRoute, request: &AutoRoutingRequest<'_>) -> f64 {
    let input_tokens = request.estimated_input_tokens.unwrap_or(0) as f64;
    let output_tokens = request
        .estimated_output_tokens
        .unwrap_or(DEFAULT_AFFORDABILITY_OUTPUT_TOKENS) as f64;
    let input_per_million = route.pricing.input_per_million.unwrap_or(0.0);
    let output_per_million = route.pricing.output_per_million.unwrap_or(0.0);
    let usd = (input_tokens * input_per_million + output_tokens * output_per_million)
        / TOKENS_PER_PRICED_MILLION;
    usd * CENTS_PER_USD
}

fn route_admission_rejections(
    registry: &Registry,
    route_id: &str,
    route: &RegistryRoute,
    task: &AutoTaskPolicy,
    request: &AutoRoutingRequest<'_>,
    runtime_profile: Option<&RegistryRuntimeProfile>,
) -> Vec<String> {
    let mut reasons = Vec::new();

    if route.commercial_status == RouteCommercialStatus::Blocked {
        reasons.push(format!("route {route_id} commercial status is blocked"));
    }
    if route.commercial_status == RouteCommercialStatus::ExperimentalOnly
        && request.trust_mode == TrustMode::ManagedCloud
    {
        reasons.push(format!(
            "route {route_id} is experimental_only and cannot serve managed traffic"
        ));
    }
    if !route.selectable || route.availability != "live" {
        reasons.push(format!("route {route_id} is not selectable"));
    }
    if let Some(allowed_harnesses) = request.allowed_harnesses
        && !allowed_harnesses.contains(&route.harness_id.as_str())
    {
        reasons.push(format!(
            "harness {} is not executable on the calling runtime",
            route.harness_id
        ));
    }
    if let Some(runtime_profile) = runtime_profile
        && !runtime_profile
            .allowed_harness_ids
            .contains(&route.harness_id)
    {
        reasons.push(format!(
            "harness {} is not admitted by runtime profile {}",
            route.harness_id,
            request.runtime_profile_id.unwrap_or_default()
        ));
    }

    let harness = registry.harnesses.get(&route.harness_id);
    for feature in &task.required_harness_features {
        let implementation = runtime_profile
            .and_then(|profile| profile.features.get(feature))
            .or_else(|| {
                if runtime_profile.is_some() {
                    None
                } else {
                    harness.and_then(|harness| harness.features.get(feature))
                }
            })
            .map(|feature| feature.implementation.as_str())
            .unwrap_or("undeclared");
        if implementation != "implemented" {
            if runtime_profile.is_some() {
                reasons.push(format!(
                    "runtime {} feature {feature} is {implementation}",
                    request.runtime_profile_id.unwrap_or_default()
                ));
            } else {
                reasons.push(format!(
                    "harness {} feature {feature} is {implementation}",
                    route.harness_id
                ));
            }
        }
    }

    reasons
}

fn rank_routes(mut candidates: Vec<RankedRoute<'_>>) -> Vec<RankedRoute<'_>> {
    candidates.sort_by(|left, right| {
        left.expected_cents
            .partial_cmp(&right.expected_cents)
            .unwrap_or(Ordering::Equal)
            .then_with(|| right.route.is_default.cmp(&left.route.is_default))
            .then_with(|| left.route_id.cmp(right.route_id))
    });
    candidates
}

fn same_model_fallbacks(
    selected_model_key: &str,
    ranked_routes: &[RankedRoute<'_>],
    seen_providers: &mut HashSet<String>,
) -> Vec<AutoFallbackRoute> {
    let mut fallbacks = Vec::new();
    for candidate in ranked_routes {
        if !seen_providers.insert(candidate.route.provider.clone()) {
            continue;
        }
        fallbacks.push(AutoFallbackRoute {
            model_key: selected_model_key.to_owned(),
            provider: candidate.route.provider.clone(),
            provider_model_id: candidate.route.provider_model_id.clone(),
            route_id: candidate.route_id.to_owned(),
            harness_id: candidate.route.harness_id.clone(),
        });
    }
    fallbacks
}

fn normalize_tier(tier: Option<&str>) -> &'static str {
    match tier.unwrap_or_default().to_ascii_lowercase().as_str() {
        "basic" | "hobby" => "free",
        "pro" | "team" => "pro",
        "max" | "max_15x" | "max-15x" | "max15x" | "max+" | "max_plus" | "max-plus" => "max",
        "enterprise" => "enterprise",
        "byok" => "byok",
        _ => "free",
    }
}

fn clamp_profile(
    requested: RoutingProfile,
    maximum: RoutingProfile,
    order: &[RoutingProfile],
) -> RoutingProfile {
    let requested_index = order.iter().position(|profile| *profile == requested);
    let maximum_index = order.iter().position(|profile| *profile == maximum);
    match (requested_index, maximum_index) {
        (Some(requested_index), Some(maximum_index)) => order[requested_index.min(maximum_index)],
        _ => maximum,
    }
}

/// Mirrors the TypeScript resolver's `tierAdmissionRejection`: a model reachable
/// only through slots no tier grants stays reachable, but a model whose slots are
/// all withheld from this tier is refused even when named explicitly.
fn tier_admission_rejection(policy: &AutoPolicy, model_key: &str, tier: &str) -> Option<String> {
    let tier_gated_slots = policy
        .tier_allowed_slots
        .values()
        .flatten()
        .map(String::as_str)
        .collect::<HashSet<_>>();
    let mut gated_slots = policy
        .slots
        .iter()
        .filter(|(slot_id, slot)| {
            tier_gated_slots.contains(slot_id.as_str()) && slot.model_key == model_key
        })
        .map(|(slot_id, _)| slot_id.as_str())
        .collect::<Vec<_>>();
    if gated_slots.is_empty() {
        return None;
    }
    gated_slots.sort_unstable();

    let fallback_slot = [policy.fallback_slot.clone()];
    let allowed_slots = policy
        .tier_allowed_slots
        .get(tier)
        .map(Vec::as_slice)
        .unwrap_or(&fallback_slot);
    if gated_slots
        .iter()
        .any(|slot_id| allowed_slots.iter().any(|allowed| allowed == slot_id))
    {
        return None;
    }

    Some(format!(
        "routing slot {} for model {model_key} is not allowed for tier {tier}",
        gated_slots.join(", ")
    ))
}

fn evaluate_eligibility<'a>(
    registry: &'a Registry,
    model_key: &str,
    task: &AutoTaskPolicy,
    request: &AutoRoutingRequest<'_>,
    runtime_profile: Option<&RegistryRuntimeProfile>,
) -> Eligibility<'a> {
    let mut reasons = Vec::new();
    let Some(model) = registry.models.get(model_key) else {
        return Eligibility {
            route_id: None,
            route: None,
            ranked_routes: Vec::new(),
            reasons: vec![format!("unknown model: {model_key}")],
        };
    };

    if model.lifecycle.availability != "live" {
        reasons.push(format!(
            "model {model_key} availability is {}",
            model.lifecycle.availability
        ));
    }
    if model.lifecycle.deprecated {
        reasons.push(format!("model {model_key} is deprecated"));
    }

    let tier = normalize_tier(request.subscription_tier);
    if let Some(rejection) = tier_admission_rejection(&registry.policies.auto, model_key, tier) {
        reasons.push(rejection);
    }
    let us_only = &registry.policies.auto.provider_policies.us_only;
    if request.us_only
        && us_only.allowed_tiers.iter().any(|allowed| allowed == tier)
        && us_only
            .excluded_providers
            .iter()
            .any(|provider| provider == &model.identity.provider)
    {
        reasons.push(format!(
            "provider {} is excluded by the US-only policy",
            model.identity.provider
        ));
    }

    let mut trust_mode_routes = registry
        .routes
        .iter()
        .filter(|(_, route)| {
            route.model_key == model_key && route.trust_modes.contains(&request.trust_mode)
        })
        .map(|(route_id, route)| (route_id.as_str(), route))
        .collect::<Vec<_>>();
    if trust_mode_routes.is_empty() {
        reasons.push(format!(
            "model {model_key} has no {} route",
            trust_mode_key(request.trust_mode)
        ));
        return Eligibility {
            route_id: None,
            route: None,
            ranked_routes: Vec::new(),
            reasons,
        };
    }
    trust_mode_routes.sort_by(|(left, _), (right, _)| left.cmp(right));

    let mut route_reasons = Vec::new();
    let mut admissible = Vec::new();
    for (route_id, route) in trust_mode_routes {
        let rejections =
            route_admission_rejections(registry, route_id, route, task, request, runtime_profile);
        if !rejections.is_empty() {
            route_reasons.extend(rejections);
            continue;
        }
        admissible.push(RankedRoute {
            route_id,
            route,
            expected_cents: route_expected_cents(route, request),
        });
    }

    let capabilities = registry.capabilities.get(model_key);
    let required = task
        .required_capabilities
        .iter()
        .map(String::as_str)
        .chain(
            request
                .required_capabilities
                .iter()
                .map(|capability| capability.as_key()),
        )
        .collect::<HashSet<_>>();
    for capability in required {
        if capabilities.and_then(|values| values.get(capability)) != Some(&Some(true)) {
            reasons.push(format!(
                "model {model_key} lacks intrinsic capability {capability}"
            ));
        }
    }

    if let Some(minimum) = task.minimum_context_tokens {
        let available = registry
            .limits
            .get(model_key)
            .and_then(|limits| limits.context_tokens)
            .unwrap_or(0);
        if available < minimum {
            reasons.push(format!(
                "model {model_key} does not meet {minimum} context tokens"
            ));
        }
    }

    if !reasons.is_empty() {
        reasons.extend(route_reasons);
        return Eligibility {
            route_id: None,
            route: None,
            ranked_routes: Vec::new(),
            reasons,
        };
    }

    let ranked_routes = rank_routes(admissible);
    let Some(selected) = ranked_routes.first() else {
        return Eligibility {
            route_id: None,
            route: None,
            ranked_routes: Vec::new(),
            reasons: route_reasons,
        };
    };
    Eligibility {
        route_id: Some(selected.route_id),
        route: Some(selected.route),
        ranked_routes,
        reasons,
    }
}

fn trust_mode_key(mode: TrustMode) -> &'static str {
    match mode {
        TrustMode::Local => "local",
        TrustMode::OnDevice => "on_device",
        TrustMode::Byok => "byok",
        TrustMode::ManagedCloud => "managed_cloud",
    }
}

struct SelectedRoute<'registry, 'model> {
    model_key: &'model str,
    eligibility: Eligibility<'registry>,
    reason: RouteReason,
    fallbacks: Vec<AutoFallbackRoute>,
}

fn selected_decision(
    request: &AutoRoutingRequest<'_>,
    requested_selection: &str,
    requested_profile: Option<RoutingProfile>,
    effective_profile: Option<RoutingProfile>,
    selected: SelectedRoute<'_, '_>,
) -> AutoRouteDecision {
    let route = selected
        .eligibility
        .route
        .expect("selected_decision requires an eligible route");
    let route_id = selected
        .eligibility
        .route_id
        .expect("selected_decision requires an eligible route id");
    AutoRouteDecision::Selected(SelectedAutoRoute {
        requested_selection: requested_selection.to_owned(),
        requested_profile,
        effective_profile,
        task_type: request.task_type,
        model_key: selected.model_key.to_owned(),
        provider: route.provider.clone(),
        provider_model_id: route.provider_model_id.clone(),
        route_id: route_id.to_owned(),
        harness_id: route.harness_id.clone(),
        fallbacks: selected.fallbacks,
        reason: selected.reason,
    })
}

const MAX_FALLBACK_ROUTES: usize = 4;

/// Every slot a fallback may draw on, best first, one entry per slot: the
/// request's own ordering, then the task's slots at every other profile in
/// policy order, then the policy fallback slot, then the tier's allowed slots
/// in their authored order restricted to slots some task policy names. A slot
/// no task lists is reachable only through a caller preference, and a failover
/// must not open that door. Admission is unchanged; this only decides how far
/// a failover may walk.
fn fallback_candidate_slots<'a>(
    policy: &'a AutoPolicy,
    task: &'a AutoTaskPolicy,
    preferred_slots: &'a [String],
    tier_slot_order: &'a [String],
) -> Vec<&'a str> {
    let policy_reachable = policy
        .tasks
        .values()
        .flat_map(|entry| entry.preferred_slots.values())
        .flatten()
        .map(String::as_str)
        .collect::<HashSet<_>>();
    let mut seen = HashSet::new();
    let mut ordered = Vec::new();
    let ladder = preferred_slots
        .iter()
        .chain(policy.profile_order.iter().flat_map(|profile| {
            task.preferred_slots
                .get(profile.as_key())
                .map(Vec::as_slice)
                .unwrap_or_default()
                .iter()
        }))
        .chain(std::iter::once(&policy.fallback_slot))
        .chain(
            tier_slot_order
                .iter()
                .filter(|slot_id| policy_reachable.contains(slot_id.as_str())),
        );
    for slot_id in ladder {
        if seen.insert(slot_id.as_str()) {
            ordered.push(slot_id.as_str());
        }
    }
    ordered
}

#[allow(clippy::too_many_arguments)]
fn build_provider_fallbacks(
    registry: &Registry,
    request: &AutoRoutingRequest<'_>,
    runtime_profile: Option<&RegistryRuntimeProfile>,
    task: &AutoTaskPolicy,
    policy: &AutoPolicy,
    allowed_slots: &HashSet<String>,
    preferred_slots: &[String],
    tier_slot_order: &[String],
    selected_model_key: &str,
    selected_provider: &str,
    selected_model_routes: &[RankedRoute<'_>],
) -> Vec<AutoFallbackRoute> {
    let candidate_slots = fallback_candidate_slots(policy, task, preferred_slots, tier_slot_order);

    let mut seen_models = HashSet::from([selected_model_key.to_owned()]);
    let mut seen_providers = HashSet::from([selected_provider.to_owned()]);
    let mut fallbacks = same_model_fallbacks(
        selected_model_key,
        selected_model_routes,
        &mut seen_providers,
    );

    for slot_id in candidate_slots {
        if !allowed_slots.contains(slot_id) {
            continue;
        }
        let Some(model_key) = policy
            .slots
            .get(slot_id)
            .map(|slot| slot.model_key.as_str())
        else {
            continue;
        };
        if !seen_models.insert(model_key.to_owned()) {
            continue;
        }

        let eligibility = evaluate_eligibility(registry, model_key, task, request, runtime_profile);
        let (Some(route_id), Some(route)) = (eligibility.route_id, eligibility.route) else {
            continue;
        };
        if !seen_providers.insert(route.provider.clone()) {
            continue;
        }

        fallbacks.push(AutoFallbackRoute {
            model_key: model_key.to_owned(),
            provider: route.provider.clone(),
            provider_model_id: route.provider_model_id.clone(),
            route_id: route_id.to_owned(),
            harness_id: route.harness_id.clone(),
        });
    }

    fallbacks.truncate(MAX_FALLBACK_ROUTES);
    fallbacks
}

/// Resolve an explicit model or Auto alias using the generated registry policy.
///
/// The resolver never crosses trust modes: a route is eligible only when its
/// generated route declaration includes the caller's exact trust boundary.
pub fn resolve_auto_route(
    request: &AutoRoutingRequest<'_>,
) -> Result<AutoRouteDecision, RegistryError> {
    Ok(resolve_against(registry()?, request))
}

fn resolve_against(registry: &Registry, request: &AutoRoutingRequest<'_>) -> AutoRouteDecision {
    let policy = &registry.policies.auto;
    let requested_selection = request
        .selection
        .unwrap_or(&policy.default_alias)
        .to_ascii_lowercase();
    let runtime_profile = if let Some(profile_id) = request.runtime_profile_id {
        let Some(profile) = registry.runtime_profiles.get(profile_id) else {
            return AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::UnknownRuntimeProfile,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!("unknown runtime profile: {profile_id}")],
            });
        };
        if profile.status != "implemented" {
            return AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::RuntimeProfileUnavailable,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!(
                    "runtime profile {profile_id} is {}",
                    profile.status
                )],
            });
        }
        if profile.trust_mode != request.trust_mode {
            return AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::RuntimeProfileMismatch,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!(
                    "runtime profile {profile_id} requires {}, not {}",
                    trust_mode_key(profile.trust_mode),
                    trust_mode_key(request.trust_mode)
                )],
            });
        }
        Some(profile)
    } else {
        None
    };
    let Some(task) = policy.tasks.get(request.task_type.as_key()) else {
        return AutoRouteDecision::Unavailable(UnavailableAutoRoute {
            code: UnavailableCode::UnknownTask,
            requested_selection,
            requested_profile: None,
            effective_profile: None,
            task_type: request.task_type,
            reasons: vec![format!(
                "unknown routing task: {}",
                request.task_type.as_key()
            )],
        });
    };

    let Some(alias) = policy.aliases.get(&requested_selection) else {
        if !registry.models.contains_key(&requested_selection) {
            return AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::UnknownSelection,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!(
                    "unknown model selection: {}",
                    request.selection.unwrap_or_default()
                )],
            });
        }
        let eligibility = evaluate_eligibility(
            registry,
            &requested_selection,
            task,
            request,
            runtime_profile,
        );
        return if let Some(route) = eligibility.route {
            let mut seen_providers = HashSet::from([route.provider.clone()]);
            let fallbacks = same_model_fallbacks(
                &requested_selection,
                &eligibility.ranked_routes,
                &mut seen_providers,
            );
            selected_decision(
                request,
                &requested_selection,
                None,
                None,
                SelectedRoute {
                    model_key: &requested_selection,
                    eligibility,
                    reason: RouteReason::Explicit,
                    fallbacks,
                },
            )
        } else {
            AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::ExplicitModelIneligible,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: eligibility.reasons,
            })
        };
    };

    let tier = normalize_tier(request.subscription_tier);
    let maximum_profile = policy
        .tier_maximum_profiles
        .get(tier)
        .copied()
        .unwrap_or(RoutingProfile::Economy);
    // Single self-routing `auto`: derive the requested band from the classified
    // task ("hi" → economy, hard coding → premium); other aliases keep their
    // static profile. The tier clamp below still narrows it to reachable slots.
    let requested_profile = if alias.compute_profile {
        policy
            .auto_profile_by_task
            .get(request.task_type.as_key())
            .copied()
            .unwrap_or(alias.profile)
    } else {
        alias.profile
    };
    let effective_profile =
        clamp_profile(requested_profile, maximum_profile, &policy.profile_order);
    let tier_slot_order = policy
        .tier_allowed_slots
        .get(tier)
        .cloned()
        .unwrap_or_else(|| vec![policy.fallback_slot.clone()]);
    let allowed_slots = tier_slot_order.iter().cloned().collect::<HashSet<_>>();
    let preferred_slots = task
        .preferred_slots
        .get(effective_profile.as_key())
        .map(Vec::as_slice)
        .unwrap_or_default();

    if let Some(current_model_key) = request.current_model_key
        && policy.continuity.prefer_current_model_when_eligible
        && (!policy.continuity.reevaluate_on_task_change
            || request.previous_task_type == Some(request.task_type)
            || (policy.continuity.prefer_current_route_for_cache
                && preferred_slots.iter().any(|slot_id| {
                    allowed_slots.contains(slot_id)
                        && policy
                            .slots
                            .get(slot_id)
                            .is_some_and(|slot| slot.model_key == current_model_key)
                })))
    {
        let eligibility =
            evaluate_eligibility(registry, current_model_key, task, request, runtime_profile);
        if let Some(route) = eligibility.route {
            let selected_provider = route.provider.clone();
            let fallbacks = build_provider_fallbacks(
                registry,
                request,
                runtime_profile,
                task,
                policy,
                &allowed_slots,
                preferred_slots,
                &tier_slot_order,
                current_model_key,
                &selected_provider,
                &eligibility.ranked_routes,
            );
            return selected_decision(
                request,
                &requested_selection,
                Some(requested_profile),
                Some(effective_profile),
                SelectedRoute {
                    model_key: current_model_key,
                    eligibility,
                    reason: RouteReason::Continuity,
                    fallbacks,
                },
            );
        }
    }

    let mut reasons = Vec::new();
    for slot_id in preferred_slots {
        if !allowed_slots.contains(slot_id) {
            reasons.push(format!(
                "routing slot {slot_id} is not allowed for tier {tier}"
            ));
            continue;
        }
        let Some(model_key) = policy
            .slots
            .get(slot_id)
            .map(|slot| slot.model_key.as_str())
        else {
            reasons.push(format!("routing slot {slot_id} is missing"));
            continue;
        };
        let eligibility = evaluate_eligibility(registry, model_key, task, request, runtime_profile);
        if let Some(route) = eligibility.route {
            let selected_provider = route.provider.clone();
            let fallbacks = build_provider_fallbacks(
                registry,
                request,
                runtime_profile,
                task,
                policy,
                &allowed_slots,
                preferred_slots,
                &tier_slot_order,
                model_key,
                &selected_provider,
                &eligibility.ranked_routes,
            );
            return selected_decision(
                request,
                &requested_selection,
                Some(requested_profile),
                Some(effective_profile),
                SelectedRoute {
                    model_key,
                    eligibility,
                    reason: RouteReason::PreferredSlot,
                    fallbacks,
                },
            );
        }
        reasons.extend(eligibility.reasons);
    }

    if !preferred_slots.contains(&policy.fallback_slot)
        && allowed_slots.contains(&policy.fallback_slot)
        && let Some(model_key) = policy
            .slots
            .get(&policy.fallback_slot)
            .map(|slot| slot.model_key.as_str())
    {
        let eligibility = evaluate_eligibility(registry, model_key, task, request, runtime_profile);
        if let Some(route) = eligibility.route {
            let selected_provider = route.provider.clone();
            let fallbacks = build_provider_fallbacks(
                registry,
                request,
                runtime_profile,
                task,
                policy,
                &allowed_slots,
                preferred_slots,
                &tier_slot_order,
                model_key,
                &selected_provider,
                &eligibility.ranked_routes,
            );
            return selected_decision(
                request,
                &requested_selection,
                Some(requested_profile),
                Some(effective_profile),
                SelectedRoute {
                    model_key,
                    eligibility,
                    reason: RouteReason::FallbackSlot,
                    fallbacks,
                },
            );
        }
        reasons.extend(eligibility.reasons);
    }

    let mut seen = HashSet::new();
    reasons.retain(|reason| seen.insert(reason.clone()));
    AutoRouteDecision::Unavailable(UnavailableAutoRoute {
        code: UnavailableCode::NoEligibleRoute,
        requested_selection,
        requested_profile: Some(requested_profile),
        effective_profile: Some(effective_profile),
        task_type: request.task_type,
        reasons,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const ALL_TASK_TYPES: [RoutingTaskType; 11] = [
        RoutingTaskType::SimpleChat,
        RoutingTaskType::General,
        RoutingTaskType::Coding,
        RoutingTaskType::Reasoning,
        RoutingTaskType::CreativeWriting,
        RoutingTaskType::Multimodal,
        RoutingTaskType::LongContext,
        RoutingTaskType::Research,
        RoutingTaskType::Agentic,
        RoutingTaskType::ComputerUse,
        RoutingTaskType::ImageGeneration,
    ];

    fn registry_declaring_only_general() -> Registry {
        serde_json::from_str(
            r#"{
              "models": {},
              "providerModelKeys": {},
              "routes": {},
              "harnesses": {},
              "runtimeProfiles": {},
              "capabilities": {},
              "limits": {},
              "policies": {
                "auto": {
                  "defaultAlias": "auto",
                  "fallbackSlot": "workhorse_general",
                  "profileOrder": ["economy", "balanced", "premium"],
                  "tierMaximumProfiles": { "free": "economy" },
                  "tierAllowedSlots": { "free": ["workhorse_general"] },
                  "providerPolicies": { "usOnly": { "allowedTiers": [], "excludedProviders": [] } },
                  "aliases": { "auto": { "profile": "balanced", "computeProfile": true } },
                  "continuity": {
                    "preferCurrentModelWhenEligible": true,
                    "preferCurrentRouteForCache": true,
                    "reevaluateOnTaskChange": true
                  },
                  "tasks": {
                    "general": {
                      "requiredCapabilities": [],
                      "requiredHarnessFeatures": [],
                      "minimumContextTokens": null,
                      "preferredSlots": {}
                    }
                  },
                  "slots": {}
                }
              }
            }"#,
        )
        .expect("fixture registry should deserialize")
    }

    #[test]
    fn a_task_the_curated_policy_omits_is_unavailable_not_a_panic() {
        let registry = registry_declaring_only_general();
        let request = AutoRoutingRequest {
            selection: Some("auto"),
            task_type: RoutingTaskType::Coding,
            ..Default::default()
        };

        let AutoRouteDecision::Unavailable(unavailable) = resolve_against(&registry, &request)
        else {
            panic!("a task with no curated policy must not resolve to a route");
        };
        assert_eq!(unavailable.code, UnavailableCode::UnknownTask);
        assert_eq!(unavailable.reasons, vec!["unknown routing task: coding"]);
    }

    #[test]
    fn the_voice_transcription_slot_resolves_to_a_live_provider_model() {
        let resolved = slot_model("voice_transcription")
            .expect("generated registry should load")
            .expect("the voice transcription slot must resolve to a route");
        let registry = registry().expect("generated registry should load");
        let expected_key = registry
            .policies
            .auto
            .slots
            .get("voice_transcription")
            .expect("slot must exist")
            .model_key
            .clone();
        assert_eq!(resolved.model_key, expected_key);
        assert_eq!(
            resolved.provider,
            registry.models[&expected_key].identity.provider
        );
        assert!(!resolved.provider_model_id.is_empty());
        assert!(!registry.models[&expected_key].lifecycle.deprecated);
    }

    #[test]
    fn an_unknown_slot_resolves_to_nothing() {
        assert_eq!(
            slot_model("fixture_slot_that_does_not_exist").expect("registry should load"),
            None
        );
    }

    #[test]
    fn every_task_type_the_resolver_accepts_has_a_curated_policy() {
        let registry = registry().expect("generated registry should load");
        let missing = ALL_TASK_TYPES
            .into_iter()
            .filter(|task| !registry.policies.auto.tasks.contains_key(task.as_key()))
            .map(RoutingTaskType::as_key)
            .collect::<Vec<_>>();
        assert!(
            missing.is_empty(),
            "routing-policies.json declares no auto.tasks entry for {missing:?}"
        );
    }
}
