//! Typed Rust access to AGI Workforce's canonical model registry.
//!
//! Model identity, capabilities, routes, harness status, and Auto policy are
//! generated from `packages/ai/model-registry`. Rust applications consume this
//! crate instead of maintaining provider/model tables or token-threshold
//! routing rules of their own.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[path = "generated/model_registry.rs"]
mod generated;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TrustMode {
    Local,
    OnDevice,
    Byok,
    ManagedCloud,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RoutingProfile {
    Economy,
    Balanced,
    Premium,
}

impl RoutingProfile {
    fn as_key(self) -> &'static str {
        match self {
            Self::Economy => "economy",
            Self::Balanced => "balanced",
            Self::Premium => "premium",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RoutingTaskType {
    SimpleChat,
    General,
    Coding,
    Reasoning,
    CreativeWriting,
    Multimodal,
    LongContext,
    Research,
    Agentic,
    ComputerUse,
    ImageGeneration,
}

impl RoutingTaskType {
    fn as_key(self) -> &'static str {
        match self {
            Self::SimpleChat => "simple_chat",
            Self::General => "general",
            Self::Coding => "coding",
            Self::Reasoning => "reasoning",
            Self::CreativeWriting => "creative_writing",
            Self::Multimodal => "multimodal",
            Self::LongContext => "long_context",
            Self::Research => "research",
            Self::Agentic => "agentic",
            Self::ComputerUse => "computer-use",
            Self::ImageGeneration => "image_generation",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IntrinsicCapability {
    TextInput,
    ImageInput,
    AudioInput,
    VideoInput,
    TextOutput,
    ImageOutput,
    AudioOutput,
    VideoOutput,
    Streaming,
    StructuredOutput,
    FunctionCalling,
    Reasoning,
}

impl IntrinsicCapability {
    fn as_key(self) -> &'static str {
        match self {
            Self::TextInput => "textInput",
            Self::ImageInput => "imageInput",
            Self::AudioInput => "audioInput",
            Self::VideoInput => "videoInput",
            Self::TextOutput => "textOutput",
            Self::ImageOutput => "imageOutput",
            Self::AudioOutput => "audioOutput",
            Self::VideoOutput => "videoOutput",
            Self::Streaming => "streaming",
            Self::StructuredOutput => "structuredOutput",
            Self::FunctionCalling => "functionCalling",
            Self::Reasoning => "reasoning",
        }
    }
}

#[derive(Debug, Clone)]
pub struct AutoRoutingRequest<'a> {
    pub selection: Option<&'a str>,
    pub task_type: RoutingTaskType,
    pub subscription_tier: Option<&'a str>,
    pub trust_mode: TrustMode,
    pub current_model_key: Option<&'a str>,
    pub previous_task_type: Option<RoutingTaskType>,
    pub required_capabilities: &'a [IntrinsicCapability],
    /// Runtime-specific harness adapters that the caller can actually execute.
    /// `None` means the caller accepts every registry-declared harness.
    pub allowed_harnesses: Option<&'a [&'a str]>,
    /// Canonical surface/mode admission profile generated by the registry.
    pub runtime_profile_id: Option<&'a str>,
    pub us_only: bool,
}

impl Default for AutoRoutingRequest<'_> {
    fn default() -> Self {
        Self {
            selection: None,
            task_type: RoutingTaskType::General,
            subscription_tier: None,
            // Fail closed when a caller forgets to declare its trust boundary.
            trust_mode: TrustMode::Local,
            current_model_key: None,
            previous_task_type: None,
            required_capabilities: &[],
            allowed_harnesses: None,
            runtime_profile_id: None,
            us_only: false,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RouteReason {
    Explicit,
    Continuity,
    PreferredSlot,
    FallbackSlot,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnavailableCode {
    UnknownSelection,
    UnknownRuntimeProfile,
    RuntimeProfileUnavailable,
    RuntimeProfileMismatch,
    ExplicitModelIneligible,
    NoEligibleRoute,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AutoFallbackRoute {
    pub model_key: String,
    pub provider: String,
    pub provider_model_id: String,
    pub route_id: String,
    pub harness_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SelectedAutoRoute {
    pub requested_selection: String,
    pub requested_profile: Option<RoutingProfile>,
    pub effective_profile: Option<RoutingProfile>,
    pub task_type: RoutingTaskType,
    pub model_key: String,
    pub provider: String,
    pub provider_model_id: String,
    pub route_id: String,
    pub harness_id: String,
    /// Ordered, policy-derived routes on distinct providers. Explicit model
    /// selections intentionally leave this empty.
    pub fallbacks: Vec<AutoFallbackRoute>,
    pub reason: RouteReason,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnavailableAutoRoute {
    pub code: UnavailableCode,
    pub requested_selection: String,
    pub requested_profile: Option<RoutingProfile>,
    pub effective_profile: Option<RoutingProfile>,
    pub task_type: RoutingTaskType,
    pub reasons: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutoRouteDecision {
    Selected(SelectedAutoRoute),
    Unavailable(UnavailableAutoRoute),
}

#[derive(Debug, Error)]
pub enum RegistryError {
    #[error("generated model registry is invalid: {0}")]
    InvalidGeneratedRegistry(String),
}

#[derive(Debug, Deserialize)]
struct Registry {
    models: HashMap<String, RegistryModel>,
    #[serde(rename = "providerModelKeys")]
    provider_model_keys: HashMap<String, Vec<String>>,
    routes: HashMap<String, RegistryRoute>,
    harnesses: HashMap<String, RegistryHarness>,
    #[serde(rename = "runtimeProfiles")]
    runtime_profiles: HashMap<String, RegistryRuntimeProfile>,
    capabilities: HashMap<String, HashMap<String, bool>>,
    limits: HashMap<String, RegistryLimits>,
    policies: RegistryPolicies,
}

#[derive(Debug, Deserialize)]
struct RegistryModel {
    identity: RegistryIdentity,
    lifecycle: RegistryLifecycle,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryIdentity {
    provider: String,
}

#[derive(Debug, Deserialize)]
struct RegistryLifecycle {
    availability: String,
    deprecated: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryRoute {
    model_key: String,
    provider: String,
    provider_model_id: String,
    harness_id: String,
    trust_modes: Vec<TrustMode>,
    availability: String,
    selectable: bool,
}

#[derive(Debug, Deserialize)]
struct RegistryHarness {
    #[serde(default)]
    features: HashMap<String, RegistryHarnessFeature>,
}

#[derive(Debug, Deserialize)]
struct RegistryHarnessFeature {
    implementation: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryRuntimeProfile {
    family: String,
    surface: String,
    execution_mode: String,
    trust_mode: TrustMode,
    status: String,
    #[serde(default)]
    features: HashMap<String, RegistryHarnessFeature>,
    allowed_harness_ids: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeProfile {
    pub id: String,
    pub family: String,
    pub surface: String,
    pub execution_mode: String,
    pub trust_mode: TrustMode,
    pub status: String,
    pub features: HashMap<String, String>,
    pub allowed_harness_ids: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegistryLimits {
    context_tokens: Option<u64>,
}

#[derive(Debug, Deserialize)]
struct RegistryPolicies {
    auto: AutoPolicy,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoPolicy {
    default_alias: String,
    fallback_slot: String,
    profile_order: Vec<RoutingProfile>,
    /// Complexity band per classified task for the self-routing `auto` alias.
    /// Unlisted tasks fall back to the alias's static profile.
    #[serde(default)]
    auto_profile_by_task: HashMap<String, RoutingProfile>,
    tier_maximum_profiles: HashMap<String, RoutingProfile>,
    tier_allowed_slots: HashMap<String, Vec<String>>,
    provider_policies: ProviderPolicies,
    aliases: HashMap<String, AutoAlias>,
    continuity: ContinuityPolicy,
    tasks: HashMap<String, AutoTaskPolicy>,
    slots: HashMap<String, AutoSlot>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProviderPolicies {
    us_only: ProviderExclusionPolicy,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProviderExclusionPolicy {
    allowed_tiers: Vec<String>,
    excluded_providers: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoAlias {
    profile: RoutingProfile,
    /// Single self-routing `auto`: derive the requested profile from the
    /// classified task instead of using `profile`. Absent → false (static).
    #[serde(default)]
    compute_profile: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContinuityPolicy {
    prefer_current_model_when_eligible: bool,
    prefer_current_route_for_cache: bool,
    reevaluate_on_task_change: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoTaskPolicy {
    required_capabilities: Vec<String>,
    required_harness_features: Vec<String>,
    minimum_context_tokens: Option<u64>,
    preferred_slots: HashMap<String, Vec<String>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AutoSlot {
    model_key: String,
}

static REGISTRY: OnceLock<Result<Registry, String>> = OnceLock::new();

fn registry() -> Result<&'static Registry, RegistryError> {
    match REGISTRY.get_or_init(|| {
        serde_json::from_str(generated::MODEL_REGISTRY_JSON).map_err(|error| error.to_string())
    }) {
        Ok(registry) => Ok(registry),
        Err(message) => Err(RegistryError::InvalidGeneratedRegistry(message.clone())),
    }
}

/// Return whether `selection` names an Auto routing profile rather than a
/// concrete provider model. Matching is case-insensitive because CLI/config
/// inputs are normalized the same way by [`resolve_auto_route`].
pub fn is_auto_routing_selection(selection: &str) -> bool {
    let Ok(registry) = registry() else {
        return false;
    };
    registry
        .policies
        .auto
        .aliases
        .contains_key(&selection.to_ascii_lowercase())
}

/// Return canonical model keys for a provider in registry-defined order.
/// Provider membership is generated from model identities, so Rust consumers
/// do not need to maintain provider-specific model tables.
pub fn model_keys_for_provider(provider: &str) -> Result<Option<Vec<String>>, RegistryError> {
    let registry = registry()?;
    Ok(registry.provider_model_keys.get(provider).cloned())
}

/// Return the generated admission profile for a concrete surface/mode runtime.
pub fn runtime_profile(id: &str) -> Result<Option<RuntimeProfile>, RegistryError> {
    let registry = registry()?;
    Ok(registry
        .runtime_profiles
        .get(id)
        .map(|profile| RuntimeProfile {
            id: id.to_owned(),
            family: profile.family.clone(),
            surface: profile.surface.clone(),
            execution_mode: profile.execution_mode.clone(),
            trust_mode: profile.trust_mode,
            status: profile.status.clone(),
            features: profile
                .features
                .iter()
                .map(|(feature, state)| (feature.clone(), state.implementation.clone()))
                .collect(),
            allowed_harness_ids: profile.allowed_harness_ids.clone(),
        }))
}

struct Eligibility<'a> {
    route_id: Option<&'a str>,
    route: Option<&'a RegistryRoute>,
    reasons: Vec<String>,
}

fn normalize_tier(tier: Option<&str>) -> &'static str {
    match tier.unwrap_or_default().to_ascii_lowercase().as_str() {
        "pro" | "team" => "pro",
        "max" | "max+" | "max_plus" | "max-plus" => "max",
        "enterprise" => "enterprise",
        "byok" => "byok",
        _ => "free",
    }
}

fn clamp_profile(
    requested: RoutingProfile,
    maximum: RoutingProfile,
    order: &[RoutingProfile],
) -> RoutingProfile {
    let requested_index = order.iter().position(|profile| *profile == requested);
    let maximum_index = order.iter().position(|profile| *profile == maximum);
    match (requested_index, maximum_index) {
        (Some(requested_index), Some(maximum_index)) => order[requested_index.min(maximum_index)],
        _ => maximum,
    }
}

fn evaluate_eligibility<'a>(
    registry: &'a Registry,
    model_key: &str,
    task: &AutoTaskPolicy,
    request: &AutoRoutingRequest<'_>,
    runtime_profile: Option<&RegistryRuntimeProfile>,
) -> Eligibility<'a> {
    let mut reasons = Vec::new();
    let Some(model) = registry.models.get(model_key) else {
        return Eligibility {
            route_id: None,
            route: None,
            reasons: vec![format!("unknown model: {model_key}")],
        };
    };

    if model.lifecycle.availability != "live" {
        reasons.push(format!(
            "model {model_key} availability is {}",
            model.lifecycle.availability
        ));
    }
    if model.lifecycle.deprecated {
        reasons.push(format!("model {model_key} is deprecated"));
    }

    let tier = normalize_tier(request.subscription_tier);
    let us_only = &registry.policies.auto.provider_policies.us_only;
    if request.us_only
        && us_only.allowed_tiers.iter().any(|allowed| allowed == tier)
        && us_only
            .excluded_providers
            .iter()
            .any(|provider| provider == &model.identity.provider)
    {
        reasons.push(format!(
            "provider {} is excluded by the US-only policy",
            model.identity.provider
        ));
    }

    let route_entry = registry.routes.iter().find(|(_, route)| {
        route.model_key == model_key && route.trust_modes.contains(&request.trust_mode)
    });
    let Some((route_id, route)) = route_entry else {
        reasons.push(format!(
            "model {model_key} has no {} route",
            trust_mode_key(request.trust_mode)
        ));
        return Eligibility {
            route_id: None,
            route: None,
            reasons,
        };
    };

    if !route.selectable || route.availability != "live" {
        reasons.push(format!("route {route_id} is not selectable"));
    }
    if let Some(allowed_harnesses) = request.allowed_harnesses
        && !allowed_harnesses.contains(&route.harness_id.as_str())
    {
        reasons.push(format!(
            "harness {} is not executable on the calling runtime",
            route.harness_id
        ));
    }
    if let Some(runtime_profile) = runtime_profile
        && !runtime_profile
            .allowed_harness_ids
            .contains(&route.harness_id)
    {
        reasons.push(format!(
            "harness {} is not admitted by runtime profile {}",
            route.harness_id,
            request.runtime_profile_id.unwrap_or_default()
        ));
    }

    let capabilities = registry.capabilities.get(model_key);
    let required = task
        .required_capabilities
        .iter()
        .map(String::as_str)
        .chain(
            request
                .required_capabilities
                .iter()
                .map(|capability| capability.as_key()),
        )
        .collect::<HashSet<_>>();
    for capability in required {
        if capabilities.and_then(|values| values.get(capability)) != Some(&true) {
            reasons.push(format!(
                "model {model_key} lacks intrinsic capability {capability}"
            ));
        }
    }

    if let Some(minimum) = task.minimum_context_tokens {
        let available = registry
            .limits
            .get(model_key)
            .and_then(|limits| limits.context_tokens)
            .unwrap_or(0);
        if available < minimum {
            reasons.push(format!(
                "model {model_key} does not meet {minimum} context tokens"
            ));
        }
    }

    let harness = registry.harnesses.get(&route.harness_id);
    for feature in &task.required_harness_features {
        let implementation = runtime_profile
            .and_then(|profile| profile.features.get(feature))
            .or_else(|| {
                if runtime_profile.is_some() {
                    None
                } else {
                    harness.and_then(|harness| harness.features.get(feature))
                }
            })
            .map(|feature| feature.implementation.as_str())
            .unwrap_or("undeclared");
        if implementation != "implemented" {
            if runtime_profile.is_some() {
                reasons.push(format!(
                    "runtime {} feature {feature} is {implementation}",
                    request.runtime_profile_id.unwrap_or_default()
                ));
            } else {
                reasons.push(format!(
                    "harness {} feature {feature} is {implementation}",
                    route.harness_id
                ));
            }
        }
    }

    if reasons.is_empty() {
        Eligibility {
            route_id: Some(route_id),
            route: Some(route),
            reasons,
        }
    } else {
        Eligibility {
            route_id: None,
            route: None,
            reasons,
        }
    }
}

fn trust_mode_key(mode: TrustMode) -> &'static str {
    match mode {
        TrustMode::Local => "local",
        TrustMode::OnDevice => "on_device",
        TrustMode::Byok => "byok",
        TrustMode::ManagedCloud => "managed_cloud",
    }
}

struct SelectedRoute<'registry, 'model> {
    model_key: &'model str,
    eligibility: Eligibility<'registry>,
    reason: RouteReason,
    fallbacks: Vec<AutoFallbackRoute>,
}

fn selected_decision(
    request: &AutoRoutingRequest<'_>,
    requested_selection: &str,
    requested_profile: Option<RoutingProfile>,
    effective_profile: Option<RoutingProfile>,
    selected: SelectedRoute<'_, '_>,
) -> AutoRouteDecision {
    let route = selected
        .eligibility
        .route
        .expect("selected_decision requires an eligible route");
    let route_id = selected
        .eligibility
        .route_id
        .expect("selected_decision requires an eligible route id");
    AutoRouteDecision::Selected(SelectedAutoRoute {
        requested_selection: requested_selection.to_owned(),
        requested_profile,
        effective_profile,
        task_type: request.task_type,
        model_key: selected.model_key.to_owned(),
        provider: route.provider.clone(),
        provider_model_id: route.provider_model_id.clone(),
        route_id: route_id.to_owned(),
        harness_id: route.harness_id.clone(),
        fallbacks: selected.fallbacks,
        reason: selected.reason,
    })
}

#[allow(clippy::too_many_arguments)]
fn build_provider_fallbacks(
    registry: &Registry,
    request: &AutoRoutingRequest<'_>,
    runtime_profile: Option<&RegistryRuntimeProfile>,
    task: &AutoTaskPolicy,
    policy: &AutoPolicy,
    allowed_slots: &HashSet<String>,
    preferred_slots: &[String],
    selected_model_key: &str,
    selected_provider: &str,
) -> Vec<AutoFallbackRoute> {
    let mut candidate_slots = preferred_slots
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>();
    if !preferred_slots.contains(&policy.fallback_slot) {
        candidate_slots.push(policy.fallback_slot.as_str());
    }

    let mut seen_models = HashSet::from([selected_model_key.to_owned()]);
    let mut seen_providers = HashSet::from([selected_provider.to_owned()]);
    let mut fallbacks = Vec::new();

    for slot_id in candidate_slots {
        if !allowed_slots.contains(slot_id) {
            continue;
        }
        let Some(model_key) = policy
            .slots
            .get(slot_id)
            .map(|slot| slot.model_key.as_str())
        else {
            continue;
        };
        if !seen_models.insert(model_key.to_owned()) {
            continue;
        }

        let eligibility = evaluate_eligibility(registry, model_key, task, request, runtime_profile);
        let (Some(route_id), Some(route)) = (eligibility.route_id, eligibility.route) else {
            continue;
        };
        if !seen_providers.insert(route.provider.clone()) {
            continue;
        }

        fallbacks.push(AutoFallbackRoute {
            model_key: model_key.to_owned(),
            provider: route.provider.clone(),
            provider_model_id: route.provider_model_id.clone(),
            route_id: route_id.to_owned(),
            harness_id: route.harness_id.clone(),
        });
    }

    fallbacks
}

/// Resolve an explicit model or Auto alias using the generated registry policy.
///
/// The resolver never crosses trust modes: a route is eligible only when its
/// generated route declaration includes the caller's exact trust boundary.
pub fn resolve_auto_route(
    request: &AutoRoutingRequest<'_>,
) -> Result<AutoRouteDecision, RegistryError> {
    let registry = registry()?;
    let policy = &registry.policies.auto;
    let requested_selection = request
        .selection
        .unwrap_or(&policy.default_alias)
        .to_ascii_lowercase();
    let runtime_profile = if let Some(profile_id) = request.runtime_profile_id {
        let Some(profile) = registry.runtime_profiles.get(profile_id) else {
            return Ok(AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::UnknownRuntimeProfile,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!("unknown runtime profile: {profile_id}")],
            }));
        };
        if profile.status != "implemented" {
            return Ok(AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::RuntimeProfileUnavailable,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!(
                    "runtime profile {profile_id} is {}",
                    profile.status
                )],
            }));
        }
        if profile.trust_mode != request.trust_mode {
            return Ok(AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::RuntimeProfileMismatch,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!(
                    "runtime profile {profile_id} requires {}, not {}",
                    trust_mode_key(profile.trust_mode),
                    trust_mode_key(request.trust_mode)
                )],
            }));
        }
        Some(profile)
    } else {
        None
    };
    let task = &policy.tasks[request.task_type.as_key()];

    let Some(alias) = policy.aliases.get(&requested_selection) else {
        if !registry.models.contains_key(&requested_selection) {
            return Ok(AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::UnknownSelection,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: vec![format!(
                    "unknown model selection: {}",
                    request.selection.unwrap_or_default()
                )],
            }));
        }
        let eligibility = evaluate_eligibility(
            registry,
            &requested_selection,
            task,
            request,
            runtime_profile,
        );
        return Ok(if eligibility.route.is_some() {
            selected_decision(
                request,
                &requested_selection,
                None,
                None,
                SelectedRoute {
                    model_key: &requested_selection,
                    eligibility,
                    reason: RouteReason::Explicit,
                    fallbacks: Vec::new(),
                },
            )
        } else {
            AutoRouteDecision::Unavailable(UnavailableAutoRoute {
                code: UnavailableCode::ExplicitModelIneligible,
                requested_selection,
                requested_profile: None,
                effective_profile: None,
                task_type: request.task_type,
                reasons: eligibility.reasons,
            })
        });
    };

    let tier = normalize_tier(request.subscription_tier);
    let maximum_profile = policy
        .tier_maximum_profiles
        .get(tier)
        .copied()
        .unwrap_or(RoutingProfile::Economy);
    // Single self-routing `auto`: derive the requested band from the classified
    // task ("hi" → economy, hard coding → premium); other aliases keep their
    // static profile. The tier clamp below still narrows it to reachable slots.
    let requested_profile = if alias.compute_profile {
        policy
            .auto_profile_by_task
            .get(request.task_type.as_key())
            .copied()
            .unwrap_or(alias.profile)
    } else {
        alias.profile
    };
    let effective_profile = clamp_profile(requested_profile, maximum_profile, &policy.profile_order);
    let allowed_slots = policy
        .tier_allowed_slots
        .get(tier)
        .cloned()
        .unwrap_or_else(|| vec![policy.fallback_slot.clone()])
        .into_iter()
        .collect::<HashSet<_>>();
    let preferred_slots = task
        .preferred_slots
        .get(effective_profile.as_key())
        .map(Vec::as_slice)
        .unwrap_or_default();

    if let Some(current_model_key) = request.current_model_key
        && policy.continuity.prefer_current_model_when_eligible
        && (!policy.continuity.reevaluate_on_task_change
            || request.previous_task_type == Some(request.task_type)
            || (policy.continuity.prefer_current_route_for_cache
                && preferred_slots.iter().any(|slot_id| {
                    allowed_slots.contains(slot_id)
                        && policy
                            .slots
                            .get(slot_id)
                            .is_some_and(|slot| slot.model_key == current_model_key)
                })))
    {
        let eligibility =
            evaluate_eligibility(registry, current_model_key, task, request, runtime_profile);
        if let Some(route) = eligibility.route {
            let selected_provider = route.provider.clone();
            let fallbacks = build_provider_fallbacks(
                registry,
                request,
                runtime_profile,
                task,
                policy,
                &allowed_slots,
                preferred_slots,
                current_model_key,
                &selected_provider,
            );
            return Ok(selected_decision(
                request,
                &requested_selection,
                Some(requested_profile),
                Some(effective_profile),
                SelectedRoute {
                    model_key: current_model_key,
                    eligibility,
                    reason: RouteReason::Continuity,
                    fallbacks,
                },
            ));
        }
    }

    let mut reasons = Vec::new();
    for slot_id in preferred_slots {
        if !allowed_slots.contains(slot_id) {
            reasons.push(format!(
                "routing slot {slot_id} is not allowed for tier {tier}"
            ));
            continue;
        }
        let Some(model_key) = policy
            .slots
            .get(slot_id)
            .map(|slot| slot.model_key.as_str())
        else {
            reasons.push(format!("routing slot {slot_id} is missing"));
            continue;
        };
        let eligibility = evaluate_eligibility(registry, model_key, task, request, runtime_profile);
        if let Some(route) = eligibility.route {
            let selected_provider = route.provider.clone();
            let fallbacks = build_provider_fallbacks(
                registry,
                request,
                runtime_profile,
                task,
                policy,
                &allowed_slots,
                preferred_slots,
                model_key,
                &selected_provider,
            );
            return Ok(selected_decision(
                request,
                &requested_selection,
                Some(requested_profile),
                Some(effective_profile),
                SelectedRoute {
                    model_key,
                    eligibility,
                    reason: RouteReason::PreferredSlot,
                    fallbacks,
                },
            ));
        }
        reasons.extend(eligibility.reasons);
    }

    if !preferred_slots.contains(&policy.fallback_slot)
        && allowed_slots.contains(&policy.fallback_slot)
        && let Some(model_key) = policy
            .slots
            .get(&policy.fallback_slot)
            .map(|slot| slot.model_key.as_str())
    {
        let eligibility = evaluate_eligibility(registry, model_key, task, request, runtime_profile);
        if let Some(route) = eligibility.route {
            let selected_provider = route.provider.clone();
            let fallbacks = build_provider_fallbacks(
                registry,
                request,
                runtime_profile,
                task,
                policy,
                &allowed_slots,
                preferred_slots,
                model_key,
                &selected_provider,
            );
            return Ok(selected_decision(
                request,
                &requested_selection,
                Some(requested_profile),
                Some(effective_profile),
                SelectedRoute {
                    model_key,
                    eligibility,
                    reason: RouteReason::FallbackSlot,
                    fallbacks,
                },
            ));
        }
        reasons.extend(eligibility.reasons);
    }

    let mut seen = HashSet::new();
    reasons.retain(|reason| seen.insert(reason.clone()));
    Ok(AutoRouteDecision::Unavailable(UnavailableAutoRoute {
        code: UnavailableCode::NoEligibleRoute,
        requested_selection,
        requested_profile: Some(requested_profile),
        effective_profile: Some(effective_profile),
        task_type: request.task_type,
        reasons,
    }))
}
