/**
 * Code Editing API
 *
 * TypeScript API wrappers for code editing Tauri commands.
 * Provides functionality for generating, applying, rejecting, and reverting code changes
 * made by the AGI system, plus composer multi-file editing sessions.
 */

import { invoke, isTauri } from '../lib/tauri-mock';

// ============================================================================
// Types
// ============================================================================

/**
 * Result of a revert operation
 */
export interface RevertResult {
  success: boolean;
  reverted_files: string[];
  failed_files: FailedRevert[];
}

/**
 * Details about a failed revert
 */
export interface FailedRevert {
  path: string;
  reason: string;
}

/**
 * Pending code edit from the AGI system
 */
export interface PendingEdit {
  id: string;
  file_path: string;
  original_content: string;
  new_content: string;
  description: string;
  created_at: number;
}

/**
 * A single code edit generated by the LLM
 */
export interface CodeEdit {
  id: string;
  file_path: string;
  original_content: string;
  modified_content: string;
  diff: string;
  description: string;
  status: 'pending' | 'applied' | 'rejected';
  created_at: number;
}

/**
 * A composer session containing multiple related edits
 */
export interface ComposerSession {
  id: string;
  edits: CodeEdit[];
  prompt: string;
  context_files: string[];
  status: string;
  created_at: number;
}

/**
 * Line-level change within a diff hunk
 */
export interface LineChange {
  type: string;
  old_line_number: number | null;
  new_line_number: number | null;
  content: string;
}

/**
 * A hunk within a file diff
 */
export interface DiffHunk {
  old_start: number;
  old_lines: number;
  new_start: number;
  new_lines: number;
  changes: LineChange[];
}

/**
 * Statistics for a file diff
 */
export interface DiffStats {
  additions: number;
  deletions: number;
  changes: number;
}

/**
 * File diff information with hunks
 */
export interface FileDiff {
  file_path: string;
  hunks: DiffHunk[];
  stats: DiffStats;
}

/**
 * A file change to apply
 */
export interface FileChange {
  path: string;
  original_content: string;
  modified_content: string;
}

/**
 * Result of applying file changes
 */
export interface ApplyResult {
  success: boolean;
  files_modified: string[];
  errors: string[];
}

// ============================================================================
// Code Edit Generation
// ============================================================================

/**
 * Generate a code edit using the LLM.
 * Sends the file content, selection, and instruction to the LLM and returns
 * a CodeEdit with the proposed changes.
 *
 * @param filePath - Absolute path to the file to edit
 * @param selection - The selected code snippet to modify
 * @param instruction - Natural language instruction for the edit
 * @returns The generated CodeEdit with diff
 */
export async function generateCodeEdit(
  filePath: string,
  selection: string,
  instruction: string,
): Promise<CodeEdit> {
  return invoke<CodeEdit>('code_generate_edit', {
    filePath,
    selection,
    instruction,
  });
}

// ============================================================================
// Composer Sessions (Multi-File Editing)
// ============================================================================

/**
 * Start a new composer session for multi-file editing.
 * The LLM analyzes context files and generates edits across multiple files
 * based on the given prompt.
 *
 * @param prompt - Natural language description of the desired changes
 * @param contextFiles - Array of file paths to use as context
 * @returns The created ComposerSession with proposed edits
 */
export async function composerStartSession(
  prompt: string,
  contextFiles: string[],
): Promise<ComposerSession> {
  return invoke<ComposerSession>('composer_start_session', {
    prompt,
    contextFiles,
  });
}

/**
 * Apply all edits in a composer session, writing changes to disk.
 *
 * @param sessionId - ID of the composer session to apply
 */
export async function composerApplySession(sessionId: string): Promise<void> {
  await invoke('composer_apply_session', { sessionId });
}

/**
 * Retrieve a composer session by ID.
 *
 * @param sessionId - ID of the composer session to retrieve
 * @returns The ComposerSession with its current state
 */
export async function composerGetSession(sessionId: string): Promise<ComposerSession> {
  return invoke<ComposerSession>('composer_get_session', { sessionId });
}

// ============================================================================
// Edit Management
// ============================================================================

/**
 * Revert changes to specified files.
 * Uses the AGI's edit history to restore original content.
 * Falls back to git checkout if no edit history exists.
 *
 * @param filePaths - Array of file paths to revert
 * @returns Result indicating which files were reverted successfully
 */
export async function revertChanges(filePaths: string[]): Promise<RevertResult> {
  if (!isTauri) {
    return {
      success: true,
      reverted_files: filePaths,
      failed_files: [],
    };
  }

  try {
    const result = await invoke<RevertResult>('revert_changes', {
      filePaths,
    });
    return result;
  } catch (error) {
    return {
      success: false,
      reverted_files: [],
      failed_files: filePaths.map((path) => ({
        path,
        reason: String(error),
      })),
    };
  }
}

/**
 * Apply a batch of file changes to disk.
 *
 * @param changes - Array of file changes with original and modified content
 * @returns Result with list of modified files and any errors
 */
export async function applyChanges(changes: FileChange[]): Promise<ApplyResult> {
  if (!isTauri) {
    return { success: true, files_modified: changes.map((c) => c.path), errors: [] };
  }

  try {
    const result = await invoke<ApplyResult>('apply_changes', { changes });
    return result;
  } catch (error) {
    return {
      success: false,
      files_modified: [],
      errors: [String(error)],
    };
  }
}

/**
 * Get a structured diff between original and modified content for a file.
 *
 * @param filePath - Path to the file (for labeling)
 * @param original - Original file content
 * @param modified - Modified file content
 * @returns Structured diff with hunks and stats
 */
export async function getFileDiff(
  filePath: string,
  original: string,
  modified: string,
): Promise<FileDiff | null> {
  if (!isTauri) {
    return null;
  }

  try {
    const result = await invoke<FileDiff>('get_file_diff', {
      filePath,
      original,
      modified,
    });
    return result;
  } catch {
    return null;
  }
}

/**
 * List all pending edits that haven't been applied yet.
 *
 * @returns Array of pending edits
 */
export async function listPendingEdits(): Promise<CodeEdit[]> {
  if (!isTauri) {
    return [];
  }

  try {
    const result = await invoke<CodeEdit[]>('code_list_pending_edits');
    return result;
  } catch {
    return [];
  }
}

/**
 * Apply a specific pending edit.
 *
 * @param editId - ID of the edit to apply
 * @returns Whether the edit was applied successfully
 */
export async function applyEdit(editId: string): Promise<boolean> {
  if (!isTauri) {
    return true;
  }

  try {
    await invoke('code_apply_edit', { editId });
    return true;
  } catch {
    return false;
  }
}

/**
 * Reject a specific pending edit.
 *
 * @param editId - ID of the edit to reject
 * @returns Whether the edit was rejected successfully
 */
export async function rejectEdit(editId: string): Promise<boolean> {
  if (!isTauri) {
    return true;
  }

  try {
    await invoke('code_reject_edit', { editId });
    return true;
  } catch {
    return false;
  }
}
