export {
  OllamaClient,
  ollamaCheckStatus,
  ollamaListModels,
  ollamaGetModelInfo,
  ollamaPullModel,
  ollamaDeleteModel,
  formatModelSize,
  type OllamaModel,
  type OllamaModelDetails,
} from './ollama';

export {
  PrivacyClient,
  updatePrivacyPreferences,
  exportUserData,
  exportUserDataParsed,
  downloadUserData,
  deleteUserAccount,
  type PrivacyPreferences,
  type ExportedData,
  type ExportMetadata,
} from './privacy';

export {
  McpClient,
  mcpInitialize,
  mcpListServers,
  mcpConnectServer,
  mcpDisconnectServer,
  mcpEnableServer,
  mcpDisableServer,
  mcpListTools,
  mcpSearchTools,
  mcpCallTool,
  mcpGetConfig,
  mcpUpdateConfig,
  mcpGetStats,
  mcpGetRegistry,
  mcpInstallServer,
  mcpGetExecutionHistory,
  mcpGetToolExecutionStats,
  mcpGetHealth,
  mcpCheckServerHealth,
  mcpGetServerLogs,
  mcpOAuthCredentialsStatus,
  mcpOAuthSetCredentialsRaw,
  mcpOAuthStartRaw,
  mcpOAuthCallbackRaw,
  mcpOAuthDisconnectRaw,
  mcpListConnectedProviders,
  mcpConnectConnector,
  mcpSaveApiKey,
  mcpServerGetConfig,
  mcpServerStart,
  mcpServerStop,
  mcpServerUpdateConfig,
  mcpUpdateFilesystemDirectories,
  mcpStoreCredential,
  mcpGetToolSchemas,
} from './mcp';

export {
  ChatClient,
  detectIntent,
  isStopCommand,
  handleStop,
  stopGeneration,
  type UserIntent,
  type IntentResult,
} from './chat';

export {
  ScreenWatcherClient,
  startScreenWatcher,
  stopScreenWatcher,
  pauseScreenWatcher,
  resumeScreenWatcher,
  getScreenWatcherStatus,
  getLatestScreenshot,
  getRecentScreenshots,
  captureScreenNow,
  onScreenCapture,
  type ScreenCapture,
  type ScreenWatcherConfig,
  type WatcherStatus,
} from './screenWatcher';

export {
  getTimeoutConfig,
  setTimeoutConfig,
  getRecommendedTimeout,
  formatDuration,
  minutesToSeconds,
  secondsToMinutes,
  type TimeoutConfig,
  type TimeoutWarning,
  type TimeoutResponse,
} from './timeout';

export {
  listBackgroundTasks,
  getBackgroundTask,
  getTaskProgress,
  createBackgroundTask,
  pauseBackgroundTask,
  resumeBackgroundTask,
  cancelBackgroundTask,
  extendTaskTimeout,
  getTaskStats,
  agiPauseTask,
  agiResumeTask,
  agiAbortTask,
  backgroundTaskList,
  backgroundTaskCancel,
  backgroundTaskStatus,
  type PersistentTask,
  type TaskStats,
  type TaskProgress,
} from './backgroundTasks';

export {
  undoGetSummary,
  undoGetChanges,
  undoChange,
  undoLast,
  undoTask,
  undoCanUndo,
  codingCheckpointCreate,
  codingCheckpointList,
  codingCheckpointRewind,
  formUndoRecord,
  formUndoAttempt,
  formUndoCanUndo,
  formUndoList,
  formUndoListUndoable,
  formUndoGet,
  formUndoClear,
  formUndoClearOld,
  formUndoStats,
  type UndoableChange,
  type UndoSummary,
  type UndoResult,
  type NamedFileCheckpoint,
  type FormSubmission,
  type FormUndoResult,
  type FormUndoStats,
} from './undo';

export {
  executeTerminalCommand,
  terminalExecute,
  terminalDetectShells,
  terminalCreateSession,
  terminalSendInput,
  terminalResize,
  terminalKill,
  terminalListSessions,
  terminalGetHistory,
  terminalClearHistory,
  terminalSetEnv,
  terminalGetEnv,
  terminalListEnv,
  terminalUnsetEnv,
  terminalAiSuggestCommand,
  terminalAiExplainError,
  terminalSmartCommit,
  terminalAiSuggestImprovements,
  type ExecuteResult as TerminalExecResult,
  type TerminalExecuteResult as TerminalSimpleResult,
  type ShellInfo as TerminalShellInfo,
  type ExecuteCommandOptions,
} from './terminal';

export * as memoryApi from './memory';

export {
  fileRead,
  fileReadText,
  fileReadBinary,
  fileReadRange,
  fsReadFileContent,
  fileWrite,
  fileWriteText,
  fileWriteBinary,
  fileDelete,
  fileRename,
  fileCopy,
  fileMove,
  fileExists,
  fileMetadata,
  fileGetMetadata,
  fileOpenWithDefaultApp,
  dirCreate,
  dirList,
  dirDelete,
  dirTraverse,
  fsGetWorkspaceFiles,
  undoFileOperation,
  type FileMetadata as FileOpsMetadata,
  type DirEntry as FileOpsDirEntry,
  type FileReadRangeResult,
  type FileContextContent,
  type WorkspaceFile,
} from './fileOps';

export {
  artifactCreate,
  artifactCreateStreaming,
  artifactAppendStreaming,
  artifactFinalizeStreaming,
  artifactGet,
  artifactGetRendered,
  artifactUpdate,
  artifactApplyDiff,
  artifactRollback,
  artifactDelete,
  artifactArchive,
  artifactUnarchive,
  artifactPin,
  artifactAddTags,
  artifactRemoveTags,
  artifactList,
  artifactGetByConversation,
  artifactGetVersions,
  artifactGetDiff,
  artifactGetStats,
  artifactExportAll,
  artifactImportAll,
  artifactClearAll,
  artifactListPersisted,
  type Artifact as ArtifactApiType,
  type ArtifactSummary as ArtifactSummaryApiType,
  type ArtifactResponse,
  type ArtifactDiffHunk,
  type ArtifactListFilter,
  type RenderedArtifact as RenderedArtifactApiType,
  type VersionDiff as VersionDiffApiType,
  type ArtifactStoreStats as ArtifactStoreStatsApiType,
} from './artifacts';

export {
  BrowserClient,
  browserInit,
  browserCheckStatus,
  browserLaunch,
  browserClose,
  browserOpenTab,
  browserCloseTab,
  browserSwitchTab,
  browserListTabs,
  browserNavigate,
  browserGoBack,
  browserGoForward,
  browserReload,
  browserGetUrl,
  browserGetTitle,
  browserWaitForNavigation,
  browserClick,
  browserType,
  browserGetText,
  browserGetAttribute,
  browserWaitForSelector,
  browserSelectOption,
  browserCheck,
  browserUncheck,
  browserHover,
  browserFocus,
  browserQueryAll,
  browserScrollIntoView,
  browserGetElementState,
  browserWaitForInteractive,
  browserHighlightElement,
  browserFillForm,
  browserDragAndDrop,
  browserUploadFile,
  browserScreenshot,
  browserGetScreenshotStream,
  browserGetContent,
  browserGetDomSnapshot,
  browserEvaluate,
  browserExecuteAsyncJs,
  browserCallFunction,
  browserGetCookies,
  browserSetCookie,
  browserClearCookies,
  browserGetPerformanceMetrics,
  browserGetFrames,
  browserExecuteInFrame,
  browserEnableRequestInterception,
  findElementSemantic,
  findAllElementsSemantic,
  clickSemantic,
  typeSemantic,
  testSelectorStrategies,
  getAccessibilityTree,
  getDomSemanticGraph,
  getInteractiveElements,
  findByRole,
  type BrowserStatusResult,
  type BrowserLaunchOptions,
  type TabInfo,
  type ElementStateResult,
  type PerformanceMetrics,
  type FrameContext,
  type BrowserCookie,
  type ElementBoundsResult,
  type SemanticResult,
} from './browser';

export * from './automation';
export * from './automationEnhanced';
export * from './codeEditing';
export * from './codeSearch';
export * from './embeddings';
export * from './media';
export * from './migration';
export * from './orchestrator';
export * from './reflection';
export * from './accountApi';

export * from './agi';

export {
  agentInit,
  agentSubmitTask,
  agentGetTaskStatus,
  agentListTasks,
  agentListTrustedWorkflows,
  agentStop,
  startAgentTask,
  resolveApproval,
  type AgentConfig,
  type AgentSubmitTaskRequest,
  type SubmitTaskResponse,
  type TaskStatusResponse,
  type AgentTask as AgentApiTask,
  type AgentTaskStep,
  type ListTasksResponse,
  type TrustedWorkflowMap,
  type ApprovalDecision,
} from './agent';

export {
  GitClient,
  gitInit,
  gitStatus,
  gitAdd,
  gitCommit,
  gitPush,
  gitPull,
  gitFetch,
  gitDiff,
  gitLog,
  gitClone,
  gitListBranches,
  gitCreateBranch,
  gitCheckout,
  gitCheckoutNewBranch,
  gitDeleteBranch,
  gitMerge,
  gitCurrentBranch,
  gitDefaultBranch,
  gitStash,
  gitStashPop,
  gitReset,
  gitCheckoutFiles,
  gitListRemotes,
  gitAddRemote,
  gitHasConflicts,
  gitListConflicts,
  gitGetConflictDetails,
  gitResolveConflict,
  gitMarkResolved,
  gitGetConflictSuggestionPrompt,
  gitAbortMerge,
  gitCompleteMerge,
  gitGetBranchDiffSummary,
  gitGeneratePrDescription,
  gitCreatePr,
  gitCheckPrReadiness,
  type GitStatus,
  type GitCommit,
  type GitBranch,
  type GitDiff,
  type GitConflictDetails,
  type ConflictResolutionRequest,
  type ConflictHunk,
  type ResolutionResult,
  type BranchDiffSummary,
  type GeneratedPrContent,
  type PrCreationConfig,
  type PrCreationResult,
  type PrReadinessResult,
} from './git';

export {
  generateCss,
  applyCss,
  getElementStyles,
  generateColorScheme,
  suggestImprovements,
  designTokensToCss,
  checkAccessibility,
  type DesignRequest,
  type DesignResponse,
  type DesignContext,
  type DesignConstraints,
  type ColorScheme,
  type DesignSuggestion,
  type DesignTokens,
  type AccessibilityReport,
  type AccessibilityIssue,
} from './design';

export {
  EmailClient,
  ContactClient,
  emailConnect,
  emailListAccounts,
  emailRemoveAccount,
  emailListFolders,
  emailFetchInbox,
  emailListMessages,
  emailGetMessage,
  emailMarkRead,
  emailDelete,
  emailMoveMessage,
  emailDownloadAttachment,
  emailSend,
  emailSendMessage,
  emailSearch,
  contactCreate,
  contactGet,
  contactList,
  contactSearch,
  contactUpdate,
  contactDelete,
  contactImportVcard,
  contactExportVcard,
  type SendEmailRequest,
  type EmailSearchResult as EmailApiSearchResult,
} from './email';

export {
  processImage,
  processRegion,
  getLanguages,
  getResult,
  processWithBoxes,
  detectLanguages,
  processMultiLanguage,
  preprocessImage,
  type OCRResult,
  type BoundingBox,
  type WordData,
  type Language,
  type LanguageDetection,
  type MultiLanguageResult,
} from './ocr';

export {
  CacheClient,
  cacheGetStats,
  cacheClearAll,
  cacheClearByType,
  cacheClearByProvider,
  cacheGetSize,
  cacheConfigure,
  cacheWarmup,
  cacheExport,
  cacheGetAnalytics,
  cachePruneExpired,
  codebaseCacheGetStats,
  codebaseCacheClearProject,
  codebaseCacheClearFile,
  codebaseCacheClearAll,
  codebaseCacheClearExpired,
  codebaseCacheGetFileTree,
  codebaseCacheSetFileTree,
  codebaseCacheGetSymbols,
  codebaseCacheSetSymbols,
  codebaseCacheGetDependencies,
  codebaseCacheSetDependencies,
  codebaseCacheCalculateHash,
  type CacheTypeStats,
  type CacheStats,
  type CacheSettings,
  type CachedQueryInfo,
  type ProviderCacheBreakdown,
  type CacheAnalytics,
  type FileTreeEntry,
  type FileTree,
  type SymbolKind,
  type SymbolInfo,
  type ImportInfo,
  type ExportInfo,
  type SymbolTable,
  type NodeType,
  type EdgeType,
  type DependencyNode,
  type DependencyEdge,
  type DependencyGraph,
  type CodebaseCacheStats,
} from './cache';

export {
  OnboardingClient,
  getOnboardingStatus,
  completeOnboardingStep,
  skipOnboardingStep,
  resetOnboarding,
  exportUserData as exportOnboardingUserData,
  checkConnectivity,
  getSessionInfo,
  updateSessionActivity,
  getUserPreference,
  setUserPreference,
  startFirstRunExperience,
  hasCompletedFirstRun,
  runInstantDemo,
  updateFirstRunStep,
  selectDemo,
  recordDemoResults,
  completeFirstRun,
  getFirstRunSession,
  getFirstRunStatistics,
  skipFirstRun,
  type OnboardingStep,
  type OnboardingStatus,
  type SessionInfo,
  type UserPreference,
  type FirstRunStep,
  type FirstRunSession,
  type DemoResult,
  type FirstRunStatistics,
} from './onboarding';

export {
  TutorialClient,
  getTutorials,
  getTutorial,
  getRecommendedTutorial,
  startTutorial,
  completeTutorialStep,
  skipTutorialStep,
  completeTutorial,
  resetTutorial,
  getTutorialProgress,
  getUserTutorialProgress,
  getTutorialStats,
  recordStepView,
  getUserRewards,
  hasReward,
  hasUnlockedFeature,
  getUserCredits,
  populateSampleData,
  hasSampleData,
  clearSampleData,
  submitTutorialFeedback,
  recordHelpSession,
  type Tutorial,
  type TutorialStep,
  type TutorialCategory,
  type TutorialDifficulty,
  type OnboardingProgress,
  type UserTutorialProgress,
  type TutorialStats,
  type Reward,
  type RewardType,
  type RewardValue,
  type BadgeRarity,
  type SampleDataSummary,
  type ActionType as TutorialActionType,
  type ValidationCriteria,
  type ValidationType,
} from './tutorials';

export {
  apiRequest,
  apiGet,
  apiPostJson,
  apiPutJson,
  apiDelete,
  apiParseResponse,
  apiExtractJsonPath,
  apiOAuthCreateClient,
  apiOAuthGetAuthUrl,
  apiOAuthExchangeCode,
  apiOAuthRefreshToken,
  apiOAuthClientCredentials,
  apiRenderTemplate,
  apiExtractTemplateVariables,
  apiValidateTemplate,
  type HttpMethod,
  type AuthType,
  type ApiRequest,
  type ApiResponse,
  type OAuth2Config,
  type TokenResponse,
  type TemplateVariable,
  type RequestTemplate,
  type ParsedResponse,
  type RenderedTemplate,
} from './apiManagement';

export {
  taskCreate,
  taskGetStatus,
  taskUpdateProgress,
  taskPause,
  taskResume,
  taskCancel,
  taskList,
  taskListByStatus,
  taskComplete,
  taskSaveContext,
  taskGetResumable,
  coordUpdateAppState,
  coordRequestApproval,
  coordGetPendingApprovals,
  type TaskStatus,
  type TaskPriority,
  type TaskStep,
  type PersistedTask,
  type AppState,
  type ApprovalRequest as TaskApprovalRequest,
} from './taskPersistence';

export {
  AnalyticsClient,
  analyticsTrackEvent,
  analyticsFlushEvents,
  analyticsGetSessionId,
  analyticsSetUserProperty,
  analyticsDeleteAllData,
  metricsGetSystem,
  metricsGetApp,
  metricsIncrementAutomations,
  metricsIncrementGoals,
  metricsSetMcpServers,
  metricsSetCacheHitRate,
  analyticsGetUsageStats,
  analyticsGetFeatureUsage,
  analyticsCalculateRoi,
  analyticsGetProcessMetrics,
  analyticsGetUserMetrics,
  analyticsGetToolMetrics,
  analyticsGetMetricTrends,
  analyticsGetTimeSavedTrend,
  analyticsGetCostSavedTrend,
  analyticsExportReport,
  analyticsGenerateWeeklyReport,
  analyticsGenerateMonthlyReport,
  analyticsSaveSnapshot,
  analyticsGetTopProcesses,
  trackWorkflowView,
  acknowledgeMilestone,
  type TelemetryEvent,
  type SystemMetrics as AnalyticsSystemMetrics,
  type AppMetrics as AnalyticsAppMetrics,
  type ROIReport,
  type ProcessMetrics,
  type UserMetrics as AnalyticsUserMetrics,
  type ToolMetrics,
  type TrendPoint,
  type UsageStats as AnalyticsUsageStatsApi,
  type FeatureUsageEntry,
} from './analytics';

export {
  dbCreatePool,
  dbExecuteQuery,
  dbExecutePrepared,
  dbExecuteBatch,
  dbClosePool,
  dbListPools,
  dbGetPoolStats,
  dbValidateQuery,
  dbBuildSelect,
  dbBuildInsert,
  dbBuildUpdate,
  dbBuildDelete,
  dbMysqlTestConnection,
  dbMysqlListTables,
  dbMysqlDescribeTable,
  dbMysqlListIndexes,
  dbMysqlCallProcedure,
  dbMysqlBulkInsert,
  dbMongoConnect,
  dbMongoFind,
  dbMongoFindOne,
  dbMongoInsertOne,
  dbMongoInsertMany,
  dbMongoUpdateMany,
  dbMongoDeleteMany,
  dbMongoDisconnect,
  dbRedisConnect,
  dbRedisGet,
  dbRedisSet,
  dbRedisDel,
  dbRedisExists,
  dbRedisExpire,
  dbRedisHGet,
  dbRedisHSet,
  dbRedisHGetAll,
  dbRedisDisconnect,
  dbStorePassword,
  dbHasStoredPassword,
  dbGetStoredPassword,
  dbDeleteStoredPassword,
  type ConnectionConfig as DbConnectionConfig,
  type PoolConfig as DbPoolConfig,
  type QueryResult as DbQueryResult,
  type SqlRowValue,
  type QueryValidation as DbQueryValidation,
  type PoolStats as DbPoolStats,
  type MySqlColumnInfo,
  type MySqlIndexInfo,
  type MongoDocument,
  type MongoFilter,
  type MongoUpdate,
  type MongoResult,
  type SelectQuery,
  type InsertQuery,
  type UpdateQuery,
  type DeleteQuery,
} from './database';

export {
  getRealtimeStats,
  recordAutomationMetrics,
  getMetricsHistory,
  compareToManual,
  compareToPreviousPeriod,
  compareToIndustryBenchmark,
  getMilestones,
  shareMilestone,
  getTodayStats,
  getWeekStats,
  getMonthStats,
  getAllTimeStats,
  getManualVsAutomatedComparison,
  getPeriodComparison,
  getBenchmarkComparison,
  getRecentActivity,
  exportRoiReport,
  type RecordAutomationRequest,
  type MetricsSnapshot,
  type RealtimeStats,
  type Comparison,
  type PeriodComparison,
  type BenchmarkComparison,
  type MilestoneData,
  type DayStats,
  type TopAutomationData,
  type DailyBreakdown,
  type WeekStats,
  type WeeklyBreakdown,
  type MonthStats,
  type MonthlyTrend,
  type AllTimeStats,
  type ComparisonData,
  type PeriodComparisonData,
  type BenchmarkComparisonData,
  type ActivityItem,
  type ExportOptions,
} from './metrics';

export {
  lspStartServer,
  lspStopServer,
  lspListServers,
  lspDetectLanguage,
  lspDidOpen,
  lspDidChange,
  lspDidClose,
  lspCompletion,
  lspHover,
  lspDefinition,
  lspReferences,
  lspRename,
  lspFormatting,
  lspWorkspaceSymbol,
  lspCodeAction,
  lspGetDiagnostics,
  lspGetAllDiagnostics,
  type LSPServer,
  type LSPPosition,
  type LSPRange,
  type LSPLocation,
  type CompletionItem,
  type HoverResult,
  type LSPDiagnostic,
  type WorkspaceSymbol,
  type TextEdit,
  type CodeAction,
  type WorkspaceEdit,
} from './lsp';

export {
  productivityConnect,
  productivityListTasks,
  productivityCreateTask,
  productivityNotionListPages,
  productivityNotionQueryDatabase,
  productivityNotionCreateDatabaseRow,
  productivityTrelloListBoards,
  productivityTrelloListCards,
  productivityTrelloCreateCard,
  productivityTrelloMoveCard,
  productivityTrelloAddComment,
  productivityAsanaListProjects,
  productivityAsanaListProjectTasks,
  productivityAsanaCreateTask,
  productivityAsanaAssignTask,
  productivityAsanaMarkComplete,
  type ProductivityProvider,
  type ProductivityTask,
  type ConnectResponse,
  type CreateTaskResponse,
} from './productivity';

export {
  VoiceClient,
  voiceTranscribeFile,
  voiceTranscribeBlob,
  voiceTranscribeLocal,
  voiceConfigure,
  voiceGetSettings,
  voiceCheckLocalWhisper,
  voiceGetCapabilities,
  voiceTtsSpeak,
  voiceTtsSpeakWithBargeIn,
  voiceTtsStop,
  voiceTtsIsPlaying,
  voiceTtsListVoices,
  voiceTtsConfigure,
  voiceTtsSpeakLocal,
  voiceWakeEnable,
  voiceWakeDisable,
  voiceWakeStatus,
  voiceWakeConfigure,
  voicePttConfigure,
  voicePttState,
  voicePttKeyDown,
  voicePttKeyUp,
  voiceStartGlobalPtt,
  voiceStopGlobalPtt,
  voiceInjectText,
  voiceDeepgramConfigure,
  voiceStartDeepgramStream,
  voiceStopDeepgramStream,
  voiceDeepgramSendAudio,
  voiceDeepgramStatus,
  voiceConvertAudioToPcm,
  voiceEnableBargeIn,
  voiceSetBargeInSensitivity,
  voiceGetBargeInStatus,
  voiceConfigureBargeIn,
  voiceStartBargeInMonitoring,
  voiceStopBargeInMonitoring,
  speechStartRecording,
  speechStopAndTranscribe,
  voiceDownloadWhisperModel,
  voiceListWhisperModels,
  voiceSetWhisperModel,
  voiceDeleteWhisperModel,
  voiceDownloadPiperVoice,
  voiceListPiperVoices,
  voiceSetPiperVoice,
  voiceDeletePiperVoice,
  voiceDownloadPiperBinary,
  voiceCheckPiperBinary,
  voiceListLocalModels,
  type VoiceTranscription,
  type VoiceSettings as VoiceApiSettings,
  type VoiceCapabilities as VoiceApiCapabilities,
  type TtsVoice,
  type TtsConfig as TtsApiConfig,
  type WakeWordConfig as WakeWordApiConfig,
  type PttConfig as PttApiConfig,
  type DeepgramConfig as DeepgramApiConfig,
  type DeepgramStreamingStats,
  type DeepgramStreamStatus as DeepgramApiStreamStatus,
  type BargeInConfig as BargeInApiConfig,
  type BargeInStats as BargeInApiStats,
  type BargeInStatus as BargeInApiStatus,
  type SpeechTranscriptResult,
  type WhisperModelInfo,
  type PiperVoiceInfo,
  type LocalModelsInfo,
  type DownloadProgress,
} from './voice';
