/**
 * memoryStore — surface-agnostic store for cross-conversation memory facts
 * the assistant should remember about the user (Claude calls this "Memory").
 *
 * Round-2 audit P0 #8 (2026-05-21). Distinct from `promptStashStore` (reusable
 * prompts/templates). Memory facts are short statements like
 * "User prefers Python over JavaScript" that the assistant should reference
 * across conversations.
 *
 * v1 LOCAL-ONLY POSTURE — facts live in MMKV/localStorage on the device.
 * Cloud sync of memory belongs to Cloud Managed (waitlist-gated) and is
 * intentionally NOT wired here; this primitive stays device-local in v1.
 */
import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface MemoryFact {
  /** Stable identifier — `mem_<random>` generated by `add()`. */
  id: string;
  /** The remembered fact in natural language (≤ 280 chars by convention). */
  text: string;
  /** Optional origin metadata: which conversation the fact came from. */
  sourceConversationId?: string;
  /** ISO timestamp the fact was first added. */
  createdAt: string;
  /** ISO timestamp the fact was last edited. */
  updatedAt: string;
}

interface MemoryState {
  /** All remembered facts, newest first. */
  facts: MemoryFact[];
  /**
   * Add a new fact. The text is trimmed and short-circuits if empty or if a
   * fact with the same (case-insensitive) text already exists.
   */
  add: (text: string, sourceConversationId?: string) => MemoryFact | null;
  /** Update the text of an existing fact. Re-stamps `updatedAt`. */
  update: (id: string, text: string) => void;
  /** Delete a single fact. */
  remove: (id: string) => void;
  /** Delete every fact. Used by "Forget everything" affordances. */
  clear: () => void;
}

function randomId(): string {
  if (typeof globalThis.crypto?.randomUUID === 'function') {
    return `mem_${globalThis.crypto.randomUUID()}`;
  }
  return `mem_${Math.random().toString(36).slice(2, 10)}_${Date.now().toString(36)}`;
}

export const useMemoryStore = create<MemoryState>()(
  persist(
    (set, get) => ({
      facts: [],
      add: (text, sourceConversationId) => {
        const trimmed = text.trim();
        if (!trimmed) return null;
        const dupe = get().facts.find((f) => f.text.toLowerCase() === trimmed.toLowerCase());
        if (dupe) return dupe;
        const now = new Date().toISOString();
        const fact: MemoryFact = {
          id: randomId(),
          text: trimmed,
          sourceConversationId,
          createdAt: now,
          updatedAt: now,
        };
        set((state) => ({ facts: [fact, ...state.facts] }));
        return fact;
      },
      update: (id, text) => {
        const trimmed = text.trim();
        if (!trimmed) return;
        set((state) => ({
          facts: state.facts.map((f) =>
            f.id === id ? { ...f, text: trimmed, updatedAt: new Date().toISOString() } : f,
          ),
        }));
      },
      remove: (id) =>
        set((state) => ({
          facts: state.facts.filter((f) => f.id !== id),
        })),
      clear: () => set({ facts: [] }),
    }),
    {
      name: 'agi-memory-store-v1',
      // Persist only the durable shape — avoid serializing the action methods.
      partialize: (state) => ({ facts: state.facts }),
    },
  ),
);

export const selectMemoryFacts = (s: MemoryState): MemoryFact[] => s.facts;
export const selectMemoryCount = (s: MemoryState): number => s.facts.length;
