'use client';

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { immer } from 'zustand/middleware/immer';
import type { ArtifactData, ArtifactVersion } from '../components/artifacts/ArtifactPreview';
import { logger } from '@shared/lib/logger';
import { getAuthToken } from '@shared/lib/get-auth-token';

// ============================================================================
// Types
// ============================================================================

export interface Artifact extends ArtifactData {
  id: string;
  title: string;
  language: string;
  content: string;
  messageId: string;
  createdAt: Date;
  /** Share ID generated by shareArtifact — stored locally for immediate link access. */
  shareId?: string;
}

type ArtifactInput = Omit<Artifact, 'createdAt'> & { createdAt?: Date };

interface ArtifactsState {
  artifacts: Artifact[];
  selectedArtifactId: string | null;
  panelOpen: boolean;
}

interface ArtifactsActions {
  addArtifact: (artifact: Omit<Artifact, 'createdAt'> & { createdAt?: Date }) => string;
  /**
   * Message-keyed add — mirrors the singular artifact-store's `addArtifact(messageId, artifact)`
   * interface so MessageBubble can use a single store.
   */
  addArtifactForMessage: (messageId: string, artifact: ArtifactData) => void;
  upsertArtifact: (artifact: ArtifactInput) => void;
  removeArtifact: (id: string) => void;
  selectArtifact: (id: string | null) => void;
  togglePanel: () => void;
  setPanelOpen: (open: boolean) => void;
  clearArtifacts: () => void;
  clearArtifactsForMessage: (messageId: string) => void;
  extractArtifactsFromContent: (content: string, messageId: string) => void;
  /** Returns all artifacts for a given messageId (O(n) scan). */
  getMessageArtifacts: (messageId: string) => Artifact[];
  /** Add a version snapshot to an existing artifact. */
  addVersion: (artifactId: string, version: ArtifactVersion) => void;
  /** Switch to a different version of an artifact. */
  setCurrentVersion: (artifactId: string, versionIndex: number) => void;
  /**
   * Persist artifact to Neon shared_artifacts and return a share ID.
   * Falls back gracefully when the table is absent.
   */
  shareArtifact: (artifactId: string) => Promise<string>;
  reset: () => void;
}

// ============================================================================
// Helpers
// ============================================================================

/** Map language identifiers to human-readable labels */
function languageLabel(lang: string): string {
  const map: Record<string, string> = {
    ts: 'TypeScript',
    tsx: 'TypeScript React',
    typescript: 'TypeScript',
    js: 'JavaScript',
    jsx: 'JavaScript React',
    javascript: 'JavaScript',
    py: 'Python',
    python: 'Python',
    rust: 'Rust',
    rs: 'Rust',
    go: 'Go',
    java: 'Java',
    rb: 'Ruby',
    ruby: 'Ruby',
    css: 'CSS',
    scss: 'SCSS',
    html: 'HTML',
    json: 'JSON',
    yaml: 'YAML',
    yml: 'YAML',
    sql: 'SQL',
    sh: 'Shell',
    bash: 'Bash',
    zsh: 'Shell',
    swift: 'Swift',
    kotlin: 'Kotlin',
    dart: 'Dart',
    cpp: 'C++',
    c: 'C',
    csharp: 'C#',
    cs: 'C#',
    php: 'PHP',
    md: 'Markdown',
    markdown: 'Markdown',
    toml: 'TOML',
    xml: 'XML',
    graphql: 'GraphQL',
    dockerfile: 'Dockerfile',
    prisma: 'Prisma',
    svg: 'SVG',
    mermaid: 'Mermaid',
  };
  return map[lang.toLowerCase()] || lang.charAt(0).toUpperCase() + lang.slice(1);
}

/**
 * Try to extract a filename from the first line of a code block.
 * Supports patterns like:
 *   // filename.ts
 *   # filename.py
 *   filename.css (block comment style)
 *   -- filename.sql
 */
function extractFilename(content: string): string | null {
  const firstLine = content.split('\n')[0]!.trim();

  // // filename.ext  or  # filename.ext
  const singleLineComment = firstLine.match(/^(?:\/\/|#|--)\s+([\w./-]+\.\w+)\s*$/);
  if (singleLineComment) return singleLineComment[1] ?? null;

  // /* filename.ext */
  const blockComment = firstLine.match(/^\/\*\s*([\w./-]+\.\w+)\s*\*\/\s*$/);
  if (blockComment) return blockComment[1] ?? null;

  return null;
}

/**
 * Parse markdown code fences from content and return structured artifacts.
 * Matches ```language\n...\n``` patterns.
 */
function parseCodeBlocks(content: string, messageId: string): Omit<Artifact, 'id' | 'createdAt'>[] {
  const results: Omit<Artifact, 'id' | 'createdAt'>[] = [];
  const regex = /```(\w+)?\s*\n([\s\S]*?)```/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(content)) !== null) {
    const language = match[1] || 'text';
    const code = match[2]!.trim();

    // Skip very short code blocks (one-liners that are not meaningful artifacts)
    if (code.length < 10) continue;

    const filename = extractFilename(code);
    const title = filename || `${languageLabel(language)} Code`;

    results.push({
      title,
      language,
      type: artifactTypeForLanguage(language),
      content: code,
      messageId,
    });
  }

  return results;
}

function artifactTypeForLanguage(language: string): ArtifactData['type'] {
  const normalized = language.toLowerCase();
  if (normalized === 'html' || normalized === 'htm') return 'html';
  if (normalized === 'jsx' || normalized === 'tsx' || normalized === 'react') return 'react';
  if (normalized === 'svg') return 'svg';
  if (normalized === 'mermaid') return 'mermaid';
  return normalized === 'markdown' || normalized === 'md' ? 'document' : 'code';
}

function normalizeArtifact(artifact: Omit<Artifact, 'createdAt'> & { createdAt?: Date }): Artifact {
  return {
    ...artifact,
    title: artifact.title || 'Untitled',
    language: artifact.language || artifact.type,
    createdAt: artifact.createdAt ?? new Date(),
  };
}

function artifactsEqual(a: Artifact, b: Artifact): boolean {
  return (
    a.title === b.title &&
    a.language === b.language &&
    a.type === b.type &&
    a.content === b.content &&
    a.messageId === b.messageId &&
    a.computeSession === b.computeSession &&
    a.generatedFile === b.generatedFile &&
    a.artifactManifest === b.artifactManifest
  );
}

// ============================================================================
// Store
// ============================================================================

export const useArtifactsStore = create<ArtifactsState & ArtifactsActions>()(
  persist(
    immer((set, get) => ({
      // State
      artifacts: [],
      selectedArtifactId: null,
      panelOpen: false,

      // Actions
      addArtifact: (artifact) => {
        const id = artifact.id || crypto.randomUUID();
        set((state) => {
          state.artifacts.push(normalizeArtifact({ ...artifact, id }));
          // Auto-select the first artifact added
          if (!state.selectedArtifactId) {
            state.selectedArtifactId = id;
          }
        });
        return id;
      },

      upsertArtifact: (artifact) => {
        set((state) => {
          const normalized = normalizeArtifact(artifact);
          const index = state.artifacts.findIndex((item) => item.id === normalized.id);
          if (index === -1) {
            state.artifacts.push(normalized);
            if (!state.selectedArtifactId) {
              state.selectedArtifactId = normalized.id;
            }
            return;
          }
          const existing = state.artifacts[index]!;
          if (!artifactsEqual(existing, normalized)) {
            state.artifacts[index] = { ...existing, ...normalized, createdAt: existing.createdAt };
          }
        });
      },

      removeArtifact: (id) => {
        set((state) => {
          state.artifacts = state.artifacts.filter((a) => a.id !== id);
          // Validate selectedArtifactId still exists after removal (covers stale selections too)
          if (!state.artifacts.some((a) => a.id === state.selectedArtifactId)) {
            state.selectedArtifactId = state.artifacts[0]?.id ?? null;
          }
          // Close panel if no artifacts remain
          if (state.artifacts.length === 0) {
            state.panelOpen = false;
          }
        });
      },

      selectArtifact: (id) => {
        set((state) => {
          state.selectedArtifactId = id;
        });
      },

      togglePanel: () => {
        set((state) => {
          state.panelOpen = !state.panelOpen;
        });
      },

      setPanelOpen: (open) => {
        set((state) => {
          state.panelOpen = open;
        });
      },

      clearArtifacts: () => {
        set((state) => {
          state.artifacts = [];
          state.selectedArtifactId = null;
          state.panelOpen = false;
        });
      },

      extractArtifactsFromContent: (content, messageId) => {
        const existing = get().artifacts;
        // Avoid re-extracting from the same message
        if (existing.some((a) => a.messageId === messageId)) return;

        const parsed = parseCodeBlocks(content, messageId);
        if (parsed.length === 0) return;

        set((state) => {
          for (const item of parsed) {
            const id = crypto.randomUUID();
            state.artifacts.push({
              ...item,
              id,
              createdAt: new Date(),
            });
            // Auto-select the first one if nothing is selected
            if (!state.selectedArtifactId) {
              state.selectedArtifactId = id;
            }
          }
        });
      },

      addArtifactForMessage: (messageId, artifact) => {
        // Idempotent: skip if an artifact with the same id already exists
        if (get().artifacts.some((a) => a.id === artifact.id)) return;
        const normalized = normalizeArtifact({
          ...artifact,
          messageId,
          title: artifact.title || 'Untitled',
          language: artifact.language || artifact.type,
        });
        set((state) => {
          state.artifacts.push(normalized);
          if (!state.selectedArtifactId) {
            state.selectedArtifactId = normalized.id;
          }
        });
      },

      getMessageArtifacts: (messageId) => {
        return get().artifacts.filter((a) => a.messageId === messageId);
      },

      clearArtifactsForMessage: (messageId) => {
        set((state) => {
          state.artifacts = state.artifacts.filter((a) => a.messageId !== messageId);
          if (!state.artifacts.some((a) => a.id === state.selectedArtifactId)) {
            state.selectedArtifactId = state.artifacts[0]?.id ?? null;
          }
          if (state.artifacts.length === 0) {
            state.panelOpen = false;
          }
        });
      },

      addVersion: (artifactId, version) => {
        set((state) => {
          const artifact = state.artifacts.find((a) => a.id === artifactId);
          if (!artifact) return;
          if (!artifact.versions) artifact.versions = [];
          artifact.versions.push(version);
          artifact.currentVersion = artifact.versions.length - 1;
        });
      },

      setCurrentVersion: (artifactId, versionIndex) => {
        set((state) => {
          const artifact = state.artifacts.find((a) => a.id === artifactId);
          if (!artifact || !artifact.versions) return;
          if (versionIndex >= 0 && versionIndex < artifact.versions.length) {
            artifact.currentVersion = versionIndex;
            artifact.content = artifact.versions[versionIndex]!.content;
          }
        });
      },

      shareArtifact: async (artifactId) => {
        const artifact = get().artifacts.find((a) => a.id === artifactId);
        if (!artifact) throw new Error('Artifact not found');

        const shareId = `share-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

        try {
          const token = await getAuthToken();
          if (token) {
            const res = await fetch('/api/artifacts/publish', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
              body: JSON.stringify({
                share_id: shareId,
                artifact_id: artifactId,
                artifact_data: artifact,
              }),
            });
            if (!res.ok) {
              logger.warn('Could not persist shared artifact to database', res.statusText);
            }
          }
        } catch (dbError) {
          logger.warn('Database error during artifact sharing', dbError);
        }

        // Store shareId on the artifact for local reference
        set((state) => {
          const artifact = state.artifacts.find((a) => a.id === artifactId);
          if (artifact) artifact.shareId = shareId;
        });

        return shareId;
      },

      reset: () => {
        set((state) => {
          state.artifacts = [];
          state.selectedArtifactId = null;
          state.panelOpen = false;
        });
      },
    })),
    {
      name: 'agi-artifacts-store',
      version: 1,
      storage: createJSONStorage(() => localStorage),
      // Only persist artifacts list; panel open state is session-scoped
      partialize: (state) => ({
        artifacts: state.artifacts,
        selectedArtifactId: state.selectedArtifactId,
      }),
      // Rehydrate createdAt strings back to Date objects
      onRehydrateStorage: () => (state) => {
        if (!state) return;
        state.artifacts = state.artifacts.map((a) => ({
          ...a,
          createdAt:
            a.createdAt instanceof Date ? a.createdAt : new Date(a.createdAt as unknown as string),
        }));
      },
    },
  ),
);
