export type AgiThemeMode = 'light' | 'dark';
export type CssVariableMap = Record<`--${string}`, string>;

/**
 * The brand ramps, mode invariant. foundation.css declares the same values as
 * `--hue-<family>` and `--hue-<family>-<step>` primitives; this mirror exists
 * for hosts that cannot import a stylesheet (mobile's Tailwind config, the
 * Chrome and VS Code panels). The two are asserted equal in both directions by
 * apps/web/shared/components/__tests__/theme-contrast.test.ts, so neither can
 * gain, lose or move a step alone. A surface reads these through a role, never
 * a step: a ramp entry is a hue, not a decision about where it renders.
 */
export const agiBrandScale = {
  cream: {
    50: '#fcfcf9',
    100: '#f9f9f6',
    200: '#f5f5f2',
  },
  charcoal: {
    700: '#363838',
    800: '#2a2c2c',
    900: '#1f2121',
  },
  'terra-cotta': {
    DEFAULT: '#da7756',
    50: '#f9e8e1',
    100: '#f5d4c8',
    200: '#ecad96',
    300: '#e38664',
    400: '#da7332',
    500: '#da7756',
    600: '#bd5d3a',
    700: '#743924',
    800: '#4d2618',
    900: '#27130c',
  },
  'warm-peach': {
    DEFAULT: '#f5c1a9',
    50: '#ffffff',
    100: '#fef9f6',
    200: '#fce8dd',
    300: '#fad7c4',
    400: '#f7c9b6',
    500: '#f5c1a9',
    600: '#f0a481',
    700: '#eb8759',
    800: '#e66a31',
    900: '#c64f14',
  },
  teal: {
    DEFAULT: '#21808d',
    50: '#8fd9e3',
    100: '#7dd3df',
    200: '#5ac7d7',
    300: '#3ab5c5',
    400: '#2d9ba8',
    500: '#21808d',
    600: '#196068',
    700: '#124043',
    800: '#0a201e',
    900: '#000000',
  },
  agent: {
    thinking: '#a855f7',
    active: '#3b82f6',
    success: '#10b981',
    error: '#ef4444',
    warning: '#f59e0b',
  },
} as const;

export type AgiBrandFamily = keyof typeof agiBrandScale;

/**
 * The `--hue-*` custom property foundation.css declares for one ramp entry.
 * Both the equality test and any host emitting a `var()` reference derive the
 * name here rather than spelling it, so a renamed family cannot leave a caller
 * pointing at a property that no longer exists.
 */
export function brandScaleVar(family: AgiBrandFamily, step: string): `--${string}` {
  return step === 'DEFAULT' ? `--hue-${family}` : `--hue-${family}-${step}`;
}

export const agiPalette = {
  light: {
    surface: {
      base: '#faf9f7',
      raised: '#ffffff',
      overlay: '#ffffff',
      hover: '#f0eeeb',
      sidebar: '#f5f4f1',
      input: '#ffffff',
      code: '#f6f8fa',
    },
    text: {
      primary: '#1a1915',
      secondary: '#595450',
      muted: '#65615b',
      placeholder: '#6f6a65',
    },
    border: {
      subtle: 'rgba(26, 25, 21, 0.08)',
      strong: 'rgba(26, 25, 21, 0.15)',
    },
    accent: {
      primary: '#21808d',
      secondary: '#da7756',
      secondarySoft: '#f5c1a9',
      secondaryHover: '#e38664',
      secondaryText: '#a44424',
      onSecondary: '#1c150b',
    },
    state: {
      danger: '#dc2626',
      info: '#2563eb',
      success: '#16a34a',
      warning: '#d97706',
    },
    stateText: {
      danger: '#c01f1f',
      info: '#1557e6',
      success: '#107535',
      warning: '#9a5504',
    },
    stateFillHover: {
      danger: '#b91c1c',
    },
    stateOnFill: {
      danger: '#ffffff',
    },
  },
  dark: {
    surface: {
      base: '#1a1915',
      raised: '#242220',
      overlay: '#2e2b28',
      hover: '#363330',
      sidebar: '#151410',
      input: '#242220',
      code: '#11100d',
    },
    text: {
      primary: '#e8e4db',
      secondary: '#b5b2ab',
      muted: '#a4a19b',
      placeholder: '#97958e',
    },
    border: {
      subtle: 'rgba(255, 235, 205, 0.08)',
      strong: 'rgba(255, 235, 205, 0.15)',
    },
    accent: {
      primary: '#21808d',
      secondary: '#da7756',
      secondarySoft: '#f5c1a9',
      secondaryHover: '#e38664',
      secondaryText: '#e39a81',
      onSecondary: '#1c150b',
    },
    state: {
      danger: '#ef4444',
      info: '#3b82f6',
      success: '#22c55e',
      warning: '#f59e0b',
    },
    stateText: {
      danger: '#f48181',
      info: '#689ff8',
      success: '#22c55e',
      warning: '#f59e0b',
    },
    stateFillHover: {
      danger: '#f87171',
    },
    stateOnFill: {
      danger: '#1c150b',
    },
  },
} as const;

export const agiCoolPalette = {
  light: {
    surface: {
      base: '#ffffff',
      raised: '#ffffff',
      overlay: '#ffffff',
      hover: '#f0f0f0',
      sidebar: '#f9f9f9',
      input: '#ffffff',
      code: '#f7f7f8',
    },
    text: {
      primary: '#0d0d0d',
      secondary: '#5d5d5d',
      muted: '#6a6a6a',
      placeholder: '#6a6a6a',
    },
    border: {
      subtle: 'rgba(0, 0, 0, 0.1)',
      strong: 'rgba(0, 0, 0, 0.16)',
    },
    accent: {
      primary: '#0b84ff',
      secondary: '#0a6ed1',
      secondarySoft: 'rgba(11, 132, 255, 0.12)',
    },
    state: {
      danger: '#dc2626',
      info: '#0b84ff',
      success: '#16a34a',
      warning: '#b45309',
    },
  },
  dark: {
    surface: {
      base: '#212121',
      raised: '#2f2f2f',
      overlay: '#2a2a2d',
      hover: '#2f2f2f',
      sidebar: '#171717',
      input: '#2f2f2f',
      code: '#1e1e1e',
    },
    text: {
      primary: '#ececec',
      secondary: '#b4b4b4',
      muted: '#999999',
      placeholder: '#999999',
    },
    border: {
      subtle: 'rgba(255, 255, 255, 0.1)',
      strong: 'rgba(255, 255, 255, 0.16)',
    },
    accent: {
      primary: '#0b84ff',
      secondary: '#0a6ed1',
      secondarySoft: 'rgba(11, 132, 255, 0.16)',
    },
    state: {
      danger: '#ef4444',
      info: '#0b84ff',
      success: '#22c55e',
      warning: '#ef8c57',
    },
  },
} as const;

/**
 * Concrete rungs of the --corner-* ladder foundation.css owns, in the same
 * size-named shape chat.css exposes. Emitted literally for hosts that cannot
 * import the stylesheet, so these must equal the rungs they mirror;
 * `agiRadiiVar` names which rung each size is, and the pair is asserted equal
 * in apps/web/shared/components/__tests__/theme-contrast.test.ts.
 */
export const agiRadii = {
  detail: '2px',
  compact: '4px',
  sm: '6px',
  md: '8px',
  menu: '10px',
  lg: '12px',
  xl: '16px',
  '2xl': '24px',
  '3xl': '32px',
  full: '9999px',
} as const;

export const agiRadiiVar = {
  detail: '--corner-detail',
  compact: '--corner-compact',
  sm: '--corner-control',
  md: '--corner-field',
  menu: '--corner-menu',
  lg: '--corner-surface',
  xl: '--corner-panel',
  '2xl': '--corner-overlay',
  '3xl': '--corner-hero',
  full: '--corner-pill',
} as const satisfies Record<keyof typeof agiRadii, `--${string}`>;

export const agiCornerCssVars = {
  '--corner-detail': agiRadii.detail,
  '--corner-compact': agiRadii.compact,
  '--corner-control': agiRadii.sm,
  '--corner-field': agiRadii.md,
  '--corner-menu': agiRadii.menu,
  '--corner-surface': agiRadii.lg,
  '--corner-panel': agiRadii.xl,
  '--corner-overlay': agiRadii['2xl'],
  '--corner-hero': agiRadii['3xl'],
  '--corner-pill': agiRadii.full,
} as const satisfies CssVariableMap &
  Record<(typeof agiRadiiVar)[keyof typeof agiRadiiVar], string>;

export const agiMotion = {
  duration: {
    instant: '90ms',
    quick: '160ms',
    moved: '260ms',
    reveal: '700ms',
  },
  curve: {
    standard: 'cubic-bezier(0.2, 0, 0, 1)',
    exit: 'cubic-bezier(0.4, 0, 1, 1)',
  },
} as const;

export const agiMotionCssVars = {
  '--duration-instant': agiMotion.duration.instant,
  '--duration-quick': agiMotion.duration.quick,
  '--duration-moved': agiMotion.duration.moved,
  '--duration-reveal': agiMotion.duration.reveal,
  '--curve-standard': agiMotion.curve.standard,
  '--curve-exit': agiMotion.curve.exit,
} as const satisfies CssVariableMap;

/**
 * Concrete family names, never the var(--font-*) indirection chat.css uses.
 * This map reaches surfaces only through `agiChatCssVars`, which is emitted as
 * a literal CSS block by `cssVarsToString` for hosts that cannot import the
 * stylesheet, none of which run next/font, so a var(--font-*) here would name
 * nothing. Keep the families in step with chat.css's fallbacks.
 *
 * The emoji faces sit last in every stack, after the generic family, so they
 * are consulted only for a codepoint no text face covers. A conversation title
 * carrying an emoji drew a missing-glyph box while the same character rendered
 * in the message body.
 */
const EMOJI_FACES = "'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'";

export const agiTypography = {
  sans: `'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif, ${EMOJI_FACES}`,
  serif: `'Newsreader', Georgia, 'Times New Roman', serif, ${EMOJI_FACES}`,
  display: `'Newsreader', Georgia, 'Times New Roman', serif, ${EMOJI_FACES}`,
  mono: `'JetBrains Mono', 'SF Mono', 'Menlo', 'Monaco', 'Consolas', monospace, ${EMOJI_FACES}`,
} as const;

/**
 * The four elevation rungs foundation.css owns, per theme. Three separate sets
 * of shadow literals used to describe the same rungs and disagreed with each
 * other and with the stylesheet; everything shadow-shaped now derives from here.
 * Emitted literally for hosts that cannot import the stylesheet, so these must
 * equal the rungs they mirror; asserted in
 * apps/web/shared/components/__tests__/theme-contrast.test.ts.
 */
export const agiElevation = {
  light: {
    1: '0 1px 2px rgb(8 10 12 / 0.06)',
    2: '0 2px 4px rgb(8 10 12 / 0.06), 0 4px 12px -4px rgb(8 10 12 / 0.1)',
    3: '0 4px 8px rgb(8 10 12 / 0.06), 0 12px 32px -8px rgb(8 10 12 / 0.14)',
    4: '0 8px 16px rgb(8 10 12 / 0.08), 0 24px 64px -12px rgb(8 10 12 / 0.2)',
  },
  dark: {
    1: '0 1px 2px rgb(0 0 0 / 0.5)',
    2: '0 2px 4px rgb(0 0 0 / 0.4), 0 4px 12px -4px rgb(0 0 0 / 0.6)',
    3: '0 4px 8px rgb(0 0 0 / 0.4), 0 12px 32px -8px rgb(0 0 0 / 0.7)',
    4: '0 8px 16px rgb(0 0 0 / 0.45), 0 24px 64px -12px rgb(0 0 0 / 0.8)',
  },
} as const satisfies Record<AgiThemeMode, Record<1 | 2 | 3 | 4, string>>;

export const agiShadows = {
  sm: agiElevation.light[1],
  md: agiElevation.light[2],
  lg: agiElevation.light[3],
} as const;

export const agiChatCssVars = {
  light: {
    '--chat-bg': agiPalette.light.surface.base,
    '--chat-fg': agiPalette.light.text.primary,
    '--chat-surface-base': agiPalette.light.surface.base,
    '--chat-surface-elevated': agiPalette.light.surface.raised,
    '--chat-surface-overlay': agiPalette.light.surface.overlay,
    '--chat-surface-hover': agiPalette.light.surface.hover,
    '--chat-loading-placeholder': agiPalette.light.surface.hover,
    '--chat-loading-indicator': agiPalette.light.text.muted,
    '--chat-sidebar-bg': agiPalette.light.surface.sidebar,
    '--chat-input-bg': agiPalette.light.surface.input,
    '--chat-code-bg': agiPalette.light.surface.code,
    '--chat-text-primary': agiPalette.light.text.primary,
    '--chat-text-secondary': agiPalette.light.text.secondary,
    '--chat-text-muted': agiPalette.light.text.muted,
    '--chat-text-placeholder': agiPalette.light.text.placeholder,
    '--chat-border': agiPalette.light.border.subtle,
    '--chat-border-strong': agiPalette.light.border.strong,
    '--chat-border-subtle': agiPalette.light.border.subtle,
    '--chat-accent-primary': agiPalette.light.accent.secondary,
    '--chat-accent-secondary': agiPalette.light.accent.primary,
    '--chat-user-bubble-bg': agiPalette.light.surface.hover,
    '--chat-thinking-text': agiPalette.light.text.secondary,
    '--chat-thinking-line': agiPalette.light.border.subtle,
    '--chat-badge-neutral': agiPalette.light.text.muted,
    '--chat-destructive': agiPalette.light.state.danger,
    '--chat-info': agiPalette.light.state.info,
    '--chat-success': agiPalette.light.state.success,
    '--chat-warning': agiPalette.light.state.warning,
    '--chat-radius-sm': agiRadii.sm,
    '--chat-radius-md': agiRadii.md,
    '--chat-radius-lg': agiRadii.lg,
    '--chat-radius-xl': agiRadii.xl,
    '--chat-radius-2xl': agiRadii['2xl'],
    '--chat-user-bubble-radius': agiRadii.xl,
    '--chat-font-sans': agiTypography.sans,
    '--chat-font-serif': agiTypography.serif,
    '--chat-font-display': agiTypography.display,
    '--chat-font-mono': agiTypography.mono,
    '--chat-shadow-sm': agiShadows.sm,
    '--chat-shadow-md': agiShadows.md,
    '--chat-shadow-lg': agiShadows.lg,
  },
  dark: {
    '--chat-bg': agiPalette.dark.surface.base,
    '--chat-fg': agiPalette.dark.text.primary,
    '--chat-surface-base': agiPalette.dark.surface.base,
    '--chat-surface-elevated': agiPalette.dark.surface.raised,
    '--chat-surface-overlay': agiPalette.dark.surface.overlay,
    '--chat-surface-hover': agiPalette.dark.surface.hover,
    '--chat-loading-placeholder': agiPalette.dark.surface.hover,
    '--chat-loading-indicator': agiPalette.dark.text.muted,
    '--chat-sidebar-bg': agiPalette.dark.surface.sidebar,
    '--chat-input-bg': agiPalette.dark.surface.input,
    '--chat-code-bg': agiPalette.dark.surface.code,
    '--chat-text-primary': agiPalette.dark.text.primary,
    '--chat-text-secondary': agiPalette.dark.text.secondary,
    '--chat-text-muted': agiPalette.dark.text.muted,
    '--chat-text-placeholder': agiPalette.dark.text.placeholder,
    '--chat-border': agiPalette.dark.border.subtle,
    '--chat-border-strong': agiPalette.dark.border.strong,
    '--chat-border-subtle': agiPalette.dark.border.subtle,
    '--chat-accent-primary': agiPalette.dark.accent.secondary,
    '--chat-accent-secondary': agiPalette.dark.accent.primary,
    '--chat-user-bubble-bg': '#2a2724',
    '--chat-thinking-text': agiPalette.dark.text.secondary,
    '--chat-thinking-line': agiPalette.dark.border.subtle,
    '--chat-badge-neutral': agiPalette.dark.text.placeholder,
    '--chat-destructive': agiPalette.dark.state.danger,
    '--chat-info': agiPalette.dark.state.info,
    '--chat-success': agiPalette.dark.state.success,
    '--chat-warning': agiPalette.dark.state.warning,
    '--chat-radius-sm': agiRadii.sm,
    '--chat-radius-md': agiRadii.md,
    '--chat-radius-lg': agiRadii.lg,
    '--chat-radius-xl': agiRadii.xl,
    '--chat-radius-2xl': agiRadii['2xl'],
    '--chat-user-bubble-radius': agiRadii.xl,
    '--chat-font-sans': agiTypography.sans,
    '--chat-font-serif': agiTypography.serif,
    '--chat-font-display': agiTypography.display,
    '--chat-font-mono': agiTypography.mono,
    '--chat-shadow-sm': agiElevation.dark[1],
    '--chat-shadow-md': agiElevation.dark[2],
    '--chat-shadow-lg': agiElevation.dark[3],
  },
} as const satisfies Record<AgiThemeMode, CssVariableMap>;

export const agiNativeColors = {
  light: {
    terraCotta: agiPalette.light.accent.secondary,
    teal: agiPalette.light.accent.primary,
    warmPeach: agiPalette.light.accent.secondarySoft,
    background: agiPalette.light.surface.base,
    surfaceBase: agiPalette.light.surface.base,
    surfaceElevated: agiPalette.light.surface.raised,
    surfaceOverlay: agiPalette.light.surface.overlay,
    surfaceHover: agiPalette.light.surface.hover,
    textPrimary: agiPalette.light.text.primary,
    textSecondary: 'rgba(26, 25, 21, 0.75)',
    textMuted: 'rgba(26, 25, 21, 0.5)',
    border: agiPalette.light.border.subtle,
    borderLight: 'rgba(26, 25, 21, 0.06)',
    charcoal900: '#f0f0f0',
    charcoal800: '#e5e5e5',
    charcoal700: '#d4d4d4',
    agentThinking: '#a855f7',
    agentActive: '#3b82f6',
    agentSuccess: '#10b981',
    agentError: '#ef4444',
    agentWarning: '#f59e0b',
    white: '#ffffff',
    black: '#000000',
    transparent: 'transparent',
    scrim: 'rgba(0, 0, 0, 0.55)',
  },
  dark: {
    terraCotta: agiPalette.dark.accent.secondary,
    teal: agiPalette.dark.accent.primary,
    warmPeach: agiPalette.dark.accent.secondarySoft,
    background: agiPalette.dark.surface.base,
    surfaceBase: agiPalette.dark.surface.base,
    surfaceElevated: agiPalette.dark.surface.raised,
    surfaceOverlay: agiPalette.dark.surface.overlay,
    surfaceHover: agiPalette.dark.surface.hover,
    textPrimary: agiPalette.dark.text.primary,
    textSecondary: 'rgba(232, 228, 219, 0.75)',
    textMuted: 'rgba(232, 228, 219, 0.5)',
    border: agiPalette.dark.border.subtle,
    borderLight: 'rgba(255, 235, 205, 0.06)',
    charcoal900: '#1f2121',
    charcoal800: '#2a2c2c',
    charcoal700: '#363838',
    agentThinking: '#a855f7',
    agentActive: '#3b82f6',
    agentSuccess: '#10b981',
    agentError: '#ef4444',
    agentWarning: '#f59e0b',
    white: '#ffffff',
    black: '#000000',
    transparent: 'transparent',
    scrim: 'rgba(0, 0, 0, 0.55)',
  },
} as const;

export const agiMobileColors = {
  light: {
    terraCotta: '#111111',
    teal: '#111111',
    warmPeach: '#ececec',
    background: '#ffffff',
    surfaceBase: '#f7f7f7',
    surfaceElevated: '#ffffff',
    surfaceOverlay: '#ffffff',
    surfaceHover: '#ececec',
    textPrimary: '#111111',
    textSecondary: 'rgba(17, 17, 17, 0.72)',
    textMuted: 'rgba(17, 17, 17, 0.62)',
    border: 'rgba(17, 17, 17, 0.09)',
    borderLight: 'rgba(17, 17, 17, 0.06)',
    charcoal900: '#f7f7f7',
    charcoal800: '#eeeeee',
    charcoal700: '#dddddd',
    agentThinking: '#7138f4',
    agentActive: '#1557e7',
    agentSuccess: '#0c755c',
    agentError: '#c01f1f',
    agentWarning: '#9b5504',
    accentSurface: 'rgba(17, 17, 17, 0.08)',
    accentBorder: 'rgba(17, 17, 17, 0.16)',
    accentText: '#ffffff',
    inputSurface: 'rgba(17, 17, 17, 0.03)',
    composerBorder: 'rgba(17, 17, 17, 0.08)',
    successSurface: 'rgba(16, 163, 127, 0.08)',
    successBorder: 'rgba(16, 163, 127, 0.35)',
    warningSurface: 'rgba(217, 119, 6, 0.12)',
    warningBorder: 'rgba(217, 119, 6, 0.28)',
    dangerSurface: 'rgba(220, 38, 38, 0.10)',
    dangerBorder: 'rgba(220, 38, 38, 0.28)',
    diffAddedFill: '#dcf5e4',
    diffAddedText: '#0f5a32',
    diffRemovedFill: '#fde6e6',
    diffRemovedText: '#8f1d22',
    neutralSurface: 'rgba(17, 17, 17, 0.08)',
    neutralBorder: 'rgba(17, 17, 17, 0.16)',
    purple: '#7834ec',
    purpleSurface: 'rgba(124, 58, 237, 0.12)',
    progressTrack: 'rgba(17, 17, 17, 0.08)',
    brandAmber: '#f0a84a',
    white: '#ffffff',
    black: '#000000',
    transparent: 'transparent',
    scrim: 'rgba(0, 0, 0, 0.46)',
    cameraOverlaySurface: 'rgba(0, 0, 0, 0.50)',
    cameraOverlaySurfaceStrong: 'rgba(0, 0, 0, 0.75)',
    cameraOverlayBorder: 'rgba(255, 255, 255, 0.16)',
    cameraOverlayText: '#ffffff',
    cameraOverlayTextMuted: 'rgba(255, 255, 255, 0.68)',
    cameraScanRegionSurface: 'rgba(16, 163, 127, 0.20)',
    cameraScanRegionBorder: 'rgba(16, 163, 127, 0.75)',
    cameraShutterBorder: 'rgba(255, 255, 255, 0.35)',
    voiceCompanionBgStart: '#2a1010',
    voiceCompanionBgMid: '#0e0808',
    voiceCompanionBgEnd: '#050305',
    voiceConversationBgStart: '#1a1040',
    voiceConversationBgMid: '#0d0d1a',
    voiceConversationBgEnd: '#050508',
    voiceOrbStart: '#8b8cf7',
    voiceOrbMid: '#c4c8fb',
    voiceOrbEnd: '#f2f4ff',
    voiceControlSurface: 'rgba(255, 255, 255, 0.10)',
    voiceTranscriptSurface: 'rgba(255, 255, 255, 0.04)',
    voiceAccentBorder: 'rgba(244, 244, 244, 0.20)',
    voiceSheetSurface: 'rgba(12, 12, 16, 0.97)',
    voiceOverlaySurface: 'rgba(15, 15, 15, 0.95)',
    voiceTextMuted: 'rgba(255, 255, 255, 0.64)',
    voiceTextSubtle: 'rgba(255, 255, 255, 0.52)',
  },
  dark: {
    terraCotta: '#f4f4f4',
    teal: '#f4f4f4',
    warmPeach: '#2f2f2f',
    background: '#0f0f0f',
    surfaceBase: '#171717',
    surfaceElevated: '#212121',
    surfaceOverlay: '#2a2a2a',
    surfaceHover: '#303030',
    textPrimary: '#f4f4f4',
    textSecondary: 'rgba(244, 244, 244, 0.74)',
    textMuted: 'rgba(244, 244, 244, 0.56)',
    border: 'rgba(255, 255, 255, 0.10)',
    borderLight: 'rgba(255, 255, 255, 0.06)',
    charcoal900: '#111111',
    charcoal800: '#1f1f1f',
    charcoal700: '#2f2f2f',
    agentThinking: '#a78bfa',
    agentActive: '#64a8fa',
    agentSuccess: '#11ad87',
    agentError: '#f87171',
    agentWarning: '#fbbf24',
    accentSurface: 'rgba(244, 244, 244, 0.12)',
    accentBorder: 'rgba(244, 244, 244, 0.24)',
    accentText: '#000000',
    inputSurface: 'rgba(255, 255, 255, 0.04)',
    composerBorder: 'rgba(255, 255, 255, 0.08)',
    successSurface: 'rgba(16, 163, 127, 0.12)',
    successBorder: 'rgba(16, 163, 127, 0.36)',
    warningSurface: 'rgba(251, 191, 36, 0.14)',
    warningBorder: 'rgba(251, 191, 36, 0.30)',
    dangerSurface: 'rgba(248, 113, 113, 0.13)',
    dangerBorder: 'rgba(248, 113, 113, 0.32)',
    diffAddedFill: '#0f2e1d',
    diffAddedText: '#7fd6a8',
    diffRemovedFill: '#3a1216',
    diffRemovedText: '#f5a3a8',
    neutralSurface: 'rgba(255, 255, 255, 0.07)',
    neutralBorder: 'rgba(255, 255, 255, 0.12)',
    purple: '#a78bfa',
    purpleSurface: 'rgba(167, 139, 250, 0.14)',
    progressTrack: 'rgba(255, 255, 255, 0.08)',
    brandAmber: '#f0a84a',
    white: '#ffffff',
    black: '#000000',
    transparent: 'transparent',
    scrim: 'rgba(0, 0, 0, 0.62)',
    cameraOverlaySurface: 'rgba(0, 0, 0, 0.50)',
    cameraOverlaySurfaceStrong: 'rgba(0, 0, 0, 0.75)',
    cameraOverlayBorder: 'rgba(255, 255, 255, 0.16)',
    cameraOverlayText: '#ffffff',
    cameraOverlayTextMuted: 'rgba(255, 255, 255, 0.68)',
    cameraScanRegionSurface: 'rgba(16, 163, 127, 0.20)',
    cameraScanRegionBorder: 'rgba(16, 163, 127, 0.75)',
    cameraShutterBorder: 'rgba(255, 255, 255, 0.35)',
    voiceCompanionBgStart: '#2a1010',
    voiceCompanionBgMid: '#0e0808',
    voiceCompanionBgEnd: '#050305',
    voiceConversationBgStart: '#1a1040',
    voiceConversationBgMid: '#0d0d1a',
    voiceConversationBgEnd: '#050508',
    voiceOrbStart: '#8b8cf7',
    voiceOrbMid: '#c4c8fb',
    voiceOrbEnd: '#f2f4ff',
    voiceControlSurface: 'rgba(255, 255, 255, 0.10)',
    voiceTranscriptSurface: 'rgba(255, 255, 255, 0.04)',
    voiceAccentBorder: 'rgba(244, 244, 244, 0.20)',
    voiceSheetSurface: 'rgba(12, 12, 16, 0.97)',
    voiceOverlaySurface: 'rgba(15, 15, 15, 0.95)',
    voiceTextMuted: 'rgba(255, 255, 255, 0.64)',
    voiceTextSubtle: 'rgba(255, 255, 255, 0.52)',
  },
} as const;

export const agiMobileHighContrastColors = {
  dark: {
    ...agiMobileColors.dark,
    terraCotta: '#ffffff',
    teal: '#ffffff',
    background: '#000000',
    surfaceBase: '#000000',
    surfaceElevated: '#111111',
    surfaceOverlay: '#1a1a1a',
    surfaceHover: '#262626',
    textPrimary: '#ffffff',
    textSecondary: '#ffffff',
    textMuted: '#d9d9d9',
    border: '#ffffff',
    borderLight: '#a6a6a6',
    accentSurface: '#262626',
    accentBorder: '#ffffff',
    inputSurface: '#111111',
    composerBorder: '#ffffff',
    successBorder: '#66e0bd',
    warningBorder: '#ffd666',
    dangerBorder: '#ff8f8f',
    neutralSurface: '#1a1a1a',
    neutralBorder: '#ffffff',
    progressTrack: '#737373',
    cameraOverlayBorder: '#ffffff',
    cameraOverlayTextMuted: '#ffffff',
    cameraScanRegionBorder: '#66e0bd',
    cameraShutterBorder: '#ffffff',
    voiceControlSurface: '#262626',
    voiceTranscriptSurface: '#111111',
    voiceAccentBorder: '#ffffff',
  },
  light: {
    ...agiMobileColors.light,
    terraCotta: '#000000',
    teal: '#000000',
    warmPeach: '#e0e0e0',
    background: '#ffffff',
    surfaceBase: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceOverlay: '#f2f2f2',
    surfaceHover: '#e0e0e0',
    textPrimary: '#000000',
    textSecondary: '#000000',
    textMuted: '#333333',
    agentThinking: '#6b2ff4',
    agentActive: '#1454de',
    agentSuccess: '#006b52',
    agentError: '#a60000',
    agentWarning: '#8a4200',
    purple: '#742eeb',
    border: '#000000',
    borderLight: '#595959',
    accentSurface: '#e0e0e0',
    accentBorder: '#000000',
    inputSurface: '#ffffff',
    composerBorder: '#000000',
    successBorder: '#006b52',
    warningBorder: '#8a4200',
    dangerBorder: '#a60000',
    neutralSurface: '#f2f2f2',
    neutralBorder: '#000000',
    progressTrack: '#737373',
    cameraOverlayBorder: '#ffffff',
    cameraOverlayTextMuted: '#ffffff',
    cameraScanRegionBorder: '#66e0bd',
    cameraShutterBorder: '#ffffff',
    voiceControlSurface: '#262626',
    voiceTranscriptSurface: '#111111',
    voiceAccentBorder: '#ffffff',
  },
} as const;

export const agiMobileAccentSwatches = {
  neutral: {
    light: agiMobileColors.light.textPrimary,
    dark: agiMobileColors.dark.textPrimary,
  },
  green: { light: '#0c735a', dark: '#12bb91' },
  blue: { light: '#1658ea', dark: '#64a8fa' },
  violet: { light: '#7a38ed', dark: '#af95fa' },
  rose: { light: '#c61a3f', dark: '#fb7e90' },
  amber: { light: '#a44c08', dark: '#fbbf24' },
} as const;

export const agiMobileNotificationLedColors = {
  critical: '#ef4444',
  high: '#f59e0b',
  normal: '#21808d',
  low: '#21808d',
} as const;

export const agiProjectAccents = [
  { id: 'emerald', label: 'Emerald', hex: '#10b981' },
  { id: 'sky', label: 'Sky', hex: '#0ea5e9' },
  { id: 'amber', label: 'Amber', hex: '#f59e0b' },
  { id: 'rose', label: 'Rose', hex: '#f43f5e' },
  { id: 'violet', label: 'Violet', hex: '#8b5cf6' },
  { id: 'zinc', label: 'Zinc', hex: '#71717a' },
] as const;

export const agiExtensionCssVars = {
  dark: {
    '--agi-ext-bg': agiPalette.dark.surface.base,
    '--agi-ext-surface': agiPalette.dark.surface.raised,
    '--agi-ext-overlay': agiPalette.dark.surface.overlay,
    '--agi-ext-hover': agiPalette.dark.surface.hover,
    '--agi-ext-text': agiPalette.dark.text.primary,
    '--agi-ext-text-muted': agiPalette.dark.text.secondary,
    '--agi-ext-text-placeholder': agiPalette.dark.text.placeholder,
    '--agi-ext-border': agiPalette.dark.border.subtle,
    '--agi-ext-border-strong': agiPalette.dark.border.strong,
    '--agi-ext-accent': agiPalette.dark.accent.secondary,
    '--agi-ext-accent-hover': agiPalette.dark.accent.secondaryHover,
    '--agi-ext-accent-text': agiPalette.dark.accent.secondaryText,
    '--agi-ext-accent-secondary': agiPalette.dark.accent.primary,
    '--agi-ext-focus': agiPalette.dark.accent.secondaryText,
    '--agi-ext-brand': agiPalette.dark.accent.secondary,
    '--agi-ext-brand-alt': agiPalette.dark.accent.primary,
    '--agi-ext-on-accent': agiPalette.dark.accent.onSecondary,
    '--agi-ext-toggle-knob': '#ffffff',
    '--agi-ext-shadow-panel': 'rgba(0, 0, 0, 0.12)',
    '--agi-ext-danger': agiPalette.dark.state.danger,
    '--agi-ext-danger-hover': agiPalette.dark.stateFillHover.danger,
    '--agi-ext-on-danger': agiPalette.dark.stateOnFill.danger,
    '--agi-ext-danger-text': agiPalette.dark.stateText.danger,
    '--agi-ext-danger-bg': 'rgba(239, 68, 68, 0.12)',
    '--agi-ext-danger-border': 'rgba(239, 68, 68, 0.3)',
    '--agi-ext-danger-shadow': 'rgba(220, 38, 38, 0.4)',
    '--agi-ext-transparent-shadow': 'rgba(220, 38, 38, 0)',
    '--agi-ext-success': agiPalette.dark.state.success,
    '--agi-ext-success-text': agiPalette.dark.stateText.success,
    '--agi-ext-success-bg': 'rgba(34, 197, 94, 0.12)',
    '--agi-ext-success-border': 'rgba(34, 197, 94, 0.32)',
    '--agi-ext-warning': agiPalette.dark.state.warning,
    '--agi-ext-warning-text': agiPalette.dark.stateText.warning,
    '--agi-ext-warning-bg': 'rgba(239, 140, 87, 0.12)',
    '--agi-ext-warning-border': 'rgba(239, 140, 87, 0.32)',
    '--agi-ext-info-text': agiPalette.dark.stateText.info,
    '--agi-ext-modal-shadow': 'rgba(0, 0, 0, 0.5)',
    '--agi-ext-scrim': 'rgba(0, 0, 0, 0.6)',
    '--agi-ext-elevation-1': agiElevation.dark[1],
    '--agi-ext-elevation-2': agiElevation.dark[2],
    '--agi-ext-elevation-3': agiElevation.dark[3],
    '--agi-ext-elevation-4': agiElevation.dark[4],
  },
  light: {
    '--agi-ext-bg': agiPalette.light.surface.base,
    '--agi-ext-surface': agiPalette.light.surface.raised,
    '--agi-ext-overlay': agiPalette.light.surface.overlay,
    '--agi-ext-hover': agiPalette.light.surface.hover,
    '--agi-ext-text': agiPalette.light.text.primary,
    '--agi-ext-text-muted': agiPalette.light.text.secondary,
    '--agi-ext-text-placeholder': agiPalette.light.text.placeholder,
    '--agi-ext-border': agiPalette.light.border.subtle,
    '--agi-ext-border-strong': agiPalette.light.border.strong,
    '--agi-ext-accent': agiPalette.light.accent.secondary,
    '--agi-ext-accent-hover': agiPalette.light.accent.secondaryHover,
    '--agi-ext-accent-text': agiPalette.light.accent.secondaryText,
    '--agi-ext-accent-secondary': agiPalette.light.accent.primary,
    '--agi-ext-focus': agiPalette.light.accent.secondaryText,
    '--agi-ext-brand': agiPalette.light.accent.secondary,
    '--agi-ext-brand-alt': agiPalette.light.accent.primary,
    '--agi-ext-on-accent': agiPalette.light.accent.onSecondary,
    '--agi-ext-toggle-knob': '#ffffff',
    '--agi-ext-shadow-panel': 'rgba(0, 0, 0, 0.12)',
    '--agi-ext-danger': agiPalette.light.state.danger,
    '--agi-ext-danger-hover': agiPalette.light.stateFillHover.danger,
    '--agi-ext-on-danger': agiPalette.light.stateOnFill.danger,
    '--agi-ext-danger-text': agiPalette.light.stateText.danger,
    '--agi-ext-danger-bg': 'rgba(220, 38, 38, 0.08)',
    '--agi-ext-danger-border': 'rgba(220, 38, 38, 0.24)',
    '--agi-ext-danger-shadow': 'rgba(220, 38, 38, 0.3)',
    '--agi-ext-transparent-shadow': 'rgba(220, 38, 38, 0)',
    '--agi-ext-success': agiPalette.light.state.success,
    '--agi-ext-success-text': agiPalette.light.stateText.success,
    '--agi-ext-success-bg': 'rgba(22, 163, 74, 0.08)',
    '--agi-ext-success-border': 'rgba(22, 163, 74, 0.24)',
    '--agi-ext-warning': agiPalette.light.state.warning,
    '--agi-ext-warning-text': agiPalette.light.stateText.warning,
    '--agi-ext-warning-bg': 'rgba(180, 83, 9, 0.08)',
    '--agi-ext-warning-border': 'rgba(180, 83, 9, 0.24)',
    '--agi-ext-info-text': agiPalette.light.stateText.info,
    '--agi-ext-modal-shadow': 'rgba(0, 0, 0, 0.32)',
    '--agi-ext-scrim': 'rgba(0, 0, 0, 0.45)',
    '--agi-ext-elevation-1': agiElevation.light[1],
    '--agi-ext-elevation-2': agiElevation.light[2],
    '--agi-ext-elevation-3': agiElevation.light[3],
    '--agi-ext-elevation-4': agiElevation.light[4],
  },
} as const satisfies Record<AgiThemeMode, CssVariableMap>;

export const agiVsCodeCssVars = {
  // 2026-06-13 (#09090b / #5e6ad2) with {@link agiCoolPalette}, so this panel,
  '--agi-vscode-bg': agiCoolPalette.dark.surface.base,
  '--agi-vscode-surface': agiCoolPalette.dark.surface.sidebar,
  '--agi-vscode-overlay': agiCoolPalette.dark.surface.overlay,
  '--agi-vscode-text': agiCoolPalette.dark.text.primary,
  '--agi-vscode-text-muted': agiCoolPalette.dark.text.secondary,
  '--agi-vscode-border': agiCoolPalette.dark.border.strong,
  '--agi-vscode-button': agiCoolPalette.dark.accent.primary,
  '--agi-vscode-button-text': '#ffffff',
  '--agi-vscode-focus': agiCoolPalette.dark.accent.primary,
  '--agi-vscode-hover': agiCoolPalette.dark.surface.hover,
  '--agi-vscode-terra': agiCoolPalette.dark.accent.secondary,
  '--agi-vscode-success': agiCoolPalette.dark.state.success,
  '--agi-vscode-warning': agiCoolPalette.dark.state.warning,
  '--agi-vscode-warning-bg': 'rgba(239, 140, 87, 0.12)',
  '--agi-vscode-warning-border': 'rgba(239, 140, 87, 0.32)',
  '--agi-vscode-danger': 'var(--vscode-errorForeground, #ef4444)',
  '--agi-vscode-danger-bg': 'rgba(239, 68, 68, 0.12)',
  '--agi-vscode-danger-border': 'rgba(239, 68, 68, 0.3)',
  '--agi-vscode-diff-added-bg':
    'var(--vscode-diffEditor-insertedLineBackground, rgba(76, 175, 80, 0.08))',
  '--agi-vscode-diff-removed-bg':
    'var(--vscode-diffEditor-removedLineBackground, rgba(244, 67, 54, 0.08))',
  '--agi-vscode-diff-modified-bg': 'rgba(255, 152, 0, 0.06)',
  '--agi-vscode-diff-added-gutter': 'var(--vscode-diffEditor-insertedTextBorder, #4caf50)',
  '--agi-vscode-diff-removed-gutter': 'var(--vscode-diffEditor-removedTextBorder, #f44336)',
  '--agi-vscode-diff-modified-gutter': '#ff9800',
} as const satisfies CssVariableMap;

export function cssVarsToString(vars: CssVariableMap): string {
  return Object.entries(vars)
    .map(([name, value]) => `${name}: ${value};`)
    .join('\n');
}
