import 'server-only';

import { NextRequest, NextResponse } from 'next/server';
import { withErrorHandler } from '@/lib/error-handler';
import { withRateLimit } from '@/lib/rate-limit';
import { createError } from '@/lib/errors';
import { getClerkAuthUser } from '@/lib/api-auth';
import { getMediaAssetById } from '@/lib/server/media-assets';
import { isMediaStorageConfigured, readStoredMedia } from '@/lib/server/media-storage';
import { handleCorsPreflightRequest, withCorsRoute } from '@/lib/cors';
import { servedByteHeaders } from '@/lib/security/served-bytes';
import {
  aiGeneratedHeaders,
  hasAiGeneratedProvenance,
  type AiGeneratedProvenance,
} from '@/lib/compliance/ai-act';

/**
 * GET /api/files/[id] — authenticated, owner-scoped, same-origin byte serving
 * for generated files (code-interpreter outputs, generated images, CSVs, PDFs)
 * persisted in `media_assets` plus R2 in production or local development
 * media storage.
 *
 * Why this exists: the chat renderers deliberately gate what they will render
 * inline — the PDF viewer accepts only `data:application/pdf`, same-origin
 * `blob:`, or a same-origin http(s)/relative URL; images accept data:/blob:/
 * same-origin. The raw R2 public URL is cross-origin, so bytes stored there
 * are downloadable but never inline-renderable. This route re-serves the
 * stored bytes from the app's own origin so those gates accept them.
 *
 * Contract (also consumed by mobile/desktop cloud surfaces later):
 *   GET /api/files/{mediaAssetId}
 *   Auth: Clerk session cookie (browser) or `Authorization: Bearer <jwt>`
 *         (mobile/desktop/CLI) — same dual path as every other API route.
 *   200: raw bytes; Content-Type from the asset row and an inline
 *        Content-Disposition carrying the original filename — EXCEPT for types
 *        a browser executes as a document (html/svg/xml), which are demoted to
 *        `application/octet-stream` + `attachment`; Cache-Control private; plus
 *        `x-agi-ai-generated`/`x-agi-ai-provenance` when the row carries an
 *        Article 50(2) claim.
 *   401: unauthenticated · 403: asset belongs to another user ·
 *   404: unknown/deleted asset · 413: asset exceeds the serve cap.
 */

type RouteContext = { params: Promise<{ id: string }> };

/** Serve cap — matches the harvest-side cap plus headroom; nothing bigger is
 * ever persisted by the generated-file pipelines (20MB per-file harvest cap). */
const MAX_SERVE_BYTES = 30 * 1024 * 1024;

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** RFC 6266 filename sanitization: keep a conservative ASCII subset. */
function safeFilename(name: unknown): string {
  const raw = typeof name === 'string' && name.trim() ? name.trim() : 'file';
  return raw.replace(/[^a-zA-Z0-9._ -]/g, '_').slice(0, 128);
}

async function handleGetFile(request: NextRequest, context: RouteContext): Promise<NextResponse> {
  const rateLimitResponse = await withRateLimit(request, 'files-serve');
  if (rateLimitResponse) return rateLimitResponse;

  const { userId } = await getClerkAuthUser(request);
  const { id } = await context.params;

  if (!UUID_RE.test(id)) {
    throw createError.notFound('File not found');
  }

  const asset = await getMediaAssetById(id);
  if (!asset || asset.deletedAt) {
    throw createError.notFound('File not found');
  }
  if (asset.userId !== userId) {
    // Owner-scoped: generated files are never shared cross-user through this
    // route. (Sharing flows have their own explicit share endpoints.)
    throw createError.forbidden('You do not have access to this file');
  }

  const isPdfPreview = new URL(request.url).searchParams.get('preview') === 'pdf';
  if (isPdfPreview && asset.mimeType.toLowerCase() !== 'application/pdf') {
    // Fail closed: the same-origin frame exception belongs only to inert PDF
    // bytes. In particular, never allow generated text/html through it.
    throw createError.notFound('PDF preview not available');
  }

  if (asset.byteSize != null && asset.byteSize > MAX_SERVE_BYTES) {
    return NextResponse.json(
      { error: { code: 'PAYLOAD_TOO_LARGE', message: 'File exceeds the inline serving limit' } },
      { status: 413 },
    );
  }

  if (!isMediaStorageConfigured() || !asset.storagePathname) {
    // No byte source we can proxy — honest 404 rather than a redirect to a
    // cross-origin URL the renderer gates would reject anyway.
    throw createError.notFound('File bytes are not available');
  }

  const object = await readStoredMedia(asset.storagePathname);
  if (!object) {
    throw createError.notFound('File bytes are not available');
  }
  if (object.data.byteLength > MAX_SERVE_BYTES) {
    return NextResponse.json(
      { error: { code: 'PAYLOAD_TOO_LARGE', message: 'File exceeds the inline serving limit' } },
      { status: 413 },
    );
  }

  const filename = safeFilename(asset.metadata['filename']);

  // EU AI Act Article 50(2). This route is how generated bytes actually leave
  // the product — the chat renderers, the Library preview and every download
  // read them from here — so the mark the generation route persisted onto the
  // asset row has to be re-emitted here or it never reaches a consumer.
  // Validated first: a row whose `metadata.aiAct` is absent (an upload) or not
  // a well-formed claim serves no marker rather than a misleading one.
  const claim = asset.metadata['aiAct'];
  const provenanceHeaders = hasAiGeneratedProvenance(claim)
    ? aiGeneratedHeaders(claim as AiGeneratedProvenance)
    : {};

  // A generated file is model- or sandbox-authored, so `text/html`/`.svg`
  // bytes served `inline` under their own type would execute as a document on
  // this origin on a top-level navigation. `servedByteHeaders` demotes exactly
  // those to an opaque download; images, PDFs, CSV and text are unchanged.
  const served = servedByteHeaders({
    contentType: asset.mimeType || object.contentType || 'application/octet-stream',
    filename,
  });

  const body = new Uint8Array(object.data);
  return new NextResponse(body, {
    status: 200,
    headers: {
      'Content-Type': served.contentType,
      'Content-Length': String(object.data.byteLength),
      'Content-Disposition': served.contentDisposition,
      ...provenanceHeaders,
      // Private: bytes are owner-scoped; never let a shared cache hold them.
      'Cache-Control': 'private, max-age=3600',
      'X-Content-Type-Options': 'nosniff',
      ...(isPdfPreview
        ? {
            'Content-Security-Policy':
              "default-src 'none'; frame-ancestors 'self'; object-src 'none'",
            'X-Frame-Options': 'SAMEORIGIN',
          }
        : {}),
    },
  });
}

export const GET = withCorsRoute(withErrorHandler(handleGetFile));

export function OPTIONS(request: NextRequest): NextResponse {
  return handleCorsPreflightRequest(request) ?? new NextResponse(null, { status: 204 });
}
