export {
  FREE_PLAN_TRAINING_DATA_DISCLOSURE,
  FREE_PLAN_TRAINING_SIGNUP_STATEMENT,
  FREE_PLAN_TRAINING_SIGNUP_NOTICE,
  FREE_PLAN_TRAINING_SIGNUP_NOTICE_LINK_LABEL,
  FREE_PLAN_TRAINING_TERMS_CARD_TITLE,
  FREE_PLAN_TRAINING_TERMS_CARD_BODY,
  FREE_PLAN_TRAINING_TERMS_CARD_LINK_LABEL,
  FREE_PLAN_TRAINING_NOTICE_TITLE,
  FREE_PLAN_TRAINING_NOTICE_LEAD,
  FREE_PLAN_TRAINING_NOTICE_TAIL,
  FREE_PLAN_TRAINING_NOTICE_LINK_LABEL,
  FREE_PLAN_TRAINING_NOTICE_DISMISS_LABEL,
} from '@agiworkforce/compliance';
