/**
 * The product domains, one owner each. A feature belongs to exactly one of
 * these, and `scripts/check-domain-ownership.mjs` proves that every table,
 * every platform capability and every durable concept is claimed once.
 *
 * @module domain-registry
 */

export const PRODUCT_DOMAINS = [
  'identity',
  'accounts',
  'sessions',
  'devices',
  'organizations',
  'workspaces',
  'membership',
  'groups',
  'roles',
  'policy',
  'entitlements',
  'billing',
  'usage',
  'chat',
  'conversation-history',
  'context',
  'personalization',
  'memory',
  'projects',
  'files',
  'library',
  'search',
  'retrieval',
  'knowledge',
  'citations',
  'research',
  'learning',
  'work',
  'agents',
  'tools',
  'approvals',
  'code',
  'browser',
  'computer-use',
  'remote-control',
  'voice',
  'image-generation',
  'video-generation',
  'artifacts',
  'documents',
  'spreadsheets',
  'presentations',
  'notebooks',
  'connected-accounts',
  'connectors',
  'mcp',
  'skills',
  'plugins',
  'hooks',
  'scheduler',
  'notifications',
  'events',
  'webhooks',
  'model-registry',
  'provider-registry',
  'routing',
  'prompt-registry',
  'inference',
  'local-runtime',
  'byok',
  'sync',
  'sharing',
  'export',
  'deletion',
  'audit',
  'analytics',
  'feedback',
  'support',
  'safety',
  'abuse',
  'admin',
  'developer-api',
  'experiments',
  'feature-flags',
  'release-management',
] as const;

export type ProductDomain = (typeof PRODUCT_DOMAINS)[number];

export function isProductDomain(value: string): value is ProductDomain {
  return (PRODUCT_DOMAINS as readonly string[]).includes(value);
}
