/**
 * Pairing Types
 *
 * Types for the QR-code pairing flow that links desktop and mobile clients.
 * The desktop app generates a pairing code; the mobile app scans it via QR
 * or manual entry. Once paired, the two communicate over WebRTC via the
 * signaling server.
 *
 * @module pairing
 * @packageDocumentation
 */

/**
 * A pairing token generated by the desktop app for mobile connection.
 *
 * The token is displayed as a QR code on the desktop and scanned by the
 * mobile app. It encodes the signaling server URL, the pairing code,
 * and optional metadata.
 *
 * @example
 * ```typescript
 * const token: PairingToken = {
 *   code: '847293',
 *   signalingUrl: 'wss://signal.agiworkforce.com',
 *   expiresAt: '2026-03-15T10:35:00Z',
 *   deviceInfo: {
 *     deviceId: 'desktop-abc',
 *     deviceName: 'MacBook Pro',
 *     platform: 'macos',
 *     appVersion: '1.2.0',
 *   },
 * };
 * ```
 */
export interface PairingToken {
  code: string;

  signalingUrl: string;

  expiresAt: string;

  deviceInfo?: DeviceInfo;

  metadata?: Record<string, unknown>;
}

export type PairingStatus =
  'generating' | 'waiting' | 'connecting' | 'paired' | 'expired' | 'failed' | 'disconnected';

/**
 * Information about a device participating in a pairing session.
 *
 * Shared between desktop and mobile during the pairing handshake so each
 * side knows what it is connecting to.
 *
 * @example
 * ```typescript
 * const device: DeviceInfo = {
 *   deviceId: 'mobile-xyz-789',
 *   deviceName: 'iPhone 16 Pro',
 *   platform: 'ios',
 *   appVersion: '1.2.0',
 *   capabilities: ['approve', 'monitor', 'voice'],
 * };
 * ```
 */
export interface DeviceInfo {
  deviceId: string;

  deviceName: string;

  platform: 'macos' | 'windows' | 'linux' | 'ios' | 'android' | 'web';

  appVersion: string;

  capabilities?: string[];

  batteryLevel?: number;

  networkType?: 'wifi' | 'cellular' | 'ethernet' | 'unknown';
}

export interface PairingSession {
  token: PairingToken;

  status: PairingStatus;

  peerDevice?: DeviceInfo;

  createdAt: string;

  pairedAt?: string | null;

  latencyMs?: number;
}

/**
 * The name mobile gives the screen a user pairs from.
 *
 * Desktop's pairing card told people to "open Desktop Companion on your
 * phone", a screen with no such name, mobile calls it Remote in the drawer
 * and in the screen header. Both surfaces read this constant so the
 * instruction cannot drift from the label again.
 */
export const MOBILE_REMOTE_SCREEN_LABEL = 'Remote';

/**
 * The two pairing codes the product issues, and the only place either one is
 * described.
 *
 * They are not interchangeable and they are not one system. A relay code pairs
 * a phone with a desktop through the signaling server; a bridge code pairs the
 * Chrome extension with the desktop over loopback, and it is read off the
 * screen and retyped, which is why its alphabet drops the characters a person
 * confuses (I, L, O, 0, 1).
 *
 * Each validator states exactly what its generator mints, no wider. The six
 * hand-written copies this replaced disagreed: one accepted 8 to 32 characters
 * for a code the relay always makes 12 of, another 6 to 12 for a code the
 * desktop always makes 8 of. A check looser than the generator admits codes
 * that cannot exist and tells the user "invalid" one round trip later than it
 * could.
 */
export const PAIRING_CODE_LENGTH = 12;

export const RELAY_PAIRING_CODE_PATTERN = new RegExp(`^[A-Z0-9]{${PAIRING_CODE_LENGTH}}$`);

/** Mirrors PAIR_CODE_ALPHABET in apps/desktop/src-tauri/src/integrations/realtime. */
export const BRIDGE_PAIRING_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

export const BRIDGE_PAIRING_CODE_LENGTH = 8;

export const BRIDGE_PAIRING_CODE_PATTERN = new RegExp(
  `^[${BRIDGE_PAIRING_CODE_ALPHABET}]{${BRIDGE_PAIRING_CODE_LENGTH}}$`,
);

/**
 * What a person typed, reduced to what a code is: separators dropped, case
 * folded up. Validators are strict, so anything a human touched is normalized
 * first and anything a machine passed on is not.
 */
export function normalizePairingCode(raw: string): string {
  return (raw ?? '').replace(/[^A-Za-z0-9]/g, '').toUpperCase();
}

export function isRelayPairingCode(value: string): boolean {
  return typeof value === 'string' && RELAY_PAIRING_CODE_PATTERN.test(value);
}

export function isBridgePairingCode(value: string): boolean {
  return typeof value === 'string' && BRIDGE_PAIRING_CODE_PATTERN.test(value);
}
