/**
 * Pairing Types
 *
 * Types for the QR-code pairing flow that links desktop and mobile clients.
 * The desktop app generates a pairing code; the mobile app scans it via QR
 * or manual entry. Once paired, the two communicate over WebRTC via the
 * signaling server.
 *
 * @module pairing
 * @packageDocumentation
 */

/**
 * A pairing token generated by the desktop app for mobile connection.
 *
 * The token is displayed as a QR code on the desktop and scanned by the
 * mobile app. It encodes the signaling server URL, the pairing code,
 * and optional metadata.
 *
 * @example
 * ```typescript
 * const token: PairingToken = {
 *   code: '847293',
 *   signalingUrl: 'wss://signal.agiworkforce.com',
 *   expiresAt: '2026-03-15T10:35:00Z',
 *   deviceInfo: {
 *     deviceId: 'desktop-abc',
 *     deviceName: 'MacBook Pro',
 *     platform: 'macos',
 *     appVersion: '1.2.0',
 *   },
 * };
 * ```
 */
export interface PairingToken {
  code: string;

  signalingUrl: string;

  expiresAt: string;

  deviceInfo?: DeviceInfo;

  metadata?: Record<string, unknown>;
}

export type PairingStatus =
  | 'generating'
  | 'waiting'
  | 'connecting'
  | 'paired'
  | 'expired'
  | 'failed'
  | 'disconnected';

/**
 * Information about a device participating in a pairing session.
 *
 * Shared between desktop and mobile during the pairing handshake so each
 * side knows what it is connecting to.
 *
 * @example
 * ```typescript
 * const device: DeviceInfo = {
 *   deviceId: 'mobile-xyz-789',
 *   deviceName: 'iPhone 16 Pro',
 *   platform: 'ios',
 *   appVersion: '1.2.0',
 *   capabilities: ['approve', 'monitor', 'voice'],
 * };
 * ```
 */
export interface DeviceInfo {
  deviceId: string;

  deviceName: string;

  platform: 'macos' | 'windows' | 'linux' | 'ios' | 'android' | 'web';

  appVersion: string;

  capabilities?: string[];

  batteryLevel?: number;

  networkType?: 'wifi' | 'cellular' | 'ethernet' | 'unknown';
}

export interface PairingSession {
  token: PairingToken;

  status: PairingStatus;

  peerDevice?: DeviceInfo;

  createdAt: string;

  pairedAt?: string | null;

  latencyMs?: number;
}
