import type { DirectoryTransport } from '@/lib/connectors/directory/types';

export interface FirstPartyTarget {
  readonly connectorId: string;
  readonly url: string;
  readonly transport: DirectoryTransport;
  readonly toolNames: readonly string[];
  readonly docsUrl: string;
  readonly categories: readonly string[];
  readonly overridesInternalUrl: boolean;
}

export const FIRST_PARTY_MCP_TARGETS: readonly FirstPartyTarget[] = [
  {
    connectorId: 'google-drive',
    url: 'https://drivemcp.googleapis.com/mcp/v1',
    transport: 'streamable-http',
    toolNames: [
      'search_files',
      'list_recent_files',
      'get_file_metadata',
      'get_file_permissions',
      'read_file_content',
      'download_file_content',
      'create_file',
      'copy_file',
    ],
    docsUrl: 'https://developers.google.com/workspace/drive/api/guides/configure-mcp-server',
    categories: ['Productivity'],
    overridesInternalUrl: true,
  },
  {
    connectorId: 'gmail',
    url: 'https://gmailmcp.googleapis.com/mcp/v1',
    transport: 'streamable-http',
    toolNames: [
      'search_threads',
      'get_thread',
      'get_message',
      'list_drafts',
      'create_draft',
      'list_labels',
      'label_message',
      'unlabel_message',
      'label_thread',
      'unlabel_thread',
    ],
    docsUrl: 'https://developers.google.com/workspace/gmail/api/guides/configure-mcp-server',
    categories: ['Communication', 'Productivity'],
    overridesInternalUrl: true,
  },
  {
    connectorId: 'google-calendar',
    url: 'https://calendarmcp.googleapis.com/mcp/v1',
    transport: 'streamable-http',
    toolNames: [
      'list_calendars',
      'list_events',
      'get_event',
      'search_events',
      'suggest_time',
      'create_event',
      'update_event',
      'delete_event',
      'respond_to_event',
    ],
    docsUrl: 'https://developers.google.com/workspace/calendar/api/guides/configure-mcp-server',
    categories: ['Productivity'],
    overridesInternalUrl: true,
  },
  {
    connectorId: 'slack',
    url: 'https://mcp.slack.com/mcp',
    transport: 'streamable-http',
    toolNames: [],
    docsUrl: 'https://docs.slack.dev/ai/slack-mcp-server/',
    categories: ['Communication'],
    overridesInternalUrl: false,
  },
  {
    connectorId: 'notion',
    url: 'https://mcp.notion.com/mcp',
    transport: 'streamable-http',
    toolNames: [
      'notion-search',
      'notion-ai-search',
      'notion-fetch',
      'notion-create-pages',
      'notion-update-page',
      'notion-create-database',
      'notion-spawn-session',
      'notion-list-agents',
    ],
    docsUrl: 'https://developers.notion.com/guides/mcp/mcp-supported-tools',
    categories: ['Productivity'],
    overridesInternalUrl: false,
  },
  {
    connectorId: 'figma',
    url: 'https://mcp.figma.com/mcp',
    transport: 'streamable-http',
    toolNames: [
      'get_design_context',
      'get_screenshot',
      'get_metadata',
      'search_design_system',
      'create_new_file',
      'generate_figma_design',
      'upload_assets',
      'weave_run_tool',
      'weave_list_tools',
    ],
    docsUrl: 'https://developers.figma.com/docs/figma-mcp-server/',
    categories: ['Design'],
    overridesInternalUrl: false,
  },
  {
    connectorId: 'jira',
    url: 'https://mcp.atlassian.com/v2/mcp',
    transport: 'streamable-http',
    toolNames: ['getJiraIssue', 'createJiraIssue', 'searchJiraIssuesUsingJql'],
    docsUrl:
      'https://support.atlassian.com/atlassian-rovo-mcp-server/docs/getting-started-with-the-atlassian-remote-mcp-server/',
    categories: ['Code', 'Productivity'],
    overridesInternalUrl: true,
  },
  {
    connectorId: 'confluence',
    url: 'https://mcp.atlassian.com/v2/mcp',
    transport: 'streamable-http',
    toolNames: ['read_confluence', 'write_confluence', 'search_confluence'],
    docsUrl:
      'https://support.atlassian.com/atlassian-rovo-mcp-server/docs/getting-started-with-the-atlassian-remote-mcp-server/',
    categories: ['Productivity'],
    overridesInternalUrl: true,
  },
  {
    connectorId: 'hubspot',
    url: 'https://mcp.hubspot.com',
    transport: 'streamable-http',
    toolNames: [
      'search_crm_objects',
      'manage_crm_objects',
      'query_crm_data',
      'manage_marketing_email',
      'get_marketing_email_analytics',
    ],
    docsUrl: 'https://developers.hubspot.com/mcp',
    categories: ['Sales and marketing'],
    overridesInternalUrl: false,
  },
  {
    connectorId: 'asana',
    url: 'https://mcp.asana.com/v2/mcp',
    transport: 'streamable-http',
    toolNames: [
      'search_tasks',
      'get_task',
      'create_tasks',
      'update_tasks',
      'get_project',
      'get_portfolio',
      'add_comment',
    ],
    docsUrl: 'https://developers.asana.com/docs/mcp-server',
    categories: ['Productivity'],
    overridesInternalUrl: true,
  },
  {
    connectorId: 'linear',
    url: 'https://mcp.linear.app/mcp',
    transport: 'streamable-http',
    toolNames: [],
    docsUrl: 'https://linear.app/docs/mcp',
    categories: ['Code', 'Productivity'],
    overridesInternalUrl: false,
  },
  {
    connectorId: 'canva',
    url: 'https://mcp.canva.com/mcp',
    transport: 'streamable-http',
    toolNames: ['read_design', 'edit_design'],
    docsUrl: 'https://www.canva.dev/docs/mcp/',
    categories: ['Design'],
    overridesInternalUrl: false,
  },
];
