import type { Metadata } from 'next';
import Link from 'next/link';
import { Header } from '@shared/components/layout/Header';
import { MarketingFooter } from '@/features/marketing/components/MarketingFooter';
import { FinalCta } from '@/features/marketing/components/FlagshipSections';
import { LedgerSection, RouteMap } from '@/features/marketing/components/LandingSections';
import { MobileHeroVisual } from '@/features/marketing/components/MobileHeroVisual';
import { LAUNCH, SURFACE_STATUS } from '../../lib/marketing-constants';

export const metadata: Metadata = {
  title: 'AGI Mobile | Private, Local-First AI for iPhone & Android',
  description:
    'AGI Mobile runs chat on your phone in Local Mode by default. Chats, memory, projects, and files stay on-device unless you choose otherwise. AGI managed cloud is in public alpha.',
  alternates: { canonical: 'https://agiworkforce.com/mobile' },
  openGraph: {
    title: 'AGI Mobile | Private, Local-First AI for iPhone & Android',
    description:
      'On-device Local chat by default. Your data stays on the phone unless you explicitly choose otherwise. AGI managed cloud is public alpha.',
    type: 'website',
    url: 'https://agiworkforce.com/mobile',
    images: [{ url: '/api/og', width: 1200, height: 630, alt: 'AGI app preview' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AGI Mobile | Private, Local-First AI for iPhone & Android',
    description: `Local Mode by default. AGI managed cloud is public alpha. ${LAUNCH.publicLabel}.`,
    images: ['/api/og'],
  },
};

const ON_DEVICE_RUNTIMES = [
  {
    heading: 'The model the operating system already holds',
    body: "On an iPhone where Apple Intelligence is available, AGI generates through Apple's Foundation Models runtime. On an Android device with AICore, it generates through Google's on-device model. Neither one is downloaded, and the app checks whether the runtime is available, downloadable, downloading, or unavailable before it offers you the model.",
  },
  {
    heading: 'A model you download once',
    body: 'Choose AGI Standard instead and the phone loads a 4B Qwen3 build, roughly 2 GB quantized, with a 262,144-token context. It runs through ExecuTorch where the device reports at least 3.5 GB of RAM, and through llama.rn from the downloaded file where it does not.',
  },
  {
    heading: 'A picker that says which one is loaded',
    body: 'Every row in the model picker carries one of three states — ready, download required, or locked — so the cost of a tap is visible before you make it. Generation also pauses on its own while the device reports thermal throttling.',
  },
] as const;

export default function MobilePage() {
  return (
    <div data-design="agi">
      <main className="agi-shell">
        <Header />

        <section className="agi-fl-hero" aria-labelledby="agi-mobile-hero-title">
          <div className="agi-fl-hero-backdrop" aria-hidden="true" />
          <div className="agi-fl-hero-split">
            <div className="agi-fl-hero-copy">
              <p className="agi-fl-eyebrow">
                AGI Mobile · iPhone &amp; Android · {SURFACE_STATUS.mobile}
              </p>
              <h1 id="agi-mobile-hero-title" className="agi-fl-h1">
                <span className="agi-fl-h1-line">
                  Your phone <em className="agi-fl-h1-em">runs the model</em>
                </span>{' '}
                <span className="agi-fl-h1-line">and keeps the chat.</span>
              </h1>
              <p className="agi-fl-lede">
                On an iPhone with Apple Intelligence the app generates through Apple&apos;s
                Foundation Models runtime, and on Android it generates through AICore. Otherwise you
                download AGI Standard once and it runs through ExecuTorch or llama.rn. Either way
                the thread is written to SQLite on the phone.
              </p>
              <div className="agi-fl-cta-row">
                <Link href="/download" className="agi-fl-cta agi-fl-cta--primary">
                  Get notified
                </Link>
              </div>
              <ul className="agi-fl-mode-ribbon" aria-label="On-device runtimes">
                <li>iOS · Apple Foundation Models</li>
                <li>Android · AICore</li>
              </ul>
            </div>
            <div className="agi-fl-hero-visual agi-fl-hero-frame--main">
              <MobileHeroVisual />
            </div>
          </div>
        </section>

        <section className="agi-fl-section" aria-labelledby="agi-mobile-runtime-title">
          <p className="agi-fl-eyebrow">On-device inference</p>
          <h2 id="agi-mobile-runtime-title" className="agi-fl-h2">
            A Local answer is generated by the phone you are holding.
          </h2>
          <p className="agi-fl-section-lede">
            The app picks a runtime from what the hardware actually reports — the system model, a
            downloaded one, or nothing yet — and it tells you which before you send anything.
          </p>
          <ul className="agi-reasons">
            {ON_DEVICE_RUNTIMES.map((runtime) => (
              <li className="agi-reason" key={runtime.heading}>
                <h3 className="agi-reason-h">{runtime.heading}</h3>
                <p className="agi-reason-p">{runtime.body}</p>
              </li>
            ))}
          </ul>
        </section>

        <section className="agi-fl-section" aria-labelledby="agi-mobile-cloud-title">
          <p className="agi-fl-eyebrow">What tapping Cloud does</p>
          <div className="agi-callout">
            <h2 id="agi-mobile-cloud-title" className="agi-callout-h">
              Switch to AGI Cloud?
            </h2>
            <p className="agi-callout-p">
              Sign in to use AGI Cloud chat. Your local chat stays on this device unless you choose
              to start a Cloud session.
            </p>
          </div>
          <p className="agi-fl-section-lede">
            That is the dialog, word for word. Local and Cloud sit side by side in the chat screen,
            onboarding lands you on Local with no account, and Cloud stays behind that prompt until
            you sign in. Sending chats you already have is a separate action under Settings → Data
            Controls: it copies conversation titles and message text, leaves file attachments and
            memory facts on the phone, and runs once when you press it.
          </p>
          <div className="agi-fl-cta-row">
            <Link href="/local" className="agi-fl-cta agi-fl-cta--ghost">
              How Local Mode is defined
            </Link>
          </div>
        </section>

        <RouteMap
          eyebrow="In the app"
          title="The drawer carries the whole workspace."
          routes={[
            {
              meta: 'Chat',
              title: 'Local chat',
              body: 'Threads run and stay on the device, and the model picker sits in the composer beside the attach and voice controls.',
              href: '/features/ai-chat',
            },
            {
              meta: 'Projects',
              title: 'Projects and recents',
              body: 'One drawer holds chats, projects, artifacts, the library, connectors, skills, schedules, and tasks.',
              href: '/features/projects',
            },
            {
              meta: 'Memory',
              title: 'Memory and personalization',
              body: 'Memory facts are held on the phone and are excluded even when you choose to sync chats to AGI Cloud.',
              href: '/features/memory',
            },
            {
              meta: 'Data',
              title: 'Data controls',
              body: 'Export chats, memory, settings, and installed model details from the device, and wipe local-only chats from Storage.',
              href: '/security',
            },
          ]}
        />

        <LedgerSection
          eyebrow="Build sheet"
          title="Here is what the build contains."
          rows={[
            {
              k: 'Default model',
              v: 'AGI Standard · Qwen3 4B Instruct · ~2 GB quantized · 262,144-token context',
            },
            { k: 'Lighter option', v: 'AGI Lite · 1B on-device build · ~1.1 GB' },
            { k: 'Chats and memory', v: 'SQLite on the device' },
            {
              k: 'Export',
              v: 'Runs on the device — chats, memory, settings, installed model details',
            },
            {
              k: 'Cloud sync',
              v: 'Manual and one-time · attachments and memory facts stay on the phone',
            },
            {
              k: 'App lock',
              v: 'The Face ID, Touch ID, or passcode already enrolled on the phone',
            },
            {
              k: 'Model training',
              v: 'Off — prompts, responses, and files are not used to train AGI-owned models',
            },
            { k: 'Platforms', v: `iPhone and Android · ${SURFACE_STATUS.mobile}` },
          ]}
        />

        <FinalCta
          eyebrow={LAUNCH.publicLabel}
          title="AGI Mobile is not in the app stores yet."
          body="The runtimes, the drawer, and the settings above are built and running on device. Neither store listing is published, and no release date has been announced."
          ctas={[{ href: '/mobile/legal', label: 'Read the mobile privacy policy' }]}
          stamp={`iPhone & Android · ${LAUNCH.shortLabel}`}
        />

        <MarketingFooter />
      </main>
    </div>
  );
}
