import { buildMetadata } from '@/lib/seo/metadata';
import { Header } from '@shared/components/layout/Header';
import { MarketingFooter } from '@/features/marketing/components/MarketingFooter';
import {
  Button,
  ButtonRow,
  Eyebrow,
  Ledger,
  Prose,
  Section,
  Stack,
  SurfaceStatus,
} from '@/features/marketing/components/system';
import { FactGrid, PageHero } from '@/features/marketing/components/pages/surfaces/shared';
import { SURFACE_STATUS } from '@/lib/marketing-constants';

export const metadata = buildMetadata({
  title: 'AGI Mobile: local chat that stays on your phone',
  description:
    'AGI Mobile runs chat on-device by default, through the phone’s own model runtime or a downloaded build. Chats, memory, projects, and files stay on the phone unless you choose otherwise. Not on the App Store or Google Play yet.',
  path: '/mobile',
});

export default function MobilePage() {
  return (
    <div data-design="agi" className="agi-ds-page">
      <Header />
      <main id="main-content">
        <PageHero
          id="agi-mobile-hero-title"
          eyebrow="AGI Mobile"
          title="Your phone runs the model and keeps the chat."
          lede="On an iPhone with Apple Intelligence the app generates through Apple's Foundation Models runtime, and on Android it generates through AICore. Otherwise you download AGI Standard once and it runs through ExecuTorch or llama.rn. Either way the thread is written to SQLite on the phone."
          ctas={[
            { href: '/download', label: 'Get notified' },
            { href: '/local', label: 'How local mode is defined', variant: 'secondary' },
          ]}
        />

        <Section id="mobile-status" labelledBy="agi-mobile-status-title" rule>
          <Stack>
            <h2 className="agi-ds-h2" id="agi-mobile-status-title">
              Where the build stands.
            </h2>
            <SurfaceStatus
              state="absent"
              name="AGI Mobile"
              detail={`${SURFACE_STATUS.mobile}. No listing on the App Store or Google Play. The runtimes and drawer described below are built and running on-device; neither store submission is published.`}
            />
          </Stack>
        </Section>

        <Section id="mobile-runtime" labelledBy="agi-mobile-runtime-title" rule ground="2">
          <Stack gap="loose">
            <div>
              <Eyebrow>On-device inference</Eyebrow>
              <h2 className="agi-ds-h2" id="agi-mobile-runtime-title">
                A local answer is generated by the phone you are holding.
              </h2>
              <Prose>
                The app picks a runtime from what the hardware actually reports, the system model, a
                downloaded one, or nothing yet, and it tells you which before you send anything.
              </Prose>
            </div>
            <FactGrid
              items={[
                {
                  meta: 'System model',
                  title: 'The model the operating system already holds',
                  body: "On an iPhone where Apple Intelligence is available, AGI generates through Apple's Foundation Models runtime. On an Android device with AICore, it generates through Google's on-device model. Neither one is downloaded by AGI.",
                },
                {
                  meta: 'Downloaded model',
                  title: 'A model you download once',
                  body: 'Choose AGI Standard instead and the phone loads a 4B Qwen3 build, roughly 2 GB quantized, with a 262,144-token context. It runs through ExecuTorch where the device reports at least 3.5 GB of RAM, and through llama.rn from the downloaded file where it does not.',
                },
                {
                  meta: 'Model picker',
                  title: 'A picker that says which one is loaded',
                  body: 'Every row in the model picker carries one of three states, ready, download required, or locked, so the cost of a tap is visible before you make it. Generation also pauses on its own while the device reports thermal throttling.',
                },
              ]}
            />
          </Stack>
        </Section>

        <Section id="mobile-cloud" labelledBy="agi-mobile-cloud-title" rule>
          <Stack gap="loose">
            <div>
              <Eyebrow>What tapping Cloud does</Eyebrow>
              <h2 className="agi-ds-h2" id="agi-mobile-cloud-title">
                Switch to AGI Cloud?
              </h2>
            </div>
            <Prose>
              &ldquo;Sign in to use AGI Cloud chat. Your local chat stays on this device unless you
              choose to start a Cloud session.&rdquo; That is the dialog, word for word. Local and
              Cloud sit side by side in the chat screen, onboarding lands you on local with no
              account, and Cloud stays behind that prompt until you sign in. Sending chats you
              already have is a separate action under Settings, Data controls: it copies
              conversation titles and message text, leaves file attachments and memory facts on the
              phone, and runs once when you press it.
            </Prose>
          </Stack>
        </Section>

        <Section id="mobile-app" labelledBy="agi-mobile-app-title" rule ground="2">
          <Stack gap="loose">
            <div>
              <Eyebrow>In the app</Eyebrow>
              <h2 className="agi-ds-h2" id="agi-mobile-app-title">
                The drawer carries the whole workspace.
              </h2>
            </div>
            <FactGrid
              items={[
                {
                  meta: 'Chat',
                  title: 'Local chat',
                  body: 'Threads run and stay on the device, and the model picker sits in the composer beside the attach and voice controls.',
                },
                {
                  meta: 'Projects',
                  title: 'Projects and recents',
                  body: 'One drawer holds chats, projects, artifacts, the library, connectors, skills, schedules, and tasks.',
                },
                {
                  meta: 'Memory',
                  title: 'Memory and personalization',
                  body: 'Memory facts are held on the phone and are excluded even when you choose to sync chats to AGI Cloud.',
                },
                {
                  meta: 'Data',
                  title: 'Data controls',
                  body: 'Export chats, memory, settings, and installed model details from the device, and wipe local-only chats from Storage.',
                },
              ]}
            />
          </Stack>
        </Section>

        <Section id="mobile-build" labelledBy="agi-mobile-build-title" rule>
          <Stack gap="loose">
            <div>
              <Eyebrow>Build sheet</Eyebrow>
              <h2 className="agi-ds-h2" id="agi-mobile-build-title">
                Here is what the build contains.
              </h2>
            </div>
            <Ledger
              caption="AGI Mobile build sheet"
              rows={[
                {
                  label: 'Default model',
                  value: 'AGI Standard, Qwen3 4B Instruct, ~2 GB quantized, 262,144-token context',
                },
                { label: 'Lighter option', value: 'AGI Lite, 1B on-device build, ~1.1 GB' },
                { label: 'Chats and memory', value: 'SQLite on the device' },
                {
                  label: 'Export',
                  value: 'Runs on the device: chats, memory, settings, installed model details',
                },
                {
                  label: 'Cloud sync',
                  value: 'Manual and one-time. Attachments and memory facts stay on the phone',
                },
                {
                  label: 'App lock',
                  value: 'The Face ID, Touch ID, or passcode already enrolled on the phone',
                },
                {
                  label: 'Model training',
                  value:
                    'Off. Prompts, responses, and files are not used to train AGI-owned models',
                },
              ]}
            />
          </Stack>
        </Section>

        <Section id="mobile-close" labelledBy="agi-mobile-close-title" rule ground="2">
          <Stack gap="loose">
            <h2 className="agi-ds-h2" id="agi-mobile-close-title">
              Neither store listing is published yet.
            </h2>
            <Prose>
              The runtimes, the drawer, and the settings above are built and running on device. No
              release date has been announced.
            </Prose>
            <ButtonRow>
              <Button href="/mobile/legal" variant="secondary">
                Read the mobile privacy policy
              </Button>
            </ButtonRow>
          </Stack>
        </Section>
      </main>
      <MarketingFooter />
    </div>
  );
}
