/**
 * Generated Image Preview Component
 * Displays images generated by Google Imagen with download functionality
 */

import React, { useState } from 'react';
import { Download, Maximize2, X, Loader2 } from 'lucide-react';
import { Button } from '@shared/ui/button';
import { Card, CardContent } from '@shared/ui/card';
import { cn } from '@shared/lib/utils';
import { googleImagenService } from '@core/integrations/google-imagen-service';

export interface GeneratedImagePreviewProps {
  imageUrl: string;
  prompt: string;
  model?: string;
  metadata?: {
    aspectRatio?: string;
    seed?: number;
    numberOfImages?: number;
  };
  className?: string;
  onDownload?: () => void;
}

export const GeneratedImagePreview: React.FC<GeneratedImagePreviewProps> = ({
  imageUrl,
  prompt,
  model,
  metadata,
  className,
  onDownload,
}) => {
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [imageLoaded, setImageLoaded] = useState(false);

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const filename = `imagen-${Date.now()}.png`;
      await googleImagenService.downloadImage(imageUrl, filename);
      onDownload?.();
    } catch (error) {
      console.error('Failed to download image:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  const handleFullscreen = () => {
    setIsFullscreen(true);
  };

  const handleCloseFullscreen = () => {
    setIsFullscreen(false);
  };

  return (
    <>
      <Card className={cn('overflow-hidden', className)}>
        <CardContent className="p-0">
          <div className="group relative">
            {/* Image */}
            <div className="relative bg-gray-100 dark:bg-gray-800">
              {!imageLoaded && (
                <div className="absolute inset-0 flex items-center justify-center">
                  <Loader2 className="h-8 w-8 animate-spin text-gray-400" />
                </div>
              )}
              <img
                src={imageUrl}
                alt={prompt}
                className={cn(
                  'h-auto w-full object-contain transition-opacity duration-300',
                  imageLoaded ? 'opacity-100' : 'opacity-0',
                )}
                onLoad={() => setImageLoaded(true)}
                loading="lazy"
              />
            </div>

            {/* Overlay with actions */}
            <div className="absolute inset-0 bg-black/0 transition-colors duration-200 group-hover:bg-black/40">
              <div className="absolute right-2 top-2 flex gap-2 opacity-0 transition-opacity duration-200 group-hover:opacity-100">
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={handleFullscreen}
                  className="bg-white/90 text-gray-900 hover:bg-white"
                >
                  <Maximize2 className="h-4 w-4" />
                </Button>
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={handleDownload}
                  disabled={isDownloading}
                  className="bg-white/90 text-gray-900 hover:bg-white"
                >
                  {isDownloading ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Download className="h-4 w-4" />
                  )}
                </Button>
              </div>
            </div>
          </div>

          {/* Metadata */}
          <div className="border-t border-gray-200 bg-gray-50 p-3 dark:border-gray-800 dark:bg-gray-900">
            <p className="line-clamp-2 text-sm text-gray-600 dark:text-gray-400">{prompt}</p>
            {(model || metadata) && (
              <div className="mt-2 flex flex-wrap gap-2 text-xs text-gray-500 dark:text-gray-500">
                {model && (
                  <span className="rounded bg-gray-200 px-2 py-1 dark:bg-gray-800">{model}</span>
                )}
                {metadata?.aspectRatio && (
                  <span className="rounded bg-gray-200 px-2 py-1 dark:bg-gray-800">
                    {metadata.aspectRatio}
                  </span>
                )}
                {metadata?.seed && (
                  <span className="rounded bg-gray-200 px-2 py-1 dark:bg-gray-800">
                    Seed: {metadata.seed}
                  </span>
                )}
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Fullscreen Modal */}
      {isFullscreen && (
        <div
          className="fixed inset-0 z-modal flex items-center justify-center bg-black/95 p-4"
          onClick={handleCloseFullscreen}
        >
          <Button
            size="sm"
            variant="ghost"
            onClick={handleCloseFullscreen}
            className="absolute right-4 top-4 text-white hover:bg-white/10"
          >
            <X className="h-6 w-6" />
          </Button>
          <img
            src={imageUrl}
            alt={prompt}
            className="max-h-full max-w-full object-contain"
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}
    </>
  );
};

/**
 * Multiple Images Preview Grid
 */
export interface GeneratedImagesGridProps {
  images: Array<{
    url: string;
    prompt: string;
    model?: string;
    metadata?: {
      aspectRatio?: string;
      seed?: number;
    };
  }>;
  className?: string;
}

export const GeneratedImagesGrid: React.FC<GeneratedImagesGridProps> = ({ images, className }) => {
  return (
    <div
      className={cn(
        'grid gap-4',
        images.length === 1 && 'grid-cols-1',
        images.length === 2 && 'grid-cols-2',
        images.length >= 3 && 'grid-cols-2 md:grid-cols-3',
        className,
      )}
    >
      {images.map((image, index) => (
        <GeneratedImagePreview
          key={index}
          imageUrl={image.url}
          prompt={image.prompt}
          model={image.model}
          metadata={image.metadata}
        />
      ))}
    </div>
  );
};
