import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { NextRequest } from 'next/server';

/**
 * EU AI Act Article 50(2) for video. The status endpoint is the only response
 * that ever carries the finished artefact — generation is async and the bytes
 * live provider-side — so it is the only place the mark can be attached
 * server-side.
 */

vi.mock('server-only', () => ({}));

vi.mock('@/lib/rate-limit', () => ({ withRateLimit: vi.fn().mockResolvedValue(null) }));
vi.mock('@/lib/cors', () => ({
  handleCorsPreflightRequest: vi.fn().mockReturnValue(null),
  getCorsHeaders: vi.fn().mockReturnValue({}),
  getSecurityHeaders: vi.fn().mockReturnValue({}),
}));
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));
vi.mock('@/lib/errors', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/lib/errors')>();
  return {
    createError: actual.createError,
    AppError: actual.AppError,
    isAppError: actual.isAppError,
  };
});
vi.mock('@/lib/error-handler', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/lib/error-handler')>();
  return { withErrorHandler: actual.withErrorHandler, handleError: actual.handleError };
});

const mockGetClerkAuthUser = vi.fn();
vi.mock('@/lib/api-auth', () => ({
  getClerkAuthUser: (...args: unknown[]) => mockGetClerkAuthUser(...args),
}));

const taskStoreMocks = vi.hoisted(() => ({ get: vi.fn() }));
vi.mock('@/lib/video-task-store', () => ({
  getVideoTask: taskStoreMocks.get,
}));

const mockFetch = vi.fn();
global.fetch = mockFetch;

import { GET } from '@/app/api/media/video/status/route';
import {
  AI_GENERATED_HEADER,
  AI_GENERATED_PROVENANCE_HEADER,
  hasAiGeneratedProvenance,
} from '@/lib/compliance/ai-act';

const BASE_URL = 'http://localhost/api/media/video/status';
const TEST_USER = { userId: 'user-test-id', email: 'test@example.com' };

function statusRequest(taskId: string): NextRequest {
  return new NextRequest(`${BASE_URL}?task_id=${encodeURIComponent(taskId)}`, {
    method: 'GET',
    headers: { Authorization: 'Bearer valid-test-token' },
  });
}

function runwayResponse(status: string, output?: string[]) {
  return {
    ok: true,
    json: async () => ({ id: 'task-abc', status, ...(output ? { output } : {}) }),
  };
}

describe('Article 50(2) — generated video provenance', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetClerkAuthUser.mockResolvedValue(TEST_USER);
    taskStoreMocks.get.mockResolvedValue({ userId: TEST_USER.userId, model: 'veo-3.1' });
    process.env['RUNWAY_API_KEY'] = 'test-runway-key';
  });

  afterEach(() => {
    delete process.env['RUNWAY_API_KEY'];
  });

  it('marks the finished video with the model it was actually generated by', async () => {
    mockFetch.mockResolvedValueOnce(runwayResponse('SUCCEEDED', ['https://cdn/video.mp4']));

    const response = await GET(statusRequest('runway_task-abc'));
    const body = await response.json();

    expect(body.status).toBe('completed');
    expect(hasAiGeneratedProvenance(body.provenance)).toBe(true);
    expect(body.provenance.kind).toBe('video');
    // The provider's status payload never echoes the model back; it comes from
    // the task record written at submission time.
    expect(body.provenance.model).toBe('veo-3.1');
    expect(response.headers.get(AI_GENERATED_HEADER)).toBe('true');
    // One artefact per response, so the whole claim rides in the header too —
    // a download tool that never reads the JSON body still sees the mark.
    expect(
      hasAiGeneratedProvenance(
        JSON.parse(response.headers.get(AI_GENERATED_PROVENANCE_HEADER) ?? 'null'),
      ),
    ).toBe(true);
  });

  it('still marks a video whose task predates the recorded model', async () => {
    taskStoreMocks.get.mockResolvedValue({ userId: TEST_USER.userId });
    mockFetch.mockResolvedValueOnce(runwayResponse('SUCCEEDED', ['https://cdn/video.mp4']));

    const response = await GET(statusRequest('runway_task-abc'));
    const body = await response.json();

    expect(hasAiGeneratedProvenance(body.provenance)).toBe(true);
    expect(body.provenance.model).toBe('runway');
  });

  it('does not claim provenance for a video that does not exist yet', async () => {
    mockFetch.mockResolvedValueOnce(runwayResponse('RUNNING'));

    const response = await GET(statusRequest('runway_task-abc'));
    const body = await response.json();

    expect(body.status).toBe('processing');
    expect(body.provenance).toBeUndefined();
    expect(response.headers.get(AI_GENERATED_HEADER)).toBeNull();
  });
});
