import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { NextRequest } from 'next/server';

vi.mock('server-only', () => ({}));

vi.mock('@/lib/rate-limit', () => ({ withRateLimit: vi.fn().mockResolvedValue(null) }));
vi.mock('@/lib/cors', () => ({
  handleCorsPreflightRequest: vi.fn().mockReturnValue(null),
  getCorsHeaders: vi.fn().mockReturnValue({}),
  getSecurityHeaders: vi.fn().mockReturnValue({}),
}));
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));
vi.mock('@/lib/errors', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/lib/errors')>();
  return {
    createError: actual.createError,
    AppError: actual.AppError,
    isAppError: actual.isAppError,
  };
});
vi.mock('@/lib/error-handler', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/lib/error-handler')>();
  return { withErrorHandler: actual.withErrorHandler, handleError: actual.handleError };
});

const mockGetClerkAuthUser = vi.fn();
vi.mock('@/lib/api-auth', () => ({
  getClerkAuthUser: (...args: unknown[]) => mockGetClerkAuthUser(...args),
}));

const taskStoreMocks = vi.hoisted(() => ({ get: vi.fn() }));
vi.mock('@/lib/video-task-store', () => ({
  getVideoTask: taskStoreMocks.get,
}));

const durableMocks = vi.hoisted(() => ({
  scoped: vi.fn(),
  get: vi.fn(),
  reconcile: vi.fn(),
  delivered: vi.fn(),
}));
vi.mock('@/lib/server/rls-db', () => ({
  getUserScopedDb: (...args: unknown[]) => durableMocks.scoped(...args),
}));
vi.mock('@/lib/server/video-generation-jobs', () => ({
  getVideoGenerationJob: (...args: unknown[]) => durableMocks.get(...args),
  beginVideoProviderCancellationAttempt: vi.fn(),
  claimVideoGenerationJob: vi.fn(),
  claimVideoIncidentAlert: vi.fn(),
  claimVideoSettlementIncidentById: vi.fn(),
  claimVideoSettlementIncidentByReservation: vi.fn(),
  completeVideoIncidentAlert: vi.fn(),
  completeVideoSettlementIncident: vi.fn(),
  countExhaustedVideoIncidentAlerts: vi.fn(),
  countExhaustedVideoSettlementIncidentAlerts: vi.fn(),
  deferVideoGenerationJob: vi.fn(),
  deferVideoGenerationJobFailure: vi.fn(),
  finalizeVideoGenerationJob: vi.fn(),
  getVideoGenerationJobForSystem: vi.fn(),
  getVideoSettlementIncident: vi.fn(),
  listDueVideoGenerationJobIds: vi.fn(),
  listPendingVideoIncidentAlertIds: vi.fn(),
  listPendingVideoSettlementIncidentIds: vi.fn(),
  markVideoGenerationOutcomeUnknown: vi.fn(),
  recordVideoProviderCancellationAttempt: vi.fn(),
}));
vi.mock('@/lib/services/video-job-reconciliation-service', () => ({
  reconcileVideoGenerationJob: (...args: unknown[]) => durableMocks.reconcile(...args),
  publicVideoJobStatus: (job: Record<string, unknown>) => ({
    success: true,
    task_id: job['id'],
    status: job['status'],
    ...(job['assetId'] ? { video_url: `/api/files/${String(job['assetId'])}` } : {}),
  }),
}));
vi.mock('@/lib/services/managed-usage-request-service', () => ({
  markManagedUsageClientDelivered: (...args: unknown[]) => durableMocks.delivered(...args),
}));

const mockFetch = vi.fn();
global.fetch = mockFetch;

import { GET } from '@/app/api/media/video/status/route';
import {
  AI_GENERATED_HEADER,
  AI_GENERATED_PROVENANCE_HEADER,
  hasAiGeneratedProvenance,
} from '@/lib/compliance/ai-act';

const BASE_URL = 'http://localhost/api/media/video/status';
const TEST_USER = { userId: 'user-test-id', email: 'test@example.com' };
const JOB_ID = '11111111-1111-4111-8111-111111111111';
const PROVENANCE_MODEL_ID = 'synthetic-durable-video-model';

function statusRequest(taskId: string): NextRequest {
  return new NextRequest(`${BASE_URL}?task_id=${encodeURIComponent(taskId)}`, {
    method: 'GET',
    headers: { Authorization: 'Bearer valid-test-token' },
  });
}

function videoJob(status: 'processing' | 'completed') {
  return {
    id: JOB_ID,
    userId: TEST_USER.userId,
    organizationId: null,
    idempotencyKey: 'agi.media.web.video.operation-123',
    requestHash: 'a'.repeat(64),
    billingLeaseToken: 'lease-video',
    estimatedCostCents: 240,
    provider: 'google',
    model: PROVENANCE_MODEL_ID,
    status,
    assetId: status === 'completed' ? JOB_ID : null,
  };
}

describe('Article 50(2), generated video provenance', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetClerkAuthUser.mockResolvedValue(TEST_USER);
    const job = videoJob('completed');
    durableMocks.scoped.mockResolvedValue({ db: {}, userId: TEST_USER.userId });
    durableMocks.get.mockResolvedValue(job);
    durableMocks.reconcile.mockResolvedValue(job);
    durableMocks.delivered.mockResolvedValue(undefined);
  });

  afterEach(() => undefined);

  it('marks the finished video with the model it was actually generated by', async () => {
    const response = await GET(statusRequest(JOB_ID));
    const body = await response.json();

    expect(body.status).toBe('completed');
    expect(hasAiGeneratedProvenance(body.provenance)).toBe(true);
    expect(body.provenance.kind).toBe('video');
    expect(body.provenance.model).toBe(PROVENANCE_MODEL_ID);
    expect(response.headers.get(AI_GENERATED_HEADER)).toBe('true');
    expect(
      hasAiGeneratedProvenance(
        JSON.parse(response.headers.get(AI_GENERATED_PROVENANCE_HEADER) ?? 'null'),
      ),
    ).toBe(true);
  });

  it('returns only the authenticated AGI asset alongside the provenance mark', async () => {
    const response = await GET(statusRequest(JOB_ID));
    const body = await response.json();

    expect(hasAiGeneratedProvenance(body.provenance)).toBe(true);
    expect(body.video_url).toBe(`/api/files/${JOB_ID}`);
    expect(body.video_url).not.toMatch(/^https?:|^data:/);
  });

  it('does not claim provenance for a video that does not exist yet', async () => {
    const job = videoJob('processing');
    durableMocks.get.mockResolvedValue(job);
    durableMocks.reconcile.mockResolvedValue(job);

    const response = await GET(statusRequest(JOB_ID));
    const body = await response.json();

    expect(body.status).toBe('processing');
    expect(body.provenance).toBeUndefined();
    expect(response.headers.get(AI_GENERATED_HEADER)).toBeNull();
  });
});
