// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountStatusParams = {
  /**
   * Bypass the cache and re-read the account from the hosted API. Without
   * it the host answers from its on-disk cache and touches the network only
   * once that cache has expired.
   */
  refresh?: boolean;
};
