// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingApprovalSnapshot } from './PendingApprovalSnapshot';

/**
 * Everything a client needs to render a turn it joined mid-flight.
 */
export type ActiveTurnSnapshot = {
  turnId: string;
  /**
   * Output streamed so far.
   */
  partialResponse: string;
  /**
   * `index` of the first `turn/output_delta` not already in
   * `partial_response`; a client drops deltas below it.
   */
  nextDeltaIndex: bigint;
  /**
   * `sequence` of the first `turn/agent_event` this snapshot does not
   * account for.
   */
  nextEventSequence: bigint;
  pendingApprovals: Array<PendingApprovalSnapshot>;
};
