// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSystemPermissions } from './FileSystemPermissions';
import type { NetworkPermissions } from './NetworkPermissions';

/**
 * Partial permission overlay used for per-command requests and approved
 * session/turn grants.
 */
export type AdditionalPermissionProfile = {
  network: NetworkPermissions | null;
  file_system: FileSystemPermissions | null;
};
