// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEvent } from './AgentEvent';

/**
 * The one envelope web SSE chunks, app-server `turn/*` notifications, and
 * desktop stream events all translate into. Mirrors this crate's existing
 * `protocol::Event { id, msg: EventMsg }` shape (metadata fields alongside
 * one nested discriminated payload) rather than flattening the payload
 * into the envelope, so envelope metadata and event-payload field names
 * can never collide.
 */
export type AgentEventEnvelope = {
  /**
   * See [`AGENT_EVENT_SCHEMA_VERSION`].
   */
  schemaVersion: number;
  /**
   * Session/conversation identity. Plain `String`, not the CLI's
   * UUID-backed `ThreadId`: the app-server dialect's real wire `threadId`
   * is already a JSON string (`developer_host.rs` takes `thread_id:
   * String`), and web/desktop session identity is not guaranteed
   * UUID-shaped (e.g. a Neon-assigned id), forcing UUID validation here
   * would reject real values from two of the three target dialects.
   */
  sessionId: string;
  /**
   * Turn identity, same `String` rationale as `session_id` (app-server's
   * real wire `turnId` is a JSON string; `developer_host.rs` formats a
   * `Uuid` to `String` before ever putting it on the wire).
   */
  turnId: string;
  /**
   * Monotonically increasing per-envelope counter, scoped to one
   * `turn_id`, starting at 0. New in this envelope, none of the three
   * source dialects has one today (app-server's `turn/output_delta`
   * notifications carry no ordering signal at all), which is a real gap
   * this envelope closes: without it, a client cannot detect a dropped
   * or reordered event on any transport that doesn't itself guarantee
   * ordering.
   */
  sequence: number;
  /**
   * Wall-clock emission time, Unix epoch milliseconds. Millisecond (not
   * second) resolution deliberately, unlike `protocol.rs`'s existing
   * turn-level timestamps (`TurnCompleteEvent.completed_at`, etc.):
   * those mark one event per turn, but a turn can emit hundreds of
   * `AgentEventEnvelope`s per second while streaming, where
   * second-granularity timestamps would collapse most of them together.
   */
  emittedAtMs: number;
  event: AgentEvent;
};
