// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEventError } from './AgentEventError';
import type { AgentEventLifecycle } from './AgentEventLifecycle';
import type { AgentEventReasoningDelta } from './AgentEventReasoningDelta';
import type { AgentEventServerToolResult } from './AgentEventServerToolResult';
import type { AgentEventServerToolUse } from './AgentEventServerToolUse';
import type { AgentEventStop } from './AgentEventStop';
import type { AgentEventTextDelta } from './AgentEventTextDelta';
import type { AgentEventToolUseDelta } from './AgentEventToolUseDelta';
import type { AgentEventToolUseEnd } from './AgentEventToolUseEnd';
import type { AgentEventToolUseStart } from './AgentEventToolUseStart';
import type { AgentEventUsage } from './AgentEventUsage';

/**
 * The discriminated event union. See the module doc for which three real
 * dialects justify this variant set and which StreamChunk variants were
 * deliberately left out.
 */
export type AgentEvent =
  | ({ type: 'text-delta' } & AgentEventTextDelta)
  | ({ type: 'reasoning-delta' } & AgentEventReasoningDelta)
  | ({ type: 'tool-use-start' } & AgentEventToolUseStart)
  | ({ type: 'tool-use-delta' } & AgentEventToolUseDelta)
  | ({ type: 'tool-use-end' } & AgentEventToolUseEnd)
  | ({ type: 'server-tool-use' } & AgentEventServerToolUse)
  | ({ type: 'server-tool-result' } & AgentEventServerToolResult)
  | ({ type: 'usage' } & AgentEventUsage)
  | ({ type: 'error' } & AgentEventError)
  | ({ type: 'stop' } & AgentEventStop)
  | ({ type: 'lifecycle' } & AgentEventLifecycle);
