// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stream-lifecycle moments that are neither content nor a terminal
 * [`AgentEventStopReason`].
 */
export type AgentEventLifecyclePhase = 'started' | 'heartbeat';
