// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskState } from './AgentTaskState';

/**
 * One engine-authored lifecycle transition.
 */
export type AgentTaskStateChanged = {
  taskId: string;
  state: AgentTaskState;
  previousState?: AgentTaskState;
  summary?: string;
};
