// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEventApprovalRequested } from './AgentEventApprovalRequested';
import type { AgentEventApprovalResolved } from './AgentEventApprovalResolved';
import type { AgentEventArtifactProduced } from './AgentEventArtifactProduced';
import type { AgentEventCommandStarted } from './AgentEventCommandStarted';
import type { AgentEventContextCompacted } from './AgentEventContextCompacted';
import type { AgentEventDeviceStepRequested } from './AgentEventDeviceStepRequested';
import type { AgentEventDeviceStepResolved } from './AgentEventDeviceStepResolved';
import type { AgentEventError } from './AgentEventError';
import type { AgentEventFileChanged } from './AgentEventFileChanged';
import type { AgentEventInputRequested } from './AgentEventInputRequested';
import type { AgentEventInputResolved } from './AgentEventInputResolved';
import type { AgentEventLifecycle } from './AgentEventLifecycle';
import type { AgentEventProgressUpdate } from './AgentEventProgressUpdate';
import type { AgentEventReasoningDelta } from './AgentEventReasoningDelta';
import type { AgentEventServerToolResult } from './AgentEventServerToolResult';
import type { AgentEventServerToolUse } from './AgentEventServerToolUse';
import type { AgentEventSourceList } from './AgentEventSourceList';
import type { AgentEventStop } from './AgentEventStop';
import type { AgentEventTextDelta } from './AgentEventTextDelta';
import type { AgentEventToolExecutionEnd } from './AgentEventToolExecutionEnd';
import type { AgentEventToolExecutionQueued } from './AgentEventToolExecutionQueued';
import type { AgentEventToolExecutionStart } from './AgentEventToolExecutionStart';
import type { AgentEventToolUseDelta } from './AgentEventToolUseDelta';
import type { AgentEventToolUseEnd } from './AgentEventToolUseEnd';
import type { AgentEventToolUseStart } from './AgentEventToolUseStart';
import type { AgentEventTurnDiff } from './AgentEventTurnDiff';
import type { AgentEventUsage } from './AgentEventUsage';
import type { AgentTaskStateChanged } from './AgentTaskStateChanged';

/**
 * The discriminated event union. See the module doc for which three real
 * dialects justify this variant set and which StreamChunk variants were
 * deliberately left out.
 */
export type AgentEvent =
  | ({ type: 'text-delta' } & AgentEventTextDelta)
  | ({ type: 'reasoning-delta' } & AgentEventReasoningDelta)
  | ({ type: 'tool-use-start' } & AgentEventToolUseStart)
  | ({ type: 'tool-use-delta' } & AgentEventToolUseDelta)
  | ({ type: 'tool-use-end' } & AgentEventToolUseEnd)
  | ({ type: 'server-tool-use' } & AgentEventServerToolUse)
  | ({ type: 'server-tool-result' } & AgentEventServerToolResult)
  | ({ type: 'usage' } & AgentEventUsage)
  | ({ type: 'error' } & AgentEventError)
  | ({ type: 'stop' } & AgentEventStop)
  | ({ type: 'lifecycle' } & AgentEventLifecycle)
  | ({ type: 'progress-update' } & AgentEventProgressUpdate)
  | ({ type: 'tool-execution-queued' } & AgentEventToolExecutionQueued)
  | ({ type: 'tool-execution-start' } & AgentEventToolExecutionStart)
  | ({ type: 'command-started' } & AgentEventCommandStarted)
  | ({ type: 'file-changed' } & AgentEventFileChanged)
  | ({ type: 'turn-diff' } & AgentEventTurnDiff)
  | ({ type: 'tool-execution-end' } & AgentEventToolExecutionEnd)
  | ({ type: 'source-list' } & AgentEventSourceList)
  | ({ type: 'approval-requested' } & AgentEventApprovalRequested)
  | ({ type: 'approval-resolved' } & AgentEventApprovalResolved)
  | ({ type: 'input-requested' } & AgentEventInputRequested)
  | ({ type: 'input-resolved' } & AgentEventInputResolved)
  | ({ type: 'device-step-requested' } & AgentEventDeviceStepRequested)
  | ({ type: 'device-step-resolved' } & AgentEventDeviceStepResolved)
  | ({ type: 'artifact-produced' } & AgentEventArtifactProduced)
  | ({ type: 'context-compacted' } & AgentEventContextCompacted)
  | ({ type: 'task-state-changed' } & AgentTaskStateChanged);
