// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEventFileChangeKind } from './AgentEventFileChangeKind';

export type AgentEventFileChanged = {
  toolCallId: string;
  path: string;
  change: AgentEventFileChangeKind;
};
