// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable task lifecycle emitted by an agent engine.
 *
 * `ReadyForReview` is intentionally distinct from `Completed`: engine work can
 * finish before a human accepts it. Timeouts map to `Failed` with a summary,
 * and recovery maps back to `Running`; neither is a durable product state.
 */
export type AgentTaskState =
  | 'queued'
  | 'running'
  | 'awaiting_input'
  | 'ready_for_review'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'paused'
  | 'archived';
