// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentEventTurnDiff = {
  unifiedDiff: string;
  /**
   * Paths the diff covers, so a surface can list them without parsing it.
   */
  paths: Array<string>;
};
