// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentEventError = {
  message: string;
  code?: string;
  retryable?: boolean;
  retryAfterSeconds?: number;
};
