// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentEventUsage = {
  inputTokens?: number;
  outputTokens?: number;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  /**
   * Subset of `cache_write_tokens` billed at Anthropic's 1-hour cache
   * rate. See `StreamChunkUsage.cacheWrite1hTokens`'s docstring for why
   * this is a separate field rather than a flag on `cache_write_tokens`.
   */
  cacheWrite1hTokens?: number;
  reasoningTokens?: number;
};
