// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from './serde_json/JsonValue';

export type AgentEventDeviceStepRequested = {
  toolCallId: string;
  /**
   * Which device tool the model called.
   */
  toolName: string;
  /**
   * Stable id of the device the step was issued to. Only that device may
   * answer it.
   */
  deviceId: string;
  /**
   * How the device names itself, for surfaces that must tell the user which
   * machine to go to.
   */
  deviceName: string;
  /**
   * One line naming what runs and where, authored by the host from the
   * model's arguments rather than echoed from them.
   */
  summary: string;
  /**
   * The step's arguments as the host planned them: a granted folder id and
   * the path, text, or command the device will act on.
   */
  input: JsonValue;
  /**
   * When the pause stops being answerable, in milliseconds since the epoch.
   */
  expiresAtMs: number;
};
