// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable task lifecycle emitted by an agent engine.
 *
 * `ReadyForReview` is intentionally distinct from `Completed`: engine work can
 * finish before a human accepts it. `AwaitingInput` waits on the user and
 * `AwaitingApproval` on a permission decision. `Partial` finished with only
 * part of the work done, and `TimedOut` stopped on a time budget rather than
 * an error. The last five variants were added after the first nine shipped,
 * so a reader built before them sees each through `legacy_equivalent`.
 */
export type AgentTaskState =
  | 'queued'
  | 'running'
  | 'awaiting_input'
  | 'ready_for_review'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'paused'
  | 'archived'
  | 'planning'
  | 'awaiting_approval'
  | 'resuming'
  | 'partial'
  | 'timed_out';
