// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from './serde_json/JsonValue';

export type AgentEventInputRequested = {
  toolCallId: string;
  connectorId: string;
  toolName: string;
  /**
   * Remote-authored input-request definitions, verbatim JSON. UNTRUSTED and
   * host-bounded (count/size capped) before this event is emitted; the host
   * treats them as data to render a form, never as instructions to execute.
   */
  inputRequests: JsonValue;
  /**
   * Opaque continuation token echoed back to the server on resume.
   */
  requestState?: string;
  /**
   * 0-based MRTR round; increments each time the same call re-pauses.
   */
  round: number;
};
