// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppServerError } from './AppServerError';
import type { JsonValue } from './serde_json/JsonValue';

export type AppServerResponse = { id: JsonValue; result?: JsonValue; error?: AppServerError };
