// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppServerCapabilities = {
  threads: boolean;
  turns: boolean;
  streaming: boolean;
  approvals: boolean;
  tools: boolean;
  mcp: boolean;
  checkpoints: boolean;
  worktrees: boolean;
  models: boolean;
  /**
   * v8 surfaces. Each is false on a host that does not implement that
   * family, so a client hides the control instead of calling a method that
   * answers "unavailable".
   */
  account?: boolean;
  instructions?: boolean;
  skills?: boolean;
  plugins?: boolean;
  hooks?: boolean;
  settings?: boolean;
  commands?: boolean;
  /**
   * `thread/delete` removes a thread and everything persisted with it.
   */
  threadDelete?: boolean;
  /**
   * `thread/reconnect` returns the live state of a running turn, so a
   * client that lost its connection resumes rendering without a gap.
   */
  reconnect?: boolean;
  /**
   * Threads carry a writer lease, and `thread/writer/*` hand it over.
   */
  writerLease?: boolean;
};
