// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time-bounded claim on the right to append turns to a thread.
 *
 * Every process that runs turns on a thread holds one while it works and
 * renews it; a claim that is not renewed before `expires_at` is stale and the
 * next writer takes it over.
 */
export type DeveloperSessionWriter = {
  holderId: string;
  /**
   * Which program holds the claim, for a person deciding whether to take it.
   */
  holderLabel: string;
  acquiredAt: string;
  expiresAt: string;
  /**
   * True when the answering host is the holder.
   */
  heldByThisHost: boolean;
  /**
   * True when the claim has lapsed and the next writer will take it over.
   */
  stale: boolean;
};
