// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperApprovalOutcome } from './DeveloperApprovalOutcome';

export type DeveloperSessionApproval = {
  requestId: string;
  kind: string;
  summary: string;
  outcome: DeveloperApprovalOutcome;
  requestedAt: string;
  decidedAt: string;
};
