// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical Auto-routing task attached by a presentation client to a local
 * developer turn. The Rust host remains the routing-policy owner; clients
 * classify intent but never select a concrete provider route themselves.
 */
export type DeveloperRoutingTaskType =
  | 'simple_chat'
  | 'general'
  | 'coding'
  | 'reasoning'
  | 'creative_writing'
  | 'multimodal'
  | 'long_context'
  | 'research'
  | 'agentic'
  | 'computer-use'
  | 'image_generation';
