// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperFileChangeKind } from './DeveloperFileChangeKind';
import type { FileChangeNotice } from './FileChangeNotice';
import type { FileChangeSubject } from './FileChangeSubject';

export type DeveloperSessionFileChange = {
  path: string;
  kind: DeveloperFileChangeKind;
  tool: string;
  toolCallId: string;
  changedAt: string;
  /**
   * Why the file changed, in one line a surface can show beside the path.
   */
  reason?: string;
  subject?: FileChangeSubject;
  notices?: Array<FileChangeNotice>;
};
