// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable trust boundary for a developer session.
 *
 * `Unknown` is reserved for legacy sessions that predate persisted routing
 * authority. Clients may list those sessions, but must not silently resume or
 * send a turn until the user explicitly chooses a new boundary.
 */
export type DeveloperSessionTrustMode = 'local' | 'byok' | 'managed' | 'unknown';
