// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasoning control supported by the current CLI developer runtime.
 */
export type DeveloperReasoningEffort = 'low' | 'medium' | 'high' | 'max';
