// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperSessionFileChange } from './DeveloperSessionFileChange';
import type { DeveloperSessionSource } from './DeveloperSessionSource';
import type { HandoffArchitecture } from './HandoffArchitecture';
import type { HandoffDecision } from './HandoffDecision';
import type { HandoffEnvironment } from './HandoffEnvironment';
import type { HandoffLastTurn } from './HandoffLastTurn';
import type { HandoffLocalResource } from './HandoffLocalResource';
import type { HandoffOrigin } from './HandoffOrigin';
import type { HandoffPlanStep } from './HandoffPlanStep';
import type { HandoffPosture } from './HandoffPosture';
import type { HandoffValidation } from './HandoffValidation';
import type { HandoffWorkspace } from './HandoffWorkspace';
import type { PendingApprovalSnapshot } from './PendingApprovalSnapshot';

/**
 * Everything one surface hands another when a session moves between them.
 *
 * Nothing in it is a live handle: the record is the whole of what travels, so
 * a receiver rebuilds its own processes instead of inheriting any.
 */
export type DeveloperSessionHandoff = {
  /**
   * Version the producing surface speaks. A receiver that cannot speak it
   * refuses the handoff rather than reading fields by guesswork.
   */
  protocolVersion: number;
  threadId: string;
  origin: HandoffOrigin;
  issuedBy: DeveloperSessionSource;
  issuedAt: string;
  fromEnvironment: HandoffEnvironment;
  toEnvironment: HandoffEnvironment;
  workspace: HandoffWorkspace;
  posture: HandoffPosture;
  /**
   * What the session is trying to achieve, in the user's terms.
   */
  objective?: string;
  decisions?: Array<HandoffDecision>;
  /**
   * What the session established about the repository it is working in.
   * Rediscovering it costs the receiving surface the same reads the origin
   * already paid for, so it travels with the work.
   */
  architecture?: HandoffArchitecture;
  plan?: Array<HandoffPlanStep>;
  /**
   * Every file the session changed, so the receiver knows the work even
   * when the tree it opens is at a different commit.
   */
  modifiedFiles?: Array<DeveloperSessionFileChange>;
  validations?: Array<HandoffValidation>;
  /**
   * Approvals the origin was still waiting on. They are re-asked here; a
   * decision is never inherited across the move.
   */
  pendingApprovals?: Array<PendingApprovalSnapshot>;
  lastTurn?: HandoffLastTurn;
  /**
   * Local resources the origin was running. Each one is restarted here.
   */
  localResources?: Array<HandoffLocalResource>;
  /**
   * Opaque fingerprint of the account the origin was signed into, never an
   * address. A receiver signed into a different account refuses the record
   * rather than opening one person's session under another's credential.
   */
  issuedForAccount?: string;
};
