// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeveloperApprovalOutcome =
  'allow_once' | 'allow_session' | 'always_allow' | 'deny' | 'cancel' | 'timeout';
