// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgiworkforceErrorInfo } from './AgiworkforceErrorInfo';

export type ErrorEvent = { message: string; agiworkforce_error_info: AgiworkforceErrorInfo | null };
