// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of file a change touched. A surface renders a test, a manifest
 * and a generated file differently because a reader weighs them differently.
 */
export type FileChangeSubject =
  'source' | 'test' | 'manifest' | 'lockfile' | 'generated' | 'documentation' | 'configuration';
