// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitPullRequestResponse = {
  url: string;
  created: boolean;
  pushed: boolean;
  note?: string;
};
