// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GranularApprovalConfig = {
  /**
   * Whether to allow shell command approval requests, including inline
   * `with_additional_permissions` and `require_escalated` requests.
   */
  sandbox_approval: boolean;
  /**
   * Whether to allow prompts triggered by execpolicy `prompt` rules.
   */
  rules: boolean;
  /**
   * Whether to allow approval prompts triggered by skill script execution.
   */
  skill_approval: boolean;
  /**
   * Whether to allow prompts triggered by the `request_permissions` tool.
   */
  request_permissions: boolean;
  /**
   * Whether to allow MCP elicitation prompts.
   */
  mcp_elicitations: boolean;
};
