// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianAssessmentAction } from './GuardianAssessmentAction';
import type { GuardianAssessmentDecisionSource } from './GuardianAssessmentDecisionSource';
import type { GuardianAssessmentStatus } from './GuardianAssessmentStatus';
import type { GuardianRiskLevel } from './GuardianRiskLevel';
import type { GuardianUserAuthorization } from './GuardianUserAuthorization';

export type GuardianAssessmentEvent = {
  /**
   * Stable identifier for this guardian review lifecycle.
   */
  id: string;
  /**
   * Thread item being reviewed, when the review maps to a concrete item.
   */
  target_item_id?: string;
  /**
   * Turn ID that this assessment belongs to.
   * Uses `#[serde(default)]` for backwards compatibility.
   */
  turn_id: string;
  status: GuardianAssessmentStatus;
  /**
   * Coarse risk label. Omitted while the assessment is in progress.
   */
  risk_level?: GuardianRiskLevel;
  /**
   * How directly the transcript authorizes the reviewed action.
   */
  user_authorization?: GuardianUserAuthorization;
  /**
   * Human-readable explanation of the final assessment. Omitted while in progress.
   */
  rationale?: string;
  /**
   * Source that produced the terminal assessment decision.
   */
  decision_source?: GuardianAssessmentDecisionSource;
  /**
   * Canonical action payload that was reviewed.
   */
  action: GuardianAssessmentAction;
};
