// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandoffValidationOutcome } from './HandoffValidationOutcome';

/**
 * One check the session ran against the work, so the receiving surface knows
 * what has already been proved and what has not.
 */
export type HandoffValidation = {
  command: string;
  outcome: HandoffValidationOutcome;
  ranAt: string;
  /**
   * Commit the check ran against, which tells the receiver whether it still
   * applies to the tree it has.
   */
  commit?: string;
};
