// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource that exists only on the machine that ran the session. None of
 * these cross a handoff; the receiving surface starts its own.
 */
export type HandoffLocalResource =
  'background_shell' | 'dev_server' | 'mcp_server' | 'sandbox' | 'file_watcher' | 'terminal';
