// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A decision the session made and is expected to keep after the move.
 */
export type HandoffDecision = { summary: string; rationale?: string; decidedAt: string };
