// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandoffLocalResource } from './HandoffLocalResource';
import type { HandoffStart } from './HandoffStart';
import type { PendingApprovalSnapshot } from './PendingApprovalSnapshot';

/**
 * What a receiving surface does with an accepted handoff.
 */
export type HandoffAdmission = {
  start: HandoffStart;
  /**
   * Local resources to start here, because none of them travelled.
   */
  restart?: Array<HandoffLocalResource>;
  /**
   * The turn the origin never finished, reported rather than continued.
   */
  interruptedTurn?: string;
  /**
   * Approvals to ask again on this surface.
   */
  reask?: Array<PendingApprovalSnapshot>;
};
