// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What produced a handoff. A chat or work thread seeds a new coding session;
 * a developer session continues under its own id.
 */
export type HandoffOrigin = 'chat' | 'work' | 'developer_session';
