// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookConfigScope } from './HookConfigScope';

export type HookSummary = {
  event: string;
  command: string;
  scope: HookConfigScope;
  /**
   * Plugin hooks from a project-local plugin directory never run; they are
   * listed so the reason a hook is inert is visible.
   */
  trusted: boolean;
  source?: string;
};
