// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppServerClientInfo } from './AppServerClientInfo';

export type InitializeParams = { clientInfo: AppServerClientInfo; experimentalApi?: boolean };
