// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppServerCapabilities } from './AppServerCapabilities';
import type { AppServerClientInfo } from './AppServerClientInfo';

export type InitializeResponse = {
  serverInfo: AppServerClientInfo;
  protocolVersion: number;
  capabilities: AppServerCapabilities;
  /**
   * Schema version of every `turn/agent_event` envelope this connection
   * will carry. Absent from servers that predate it.
   */
  agentEventSchemaVersion?: number;
  /**
   * Oldest protocol version this server answers. Absent from servers that
   * predate it.
   */
  minimumProtocolVersion?: number;
};
