// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalModelSummary } from './LocalModelSummary';

export type LocalModelListResponse = { models: Array<LocalModelSummary> };
