// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalModelProvider } from './LocalModelProvider';

/**
 * One model discovered from a local-only runtime owned by the CLI.
 *
 * The developer client receives only the provider and model identifier needed
 * for presentation and selection. Base URLs and probe diagnostics stay inside
 * the trusted CLI boundary.
 */
export type LocalModelSummary = { id: string; provider: LocalModelProvider };
