// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpAuthRequiredNotification = {
  threadId: string;
  turnId: string;
  toolCallId: string;
  server: string;
  scope?: string;
  connectUrl?: string;
};
