// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpRemoteTransport } from './McpRemoteTransport';

export type McpAddParams = {
  name: string;
  command?: string;
  args?: Array<string>;
  url?: string;
  transport?: McpRemoteTransport;
  env?: { [key in string]?: string };
  headers?: { [key in string]?: string };
  overwrite?: boolean;
};
