// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpPromptSummary } from './McpPromptSummary';
import type { McpResourceSummary } from './McpResourceSummary';
import type { McpToolSummary } from './McpToolSummary';

export type McpServerToolsResponse = {
  name: string;
  tools: Array<McpToolSummary>;
  prompts?: Array<McpPromptSummary>;
  resources?: Array<McpResourceSummary>;
  warnings?: Array<string>;
};
