// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryScope } from './MemoryScope';

export type MemoryAddResponse = { scope: MemoryScope; path: string };
