// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Turn kinds that reject same-turn steering.
 */
export type NonSteerableTurnKind = 'review' | 'compact';
