// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSummary } from './PluginSummary';

export type PluginUpdateResponse = {
  id: string;
  updated: boolean;
  previousVersion?: string;
  version?: string;
  changedFiles?: Array<string>;
  plugins: Array<PluginSummary>;
};
