// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedPermissionDecision } from './SavedPermissionDecision';
import type { SavedPermissionKind } from './SavedPermissionKind';

export type SavedPermission = {
  id: string;
  kind: SavedPermissionKind;
  label: string;
  decision: SavedPermissionDecision;
};
