// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from './AbsolutePathBuf';
import type { ApprovalsReviewer } from './ApprovalsReviewer';
import type { AskForApproval } from './AskForApproval';
import type { EventMsg } from './EventMsg';
import type { PermissionProfile } from './PermissionProfile';
import type { ReasoningEffort } from './ReasoningEffort';
import type { ServiceTier } from './ServiceTier';
import type { ThreadId } from './ThreadId';

export type SessionConfiguredEvent = {
  session_id: ThreadId;
  forked_from_id: ThreadId | null;
  /**
   * Optional user-facing thread name (may be unset).
   */
  thread_name?: string;
  /**
   * Tell the client what model is being queried.
   */
  model: string;
  model_provider_id: string;
  service_tier: ServiceTier | null;
  /**
   * When to escalate for approval for execution
   */
  approval_policy: AskForApproval;
  /**
   * Configures who approval requests are routed to for review once they have
   * been escalated. This does not disable separate safety checks such as
   * ARC.
   */
  approvals_reviewer: ApprovalsReviewer;
  /**
   * Canonical effective permissions for commands executed in the session.
   */
  permission_profile: PermissionProfile;
  /**
   * Working directory that should be treated as the *root* of the
   * session.
   */
  cwd: AbsolutePathBuf;
  /**
   * The effort the model is putting into reasoning about the user's request.
   */
  reasoning_effort: ReasoningEffort | null;
  /**
   * Identifier of the history log file (inode on Unix, 0 otherwise).
   */
  history_log_id: bigint;
  /**
   * Current number of entries in the history log.
   */
  history_entry_count: number;
  /**
   * Optional initial messages (as events) for resumed sessions.
   * When present, UIs can use these to seed the history.
   */
  initial_messages: Array<EventMsg> | null;
  /**
   * Path in which the rollout is stored. Can be `None` for ephemeral threads
   */
  rollout_path: string | null;
};
