// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from './AbsolutePathBuf';

export type SkillInterface = {
  display_name?: string;
  short_description?: string;
  icon_small?: AbsolutePathBuf;
  icon_large?: AbsolutePathBuf;
  brand_color?: string;
  default_prompt?: string;
};
