// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shape of a command result so a client renders it instead of parsing prose.
 */
export type SlashCommandResultKind = 'text' | 'skills' | 'plugins' | 'mcp' | 'hooks' | 'settings';
