// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperSessionSource } from './DeveloperSessionSource';
import type { DeveloperSessionTrustMode } from './DeveloperSessionTrustMode';
import type { DeveloperSessionWriter } from './DeveloperSessionWriter';
import type { ThreadStatus } from './ThreadStatus';

export type ThreadSummary = {
  id: string;
  title: string;
  model?: string;
  cwd?: string;
  /**
   * Provider route persisted by the CLI host (for example `anthropic`,
   * `ollama`, a custom provider name, or `managed_cloud`). This is metadata,
   * never authority supplied by a presentation client.
   */
  provider?: string;
  trustMode: DeveloperSessionTrustMode;
  createdAt: string;
  updatedAt: string;
  createdBy: DeveloperSessionSource;
  status: ThreadStatus;
  /**
   * Checked-out branch as the host last persisted it. Listing never
   * recomputes it, so a long list costs no git invocations.
   */
  gitBranch?: string;
  /**
   * Top level of the thread's git worktree. Distinct from `cwd`, which may
   * be a subdirectory of it.
   */
  worktreeRoot?: string;
  /**
   * `clientInfo.name` of the connection that created the thread, where
   * `created_by` is only the coarse surface.
   */
  client?: string;
  /**
   * Remote the thread's repository fetches from, with any credential
   * stripped, as the host last persisted it.
   */
  repository?: string;
  /**
   * Process currently entitled to append turns to this thread. Absent when
   * no writer has claimed it.
   */
  writer?: DeveloperSessionWriter;
};
