// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandoffEnvironment } from './HandoffEnvironment';

/**
 * Ask a thread for the record another surface needs to carry it on.
 */
export type ThreadHandoffParams = {
  threadId: string;
  /**
   * Where the work is going. The record is addressed to it, and a surface
   * that is not it refuses the handoff rather than taking someone else's.
   */
  toEnvironment: HandoffEnvironment;
};
