// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperMessage } from './DeveloperMessage';
import type { DeveloperSessionApproval } from './DeveloperSessionApproval';
import type { DeveloperSessionFileChange } from './DeveloperSessionFileChange';
import type { ThreadSummary } from './ThreadSummary';

export type ThreadReadResponse = {
  thread: ThreadSummary;
  messages: Array<DeveloperMessage>;
  /**
   * Whether `messages` is a bounded newest-message window rather than the
   * thread's complete persisted transcript.
   */
  transcriptTruncated: boolean;
  /**
   * Every approval decided on this thread, oldest first.
   */
  approvals?: Array<DeveloperSessionApproval>;
  /**
   * Every file a tool on this thread wrote, oldest first. An entry whose
   * `kind` is `created` is a file the thread generated.
   */
  fileChanges?: Array<DeveloperSessionFileChange>;
};
