// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadCheckpoint = {
  checkpointIndex: number;
  createdAt: string;
  prompt: string;
  messageIndex?: number;
  trackedFiles: number;
};
