// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperMessage } from './DeveloperMessage';
import type { ThreadSummary } from './ThreadSummary';

export type ThreadReadResponse = {
  thread: ThreadSummary;
  messages: Array<DeveloperMessage>;
  /**
   * Whether `messages` is a bounded newest-message window rather than the
   * thread's complete persisted transcript.
   */
  transcriptTruncated: boolean;
};
