// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadListParams = {
  cursor?: string;
  limit?: number;
  cwd?: string;
  includeArchived?: boolean;
  /**
   * Also list the account's open cloud Code sessions, after the local
   * threads on the first page.
   */
  includeCloud?: boolean;
};
