// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperPlanStep } from './DeveloperPlanStep';
import type { DeveloperTodo } from './DeveloperTodo';

export type ThreadPlanNotification = {
  threadId: string;
  plan?: Array<DeveloperPlanStep>;
  todos?: Array<DeveloperTodo>;
};
