// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RewindSkippedFile } from './RewindSkippedFile';
import type { ThreadSummary } from './ThreadSummary';

export type ThreadRewindResponse = {
  thread: ThreadSummary;
  prompt: string;
  conversationRestored: boolean;
  restoredFiles?: Array<string>;
  removedFiles?: Array<string>;
  skippedFiles?: Array<RewindSkippedFile>;
};
