// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperSessionSource } from './DeveloperSessionSource';
import type { DeveloperSessionTrustMode } from './DeveloperSessionTrustMode';
import type { ThreadStatus } from './ThreadStatus';

export type ThreadSummary = {
  id: string;
  title: string;
  model?: string;
  cwd?: string;
  /**
   * Provider route persisted by the CLI host (for example `anthropic`,
   * `ollama`, a custom provider name, or `managed_cloud`). This is metadata,
   * never authority supplied by a presentation client.
   */
  provider?: string;
  trustMode: DeveloperSessionTrustMode;
  createdAt: string;
  updatedAt: string;
  createdBy: DeveloperSessionSource;
  status: ThreadStatus;
};
