// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalModelProvider } from './LocalModelProvider';

export type ThreadStartParams = {
  model?: string;
  provider?: LocalModelProvider;
  cwd?: string;
  title?: string;
};
