// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolApprovalOutcome } from './ToolApprovalOutcome';
import type { ToolApprovalReason } from './ToolApprovalReason';
import type { ToolPermissionScope } from './ToolPermissionScope';

export type ToolApprovalDecision = {
  requestId: string;
  outcome: ToolApprovalOutcome;
  remember: ToolPermissionScope;
  reason: ToolApprovalReason;
};
