// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors `SourceSurface` in `packages/contracts/types/src/suite-contracts.ts`;
 * the TypeScript side asserts the two lists agree.
 */
export type ToolSurface = 'web' | 'desktop' | 'mobile' | 'cli' | 'vscode' | 'chrome';
