// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolArtifact } from './ToolArtifact';
import type { ToolCostHints } from './ToolCostHints';
import type { ToolErrorClass } from './ToolErrorClass';
import type { ToolResultStatus } from './ToolResultStatus';

export type ToolResult = {
  callId: string;
  tool: string;
  status: ToolResultStatus;
  errorClass?: ToolErrorClass;
  message?: string;
  artifacts: Array<ToolArtifact>;
  cost?: ToolCostHints;
};
