// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolArtifactKind } from './ToolArtifactKind';

export type ToolArtifact = {
  id: string;
  kind: ToolArtifactKind;
  uri?: string;
  mimeType?: string;
  byteSize?: number;
};
