// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolPermissionDecision } from './ToolPermissionDecision';
import type { ToolPermissionScope } from './ToolPermissionScope';

export type ToolPermission = {
  tool: string;
  decision: ToolPermissionDecision;
  scope: ToolPermissionScope;
  rememberable: boolean;
};
