// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEventApprovalRiskLevel } from './AgentEventApprovalRiskLevel';
import type { ToolActionClass } from './ToolActionClass';
import type { ToolApprovalReason } from './ToolApprovalReason';

export type ToolApprovalRequest = {
  requestId: string;
  callId: string;
  tool: string;
  actionClass: ToolActionClass;
  arguments: Record<string, unknown>;
  reason: ToolApprovalReason;
  riskLevel: AgentEventApprovalRiskLevel;
  reversible: boolean;
  undoHint?: string;
  unattended: boolean;
  rememberable: boolean;
};
