// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnSummary } from './TurnSummary';

export type TurnStartResponse = { turn: TurnSummary };
