// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a turn ended without completing: the closed set a client may branch on,
 * which prose that changes with every provider cannot be.
 */
export type TurnFailureCode =
  | 'provider_auth_missing'
  | 'account_signed_out'
  | 'plan_excludes_model'
  | 'usage_limit_reached'
  | 'provider_auth_invalid'
  | 'provider_rate_limited'
  | 'free_allowance_exhausted'
  | 'provider_unavailable'
  | 'stream_interrupted'
  | 'context_window_exceeded'
  | 'output_limit_reached'
  | 'refused_by_safety'
  | 'network'
  | 'tool_denied'
  | 'interrupted'
  | 'timeout'
  | 'invalid_request'
  | 'unknown';
