// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperAgentMode } from './DeveloperAgentMode';
import type { DeveloperReasoningEffort } from './DeveloperReasoningEffort';
import type { DeveloperRoutingTaskType } from './DeveloperRoutingTaskType';
import type { UserInput } from './UserInput';

export type TurnStartParams = {
  threadId: string;
  input: Array<UserInput>;
  model?: string;
  routingTaskType?: DeveloperRoutingTaskType;
  cwd?: string;
  agentMode?: DeveloperAgentMode;
  reasoningEffort?: DeveloperReasoningEffort;
  /**
   * Local text files explicitly selected by the client for this session.
   * The host must canonicalize and constrain every path to its workspace.
   */
  contextFiles?: Array<string>;
  /**
   * Client-chosen idempotency key. A `turn/start` repeating the key of a
   * turn the host already accepted on this thread answers that turn instead
   * of starting a second one, so a retry after a dropped connection never
   * runs the same tools twice.
   */
  clientTurnId?: string;
};
