// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStatus } from './TurnStatus';

export type TurnSummary = { id: string; threadId: string; status: TurnStatus };
