// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeSummary } from './WorktreeSummary';

export type WorktreeListResponse = { worktrees: Array<WorktreeSummary> };
