import {act,renderHook,cleanup} from '/Users/siddhartha/Desktop/agiworkforce/.worktrees/billing-e2e/apps/web/node_modules/@testing-library/react/dist/index.js';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {useChatStore} from '/Users/siddhartha/Desktop/agiworkforce/.worktrees/billing-e2e/apps/web/shared/stores/web-chat-store.ts';
import {useChatStream} from '/Users/siddhartha/Desktop/agiworkforce/.worktrees/billing-e2e/apps/web/lib/hooks/useChatStream.ts';
import {useConversations,__resetConversationListLoadForTests} from '/Users/siddhartha/Desktop/agiworkforce/.worktrees/billing-e2e/apps/web/lib/hooks/useConversations.ts';
vi.mock('@/lib/identity/client',()=>({useSession:()=>({getToken:async()=> 'token',isLoaded:true,isSignedIn:true,userId:'user-1'})}));
const id='c0ffee00-0000-4000-8000-000000000001';
const conversation={id,title:'cached',model:'auto',project_id:null,pinned:false,starred:false,archived:false,is_temporary:false,created_at:'2026-09-29T10:00:00.000Z',updated_at:'2026-09-29T11:00:00.000Z'};
const local={id:'10000000-0000-4000-8000-000000000001',role:'user',content:'old',createdAt:'2026-09-29T10:00:00.000Z'};
beforeEach(()=>{useChatStore.getState().reset();__resetConversationListLoadForTests();});
afterEach(()=>{cleanup();vi.useRealTimers();vi.unstubAllGlobals();});
it('continues polling a recovered running turn and clears busy on completion',async()=>{
 vi.useFakeTimers();
 useChatStore.setState({activeConversationId:id,messages:[local],messagesByConversation:{[id]:[local]},conversations:[{...conversation,isTemporary:false}]});
 let polls=0;
 vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({runs:++polls===1?[{id:'11111111-1111-4111-8111-111111111111',state:'running',staleForMs:1}]:[]}),{status:200})));
 renderHook(()=>useChatStream());
 await act(async()=>{await Promise.resolve();await Promise.resolve();});
 expect(useChatStore.getState().isLoading).toBe(true);
 await act(async()=>{await vi.advanceTimersByTimeAsync(5001);});
 expect(polls).toBe(2);
 expect(useChatStore.getState().isLoading).toBe(false);
});
it('sends a cancellation for the recovered cloud run when Stop is pressed',async()=>{
 useChatStore.setState({activeConversationId:id,messages:[local],messagesByConversation:{[id]:[local]},conversations:[{...conversation,isTemporary:false}]});
 const requests=[] as Array<{url:string,method:string}>; 
 vi.stubGlobal('fetch',vi.fn(async(url,init)=>{requests.push({url:String(url),method:init?.method??'GET'});return new Response(JSON.stringify({runs:[{id:'11111111-1111-4111-8111-111111111111',state:'running',staleForMs:1}]}),{status:200});}));
 const {result}=renderHook(()=>useChatStream());
 await act(async()=>{await Promise.resolve();await Promise.resolve();});
 expect(useChatStore.getState().isLoading).toBe(true);
 act(()=>result.current.stopGeneration(id));
 await act(async()=>{await Promise.resolve();});
 expect(requests.some(r=>r.method==='POST'&&r.url.endsWith('/11111111-1111-4111-8111-111111111111'))).toBe(true);
});
it('merges fresh server messages into a cached nonstreaming conversation on reopening',async()=>{
 useChatStore.setState({activeConversationId:id,messages:[local],messagesByConversation:{[id]:[local]},conversations:[{...conversation,isTemporary:false}]});
 const wire=(mid:string,content:string)=>({id:mid,conversation_id:id,role:'user',content,model:null,provider:null,input_tokens:0,output_tokens:0,created_at:'2026-09-29T11:00:00.000Z',metadata:null});
 vi.stubGlobal('fetch',vi.fn(async(url)=>new Response(JSON.stringify(String(url).includes('/'+id)?{conversation,messages:[wire(local.id,'old'),wire('10000000-0000-4000-8000-000000000002','new from another device')],total:2,hasMore:false}:{conversations:[conversation],hasMore:false,nextOffset:1}),{status:200})));
 const {result}=renderHook(()=>useConversations());
 await act(async()=>{expect(await result.current.loadConversation(id)).toBe(true);});
 expect(useChatStore.getState().messagesByConversation[id].map(m=>m.content)).toEqual(['old','new from another device']);
});
