import type { Provider } from '../stores/settingsStore';

export const PROVIDER_LABELS: Record<Provider, string> = {
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  google: 'Google',
  ollama: 'Ollama',
  xai: 'xAI',
  deepseek: 'DeepSeek',
  qwen: 'Qwen',
  moonshot: 'Moonshot AI',
  managed_cloud: 'Managed Cloud',
};

export const THINKING_MODEL_VARIANTS: Record<string, string> = {
  'gpt-5.2': 'gpt-5.2-pro',
  'gpt-5.1': 'gpt-5.1-thinking',
  'gpt-5.1-chat-latest': 'gpt-5.1-thinking',
  'claude-sonnet-4-5': 'claude-opus-4-5',
  'gemini-3-pro': 'gemini-3-deep-think',
  'gemini-3-flash': 'gemini-3-deep-think',
  'qwen3-turbo': 'qwen3-max',
};

export const MODEL_PRESETS: Record<Provider, Array<{ value: string; label: string }>> = {
  openai: [
    { value: 'gpt-5-nano', label: 'GPT-5 Nano ⚡ (Ultra Fast & Cheap)' },
    { value: 'gpt-5.2', label: 'GPT-5.2 ⭐ (Flagship)' },
    { value: 'gpt-5.2-pro', label: 'GPT-5.2 Pro 🧠 (High Performance)' },
    { value: 'gpt-5.2-chat-latest', label: 'GPT-5.2 Chat (Efficient)' },
    { value: 'gpt-5.2-codex', label: 'GPT-5.2 Codex (Agentic Coding)' },
    { value: 'gpt-5.1', label: 'GPT-5.1 (Balanced)' },
    { value: 'gpt-5.1-chat-latest', label: 'GPT-5.1 Instant (Quick Responses)' },
    { value: 'gpt-5.1-thinking', label: 'GPT-5.1 Thinking 🧠' },
    { value: 'gpt-5.1-codex-max', label: 'GPT-5.1-Codex-Max' },
  ],
  anthropic: [
    { value: 'claude-haiku-4-5', label: 'Claude Haiku 4.5 ⚡ (Fast & Cost Effective)' },
    { value: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5 ⭐ (Best Coding - 77.2% SWE-bench)' },
    { value: 'claude-opus-4-5', label: 'Claude Opus 4.5 🧠 (Deep Reasoning/Thinking)' },
  ],
  google: [
    { value: 'gemini-3-flash', label: 'Gemini 3 Flash ⚡ (Ultra Fast & Cheap - Best Value)' },
    { value: 'gemini-3-pro', label: 'Gemini 3 Pro ⭐ (Top Benchmarks)' },
    { value: 'gemini-3-deep-think', label: 'Gemini 3 Deep Think 🧠 (Advanced Reasoning)' },
  ],
  ollama: [{ value: 'llama4-maverick', label: 'Llama 4 Maverick ⭐ (1M Context, Local)' }],
  xai: [
    { value: 'grok-3-mini', label: 'Grok 3 Mini ⚡ (Fast & Affordable)' },
    {
      value: 'grok-4.1-fast-reasoning',
      label: 'Grok 4.1 Fast 🧠 (Reasoning, 2M Context) - Same Price',
    },
    { value: 'grok-4.1-fast', label: 'Grok 4.1 Fast ⚡ (Tool-calling, 2M Context)' },
    { value: 'grok-4.1', label: 'Grok 4.1 ⭐ (Enhanced Reasoning)' },
  ],
  deepseek: [{ value: 'deepseek-v3', label: 'DeepSeek V3.2 ⚡ (Ultra Cheap)' }],
  qwen: [{ value: 'qwen3-max', label: 'Qwen3-Max ⭐ 🧠 (Thinking Mode)' }],
  moonshot: [
    {
      value: 'kimi-k2-thinking',
      label: 'Kimi K2 Thinking ⭐ 🧠 (Advanced Reasoning)',
    },
  ],
  managed_cloud: [{ value: 'managed-cloud-auto', label: 'Auto (Smart Routing) ⭐' }],
};

export const PROVIDERS_IN_ORDER: Provider[] = [
  'openai',
  'anthropic',
  'google',
  'ollama',
  'xai',
  'deepseek',
  'qwen',
  'moonshot',
  'managed_cloud',
];

export const MODEL_CONTEXT_WINDOWS: Record<string, number> = {
  'gpt-5.2': 128_000,
  'gpt-5.2-pro': 128_000,
  'gpt-5.2-chat-latest': 128_000,
  'gpt-5.2-codex': 256_000,

  'gpt-5.1': 128_000,
  'gpt-5.1-chat-latest': 128_000,
  'gpt-5.1-thinking': 128_000,
  'gpt-5.1-codex-max': 256_000,

  'claude-sonnet-4-5': 200_000,
  'claude-haiku-4-5': 200_000,
  'claude-opus-4-5': 200_000,

  'gemini-3-pro': 2_000_000,
  'gemini-3-flash': 2_000_000,
  'gemini-3-deep-think': 2_000_000,

  'llama4-maverick': 1_000_000,

  'grok-4.1': 128_000,
  'grok-4.1-fast': 2_000_000,
  'grok-4.1-fast-reasoning': 2_000_000,

  'qwen3-max': 128_000,

  'kimi-k2-thinking': 256_000,

  'managed-cloud-auto': 128_000,
};

export function getModelContextWindow(modelId: string): number {
  return MODEL_CONTEXT_WINDOWS[modelId] ?? 4096;
}

export interface ModelCapabilities {
  streaming: boolean;
  tools: boolean;
  vision: boolean;
  json: boolean;
  thinking: boolean;
  computerUse: boolean; // Can control mouse/keyboard
  agentic: boolean; // Can run multi-step workflows
  imageGen: boolean; // Can generate images
  videoGen: boolean; // Can generate videos
  search: boolean; // Can search the web
  research: boolean; // Deep research capabilities
}

export interface ModelMetadata {
  id: string;
  apiModelId?: string; // Real API model ID for backend calls
  name: string;
  provider: Provider;
  modelType: 'chat' | 'code' | 'reasoning' | 'multimodal' | 'image' | 'video' | 'search';
  contextWindow: number;
  inputCost: number;
  outputCost: number;
  capabilities: ModelCapabilities;
  benchmarks?: {
    swebench?: number;
    humaneval?: number;
    mmlu?: number;
  };
  speed: 'very-fast' | 'fast' | 'medium' | 'slow';
  quality: 'excellent' | 'good' | 'fair';
  qualityTier: 'fast' | 'balanced' | 'best';
  bestFor: string[];
  released?: string;
}

export const MODEL_METADATA: Record<string, ModelMetadata> = {
  // ============================================
  // MANAGED CLOUD (AUTO)
  // ============================================
  'managed-cloud-auto': {
    id: 'managed-cloud-auto',
    name: 'Auto (Best Value)',
    provider: 'managed_cloud',
    modelType: 'chat',
    contextWindow: 128_000,
    inputCost: 0,
    outputCost: 0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: true,
      computerUse: true,
      agentic: true,
      imageGen: true,
      videoGen: true,
      search: true,
      research: true,
    },
    speed: 'fast',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: ['All Tasks (Managed)'],
    released: 'December 2025',
  },
  // ============================================
  // ULTRA-CHEAP SPEED MODELS (December 2025)
  // ============================================
  'gpt-5-nano': {
    id: 'gpt-5-nano',
    apiModelId: 'gpt-5-nano',
    name: 'GPT-5 Nano',
    provider: 'openai',
    modelType: 'chat',
    contextWindow: 400_000,
    inputCost: 0.05,
    outputCost: 0.4,
    capabilities: {
      streaming: true,
      tools: true,
      vision: false,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: false,
      imageGen: false,
      videoGen: false,
      search: false,
      research: false,
    },
    speed: 'very-fast',
    quality: 'good',
    qualityTier: 'fast',
    bestFor: ['Classification', 'Summarization', 'Simple Tasks', 'High Volume'],
    released: 'December 2025',
  },
  'deepseek-v3': {
    id: 'deepseek-v3',
    apiModelId: 'deepseek-chat',
    name: 'DeepSeek V3.2',
    provider: 'deepseek',
    modelType: 'chat',
    contextWindow: 128_000,
    inputCost: 0.028,
    outputCost: 0.42,
    capabilities: {
      streaming: true,
      tools: true,
      vision: false,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: false,
      imageGen: false,
      videoGen: false,
      search: false,
      research: false,
    },
    speed: 'fast',
    quality: 'good',
    qualityTier: 'fast',
    bestFor: ['Budget Tasks', 'High Volume', 'Cost Efficiency'],
    released: 'December 2025',
  },
  'grok-3-mini': {
    id: 'grok-3-mini',
    apiModelId: 'grok-3-mini',
    name: 'Grok 3 Mini',
    provider: 'xai',
    modelType: 'chat',
    contextWindow: 131_000,
    inputCost: 0.3,
    outputCost: 0.5,
    capabilities: {
      streaming: true,
      tools: true,
      vision: false,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: false,
      imageGen: false,
      videoGen: false,
      search: false,
      research: false,
    },
    speed: 'fast',
    quality: 'good',
    qualityTier: 'fast',
    bestFor: ['General Tasks', 'Cost Efficiency', 'Quick Responses'],
    released: 'December 2025',
  },

  // ============================================
  // EXISTING MODELS
  // ============================================
  'gpt-5.1': {
    id: 'gpt-5.1',
    name: 'GPT-5.1',
    provider: 'openai',
    modelType: 'chat',
    contextWindow: 128_000,
    inputCost: 5.5,
    outputCost: 16.5,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    benchmarks: {
      swebench: 68.0,
      humaneval: 94.0,
      mmlu: 90.5,
    },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'balanced',
    bestFor: ['General Intelligence', 'Reduced Hallucinations', 'Better Prompt Adherence'],
    released: 'November 24, 2025',
  },
  'gpt-5.2': {
    id: 'gpt-5.2',
    name: 'GPT-5.2',
    provider: 'openai',
    modelType: 'chat',
    contextWindow: 128_000,
    inputCost: 6.0,
    outputCost: 18.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    benchmarks: { swebench: 78.5, humaneval: 96.0, mmlu: 93.0 },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'balanced',
    bestFor: ['Flagship Tasks', 'Complex Reasoning'],
    released: 'December 2025',
  },
  'gpt-5.2-pro': {
    id: 'gpt-5.2-pro',
    name: 'GPT-5.2 Pro',
    provider: 'openai',
    modelType: 'reasoning',
    contextWindow: 128_000,
    inputCost: 10.0,
    outputCost: 30.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: { swebench: 82.0, humaneval: 97.5, mmlu: 95.0 },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: ['Deep Analysis', 'Hardest Problems'],
    released: 'December 2025',
  },
  'gpt-5.2-chat-latest': {
    id: 'gpt-5.2-chat-latest',
    name: 'GPT-5.2 Chat',
    provider: 'openai',
    modelType: 'chat',
    contextWindow: 128_000,
    inputCost: 4.0,
    outputCost: 12.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    speed: 'fast',
    quality: 'excellent',
    qualityTier: 'balanced',
    bestFor: ['Chat', 'Quick Responses'],
    released: 'December 2025',
  },
  'gpt-5.2-codex': {
    id: 'gpt-5.2-codex',
    name: 'GPT-5.2 Codex',
    provider: 'openai',
    modelType: 'code',
    contextWindow: 256_000,
    inputCost: 8.0,
    outputCost: 24.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'balanced',
    bestFor: ['Coding', 'Agentic Workflows'],
    released: 'December 2025',
  },
  'gpt-5.1-chat-latest': {
    id: 'gpt-5.1-chat-latest',
    name: 'GPT-5.1 Instant',
    provider: 'openai',
    modelType: 'chat',
    contextWindow: 128_000,
    inputCost: 4.0,
    outputCost: 12.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    benchmarks: {
      swebench: 65.0,
      humaneval: 92.0,
      mmlu: 89.0,
    },
    speed: 'fast',
    quality: 'excellent',
    qualityTier: 'fast',
    bestFor: ['Quick Responses', 'Real-time Applications'],
    released: 'November 24, 2025',
  },
  'gpt-5.1-thinking': {
    id: 'gpt-5.1-thinking',
    name: 'GPT-5.1 Thinking',
    provider: 'openai',
    modelType: 'reasoning',
    contextWindow: 128_000,
    inputCost: 7.0,
    outputCost: 21.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: true,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: {
      swebench: 72.0,
      humaneval: 95.5,
      mmlu: 91.5,
    },
    speed: 'slow',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: ['Complex Tasks', 'Deep Reasoning', 'Multi-step Problems'],
    released: 'November 24, 2025',
  },
  'gpt-5.1-codex-max': {
    id: 'gpt-5.1-codex-max',
    name: 'GPT-5.1-Codex-Max',
    provider: 'openai',
    modelType: 'code',
    contextWindow: 256_000,
    inputCost: 8.0,
    outputCost: 24.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: true,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: {
      swebench: 75.0,
      humaneval: 96.0,
      mmlu: 92.0,
    },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: ['Agentic Coding', 'Long-running Tasks (24h+)', 'Complex Software Engineering'],
    released: 'November 24, 2025',
  },

  'gemini-3-pro': {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    provider: 'google',
    modelType: 'multimodal',
    contextWindow: 2_000_000,
    inputCost: 1.5,
    outputCost: 6.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    benchmarks: {
      swebench: 62.0,
      humaneval: 91.5,
      mmlu: 89.5,
    },
    speed: 'fast',
    quality: 'excellent',
    qualityTier: 'balanced',
    bestFor: ['Reasoning', 'Multimodal Understanding', 'Agentic Coding', 'Enterprise Applications'],
    released: 'November 24, 2025',
  },
  'gemini-3-flash': {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'google',
    modelType: 'multimodal',
    contextWindow: 2_000_000,
    inputCost: 0.1,
    outputCost: 0.4,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: false,
      imageGen: false,
      videoGen: false,
      search: false,
      research: false,
    },
    benchmarks: {
      swebench: 55.0,
      humaneval: 88.5,
      mmlu: 87.0,
    },
    speed: 'very-fast',
    quality: 'excellent',
    qualityTier: 'fast',
    bestFor: ['Speed', 'Cost Efficiency', 'Enterprise Applications'],
    released: 'November 24, 2025',
  },
  'gemini-3-deep-think': {
    id: 'gemini-3-deep-think',
    name: 'Gemini 3 Deep Think',
    provider: 'google',
    modelType: 'reasoning',
    contextWindow: 2_000_000,
    inputCost: 3.0,
    outputCost: 12.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: true,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: {
      swebench: 68.0,
      humaneval: 93.0,
      mmlu: 90.5,
    },
    speed: 'slow',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: ['Advanced Reasoning', 'Complex Enterprise Tasks'],
    released: 'November 24, 2025',
  },

  'claude-sonnet-4-5': {
    id: 'claude-sonnet-4-5',
    name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    modelType: 'code',
    contextWindow: 200_000,
    inputCost: 3.0,
    outputCost: 15.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: true,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    benchmarks: {
      swebench: 77.2,
      humaneval: 93.7,
      mmlu: 88.7,
    },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'balanced',
    bestFor: ['Coding', 'Software Engineering', 'Technical Writing'],
    released: 'November 24, 2025',
  },
  'claude-haiku-4-5': {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    modelType: 'chat',
    contextWindow: 200_000,
    inputCost: 1.0,
    outputCost: 5.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: false,
      imageGen: false,
      videoGen: false,
      search: false,
      research: false,
    },
    benchmarks: {
      swebench: 65.0,
      humaneval: 88.9,
      mmlu: 85.9,
    },
    speed: 'very-fast',
    quality: 'excellent',
    qualityTier: 'fast',
    bestFor: ['Auto Mode', 'Fast Responses', 'Cost Efficiency'],
    released: 'October 15, 2025',
  },
  'claude-opus-4-5': {
    id: 'claude-opus-4-5',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    modelType: 'reasoning',
    contextWindow: 200_000,
    inputCost: 5.0, // Updated December 2025 (was $15)
    outputCost: 25.0, // Updated December 2025 (was $75)
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: true,
      computerUse: true,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: {
      swebench: 74.0,
      humaneval: 94.5,
      mmlu: 91.0,
    },
    speed: 'slow',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: ['Complex Reasoning', 'Research', 'Long Context', 'Deep Analysis'],
    released: 'November 24, 2025',
  },

  'llama4-maverick': {
    id: 'llama4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'ollama',
    modelType: 'chat',
    contextWindow: 1_000_000,
    inputCost: 0,
    outputCost: 0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: false,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: false,
      imageGen: false,
      videoGen: false,
      search: false,
      research: false,
    },
    benchmarks: {
      swebench: 52.0,
      humaneval: 87.0,
      mmlu: 86.0,
    },
    speed: 'fast',
    quality: 'excellent',
    qualityTier: 'fast',
    bestFor: ['Local Inference', 'Privacy', 'Zero Cost'],
    released: 'November 24, 2025',
  },

  'grok-4.1': {
    id: 'grok-4.1',
    name: 'Grok 4.1',
    provider: 'xai',
    modelType: 'chat',
    contextWindow: 128_000,
    inputCost: 5.5,
    outputCost: 16.5,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    benchmarks: {
      swebench: 62.0,
      humaneval: 90.0,
      mmlu: 87.5,
    },
    speed: 'fast',
    quality: 'excellent',
    qualityTier: 'balanced',
    bestFor: [
      'Enhanced Reasoning',
      'Multimodal Understanding',
      'Emotional Intelligence',
      'Reduced Factual Errors',
    ],
    released: 'November 24, 2025',
  },
  'grok-4.1-fast-reasoning': {
    id: 'grok-4.1-fast-reasoning',
    name: 'Grok 4.1 Fast (Reasoning)',
    provider: 'xai',
    modelType: 'reasoning',
    contextWindow: 2_000_000,
    inputCost: 0.1,
    outputCost: 0.4,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: true,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: {
      swebench: 65.0,
      humaneval: 90.0,
      mmlu: 88.0,
    },
    speed: 'very-fast',
    quality: 'excellent',
    qualityTier: 'fast',
    bestFor: [
      'Reasoning',
      'Tool-calling',
      'Agentic Workflows',
      '2M Token Context',
      'Agent Tools API',
    ],
    released: 'November 24, 2025',
  },
  'grok-4.1-fast': {
    id: 'grok-4.1-fast',
    name: 'Grok 4.1 Fast',
    provider: 'xai',
    modelType: 'chat',
    contextWindow: 2_000_000,
    inputCost: 0.1,
    outputCost: 0.4,
    capabilities: {
      streaming: true,
      tools: true,
      vision: true,
      json: true,
      thinking: false,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: false,
    },
    benchmarks: {
      swebench: 58.0,
      humaneval: 88.5,
      mmlu: 86.0,
    },
    speed: 'very-fast',
    quality: 'excellent',
    qualityTier: 'fast',
    bestFor: ['Tool-calling', 'Agentic Workflows', '2M Token Context', 'Agent Tools API'],
    released: 'November 24, 2025',
  },

  'qwen3-max': {
    id: 'qwen3-max',
    name: 'Qwen3-Max',
    provider: 'qwen',
    modelType: 'reasoning',
    contextWindow: 128_000,
    inputCost: 2.5,
    outputCost: 10.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: false,
      json: true,
      thinking: true,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: {
      swebench: 70.0,
      humaneval: 92.5,
      mmlu: 89.0,
    },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: ['Thinking Mode', 'Advanced Reasoning', 'Foundation Model Performance'],
    released: 'November 24, 2025',
  },

  'kimi-k2-thinking': {
    id: 'kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    provider: 'moonshot',
    modelType: 'reasoning',
    contextWindow: 256_000,
    inputCost: 1.5,
    outputCost: 6.0,
    capabilities: {
      streaming: true,
      tools: true,
      vision: false,
      json: true,
      thinking: true,
      computerUse: false,
      agentic: true,
      imageGen: false,
      videoGen: false,
      search: true,
      research: true,
    },
    benchmarks: {
      swebench: 71.3,
      humaneval: 91.0,
      mmlu: 88.5,
    },
    speed: 'medium',
    quality: 'excellent',
    qualityTier: 'best',
    bestFor: [
      'Advanced Reasoning',
      'Agentic Tasks',
      'Thinking Mode',
      'Complex Problem Solving',
      '200-300 Sequential Tool Calls',
    ],
    released: 'November 24, 2025',
  },
};

export function getModelMetadata(modelId: string): ModelMetadata | null {
  return MODEL_METADATA[modelId] ?? null;
}

export function getProviderModels(provider: Provider): ModelMetadata[] {
  return Object.values(MODEL_METADATA).filter((model) => model.provider === provider);
}

export function getAllModels(): ModelMetadata[] {
  return Object.values(MODEL_METADATA);
}

export function formatCost(inputCost: number, outputCost: number): string {
  if (inputCost === 0 && outputCost === 0) {
    return 'Free (Local)';
  }
  return `$${inputCost.toFixed(2)}/$${outputCost.toFixed(2)} per 1M tokens`;
}

export function estimateCost(modelId: string, inputTokens: number, outputTokens: number): number {
  const metadata = getModelMetadata(modelId);
  if (!metadata) return 0;

  const inputCost = (inputTokens / 1_000_000) * metadata.inputCost;
  const outputCost = (outputTokens / 1_000_000) * metadata.outputCost;

  return inputCost + outputCost;
}
