/**
 * @agiworkforce/ui — cross-surface PURE UI: pure-presentation components and
 * plain config/contract data shared by web (apps/web) and desktop (apps/desktop).
 *
 * Boundary rule: ONLY pure presentation (no data/IO, currentColor SVG) and
 * config/contract (plain data) live here. Anything that imports a store, calls
 * invoke()/fetch(), or reads Next/RSC stays per-surface.
 */

export { ProviderMark, hasProviderMark } from './ProviderMark';
export { AgiMark } from './AgiMark';
export { cn } from './cn';
export { lucideToolIcon } from './toolIcon';
export {
  Alert,
  AlertTitle,
  AlertDescription,
  type AlertProps,
  AccessibleDialog,
  type AccessibleDialogProps,
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
  ContextMenu,
  ContextMenuTrigger,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuCheckboxItem,
  ContextMenuRadioItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuGroup,
  ContextMenuPortal,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuRadioGroup,
  HoverCard,
  HoverCardTrigger,
  HoverCardContent,
  Button,
  buttonVariants,
  type ButtonProps,
  LoadingButton,
  type LoadingButtonProps,
  ResizeHandle,
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  SelectScrollUpButton,
  SelectScrollDownButton,
  Spinner,
  spinnerVariants,
  type SpinnerProps,
  Textarea,
  type TextareaProps,
  EmptyState,
  Badge,
  badgeVariants,
  type BadgeProps,
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuRadioGroup,
  Input,
  type InputProps,
  Progress,
  ScrollArea,
  ScrollBar,
  Skeleton,
  SkeletonText,
  SkeletonCard,
  SkeletonListItem,
  SkeletonChatMessage,
  SkeletonTableRow,
  SkeletonFormField,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
  Checkbox,
  Separator,
  Switch,
  ResponsiveContainer,
  type ResponsiveContainerProps,
  ResponsiveGrid,
  type ResponsiveGridProps,
  ResponsiveShow,
  type ResponsiveShowProps,
  TouchTarget,
  type TouchTargetProps,
  useBreakpoint,
  useIsTouchDevice,
  Dialog,
  DialogPortal,
  DialogOverlay,
  DialogClose,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  AlertDialog,
  AlertDialogPortal,
  AlertDialogOverlay,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
  Popover,
  PopoverTrigger,
  PopoverContent,
  type ToastProps,
  type ToastActionElement,
  ToastProvider,
  ToastViewport,
  Toast,
  ToastTitle,
  ToastDescription,
  ToastClose,
  ToastAction,
  ToastIcon,
  Label,
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
  Slider,
  ConfirmDialog,
  useConfirm,
  type ConfirmDialogProps,
  PromptDialog,
  usePrompt,
  type PromptDialogProps,
  FormField,
  type FormFieldProps,
  SectionErrorBoundary,
  type SectionErrorBoundaryProps,
} from './primitives';
export {
  Sidebar,
  type SidebarProps,
  ProjectsView,
  type ProjectsViewProps,
  type ProjectViewProject,
  type ProjectViewConversation,
  type ProjectViewFile,
  SessionItem,
  type SessionItemProps,
  type SessionItemHandlers,
  SearchOverlay,
  type SearchOverlayProps,
  Menu,
  MenuItem,
  MenuSeparator,
  type MenuProps,
  type MenuItemProps,
  getTemporalGroup,
  TEMPORAL_LABELS,
  toSafeDate,
  type SidebarSession,
  type SidebarProject,
  type SidebarMode,
  type SidebarTemporalGroup,
  type SidebarNavItem,
  type SidebarIconComponent,
} from './sidebar';
export {
  SETTINGS_NAV,
  SETTINGS_NAV_GROUPS,
  type SettingsNavEntry,
  type SettingsNavGroup,
  type SettingsNavKey,
} from './settings-nav';
export {
  SettingsModal,
  type SettingsModalProps,
  ConnectorLogo,
  type ConnectorLogoProps,
  type SettingsDataAdapter,
  type SettingsConnector,
  type ConnectedConnector,
  type SettingsSkill,
  type SettingsPlugin,
  type SettingsSectionKey,
} from './settings-modal';
