// The hierarchy is declared once, in the context contract, so the web app, the
// context engine and any other surface resolve a conflict the same way.
export {
  CONTEXT_ONLY_INSTRUCTION_LAYERS,
  INSTRUCTION_CONFLICTS,
  INSTRUCTION_LAYERS,
  contextClassesInInstructionLayer,
  describeInstructionConflictOutcome,
  describeInstructionLayer,
  instructionLayerForContextClass,
  instructionLayerForTrust,
  instructionLayerRank,
  instructionLayerTrust,
  instructionLayerTrustMismatches,
  instructionOrderProblems,
  isContextOnlyInstructionLayer,
  isInstructionLayer,
  orderInstructionBlocks,
  precedenceDisagreements,
  resolveInstructionConflict,
  type InstructionBlock,
  type InstructionConflictOutcome,
  type InstructionConflictRule,
  type InstructionLayer,
  type PrecedenceDisagreement,
} from '@agiworkforce/context';
