/**
 * Cross-surface web-search execution queries.
 *
 * Intrinsic model support remains in model capabilities. Whether AGI has an
 * implemented native, injected, or managed execution path is a harness fact
 * generated by `@agiworkforce/model-registry`. This module exposes the legacy
 * service API without owning provider allowlists of its own.
 */

import { getProvidersWithImplementedHarnessFeature } from '@agiworkforce/types';

/** Providers for which the v1 route injects a native web-search server tool
 * that survives to the wire. Derived from canonical harness execution facts. */
export const WEB_SEARCH_INJECTION_PROVIDERS: ReadonlySet<string> = new Set(
  getProvidersWithImplementedHarnessFeature('webSearchInjection'),
);

/** True when the v1 chat route injects a native web-search tool for `provider`
 * that survives to the wire. */
export function providerInjectsWebSearchTool(provider: string | undefined | null): boolean {
  return provider ? WEB_SEARCH_INJECTION_PROVIDERS.has(provider.toLowerCase()) : false;
}

/**
 * Providers for which enabling web search actually, provably yields results
 * TODAY via an implemented native/resolved harness path. Does NOT include
 * providers that only search via the generic tool fallback.
 */
export const WEB_SEARCH_CAPABLE_PROVIDERS: ReadonlySet<string> = new Set(
  getProvidersWithImplementedHarnessFeature('webSearch'),
);

/**
 * True when turning on the composer Web search toggle for a model on
 * `provider` actually produces web results TODAY via a provider-native or
 * resolved path (NOT counting the WP4 generic-tool fallback — see
 * `webSearchNeedsGenericTool` for that half of the gate).
 */
export function providerSupportsWebSearch(provider: string | undefined | null): boolean {
  return provider ? WEB_SEARCH_CAPABLE_PROVIDERS.has(provider.toLowerCase()) : false;
}

/**
 * WP4 — true for providers with NO working provider-native search path on
 * this route, so a genuinely-search-capable experience for them requires the
 * generic platform-executed `web_search` function tool rather than a native
 * harness path. This is every provider absent from the registry-derived
 * `WEB_SEARCH_CAPABLE_PROVIDERS` set.
 *
 * Server-side gating (request-processor.ts) offers the generic tool when
 * this is true AND a search backend is configured
 * (`webSearchBackendConfigured()` in web-search-tool.ts) AND the resolved
 * model is tools-capable AND the request enters the streaming tool loop.
 * Composer UIs must use `isWebSearchAvailable` below so model capability and
 * real deployment readiness stay aligned with the server gate.
 */
export function webSearchNeedsGenericTool(provider: string | undefined | null): boolean {
  if (!provider) return false;
  return !WEB_SEARCH_CAPABLE_PROVIDERS.has(provider.toLowerCase());
}

export interface WebSearchAvailabilityInput {
  provider: string | undefined | null;
  /** Model/catalog support for the provider's own hosted search path. */
  modelSupportsNativeSearch: boolean | undefined;
  /** Function/tool calling support required by AGI's generic search tool. */
  modelSupportsTools: boolean | undefined;
  /** Whether this deployment has the generic search backend configured. */
  genericBackendConfigured: boolean;
}

/**
 * Cross-surface truth for whether the Web search composer control can produce
 * results for the selected Cloud model right now.
 *
 * Provider-native search requires the model's intrinsic `search` capability.
 * The AGI-managed fallback intentionally does not: it is an ordinary function
 * tool executed by the platform, so it requires tool calling plus the real
 * deployment backend. This mirrors `shouldOfferGenericWebSearchTool` in the
 * web route without leaking server environment details into clients.
 */
export function isWebSearchAvailable({
  provider,
  modelSupportsNativeSearch,
  modelSupportsTools,
  genericBackendConfigured,
}: WebSearchAvailabilityInput): boolean {
  if (!provider) return false;
  if (providerSupportsWebSearch(provider)) return modelSupportsNativeSearch === true;
  return (
    webSearchNeedsGenericTool(provider) && modelSupportsTools === true && genericBackendConfigured
  );
}
