// screens-j-legal.jsx — Section J · Legal + errors (3 screens)

// J39 · Legal index
function LegalIndex({ dark = false }) {
  const p = wfPalette(dark);
  const items = [
    ['eye', 'Privacy policy', 'Last updated · May 18, 2026'],
    ['flag', 'Terms of service', 'Last updated · May 1, 2026'],
    ['info', 'Article 50 disclosures (EU AI Act)', 'For EU users · transparency obligations'],
    ['book', 'Open-source acknowledgments', '184 packages · MIT, Apache 2, BSD'],
    ['lock', 'Cookie & tracking', 'No ATT prompts unless tracking is enabled'],
    ['heart', 'California consumer privacy (CCPA)', 'Your CCPA rights'],
  ];
  return (
    <WirePhone dark={dark}>
      <WireTopBar dark={dark} left="back" title="Legal" />
      <WireBg dark={dark}>
        {items.map(([g, t, sub]) => (
          <WireListRow
            key={t}
            dark={dark}
            leading={<WireGlyph dark={dark} kind={g} size={20} />}
            title={t}
            sub={sub}
            trailing={<WireGlyph dark={dark} kind="chev" size={14} />}
          />
        ))}
        <div style={{ padding: '14px 18px' }}>
          <WireText dark={dark} hand size={11} color={p.ink3}>
            Region · United States · change in Personalization
          </WireText>
        </div>
      </WireBg>
    </WirePhone>
  );
}

// J40 · Article 50 disclosures
function Article50({ dark = false }) {
  const p = wfPalette(dark);
  return (
    <WirePhone dark={dark}>
      <WireTopBar dark={dark} left="back" title="Article 50" sub="EU AI Act · transparency" />
      <WireBg dark={dark}>
        <div style={{ padding: '14px 22px 0' }}>
          <span className="wf-script" style={{ fontSize: 28, fontWeight: 700, color: p.ink }}>
            You're talking to an AI.
          </span>
          <div style={{ marginTop: 4 }}>
            <WireText dark={dark} hand size={12} color={p.ink3}>
              This screen meets Article 50 of the EU AI Act.
            </WireText>
          </div>
        </div>
        <div style={{ padding: '18px 22px 0', display: 'flex', flexDirection: 'column', gap: 14 }}>
          {[
            [
              '1',
              'AI detection',
              'Every response in AGI is generated by a large language model. The provider and model name appear under each turn as a provenance chip.',
            ],
            [
              '2',
              'Synthetic content',
              'Images, video, and audio AGI generates are watermarked (where the provider supports it) and labelled as AI-generated in the file metadata.',
            ],
            [
              '3',
              'Emotional / biometric inference',
              'AGI does not infer emotion or biometric identity from voice or video, on-device or in cloud.',
            ],
            [
              '4',
              'Public-interest content',
              'AGI labels text generated for the public — drafts, articles, captions — as AI-generated in exports.',
            ],
          ].map(([n, h, body]) => (
            <div
              key={n}
              style={{
                padding: 14,
                borderRadius: 12,
                border: `1.5px solid ${p.rule}`,
                background: dark ? p.surface : '#fff',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <div
                  style={{
                    width: 24,
                    height: 24,
                    borderRadius: 12,
                    background: p.accent,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  <span
                    className="wf-hand"
                    style={{ fontSize: 13, color: '#fff', fontWeight: 700 }}
                  >
                    {n}
                  </span>
                </div>
                <WireText dark={dark} hand size={14} weight={600}>
                  {h}
                </WireText>
              </div>
              <div style={{ marginTop: 8 }}>
                <WireText dark={dark} hand size={13} color={p.ink2}>
                  {body}
                </WireText>
              </div>
            </div>
          ))}
        </div>
        <div style={{ padding: '18px 22px 24px' }}>
          <div
            style={{
              padding: '12px 14px',
              borderRadius: 12,
              border: `1.5px dashed ${p.accent}`,
              display: 'flex',
              alignItems: 'center',
              gap: 10,
            }}
          >
            <div
              style={{
                width: 22,
                height: 22,
                borderRadius: 4,
                background: p.accent,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <WireGlyph dark={true} kind="check" size={14} />
            </div>
            <WireText dark={dark} hand size={13}>
              I understand and acknowledge.
            </WireText>
          </div>
        </div>
      </WireBg>
      <div style={{ padding: '12px 22px 16px' }}>
        <WireButton dark={dark} variant="accent" size="xl" w="100%">
          Continue to AGI
        </WireButton>
      </div>
    </WirePhone>
  );
}

// J41 · Error / Not found
function ErrorScreen({ dark = false, kind = '404' }) {
  const p = wfPalette(dark);
  const cfg = {
    404: {
      num: '404',
      h: "We couldn't find that chat.",
      body: "It may have been deleted, or you don't have access.",
      cta: 'Go to chat',
    },
    net: {
      num: 'OFFLINE',
      h: 'No connection.',
      body: 'Cloud models need internet. On-device models still work.',
      cta: 'Use on-device',
    },
    srv: {
      num: '5XX',
      h: 'AGI is having a moment.',
      body: "Our cloud provider is degraded. We're on it.",
      cta: 'Try again',
    },
  }[kind];
  return (
    <WirePhone dark={dark}>
      <WireTopBar dark={dark} left="back" title="" />
      <WireBg dark={dark}>
        <div
          style={{
            flex: 1,
            padding: '60px 32px 0',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textAlign: 'center',
          }}
        >
          <WireBrand dark={dark} size={64} />
          <div style={{ marginTop: 20 }}>
            <span className="wf-script" style={{ fontSize: 18, color: p.ink3, letterSpacing: 4 }}>
              {cfg.num}
            </span>
          </div>
          <div style={{ marginTop: 10, maxWidth: 320 }}>
            <span className="wf-script" style={{ fontSize: 30, fontWeight: 700, color: p.ink }}>
              {cfg.h}
            </span>
          </div>
          <div style={{ marginTop: 10, maxWidth: 320 }}>
            <WireText dark={dark} hand size={14} color={p.ink2}>
              {cfg.body}
            </WireText>
          </div>
          <div
            style={{
              marginTop: 24,
              display: 'flex',
              flexDirection: 'column',
              gap: 10,
              width: '100%',
              maxWidth: 320,
            }}
          >
            <WireButton dark={dark} variant="accent" size="lg" w="100%">
              {cfg.cta}
            </WireButton>
            <WireButton dark={dark} size="md" w="100%">
              Send feedback
            </WireButton>
          </div>
        </div>
      </WireBg>
    </WirePhone>
  );
}

function renderSectionJ() {
  const W = 470,
    H = 1000;
  const wrap = (id, label, dark, El) => (
    <DCArtboard id={id} label={label} width={W} height={H}>
      <div
        style={{
          width: W,
          height: H,
          padding: 14,
          background: dark ? '#1f1c18' : '#f0eee9',
          boxSizing: 'border-box',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        {El}
      </div>
    </DCArtboard>
  );
  return (
    <DCSection
      id="legal"
      title="11 — Legal & errors"
      subtitle="legal index · Article 50 · 404/offline/5xx"
    >
      {wrap('j39-light', '11.1 · Legal index · light', false, <LegalIndex dark={false} />)}
      {wrap('j39-dark', '11.1 · Legal index · dark', true, <LegalIndex dark />)}

      {wrap('j40-light', '11.2 · Article 50 disclosure · light', false, <Article50 dark={false} />)}
      {wrap('j40-dark', '11.2 · Article 50 disclosure · dark', true, <Article50 dark />)}

      {wrap(
        'j41-404-light',
        '11.3 · 404 not found · light',
        false,
        <ErrorScreen dark={false} kind="404" />,
      )}
      {wrap(
        'j41-net-light',
        '11.3 · Offline · light',
        false,
        <ErrorScreen dark={false} kind="net" />,
      )}
      {wrap(
        'j41-srv-light',
        '11.3 · Server error · light',
        false,
        <ErrorScreen dark={false} kind="srv" />,
      )}
      {wrap('j41-404-dark', '11.3 · 404 not found · dark', true, <ErrorScreen dark kind="404" />)}
    </DCSection>
  );
}

Object.assign(window, { LegalIndex, Article50, ErrorScreen, renderSectionJ });
