import { isCodeForgeHost, isHostingPlatformHost } from '@/lib/connectors/directory/hosts';

const CONNECTOR_BRAND_SLUGS: Readonly<Record<string, string>> = {
  gmail: 'gmail',
  'google-calendar': 'googlecalendar',
  'google-drive': 'googledrive',
  'google-sheets': 'googlesheets',
  'google-analytics': 'googleanalytics',
  bigquery: 'googlebigquery',
  gcp: 'googlecloud',
  notion: 'notion',
  airtable: 'airtable',
  clickup: 'clickup',
  trello: 'trello',
  todoist: 'todoist',
  basecamp: 'basecamp',
  evernote: 'evernote',
  asana: 'asana',
  github: 'github',
  gitlab: 'gitlab',
  bitbucket: 'bitbucket',
  linear: 'linear',
  sentry: 'sentry',
  datadog: 'datadog',
  pagerduty: 'pagerduty',
  circleci: 'circleci',
  vercel: 'vercel',
  n8n: 'n8n',
  confluence: 'confluence',
  atlassian: 'atlassian',
  jira: 'jira',
  zoom: 'zoom',
  discord: 'discord',
  telegram: 'telegram',
  whatsapp: 'whatsapp',
  hubspot: 'hubspot',
  calendly: 'calendly',
  intercom: 'intercom',
  zendesk: 'zendesk',
  mailchimp: 'mailchimp',
  mixpanel: 'mixpanel',
  posthog: 'posthog',
  twitter: 'x',
  instagram: 'instagram',
  facebook: 'facebook',
  youtube: 'youtube',
  stripe: 'stripe',
  shopify: 'shopify',
  quickbooks: 'quickbooks',
  xero: 'xero',
  paypal: 'paypal',
  square: 'square',
  figma: 'figma',
  'anthropic-api': 'anthropic',
  huggingface: 'huggingface',
  wandb: 'weightsandbiases',
  replicate: 'replicate',
  ollama: 'ollama',
  elevenlabs: 'elevenlabs',
  modelcontextprotocol: 'modelcontextprotocol',
  context7: 'modelcontextprotocol',
  cloudflare: 'cloudflare',
  digitalocean: 'digitalocean',
  snowflake: 'snowflake',
  databricks: 'databricks',
  postgresql: 'postgresql',
  mongodb: 'mongodb',
  redis: 'redis',
  elasticsearch: 'elasticsearch',
  dropbox: 'dropbox',
  box: 'box',
  supabase: 'supabase',
  neon: 'neon',
  netlify: 'netlify',
  zapier: 'zapier',
};

const BRAND_HOST_SLUGS: Readonly<Record<string, string>> = {
  'notion.com': 'notion',
  'notion.so': 'notion',
  'notion.site': 'notion',
  'githubcopilot.com': 'github',
  'gitlab.com': 'gitlab',
  'bitbucket.org': 'bitbucket',
  'atlassian.com': 'atlassian',
  'atlassian.net': 'atlassian',
  'asana.com': 'asana',
  'linear.app': 'linear',
  'sentry.dev': 'sentry',
  'sentry.io': 'sentry',
  'datadoghq.com': 'datadog',
  'pagerduty.com': 'pagerduty',
  'circleci.com': 'circleci',
  'vercel.com': 'vercel',
  'n8n.io': 'n8n',
  'n8n.cloud': 'n8n',
  'zoom.us': 'zoom',
  'discord.com': 'discord',
  'discord.gg': 'discord',
  'telegram.org': 'telegram',
  't.me': 'telegram',
  'whatsapp.com': 'whatsapp',
  'hubspot.com': 'hubspot',
  'calendly.com': 'calendly',
  'intercom.com': 'intercom',
  'intercom.io': 'intercom',
  'zendesk.com': 'zendesk',
  'mailchimp.com': 'mailchimp',
  'mixpanel.com': 'mixpanel',
  'posthog.com': 'posthog',
  'x.com': 'x',
  'twitter.com': 'x',
  'instagram.com': 'instagram',
  'facebook.com': 'facebook',
  'youtube.com': 'youtube',
  'stripe.com': 'stripe',
  'shopify.com': 'shopify',
  'myshopify.com': 'shopify',
  'xero.com': 'xero',
  'paypal.com': 'paypal',
  'squareup.com': 'square',
  'figma.com': 'figma',
  'anthropic.com': 'anthropic',
  'claude.ai': 'anthropic',
  'huggingface.co': 'huggingface',
  'wandb.ai': 'weightsandbiases',
  'replicate.com': 'replicate',
  'ollama.com': 'ollama',
  'elevenlabs.io': 'elevenlabs',
  'modelcontextprotocol.io': 'modelcontextprotocol',
  'cloudflare.com': 'cloudflare',
  'digitalocean.com': 'digitalocean',
  'snowflake.com': 'snowflake',
  'snowflakecomputing.com': 'snowflake',
  'databricks.com': 'databricks',
  'postgresql.org': 'postgresql',
  'mongodb.com': 'mongodb',
  'redis.io': 'redis',
  'elastic.co': 'elastic',
  'dropbox.com': 'dropbox',
  'box.com': 'box',
  'googleapis.com': 'google',
  'google.com': 'google',
  'supabase.com': 'supabase',
  'neon.tech': 'neon',
  'netlify.com': 'netlify',
  'zapier.com': 'zapier',
  'make.com': 'make',
  'ifttt.com': 'ifttt',
  'airtable.com': 'airtable',
  'clickup.com': 'clickup',
  'todoist.com': 'todoist',
  'todoist.net': 'todoist',
  'trello.com': 'trello',
  'basecamp.com': 'basecamp',
  'evernote.com': 'evernote',
  'mapbox.com': 'mapbox',
  'algolia.com': 'algolia',
  'clickhouse.com': 'clickhouse',
  'timescale.com': 'timescale',
  'upstash.com': 'upstash',
  'newrelic.com': 'newrelic',
  'dynatrace.com': 'dynatrace',
  'grafana.com': 'grafana',
  'grafana.net': 'grafana',
  'coinmarketcap.com': 'coinmarketcap',
  'alchemy.com': 'alchemy',
  'wolfram.com': 'wolfram',
  'webflow.com': 'webflow',
  'wix.com': 'wix',
  'wordpress.org': 'wordpress',
  'wordpress.com': 'wordpress',
  'postman.com': 'postman',
  'docker.com': 'docker',
  'docker.io': 'docker',
  'nvidia.com': 'nvidia',
  'stackoverflow.com': 'stackoverflow',
  'cypress.io': 'cypress',
  'svelte.dev': 'svelte',
  'deno.com': 'deno',
  'deno.land': 'deno',
  'replit.com': 'replit',
  'oreilly.com': 'oreilly',
  'sap.com': 'sap',
  'apollographql.com': 'apollographql',
  'appwrite.io': 'appwrite',
  'perforce.com': 'perforce',
  'mastercard.com': 'mastercard',
  'netapp.com': 'netapp',
  'onlyoffice.com': 'onlyoffice',
  'vonage.com': 'vonage',
  'vonage.dev': 'vonage',
  'airbyte.com': 'airbyte',
  'airbyte.ai': 'airbyte',
  'anaconda.com': 'anaconda',
  'lucid.app': 'lucid',
  'lucidchart.com': 'lucid',
  'bitly.com': 'bitly',
  'bit.ly': 'bitly',
  'railway.com': 'railway',
  'fly.io': 'flydotio',
  'render.com': 'render',
  'hetzner.com': 'hetzner',
  'ovh.com': 'ovh',
  'ovhcloud.com': 'ovh',
  'jetbrains.com': 'jetbrains',
  'brave.com': 'brave',
  'duckduckgo.com': 'duckduckgo',
  'wikipedia.org': 'wikipedia',
  'spotify.com': 'spotify',
  'reddit.com': 'reddit',
  'tiktok.com': 'tiktok',
  'pinterest.com': 'pinterest',
  'strava.com': 'strava',
  'garmin.com': 'garmin',
  'fitbit.com': 'fitbit',
  'home-assistant.io': 'homeassistant',
  'steampowered.com': 'steam',
  'twitch.tv': 'twitch',
  'nasa.gov': 'nasa',
  'arxiv.org': 'arxiv',
  'producthunt.com': 'producthunt',
  'medium.com': 'medium',
  'substack.com': 'substack',
  'miro.com': 'miro',
  'framer.com': 'framer',
  'retool.com': 'retool',
  'metabase.com': 'metabase',
  'hotjar.com': 'hotjar',
  'matomo.org': 'matomo',
  'meilisearch.com': 'meilisearch',
  'opensearch.org': 'opensearch',
  'selenium.dev': 'selenium',
  'mailgun.com': 'mailgun',
  'pusher.com': 'pusher',
  'livekit.io': 'livekit',
  'cloudinary.com': 'cloudinary',
  'unsplash.com': 'unsplash',
  'pexels.com': 'pexels',
  'giphy.com': 'giphy',
  'crunchbase.com': 'crunchbase',
  'tradingview.com': 'tradingview',
  'robinhood.com': 'robinhood',
  'ethereum.org': 'ethereum',
  'bitcoin.org': 'bitcoin',
  'solana.com': 'solana',
  'chain.link': 'chainlink',
  'opensea.io': 'opensea',
  'binance.com': 'binance',
  'coinbase.com': 'coinbase',
  'revolut.com': 'revolut',
  'wise.com': 'wise',
  'okta.com': 'okta',
  'auth0.com': 'auth0',
  'clerk.com': 'clerk',
  '1password.com': '1password',
  'bitwarden.com': 'bitwarden',
  'tailscale.com': 'tailscale',
  'ngrok.com': 'ngrok',
  'zoho.com': 'zoho',
  'intel.com': 'intel',
  'amd.com': 'amd',
  'apple.com': 'apple',
  'meta.com': 'meta',
  'samsung.com': 'samsung',
  'sony.com': 'sony',
  'shopify.dev': 'shopify',
  'woocommerce.com': 'woocommerce',
  'bigcommerce.com': 'bigcommerce',
  'squarespace.com': 'squarespace',
  'sketch.com': 'sketch',
  'blender.org': 'blender',
  'unrealengine.com': 'unrealengine',
  'godotengine.org': 'godotengine',
  'epicgames.com': 'epicgames',
  'roblox.com': 'roblox',
  'hashicorp.com': 'hashicorp',
  'pulumi.com': 'pulumi',
  'ansible.com': 'ansible',
  'kubernetes.io': 'kubernetes',
  'qdrant.tech': 'qdrant',
  'milvus.io': 'milvus',
  'neo4j.com': 'neo4j',
  'langchain.com': 'langchain',
  'perplexity.ai': 'perplexity',
  'mistral.ai': 'mistralai',
  'deepgram.com': 'deepgram',
  'firebase.google.com': 'firebase',
  'planetscale.com': 'planetscale',
  'prometheus.io': 'prometheus',
  'obsidian.md': 'obsidian',
  'coda.io': 'coda',
  'looker.com': 'looker',
  'scrapy.org': 'scrapy',
  'pptr.dev': 'puppeteer',
  'resend.com': 'resend',
  'brevo.com': 'brevo',
  'agora.io': 'agora',
  'pixabay.com': 'pixabay',
  'suno.com': 'suno',
  'polygon.technology': 'polygon',
  'mastodon.social': 'mastodon',
  'joinmastodon.org': 'mastodon',
  'bsky.app': 'bluesky',
  'signal.org': 'signal',
  'mattermost.com': 'mattermost',
  'rocket.chat': 'rocketdotchat',
  'webex.com': 'webex',
  'typeform.com': 'typeform',
  'surveymonkey.com': 'surveymonkey',
  'qualtrics.com': 'qualtrics',
  'helpscout.com': 'helpscout',
  'gumroad.com': 'gumroad',
  'lemonsqueezy.com': 'lemonsqueezy',
  'paddle.com': 'paddle',
  'braintreepayments.com': 'braintree',
  'adyen.com': 'adyen',
  'razorpay.com': 'razorpay',
  'payoneer.com': 'payoneer',
  'gusto.com': 'gusto',
  'greenhouse.io': 'greenhouse',
  'indeed.com': 'indeed',
  'glassdoor.com': 'glassdoor',
  'uber.com': 'uber',
  'lyft.com': 'lyft',
  'airbnb.com': 'airbnb',
  'expedia.com': 'expedia',
  'tripadvisor.com': 'tripadvisor',
  'openstreetmap.org': 'openstreetmap',
  'here.com': 'here',
  'tomtom.com': 'tomtom',
  'semanticscholar.org': 'semanticscholar',
  'orcid.org': 'orcid',
  'zotero.org': 'zotero',
  'mendeley.com': 'mendeley',
  'ycombinator.com': 'ycombinator',
  'dev.to': 'devdotto',
  'hashnode.com': 'hashnode',
  'quora.com': 'quora',
  'appsmith.com': 'appsmith',
  'budibase.com': 'budibase',
  'baserow.io': 'baserow',
  'superset.apache.org': 'apachesuperset',
  'redash.io': 'redash',
  'umami.is': 'umami',
  'fathom.video': 'fathom',
  'jenkins.io': 'jenkins',
  'travis-ci.com': 'travisci',
  'gitea.io': 'gitea',
  'gitea.com': 'gitea',
  'codeberg.org': 'codeberg',
  'homebrew.sh': 'homebrew',
  'brew.sh': 'homebrew',
  'raspberrypi.com': 'raspberrypi',
  'philips-hue.com': 'philipshue',
  'sonarsource.com': 'sonarqubeserver',
  'snyk.io': 'snyk',
  'vaultproject.io': 'vault',
  'keycloak.org': 'keycloak',
  'lastpass.com': 'lastpass',
  'dashlane.com': 'dashlane',
  'proton.me': 'proton',
  'wireguard.com': 'wireguard',
  'aircall.io': 'aircall',
  'notion.dev': 'notion',
};

const PUBLISHER_BRAND_SLUGS: Readonly<Record<string, string>> = {
  stripe: 'stripe',
  cloudflare: 'cloudflare',
  vercel: 'vercel',
  supabase: 'supabase',
  neondatabase: 'neon',
  github: 'github',
  googleapis: 'google',
  google: 'google',
  googleworkspace: 'google',
  hubspot: 'hubspot',
  atlassian: 'atlassian',
  linear: 'linear',
  getsentry: 'sentry',
  posthog: 'posthog',
  grafana: 'grafana',
  elastic: 'elastic',
  mongodb: 'mongodb',
  redis: 'redis',
  neo4j: 'neo4j',
  brave: 'brave',
  zapier: 'zapier',
  n8nio: 'n8n',
  shopify: 'shopify',
  paypal: 'paypal',
  square: 'square',
  intercom: 'intercom',
  zendesk: 'zendesk',
  figma: 'figma',
  makenotion: 'notion',
  asana: 'asana',
  clickup: 'clickup',
  airtable: 'airtable',
  doist: 'todoist',
  box: 'box',
  dropbox: 'dropbox',
  discord: 'discord',
  spotify: 'spotify',
  anthropics: 'anthropic',
  huggingface: 'huggingface',
  replicate: 'replicate',
  ollama: 'ollama',
  langchainai: 'langchain',
  qdrant: 'qdrant',
  milvusio: 'milvus',
  datadog: 'datadog',
  pagerduty: 'pagerduty',
  docker: 'docker',
  kubernetes: 'kubernetes',
  hashicorp: 'hashicorp',
  pulumi: 'pulumi',
  ansible: 'ansible',
  jetbrains: 'jetbrains',
  nvidia: 'nvidia',
  mapbox: 'mapbox',
  algolia: 'algolia',
  clickhouse: 'clickhouse',
  timescale: 'timescale',
  upstash: 'upstash',
  apollographql: 'apollographql',
  appwrite: 'appwrite',
  perforce: 'perforce',
  sap: 'sap',
  netapp: 'netapp',
  onlyoffice: 'onlyoffice',
  vonage: 'vonage',
  automattic: 'automattic',
  dynatrace: 'dynatrace',
  mastercard: 'mastercard',
  tampermonkey: 'tampermonkey',
  qiskit: 'qiskit',
  hewlettpackard: 'hp',
  bytedance: 'bytedance',
  victoriametrics: 'victoriametrics',
  zoom: 'zoom',
  modelcontextprotocol: 'modelcontextprotocol',
  netlify: 'netlify',
  railwayapp: 'railway',
  digitalocean: 'digitalocean',
  hetzner: 'hetzner',
  intel: 'intel',
  amd: 'amd',
  apple: 'apple',
  samsung: 'samsung',
  sony: 'sony',
  mailgun: 'mailgun',
  mailchimp: 'mailchimp',
  zoho: 'zoho',
  okta: 'okta',
  auth0: 'auth0',
  clerk: 'clerk',
  keycloak: 'keycloak',
  '1password': '1password',
  bitwarden: 'bitwarden',
  tailscale: 'tailscale',
  ngrok: 'ngrok',
  wolfram: 'wolfram',
  nasa: 'nasa',
  reddit: 'reddit',
  pinterest: 'pinterest',
  tiktok: 'tiktok',
  strava: 'strava',
  garmin: 'garmin',
  homeassistant: 'homeassistant',
  epicgames: 'epicgames',
  roblox: 'roblox',
  woocommerce: 'woocommerce',
  bigcommerce: 'bigcommerce',
  squarespace: 'squarespace',
  wix: 'wix',
  webflow: 'webflow',
  framer: 'framer',
  retool: 'retool',
  blender: 'blender',
  godotengine: 'godotengine',
  coinbase: 'coinbase',
  binance: 'binance',
  ethereum: 'ethereum',
  bitcoin: 'bitcoin',
  solanalabs: 'solana',
  metabase: 'metabase',
  snowflakedb: 'snowflake',
  databricks: 'databricks',
  cypressio: 'cypress',
  sveltejs: 'svelte',
  denoland: 'deno',
  replit: 'replit',
  oreilly: 'oreilly',
  wordpress: 'wordpress',
  jenkinsci: 'jenkins',
  homebrew: 'homebrew',
  raspberrypi: 'raspberrypi',
  snyk: 'snyk',
  sonarsource: 'sonarqubeserver',
  resend: 'resend',
  deepgram: 'deepgram',
  mistralai: 'mistralai',
  planetscale: 'planetscale',
  prometheus: 'prometheus',
  obsidianmd: 'obsidian',
  coda: 'coda',
  looker: 'looker',
  scrapy: 'scrapy',
  puppeteer: 'puppeteer',
  mastodon: 'mastodon',
  mattermost: 'mattermost',
  rocketchat: 'rocketdotchat',
  typeform: 'typeform',
  gusto: 'gusto',
  uber: 'uber',
  lyft: 'lyft',
  airbnb: 'airbnb',
  openstreetmap: 'openstreetmap',
  zotero: 'zotero',
  hashnode: 'hashnode',
  budibase: 'budibase',
  baserow: 'baserow',
  lastpass: 'lastpass',
  dashlane: 'dashlane',
  wireguard: 'wireguard',
  twitchdev: 'twitch',
  miroapp: 'miro',
  alchemyplatform: 'alchemy',
  postmanlabs: 'postman',
  gogitea: 'gitea',
  protonmail: 'proton',
  getbrevo: 'brevo',
  openrouterteam: 'openrouter',
  agoraio: 'agora',
  blueskysocial: 'bluesky',
  appsmithorg: 'appsmith',
  umamisoftware: 'umami',
  gitlab: 'gitlab',
};

const VERIFIED_BRAND_SLUGS: ReadonlySet<string> = new Set([
  ...Object.values(CONNECTOR_BRAND_SLUGS),
  ...Object.values(BRAND_HOST_SLUGS),
  ...Object.values(PUBLISHER_BRAND_SLUGS),
]);

export interface BrandSignals {
  readonly publisher: string;
  readonly hosts: readonly string[];
  readonly repositoryOwner?: string | null;
}

export function brandSlugForConnectorId(connectorId: string): string | null {
  return CONNECTOR_BRAND_SLUGS[connectorId] ?? null;
}

function normalizeForBrandMatch(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/gu, '');
}

export function brandSlugForPublisherHandle(handle: string): string | null {
  return PUBLISHER_BRAND_SLUGS[normalizeForBrandMatch(handle)] ?? null;
}

export function brandSlugForPublisher(publisher: string): string | null {
  const normalized = normalizeForBrandMatch(publisher);
  const mapped = PUBLISHER_BRAND_SLUGS[normalized];
  if (mapped) return mapped;
  return VERIFIED_BRAND_SLUGS.has(normalized) ? normalized : null;
}

export function brandSlugForHost(host: string): string | null {
  const lowered = host.toLowerCase();
  if (isHostingPlatformHost(lowered) || isCodeForgeHost(lowered)) return null;
  const labels = lowered.split('.');
  for (let index = 0; index < labels.length - 1; index += 1) {
    const slug = BRAND_HOST_SLUGS[labels.slice(index).join('.')];
    if (slug) return slug;
  }
  return null;
}

export function brandSlugForSignals(signals: BrandSignals): string | null {
  for (const host of signals.hosts) {
    const slug = brandSlugForHost(host);
    if (slug) return slug;
  }
  const publisherSlug = brandSlugForPublisher(signals.publisher);
  if (publisherSlug) return publisherSlug;
  return signals.repositoryOwner ? brandSlugForPublisher(signals.repositoryOwner) : null;
}

export function isVerifiedBrandSlug(slug: string): boolean {
  return VERIFIED_BRAND_SLUGS.has(slug);
}
