export const DIRECTORY_CATEGORIES = [
  'Code',
  'Communication',
  'Data',
  'Design',
  'Financial services',
  'Health',
  'Legal',
  'Life sciences',
  'Productivity',
  'Sales and marketing',
  'Other',
] as const;

export type DirectoryCategory = (typeof DIRECTORY_CATEGORIES)[number];

export const OTHER_CATEGORY: DirectoryCategory = 'Other';

type KeywordCategory = Exclude<DirectoryCategory, typeof OTHER_CATEGORY>;

export interface DirectoryCategorySignals {
  readonly name: string;
  readonly description: string;
  readonly id?: string;
  readonly hosts?: readonly string[];
}

const MAX_CATEGORIES_PER_RECORD = 3;
const NAME_HIT_WEIGHT = 2;
const DESCRIPTION_HIT_WEIGHT = 1;
const HOST_HIT_WEIGHT = 3;
const PREFIX_MARKER = '*';
const RAW_PATTERN_MARKER = '/';

const CATEGORY_TERMS: Readonly<Record<KeywordCategory, readonly string[]>> = {
  Code: [
    'git',
    'github',
    'gitlab',
    'bitbucket',
    'repo',
    'repositor*',
    'commit',
    'pull request',
    'merge request',
    'code',
    'coding',
    'codebase',
    'compiler*',
    'lint*',
    'eslint',
    'prettier',
    'test',
    'testing',
    'unit test',
    'coverage',
    'debug*',
    'ci/cd',
    'continuous integration',
    'continuous delivery',
    'build',
    'builds',
    'deploy*',
    'devops',
    'kubernetes',
    'k8s',
    'docker*',
    'container',
    'helm',
    'terraform',
    'ansible',
    'pulumi',
    'infrastructure',
    'cloud',
    'aws',
    'gcp',
    'azure',
    'serverless',
    'lambda',
    'api',
    'sdk',
    'cli',
    'terminal',
    'shell',
    'bash',
    'ssh',
    'linux',
    'unix',
    'macos',
    'windows',
    'ios',
    'android',
    'npm',
    'pypi',
    'package',
    'library',
    'libraries',
    'framework',
    'react',
    'vue',
    'angular',
    'svelte',
    'next.js',
    'nextjs',
    'node.js',
    'nodejs',
    'python',
    'typescript',
    'javascript',
    'java',
    'rust',
    'golang',
    'kotlin',
    'swift',
    'flutter',
    'dotnet',
    '.net',
    'c#',
    'php',
    'ruby',
    'rails',
    'django',
    'flask',
    'laravel',
    'developer',
    'development',
    'programming',
    'engineer*',
    'software',
    'ide',
    'vscode',
    'vs code',
    'cursor',
    'jetbrains',
    'xcode',
    'sandbox*',
    'runtime',
    'compile*',
    'function',
    'endpoint',
    'webhook',
    'graphql',
    'rest api',
    'openapi',
    'swagger',
    'json schema',
    'schema',
    'orm',
    'prisma',
    'migration',
    'log',
    'logging',
    'observab*',
    'monitoring',
    'tracing',
    'telemetry',
    'incident',
    'on-call',
    'oncall',
    'pagerduty',
    'alerting',
    'uptime',
    'error tracking',
    'sentry',
    'crash',
    'security',
    'vulnerab*',
    'cve',
    'pentest*',
    'penetration test*',
    'secret',
    'auth',
    'oauth',
    'sso',
    'iam',
    'rbac',
    'llm',
    'prompt',
    'rag',
    'fine-tun*',
    'inference',
    'gpu',
    'cuda',
    'benchmark*',
    'eval',
    'evals',
    'evaluation',
    'orchestrat*',
    'browser automation',
    'playwright',
    'puppeteer',
    'selenium',
    'headless',
    'regex',
    'script',
    'scripting',
    'plugin',
    'extension',
    'toolkit',
    'devtools',
    'sysadmin',
    'server management',
    'dns',
    'domain',
    'hosting',
    'cdn',
    'ssl',
    'tls',
    'certificate',
    'network',
    'networking',
    'vpn',
    'proxy',
    'firewall',
    'ip address*',
    'blockchain',
    'smart contract',
    'solidity',
    'web3',
    'evm',
    'rpc',
    'sbom',
    'static analy*',
    'refactor*',
    'agent framework',
    'mcp server',
    'mcp tools',
  ],
  Communication: [
    'slack',
    'discord',
    'telegram',
    'whatsapp',
    'imessage',
    'sms',
    'mms',
    'text message',
    'email',
    'e-mail',
    'mail',
    'gmail',
    'outlook',
    'inbox',
    'messag*',
    'chat',
    'chats',
    'chatting',
    'microsoft teams',
    'zoom',
    'google meet',
    'video call',
    'voice',
    'call',
    'calls',
    'calling',
    'phone',
    'telephony',
    'voip',
    'sip',
    'pbx',
    'twilio',
    'vonage',
    'notification',
    'push notification',
    'webex',
    'mastodon',
    'bluesky',
    'irc',
    'xmpp',
    'live chat',
    'contact center',
    'call center',
    'conferenc*',
    'announcement',
    'broadcast*',
    'dm',
    'dms',
  ],
  Data: [
    'data',
    'database',
    'db',
    'sql',
    'postgres*',
    'mysql',
    'sqlite',
    'mongodb',
    'mongo',
    'redis',
    'snowflake',
    'bigquery',
    'databricks',
    'clickhouse',
    'duckdb',
    'warehouse',
    'lakehouse',
    'data lake',
    'etl',
    'elt',
    'analytics',
    'dashboard',
    'metric',
    'kpi',
    'report',
    'reporting',
    'statistic*',
    'stats',
    'dataset',
    'csv',
    'query',
    'queries',
    'search',
    'web search',
    'search engine',
    'scrap*',
    'crawl*',
    'research',
    'paper',
    'arxiv',
    'scholar*',
    'citation',
    'knowledge base',
    'knowledge graph',
    'graph database',
    'vector',
    'embedding',
    'semantic search',
    'memory',
    'memories',
    'recall',
    'retrieval',
    'lookup',
    'registry',
    'directory',
    'weather',
    'forecast*',
    'climate',
    'geospatial',
    'gis',
    'map',
    'maps',
    'geocod*',
    'location',
    'address',
    'places',
    'satellite',
    'astronom*',
    'news',
    'headline',
    'feed',
    'rss',
    'trend',
    'insight',
    'intelligence',
    'fact',
    'wiki',
    'wikipedia',
    'encyclopedia',
    'reference',
    'open data',
    'census',
    'demograph*',
    'indicator',
    'energy',
    'electricity',
    'sports',
    'score',
    'fixtures',
    'league',
    'ranking',
    'leaderboard',
    'movie',
    'film',
    'extract*',
    'parse',
    'parsing',
    'parser',
    'structured data',
    'json',
    'xml',
    'convert*',
    'transform*',
    'enrich*',
    'verify',
    'verification',
    'validate',
    'validation',
    'monitor',
    'track',
    'tracking',
    'aggregat*',
    'history',
    'archive',
    'explorer',
  ],
  Design: [
    'design',
    'designer',
    'figma',
    'canva',
    'sketch',
    'adobe',
    'photoshop',
    'illustrator',
    'image',
    'photo',
    'picture',
    'video',
    'audio',
    'music',
    'sound',
    'text-to-speech',
    'tts',
    'podcast',
    'animation',
    'animate',
    '3d',
    'render*',
    'svg',
    'icon',
    'logo',
    'font',
    'typograph*',
    'color',
    'colour',
    'palette',
    'ui',
    'ux',
    'wireframe',
    'mockup',
    'prototype',
    'tailwind',
    'css',
    'theme',
    'sprite*',
    'texture',
    'creative',
    'art',
    'artwork',
    'illustration',
    'drawing',
    'canvas',
    'meme',
    'gif',
    'thumbnail',
    'diagram',
    'whiteboard',
    'miro',
    'excalidraw',
    'blender',
    'unity',
    'unreal',
    'godot',
    'game dev*',
    'generat* image*',
    'visual',
    'graphic',
    'media',
    'fashion',
  ],
  'Financial services': [
    'financ*',
    'fintech',
    'payment',
    'pay',
    'payout',
    'invoice',
    'invoicing',
    'billing',
    'subscription',
    'refund',
    'transaction',
    'bank',
    'banking',
    'balance',
    'ledger',
    'accounting',
    'bookkeeping',
    'tax',
    'taxes',
    'taxation',
    'vat',
    'payroll',
    'expense',
    'budget',
    'budgeting',
    'stock',
    'stocks',
    'stock market',
    'equities',
    'etf',
    'bond',
    'fund',
    'funds',
    'funding',
    'portfolio',
    'invest*',
    'trading',
    'trade',
    'trades',
    'trader',
    'broker*',
    'exchange',
    'forex',
    'fx',
    'currenc*',
    'crypto*',
    'bitcoin',
    'btc',
    'ethereum',
    'eth',
    'solana',
    'defi',
    'wallet',
    'nft',
    'usdc',
    'stablecoin',
    'x402',
    'on-chain',
    'onchain',
    'dex',
    'amm',
    'swap',
    'yield',
    'staking',
    'lending',
    'loan',
    'mortgage',
    'credit',
    'underwrit*',
    'insurance',
    'insurer',
    'fraud',
    'aml',
    'kyc',
    'stripe',
    'paypal',
    'square',
    'plaid',
    'quickbooks',
    'xero',
    'prediction market',
    'betting',
    'revenue',
    'mrr',
    'arr',
    'treasury',
    'remittance',
    'money',
    'cash',
    'fee',
    'fees',
    'escrow',
    'settlement',
    'spend',
    'spending',
    'wealth',
    'retirement',
    'pension',
    'liquidat*',
    'market',
    'markets',
    'price',
    'prices',
    'pricing',
    'quote',
    'quotes',
    'ticker',
    'receipt',
    'purchase',
    'order',
    'orders',
  ],
  Health: [
    'health*',
    'medical',
    'medicine',
    'clinic*',
    'patient',
    'hospital',
    'doctor',
    'physician',
    'nurs*',
    'ehr',
    'emr',
    'fhir',
    'hl7',
    'telehealth',
    'telemedicine',
    'symptom',
    'diagnos*',
    'treatment',
    'therapy',
    'therapist',
    'mental health',
    'wellness',
    'wellbeing',
    'well-being',
    'fitness',
    'workout',
    'exercise',
    'gym',
    'strava',
    'whoop',
    'garmin',
    'fitbit',
    'sleep',
    'nutrition*',
    'calorie',
    'diet',
    'meal',
    'meals',
    'pregnan*',
    'due date',
    'fertility',
    'medication',
    'prescription',
    'pharmacy',
    'dental',
    'veterinar*',
    'first aid',
    'epidemi*',
    'public health',
    'hipaa',
    'care plan',
    'caregiver',
    'addiction',
    'substance abuse',
    'rehab*',
    'samhsa',
    'cdc',
    'recovery',
    'strain',
  ],
  Legal: [
    'legal',
    'law',
    'laws',
    'lawyer',
    'attorney',
    'law firm',
    'court',
    'caselaw',
    'case law',
    'statute',
    'legislation',
    'regulation',
    'regulatory',
    'complian*',
    'gdpr',
    'ccpa',
    'sox',
    'dora',
    'nis2',
    'eu ai act',
    'cyber resilience act',
    '/(?<!smart\\s)contracts?\\b',
    'agreement',
    'clause',
    'nda',
    'terms of service',
    'privacy policy',
    'litigation',
    'lawsuit',
    'patent',
    'trademark',
    'copyright',
    'intellectual property',
    'jurisdiction',
    'ordinance',
    'zoning',
    'permit',
    'notary',
    'e-signature',
    'esign*',
    'docusign',
    'tribunal',
    'judge',
    'ruling',
    'verdict',
    'arbitration',
    'sanction',
    'policy gate',
    'governance',
    'audit',
    'attestation',
    'evidence',
    'immigration',
    'deadline',
  ],
  'Life sciences': [
    'pharma*',
    'biotech*',
    'biolog*',
    'biomed*',
    'bioinformatic*',
    'genom*',
    'gene',
    'genes',
    'genetic*',
    'dna',
    'rna',
    'protein',
    'molecul*',
    'chemistr*',
    'chemical',
    'compound',
    'drug',
    'drug discovery',
    'clinical trial',
    'lab',
    'laborator*',
    'assay',
    'pubmed',
    'ncbi',
    'uniprot',
    'sequenc*',
    'crispr',
    'antibod*',
    'vaccine',
    'pathogen',
    'microbio*',
    'neuroscien*',
    'enzyme',
    'fda',
    'life science',
    'aquaculture',
    'agricultur*',
    'crop',
    'livestock',
    'cattle',
    'gardening',
    'plant',
    'species',
    'ecolog*',
    'conservation',
    'wildlife',
  ],
  Productivity: [
    'task',
    'todo',
    'to-do',
    'todoist',
    'project management',
    'project',
    'kanban',
    'sprint',
    'backlog',
    'issue',
    'calendar',
    'schedul*',
    'appointment',
    'booking',
    'reservation',
    'meeting',
    'agenda',
    'reminder',
    'note',
    'notes',
    'notion',
    'obsidian',
    'evernote',
    'notebook',
    'journal',
    'diary',
    'doc',
    'docs',
    'document',
    'documentation',
    'google docs',
    'pdf',
    'file',
    'files',
    'filesystem',
    'folder',
    'storage',
    'drive',
    'dropbox',
    'box',
    'onedrive',
    'sharepoint',
    'upload',
    'download',
    'sync',
    'backup',
    'spreadsheet',
    'excel',
    'sheets',
    'google sheets',
    'airtable',
    'table',
    'form',
    'forms',
    'survey',
    'typeform',
    'workflow',
    'automation',
    'automate',
    'zapier',
    'make.com',
    'n8n',
    'ifttt',
    'integration',
    'productivity',
    'assistant',
    'organiz*',
    'organis*',
    'plan',
    'plans',
    'planner',
    'planning',
    'time tracking',
    'timesheet',
    'pomodoro',
    'habit',
    'goal',
    'okr',
    'checklist',
    'template',
    'wiki',
    'knowledge management',
    'confluence',
    'jira',
    'asana',
    'trello',
    'clickup',
    'linear',
    'monday.com',
    'bookmark',
    'read later',
    'reading list',
    'summar*',
    'translat*',
    'transcri*',
    'dictat*',
    'writing',
    'writer',
    'editor',
    'grammar',
    'spell*',
    'proofread*',
    'clipboard',
    'cron',
    'travel',
    'trip',
    'flight',
    'hotel',
    'itinerar*',
    'shopping list',
    'recipe',
    'learning',
    'course',
    'study',
    'flashcard',
    'quiz',
    'education',
    'tutor',
    'career',
    'job',
    'jobs',
    'resume',
    'hiring',
    'recruit*',
    'employee',
    'onboarding',
    'collaborat*',
    'presentation',
    'slide',
    'deck',
    'ocr',
    'convert pdf',
    'clock',
    'timer',
    'timezone',
    'time zone',
    'countdown',
    'personal',
    'daily',
    'routine',
  ],
  'Sales and marketing': [
    'crm',
    'sales',
    'sale',
    'sell',
    'selling',
    'seller',
    'lead',
    'leads',
    'lead generation',
    'lead gen',
    'prospect*',
    'deal',
    'deals',
    'opportunit*',
    'customer',
    'contact',
    'contacts',
    'hubspot',
    'salesforce',
    'pipedrive',
    'zoho',
    'marketing',
    'campaign',
    'ads',
    'advertis*',
    'google ads',
    'ppc',
    'seo',
    'sem',
    'geo',
    'aeo',
    'keyword',
    'backlink',
    'serp',
    'rank tracking',
    'search console',
    'landing page',
    'funnel',
    'conversion',
    'a/b test*',
    'email marketing',
    'newsletter',
    'mailchimp',
    'klaviyo',
    'brevo',
    'outreach',
    'cold email',
    'engagement',
    'social media',
    'instagram',
    'facebook',
    'tiktok',
    'linkedin',
    'twitter',
    'youtube',
    'pinterest',
    'reddit',
    'influencer',
    'content marketing',
    'content',
    'blog',
    'cms',
    'wordpress',
    'webflow',
    'publish*',
    'brand',
    'branding',
    'reputation',
    'review',
    'reviews',
    'rating',
    'feedback',
    'nps',
    'e-commerce',
    'ecommerce',
    'commerce',
    'shop',
    'shops',
    'shopping',
    'shopify',
    'store',
    'stores',
    'storefront',
    'woocommerce',
    'amazon',
    'etsy',
    'ebay',
    'product',
    'catalog',
    'catalogue',
    'listing',
    'inventory',
    'order management',
    'cart',
    'checkout',
    'coupon',
    'discount',
    'price comparison',
    'affiliate',
    'referral',
    'loyalty',
    'reward',
    'retail',
    'merchant',
    'customer support',
    'support ticket',
    'ticket',
    'helpdesk',
    'help desk',
    'zendesk',
    'freshdesk',
    'intercom',
    'churn',
    'retention',
    'upsell',
    'cpq',
    'proposal',
    'pitch',
    'competitor',
    'competitive intelligence',
    'market research',
    'persona',
    'audience',
    'attribution',
    'utm',
    'growth',
    'launch',
    'startup',
    'saas',
    'business',
    'company',
    'companies',
    'b2b',
    'marketplace',
    'vendor',
    'supplier',
    'shipping',
    'shipment',
    'delivery',
    'logistics',
    'freight',
    'parcel',
    'go-to-market',
  ],
};

const CATEGORY_HOST_DOMAINS: Readonly<Record<KeywordCategory, readonly string[]>> = {
  Code: [
    'vercel.com',
    'cloudflare.com',
    'sentry.io',
    'sentry.dev',
    'datadoghq.com',
    'pagerduty.com',
    'circleci.com',
    'githubcopilot.com',
    'gitlab.com',
    'supabase.com',
    'neon.tech',
    'mongodb.com',
    'redis.io',
    'postman.com',
    'docker.com',
    'hashicorp.com',
    'grafana.com',
    'newrelic.com',
    'dynatrace.com',
    'sonatype.com',
    'snyk.io',
    'checkmarx.com',
    'cypress.io',
    'browserbase.com',
    'netlify.app',
    'nvidia.com',
    'opslevel.com',
    'railway.com',
    'fusionauth.dev',
    'devexpress.com',
    'vaadin.com',
    'svelte.dev',
    'stackoverflow.com',
  ],
  Communication: [
    'slack.com',
    'discord.com',
    'telegram.org',
    'zoom.us',
    'twilio.com',
    'vonage.dev',
    'vonage.com',
    'infobip.com',
    'sendgrid.com',
    'mailgun.com',
    'resend.com',
    'mailbox.bot',
  ],
  Data: [
    'mapbox.com',
    'algolia.com',
    'clickhouse.com',
    'snowflake.com',
    'databricks.com',
    'elastic.co',
    'timescale.com',
    'upstash.com',
    'pinecone.io',
    'weaviate.io',
    'qdrant.tech',
    'exa.ai',
    'tavily.com',
    'brave.com',
    'firecrawl.dev',
    'apify.com',
    'apify.actor',
    'hasdata.com',
    'serper.dev',
    'carto.com',
    'roboflow.com',
    'wolfram.com',
    'airbyte.ai',
    'thoughtspot.app',
  ],
  Design: [
    'figma.com',
    'canva.com',
    'adobe.com',
    'picsart.com',
    'unsplash.com',
    'pexels.com',
    'cloudinary.com',
    'elevenlabs.io',
    'brandfetch.io',
    'eraser.io',
  ],
  'Financial services': [
    'stripe.com',
    'paypal.com',
    'squareup.com',
    'plaid.com',
    'intuit.com',
    'xero.com',
    'coinbase.com',
    'binance.com',
    'alchemy.com',
    'avalara.com',
    'mastercard.com',
    'coinmarketcap.com',
    'flat.cash',
  ],
  Health: ['whoop.com', 'strava.com', 'garmin.com', 'fitbit.com'],
  Legal: ['docusign.com'],
  'Life sciences': ['nih.gov', 'uniprot.org', 'ebi.ac.uk'],
  Productivity: [
    'notion.com',
    'notion.so',
    'notion.site',
    'asana.com',
    'linear.app',
    'clickup.com',
    'monday.com',
    'airtable.com',
    'todoist.net',
    'todoist.com',
    'trello.com',
    'atlassian.com',
    'box.com',
    'dropbox.com',
    'zapier.com',
    'make.com',
    'n8n.io',
    'ifttt.com',
    'calendly.com',
    'lucid.app',
    'padlet.com',
    'onlyoffice.com',
    'egnyte.com',
    'aftership.com',
  ],
  'Sales and marketing': [
    'hubspot.com',
    'salesforce.com',
    'zendesk.com',
    'shopify.com',
    'mailchimp.com',
    'klaviyo.com',
    'semrush.com',
    'ahrefs.com',
    'seranking.com',
    'bitly.com',
    'webflow.com',
    'wix.com',
    'wordpress.org',
    'zomato.com',
  ],
};

const KEYWORD_CATEGORIES = Object.keys(CATEGORY_TERMS) as readonly KeywordCategory[];

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}

function termPattern(term: string): RegExp {
  if (term.startsWith(RAW_PATTERN_MARKER)) return new RegExp(term.slice(1), 'iu');
  if (term.endsWith(PREFIX_MARKER)) {
    return new RegExp(`\\b${escapeRegExp(term.slice(0, -1))}\\w*`, 'iu');
  }
  const words = term.split(' ').map(escapeRegExp).join('\\s+');
  return new RegExp(`(?<![\\w.])${words}(?:s|es)?(?![\\w])`, 'iu');
}

const COMPILED_TERMS: ReadonlyMap<KeywordCategory, readonly RegExp[]> = new Map(
  KEYWORD_CATEGORIES.map((category) => [category, CATEGORY_TERMS[category].map(termPattern)]),
);

const HOST_CATEGORY_INDEX: ReadonlyMap<string, KeywordCategory> = new Map(
  KEYWORD_CATEGORIES.flatMap((category) =>
    CATEGORY_HOST_DOMAINS[category].map((domain) => [domain, category] as const),
  ),
);

function countHits(patterns: readonly RegExp[], text: string): number {
  if (!text) return 0;
  let hits = 0;
  for (const pattern of patterns) if (pattern.test(text)) hits += 1;
  return hits;
}

function hostCategory(host: string): KeywordCategory | null {
  const labels = host.toLowerCase().split('.');
  for (let index = 0; index < labels.length - 1; index += 1) {
    const candidate = labels.slice(index).join('.');
    const category = HOST_CATEGORY_INDEX.get(candidate);
    if (category) return category;
  }
  return null;
}

function idAsText(id: string | undefined): string {
  if (!id) return '';
  const leaf = id.split('/').pop() ?? id;
  return leaf.replace(/[-_.]+/gu, ' ');
}

export function scoreDirectoryCategories(
  signals: DirectoryCategorySignals,
): ReadonlyMap<KeywordCategory, number> {
  const nameText = `${signals.name} ${idAsText(signals.id)}`;
  const scores = new Map<KeywordCategory, number>();
  for (const category of KEYWORD_CATEGORIES) {
    const patterns = COMPILED_TERMS.get(category) ?? [];
    const score =
      countHits(patterns, nameText) * NAME_HIT_WEIGHT +
      countHits(patterns, signals.description) * DESCRIPTION_HIT_WEIGHT;
    if (score > 0) scores.set(category, score);
  }
  for (const host of signals.hosts ?? []) {
    const category = hostCategory(host);
    if (category) scores.set(category, (scores.get(category) ?? 0) + HOST_HIT_WEIGHT);
  }
  return scores;
}

export function deriveDirectoryCategories(signals: DirectoryCategorySignals): DirectoryCategory[] {
  const scores = scoreDirectoryCategories(signals);
  const ranked = KEYWORD_CATEGORIES.filter((category) => scores.has(category)).sort(
    (left, right) => (scores.get(right) ?? 0) - (scores.get(left) ?? 0),
  );
  const chosen = ranked.slice(0, MAX_CATEGORIES_PER_RECORD);
  return chosen.length > 0 ? chosen : [OTHER_CATEGORY];
}

export function isDirectoryCategory(value: string): value is DirectoryCategory {
  return (DIRECTORY_CATEGORIES as readonly string[]).includes(value);
}
