export const VIDEO_PROVIDER_TASK_ATTACHMENT_GRACE_MS = 12 * 60 * 1_000;

export const VIDEO_WORKFLOW_START_DEADLINE_MS = 15_000;
export const VIDEO_JOB_PERSISTENCE_BUDGET_MS = 15_000;

export const VIDEO_JOB_SETUP_BUDGET_MS =
  VIDEO_WORKFLOW_START_DEADLINE_MS + VIDEO_JOB_PERSISTENCE_BUDGET_MS;

export const VIDEO_ADMISSION_FLOOR_SECONDS = 60;
export const VIDEO_ADMISSION_CEILING_SECONDS = 600;

export const VIDEO_GENERATION_ADMISSION_SECONDS = Math.min(
  VIDEO_ADMISSION_CEILING_SECONDS,
  Math.max(VIDEO_ADMISSION_FLOOR_SECONDS, Math.ceil(VIDEO_JOB_SETUP_BUDGET_MS / 1_000)),
);
