import type { CodeSession } from './types';

export const CODE_SESSIONS: CodeSession[] = [
  {
    id: 'recent-commits-plan',
    title: 'Implement plan from recent commits',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'claude/implement-plan-R2cif',
    mode: 'code',
    status: 'connecting',
    environment: 'cloud',
    lastActivityLabel: 'Default',
    transcript: [
      'All changes committed and pushed. All agents have now completed.',
      'Bash pkg-config --exists gtk-3.0 && echo "GDK found" || echo "GDK not found"',
      'Still blocked by DNS. All work is complete and pushed.',
      'These background apt install attempts keep completing but failing silently due to DNS.',
      'All code work is done. No action needed.',
    ],
  },
  {
    id: 'fix-bugs-main',
    title: 'Find and fix bugs',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'codex/fix-bugs-main',
    mode: 'plan',
    status: 'idle',
    environment: 'cloud',
    lastActivityLabel: 'Idle',
    transcript: [],
  },
  {
    id: 'fix-bugs-hxf',
    title: 'Find and fix bugs',
    repo: 'siddharthanagula3/HxF',
    branch: 'codex/fix-bugs-HxF',
    mode: 'code',
    status: 'idle',
    environment: 'cloud',
    lastActivityLabel: 'Idle',
    transcript: [],
  },
  {
    id: 'audit-entire-codebase',
    title: 'Audit entire codebase',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'codex/audit-entire-codebase',
    mode: 'plan',
    status: 'idle',
    environment: 'cloud',
    lastActivityLabel: 'Idle',
    transcript: [],
  },
  {
    id: 'interactive-session',
    title: 'Interactive session',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'desktop/interactive-session',
    mode: 'code',
    status: 'disconnected',
    environment: 'desktop',
    lastActivityLabel: 'Disconnected',
    transcript: [],
  },
  {
    id: 'production-audit-agentautomation',
    title: 'Production-ready codebase audit and fixes',
    repo: 'siddharthanagula3/agiagentautomation',
    branch: 'codex/production-audit',
    mode: 'code',
    status: 'idle',
    environment: 'cloud',
    lastActivityLabel: 'Idle',
    transcript: [],
  },
  {
    id: 'task-notification-archive',
    title: '<task-notification> <task-id>a2e842dca5...',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'archive/task-notification',
    mode: 'code',
    status: 'archived',
    environment: 'desktop',
    lastActivityLabel: 'Disconnected',
    transcript: [],
  },
  {
    id: 'image-source-archive-one',
    title: '[Image: source: /var/folders/9_/_g0m618I0s...',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'archive/image-source-one',
    mode: 'code',
    status: 'archived',
    environment: 'desktop',
    lastActivityLabel: 'Disconnected',
    transcript: [],
  },
  {
    id: 'image-source-archive-two',
    title: '[Image: source: /var/folders/9_/_g0m618I0s...',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'archive/image-source-two',
    mode: 'code',
    status: 'archived',
    environment: 'desktop',
    lastActivityLabel: 'Disconnected',
    transcript: [],
  },
  {
    id: 'archived-interactive-session',
    title: 'Interactive session',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'archive/interactive-session',
    mode: 'code',
    status: 'archived',
    environment: 'desktop',
    lastActivityLabel: 'Disconnected',
    transcript: [],
  },
  {
    id: 'request-interrupted',
    title: '[Request interrupted by user]',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'archive/request-interrupted',
    mode: 'code',
    status: 'archived',
    environment: 'desktop',
    lastActivityLabel: 'Disconnected',
    transcript: [],
  },
  {
    id: 'approved-archive',
    title: 'approved',
    repo: 'siddharthanagula3/agiworkforce-desktop-app',
    branch: 'archive/approved',
    mode: 'code',
    status: 'archived',
    environment: 'desktop',
    lastActivityLabel: 'Disconnected',
    transcript: [],
  },
];

export function getCodeSessionById(id: string | undefined): CodeSession {
  return CODE_SESSIONS.find((session) => session.id === id) ?? CODE_SESSIONS[0];
}
