export type ConnectorCategory =
  | 'Communication'
  | 'Productivity'
  | 'Development'
  | 'Storage'
  | 'Design'
  | 'CRM & Sales'
  | 'Analytics'
  | 'Data & BI'
  | 'Automation'
  | 'Finance'
  | 'Marketing'
  | 'AI & ML'
  | 'Content'
  | 'Meetings'
  | 'Research'
  | 'DevOps';

export type ConnectorAuthType = 'oauth' | 'api_key' | 'mcp_remote' | 'none';

export interface ConnectorDef {
  id: string;
  name: string;
  icon: string;
  iconUrl?: string;
  description: string;
  provider: string;
  category: ConnectorCategory;
  color: string;
  featured?: boolean;
  comingSoon?: boolean;
  authType: ConnectorAuthType;
  oauthProvider?: string;
  mcpPackage?: string;
  mcpTransport?: 'stdio' | 'sse' | 'http';
  oauthScopes?: string[];
  apiKeyPlaceholder?: string;
  docsUrl?: string;
}

export const CONNECTOR_CATEGORIES: ConnectorCategory[] = [
  'Communication',
  'Productivity',
  'Development',
  'Storage',
  'Design',
  'CRM & Sales',
  'Analytics',
  'Data & BI',
  'Automation',
  'Finance',
  'Marketing',
  'AI & ML',
  'Content',
  'Meetings',
  'Research',
  'DevOps',
];

export const CONNECTORS: ConnectorDef[] = [
  // ─────────────────────────────────────────────
  // Featured connectors
  // ─────────────────────────────────────────────
  {
    id: 'gmail',
    name: 'Gmail',
    icon: '\u{1F4E7}',
    iconUrl: 'https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico',
    description: 'Draft replies, summarize threads, & search your inbox',
    provider: 'google',
    category: 'Communication',
    color: 'red',
    featured: true,
    authType: 'oauth',
    oauthProvider: 'google',
    oauthScopes: ['https://www.googleapis.com/auth/gmail.modify'],
    docsUrl: 'https://developers.google.com/gmail/api',
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    icon: '\u{1F4C5}',
    iconUrl: 'https://calendar.google.com/googlecalendar/images/favicons_2020q4/calendar_31.ico',
    description: 'Manage your schedule and coordinate meetings effortlessly',
    provider: 'google',
    category: 'Meetings',
    color: 'blue',
    featured: true,
    authType: 'oauth',
    oauthProvider: 'google',
    oauthScopes: ['https://www.googleapis.com/auth/calendar'],
    docsUrl: 'https://developers.google.com/calendar/api',
  },
  {
    id: 'notion',
    name: 'Notion',
    icon: '\u{1F4DD}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=notion.so&sz=32',
    description: 'Connect your Notion workspace to search, update, and power workflows',
    provider: 'notion',
    category: 'Productivity',
    color: 'gray',
    featured: true,
    authType: 'oauth',
    docsUrl: 'https://developers.notion.com',
  },
  {
    id: 'figma',
    name: 'Figma',
    icon: '\u{1F3A8}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=figma.com&sz=32',
    description: 'Generate diagrams and better code from Figma context',
    provider: 'figma',
    category: 'Design',
    color: 'purple',
    featured: true,
    authType: 'oauth',
    mcpPackage: '@sethdouglasford/mcp-figma',
    mcpTransport: 'stdio',
    docsUrl: 'https://www.figma.com/developers',
  },
  {
    id: 'slack',
    name: 'Slack',
    icon: '\u{1F4AC}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=slack.com&sz=32',
    description: 'Send messages, create canvases, and fetch Slack data',
    provider: 'slack',
    category: 'Communication',
    color: 'purple',
    featured: true,
    authType: 'oauth',
    mcpPackage: '@modelcontextprotocol/server-slack',
    mcpTransport: 'stdio',
    oauthScopes: ['channels:read', 'chat:write', 'users:read'],
    docsUrl: 'https://api.slack.com',
  },
  {
    id: 'canva',
    name: 'Canva',
    icon: '\u{1F58C}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=canva.com&sz=32',
    description: 'Search, create, autofill, and export Canva designs',
    provider: 'canva',
    category: 'Design',
    color: 'blue',
    featured: true,
    authType: 'oauth',
    docsUrl: 'https://www.canva.dev',
  },
  {
    id: 'atlassian',
    name: 'Atlassian',
    icon: '\u{1F680}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=atlassian.com&sz=32',
    description: 'Access Jira & Confluence from Claude',
    provider: 'atlassian',
    category: 'Productivity',
    color: 'blue',
    featured: true,
    authType: 'oauth',
    oauthProvider: 'atlassian',
    docsUrl: 'https://developer.atlassian.com',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    icon: '\u{1F9F2}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=hubspot.com&sz=32',
    description: 'Chat with your CRM data to get personalized insights',
    provider: 'hubspot',
    category: 'CRM & Sales',
    color: 'orange',
    featured: true,
    authType: 'oauth',
    docsUrl: 'https://developers.hubspot.com',
  },
  {
    id: 'linear',
    name: 'Linear',
    icon: '\u{1F3AF}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=linear.app&sz=32',
    description: 'Manage issues, projects & team workflows in Linear',
    provider: 'linear',
    category: 'Development',
    color: 'purple',
    featured: true,
    authType: 'oauth',
    docsUrl: 'https://developers.linear.app',
  },
  {
    id: 'github',
    name: 'GitHub',
    icon: '\u{1F419}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=github.com&sz=32',
    description: 'Read repos, issues, and PRs',
    provider: 'github',
    category: 'Development',
    color: 'gray',
    featured: true,
    authType: 'oauth',
    mcpPackage: '@modelcontextprotocol/server-github',
    mcpTransport: 'stdio',
    oauthScopes: ['repo', 'read:org'],
    docsUrl: 'https://docs.github.com/en/rest',
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    icon: '\u{1F4C1}',
    iconUrl: 'https://ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png',
    description: 'Find and analyze files instantly',
    provider: 'google',
    category: 'Storage',
    color: 'blue',
    featured: true,
    authType: 'oauth',
    oauthProvider: 'google',
    oauthScopes: ['https://www.googleapis.com/auth/drive.readonly'],
    docsUrl: 'https://developers.google.com/drive/api',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    icon: '\u{25B2}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=vercel.com&sz=32',
    description: 'Analyze, debug, and manage projects and deployments',
    provider: 'vercel',
    category: 'DevOps',
    color: 'gray',
    featured: true,
    authType: 'api_key',
    mcpPackage: '@vercel/mcp',
    mcpTransport: 'stdio',
    apiKeyPlaceholder: 'Bearer token...',
    docsUrl: 'https://vercel.com/docs/rest-api',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    icon: '\u{1F4B3}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=stripe.com&sz=32',
    description: 'Payment processing and financial infrastructure tools',
    provider: 'stripe',
    category: 'Finance',
    color: 'purple',
    featured: true,
    authType: 'api_key',
    mcpPackage: '@stripe/mcp',
    mcpTransport: 'stdio',
    apiKeyPlaceholder: 'sk_...',
    docsUrl: 'https://docs.stripe.com/api',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    icon: '\u{26A1}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=supabase.com&sz=32',
    description: 'Manage databases, authentication, and storage',
    provider: 'supabase',
    category: 'Development',
    color: 'green',
    featured: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'sbp_...',
    docsUrl: 'https://supabase.com/docs',
  },
  {
    id: 'context7',
    name: 'Context7',
    icon: '\u{1F4DA}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=context7.com&sz=32',
    description: 'Up-to-date docs for LLMs and AI code editors',
    provider: 'context7',
    category: 'AI & ML',
    color: 'teal',
    featured: true,
    authType: 'mcp_remote',
    mcpPackage: '@upstash/context7-mcp',
    mcpTransport: 'http',
    docsUrl: 'https://context7.com',
  },

  // ─────────────────────────────────────────────
  // Communication
  // ─────────────────────────────────────────────
  {
    id: 'outlook',
    name: 'Outlook',
    icon: '\u{1F4E8}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=outlook.com&sz=32',
    description: 'Microsoft email and calendar',
    provider: 'microsoft',
    category: 'Communication',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    oauthProvider: 'microsoft',
    oauthScopes: ['Mail.ReadWrite', 'Calendars.ReadWrite'],
    docsUrl: 'https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    icon: '\u{1F4E9}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=intercom.com&sz=32',
    description: 'Access to Intercom data for better customer insights',
    provider: 'intercom',
    category: 'Communication',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developers.intercom.com',
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    icon: '\u{1F465}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=teams.microsoft.com&sz=32',
    description: 'Collaborate with your team in Microsoft Teams',
    provider: 'microsoft',
    category: 'Communication',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    oauthProvider: 'microsoft',
    oauthScopes: ['Team.ReadBasic.All', 'Chat.ReadWrite'],
    docsUrl: 'https://learn.microsoft.com/en-us/graph/teams-concept-overview',
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: '\u{1F3AE}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=discord.com&sz=32',
    description: 'Manage Discord servers, channels, and messages',
    provider: 'discord',
    category: 'Communication',
    color: 'purple',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'Bot token...',
    docsUrl: 'https://discord.com/developers/docs',
  },

  // ─────────────────────────────────────────────
  // Productivity
  // ─────────────────────────────────────────────
  {
    id: 'asana',
    name: 'Asana',
    icon: '\u{1F4CB}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=asana.com&sz=32',
    description: 'Connect to Asana to coordinate tasks, projects, and goals',
    provider: 'asana',
    category: 'Productivity',
    color: 'orange',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developers.asana.com',
  },
  {
    id: 'monday',
    name: 'monday.com',
    icon: '\u{1F4C6}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=monday.com&sz=32',
    description: 'Manage projects, boards, and workflows in monday.com',
    provider: 'monday',
    category: 'Productivity',
    color: 'orange',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developer.monday.com',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    icon: '\u{2705}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=clickup.com&sz=32',
    description: 'Project management & collaboration for teams & agents',
    provider: 'clickup',
    category: 'Productivity',
    color: 'purple',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://clickup.com/api',
  },
  {
    id: 'jira',
    name: 'Jira',
    icon: '\u{1F4CC}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=jira.atlassian.com&sz=32',
    description: 'Project management and tracking',
    provider: 'atlassian',
    category: 'Productivity',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    oauthProvider: 'atlassian',
    docsUrl: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3/',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    icon: '\u{1F4CA}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=airtable.com&sz=32',
    description: 'Bring your structured data to Claude',
    provider: 'airtable',
    category: 'Productivity',
    color: 'blue',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'pat...',
    docsUrl: 'https://airtable.com/developers/web/api',
  },

  // ─────────────────────────────────────────────
  // Development
  // ─────────────────────────────────────────────
  {
    id: 'sentry',
    name: 'Sentry',
    icon: '\u{1F41B}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=sentry.io&sz=32',
    description: 'Search, query, and debug errors intelligently',
    provider: 'sentry',
    category: 'Development',
    color: 'purple',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'sntrys_...',
    docsUrl: 'https://docs.sentry.io/api/',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    icon: '\u{2601}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=32',
    description: 'Build applications with compute, storage, and AI',
    provider: 'cloudflare',
    category: 'DevOps',
    color: 'orange',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API token...',
    docsUrl: 'https://developers.cloudflare.com/api/',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    icon: '\u{1F310}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=netlify.com&sz=32',
    description: 'Create, deploy, manage, and secure websites on Netlify',
    provider: 'netlify',
    category: 'DevOps',
    color: 'teal',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API token...',
    docsUrl: 'https://docs.netlify.com/api/get-started/',
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    icon: '\u{1F6F0}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=planetscale.com&sz=32',
    description: 'Authenticated access to your Postgres and MySQL DBs',
    provider: 'planetscale',
    category: 'Development',
    color: 'gray',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'pscale_tkn_...',
    docsUrl: 'https://planetscale.com/docs',
  },

  // ─────────────────────────────────────────────
  // Design
  // ─────────────────────────────────────────────
  {
    id: 'miro',
    name: 'Miro',
    icon: '\u{1F5BC}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=miro.com&sz=32',
    description: 'Access and create new content on Miro boards',
    provider: 'miro',
    category: 'Design',
    color: 'amber',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developers.miro.com',
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    icon: '\u{270F}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=excalidraw.com&sz=32',
    description: 'Create interactive hand-drawn diagrams',
    provider: 'excalidraw',
    category: 'Design',
    color: 'purple',
    comingSoon: true,
    authType: 'mcp_remote',
    docsUrl: 'https://docs.excalidraw.com',
  },

  // ─────────────────────────────────────────────
  // CRM & Sales
  // ─────────────────────────────────────────────
  {
    id: 'salesforce',
    name: 'Salesforce',
    icon: '\u{2601}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=salesforce.com&sz=32',
    description: 'Access Salesforce CRM data and automate workflows',
    provider: 'salesforce',
    category: 'CRM & Sales',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developer.salesforce.com/docs/apis',
  },
  {
    id: 'close',
    name: 'Close',
    icon: '\u{1F4DE}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=close.com&sz=32',
    description: 'Connect to Close CRM to access and act on your sales data',
    provider: 'close',
    category: 'CRM & Sales',
    color: 'gray',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'api_...',
    docsUrl: 'https://developer.close.com',
  },
  {
    id: 'attio',
    name: 'Attio',
    icon: '\u{1F4C7}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=attio.com&sz=32',
    description: 'Search, manage, and update your Attio CRM from Claude',
    provider: 'attio',
    category: 'CRM & Sales',
    color: 'purple',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://developers.attio.com',
  },
  {
    id: 'apollo',
    name: 'Apollo.io',
    icon: '\u{1F3AF}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=apollo.io&sz=32',
    description: 'Find buyers. Book more meetings. Close more deals.',
    provider: 'apollo',
    category: 'CRM & Sales',
    color: 'blue',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://apolloio.github.io/apollo-api-docs/',
  },
  {
    id: 'clay',
    name: 'Clay',
    icon: '\u{1F9F1}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=clay.com&sz=32',
    description: 'Find prospects. Research accounts. Personalize outreach.',
    provider: 'clay',
    category: 'CRM & Sales',
    color: 'gray',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://docs.clay.com',
  },

  // ─────────────────────────────────────────────
  // Data & BI / Analytics
  // ─────────────────────────────────────────────
  {
    id: 'snowflake',
    name: 'Snowflake',
    icon: '\u{2744}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=snowflake.com&sz=32',
    description: 'Retrieve both structured and unstructured data',
    provider: 'snowflake',
    category: 'Data & BI',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://docs.snowflake.com',
  },
  {
    id: 'databricks',
    name: 'Databricks',
    icon: '\u{1F9F1}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=databricks.com&sz=32',
    description: 'Managed MCP servers with Unity Catalog and Mosaic AI',
    provider: 'databricks',
    category: 'Data & BI',
    color: 'red',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'dapi...',
    docsUrl: 'https://docs.databricks.com/api/',
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    icon: '\u{1F4C8}',
    iconUrl: 'https://www.gstatic.com/images/branding/product/1x/google_cloud_32dp.png',
    description: 'BigQuery: Advanced analytical insights for agents',
    provider: 'google',
    category: 'Data & BI',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    oauthProvider: 'google',
    oauthScopes: ['https://www.googleapis.com/auth/bigquery.readonly'],
    docsUrl: 'https://cloud.google.com/bigquery/docs/reference/rest',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    icon: '\u{1F4C9}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=amplitude.com&sz=32',
    description: 'Search, access, and get insights on your Amplitude data',
    provider: 'amplitude',
    category: 'Analytics',
    color: 'blue',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://www.docs.developers.amplitude.com',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    icon: '\u{1F994}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=posthog.com&sz=32',
    description: 'Query, analyze, and manage your PostHog insights',
    provider: 'posthog',
    category: 'Analytics',
    color: 'blue',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'phx_...',
    docsUrl: 'https://posthog.com/docs/api',
  },

  // ─────────────────────────────────────────────
  // Finance
  // ─────────────────────────────────────────────
  {
    id: 'paypal',
    name: 'PayPal',
    icon: '\u{1F4B0}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=paypal.com&sz=32',
    description: 'Access PayPal payments platform',
    provider: 'paypal',
    category: 'Finance',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developer.paypal.com/docs/api/overview/',
  },
  {
    id: 'ramp',
    name: 'Ramp',
    icon: '\u{1F4B5}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=ramp.com&sz=32',
    description: 'Search, access, and analyze your Ramp financial data',
    provider: 'ramp',
    category: 'Finance',
    color: 'green',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://docs.ramp.com',
  },
  {
    id: 'square',
    name: 'Square',
    icon: '\u{1F4B3}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=squareup.com&sz=32',
    description: 'Search and manage transaction, merchant, and payment data',
    provider: 'square',
    category: 'Finance',
    color: 'gray',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developer.squareup.com/docs',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    icon: '\u{1F3E6}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=mercury.com&sz=32',
    description: 'Search, analyze and understand your finances on Mercury',
    provider: 'mercury',
    category: 'Finance',
    color: 'purple',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://docs.mercury.com',
  },

  // ─────────────────────────────────────────────
  // Automation
  // ─────────────────────────────────────────────
  {
    id: 'zapier',
    name: 'Zapier',
    icon: '\u{26A1}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=zapier.com&sz=32',
    description: 'Automate workflows across thousands of apps via conversation',
    provider: 'zapier',
    category: 'Automation',
    color: 'orange',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://docs.zapier.com',
  },
  {
    id: 'n8n',
    name: 'n8n',
    icon: '\u{1F504}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=n8n.io&sz=32',
    description: 'Access and run your n8n workflows',
    provider: 'n8n',
    category: 'Automation',
    color: 'red',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://docs.n8n.io/api/',
  },
  {
    id: 'make',
    name: 'Make',
    icon: '\u{2699}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=make.com&sz=32',
    description: 'Run Make scenarios and manage your Make account',
    provider: 'make',
    category: 'Automation',
    color: 'purple',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API token...',
    docsUrl: 'https://www.make.com/en/api-documentation',
  },
  {
    id: 'workato',
    name: 'Workato',
    icon: '\u{1F527}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=workato.com&sz=32',
    description: 'Automate workflows and connect your business apps',
    provider: 'workato',
    category: 'Automation',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://docs.workato.com/api/',
  },

  // ─────────────────────────────────────────────
  // Storage
  // ─────────────────────────────────────────────
  {
    id: 'box',
    name: 'Box',
    icon: '\u{1F4E6}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=box.com&sz=32',
    description: 'Search, access and get insights on your Box content',
    provider: 'box',
    category: 'Storage',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developer.box.com',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    icon: '\u{2601}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=onedrive.com&sz=32',
    description: 'Microsoft file storage',
    provider: 'microsoft',
    category: 'Storage',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    oauthProvider: 'microsoft',
    oauthScopes: ['Files.ReadWrite.All'],
    docsUrl: 'https://learn.microsoft.com/en-us/onedrive/developer/',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    icon: '\u{1F4E5}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=dropbox.com&sz=32',
    description: 'Access and manage Dropbox files and folders',
    provider: 'dropbox',
    category: 'Storage',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://www.dropbox.com/developers',
  },

  // ─────────────────────────────────────────────
  // Meetings
  // ─────────────────────────────────────────────
  {
    id: 'fireflies',
    name: 'Fireflies',
    icon: '\u{1F56F}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=fireflies.ai&sz=32',
    description: 'Analyze and generate insights from meeting transcripts',
    provider: 'fireflies',
    category: 'Meetings',
    color: 'purple',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://docs.fireflies.ai',
  },
  {
    id: 'granola',
    name: 'Granola',
    icon: '\u{1F4D3}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=granola.ai&sz=32',
    description: 'The AI notepad for meetings',
    provider: 'granola',
    category: 'Meetings',
    color: 'amber',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://granola.ai',
  },
  {
    id: 'fellow',
    name: 'Fellow.ai',
    icon: '\u{1F91D}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=fellow.app&sz=32',
    description: 'Chat with your meetings to uncover actionable insights',
    provider: 'fellow',
    category: 'Meetings',
    color: 'blue',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://developer.fellow.app',
  },

  // ─────────────────────────────────────────────
  // Marketing
  // ─────────────────────────────────────────────
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    icon: '\u{1F4E3}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=klaviyo.com&sz=32',
    description: 'Report, strategize & create with real-time Klaviyo data',
    provider: 'klaviyo',
    category: 'Marketing',
    color: 'green',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'pk_...',
    docsUrl: 'https://developers.klaviyo.com',
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    icon: '\u{1F4EC}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=activecampaign.com&sz=32',
    description: 'Autonomous marketing to transform how you work',
    provider: 'activecampaign',
    category: 'Marketing',
    color: 'blue',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API key...',
    docsUrl: 'https://developers.activecampaign.com',
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    icon: '\u{1F4EE}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=mailchimp.com&sz=32',
    description: 'Email marketing, automations, and audience management',
    provider: 'mailchimp',
    category: 'Marketing',
    color: 'amber',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'key-...',
    docsUrl: 'https://mailchimp.com/developer/',
  },

  // ─────────────────────────────────────────────
  // AI & ML
  // ─────────────────────────────────────────────
  {
    id: 'huggingface',
    name: 'Hugging Face',
    icon: '\u{1F917}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=32',
    description: 'Access the Hugging Face Hub and thousands of Gradio Apps',
    provider: 'huggingface',
    category: 'AI & ML',
    color: 'amber',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'hf_...',
    docsUrl: 'https://huggingface.co/docs/api-inference',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    icon: '\u{1F3A4}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=32',
    description: 'Generate speech, sound effects, and music',
    provider: 'elevenlabs',
    category: 'AI & ML',
    color: 'gray',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'sk_...',
    docsUrl: 'https://elevenlabs.io/docs/api-reference',
  },

  // ─────────────────────────────────────────────
  // Content
  // ─────────────────────────────────────────────
  {
    id: 'wordpress',
    name: 'WordPress',
    icon: '\u{1F4F0}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=wordpress.com&sz=32',
    description: 'Secure AI access to manage your WordPress.com sites',
    provider: 'wordpress',
    category: 'Content',
    color: 'blue',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://developer.wordpress.com/docs/api/',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    icon: '\u{1F578}\u{FE0F}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=webflow.com&sz=32',
    description: 'Manage Webflow CMS, pages, assets and sites',
    provider: 'webflow',
    category: 'Content',
    color: 'blue',
    comingSoon: true,
    authType: 'api_key',
    apiKeyPlaceholder: 'API token...',
    docsUrl: 'https://developers.webflow.com',
  },
  {
    id: 'gamma',
    name: 'Gamma',
    icon: '\u{1F4A1}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=gamma.app&sz=32',
    description: 'Create presentations, docs, socials, and sites with AI',
    provider: 'gamma',
    category: 'Content',
    color: 'purple',
    comingSoon: true,
    authType: 'oauth',
    docsUrl: 'https://gamma.app',
  },

  // ─────────────────────────────────────────────
  // Research
  // ─────────────────────────────────────────────
  {
    id: 'pubmed',
    name: 'PubMed',
    icon: '\u{1F9EC}',
    iconUrl: 'https://www.google.com/s2/favicons?domain=pubmed.ncbi.nlm.nih.gov&sz=32',
    description: 'Search biomedical literature from PubMed',
    provider: 'pubmed',
    category: 'Research',
    color: 'blue',
    comingSoon: true,
    authType: 'mcp_remote',
    docsUrl: 'https://pubmed.ncbi.nlm.nih.gov',
  },
];

export const FEATURED_CONNECTORS = CONNECTORS.filter((c) => c.featured);
