//! Why a file the session wrote changed, read from the text it replaced.
//!
//! The recorder already holds the before and the after of every write a tool
//! made, so the reason is derived from the change itself rather than from what
//! the tool call said it was doing.

use agiworkforce_protocol::developer_session::{FileChangeNotice, FileChangeSubject};
use std::collections::HashSet;
use std::path::Path;

/// How much of the file the change replaced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ChangeExtent {
    Created,
    Edited,
    Rewritten,
}

impl ChangeExtent {
    fn label(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Edited => "edited",
            Self::Rewritten => "rewritten whole",
        }
    }
}

/// What the change was: the kind of file, how much of it moved, and anything
/// in it a person would want told about before it lands.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ChangeReason {
    pub subject: FileChangeSubject,
    pub extent: ChangeExtent,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub notices: Vec<FileChangeNotice>,
}

impl ChangeReason {
    /// One line naming the change, for a surface that shows a file list.
    pub fn describe(&self) -> String {
        let mut described = format!("{} {}", self.subject.label(), self.extent.label());
        for notice in &self.notices {
            described.push_str("; ");
            described.push_str(notice.label());
        }
        described
    }
}

const TEST_DIRECTORIES: &[&str] = &["tests", "test", "__tests__", "spec", "e2e"];
const TEST_INFIXES: &[&str] = &[".test.", ".spec.", "_test.", "_spec."];
const MANIFESTS: &[&str] = &[
    "package.json",
    "Cargo.toml",
    "pyproject.toml",
    "requirements.txt",
    "go.mod",
    "Gemfile",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "composer.json",
    "pubspec.yaml",
];
const LOCKFILES: &[&str] = &[
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
    "bun.lockb",
    "Cargo.lock",
    "poetry.lock",
    "uv.lock",
    "Gemfile.lock",
    "composer.lock",
    "go.sum",
    "pubspec.lock",
];
const DOCUMENTATION_EXTENSIONS: &[&str] = &["md", "mdx", "rst", "adoc", "txt"];
const CONFIGURATION_EXTENSIONS: &[&str] = &["json", "yaml", "yml", "toml", "ini", "env", "conf"];

/// Markers that are debugging aids in the language they appear in, and are
/// never something a finished change means to leave behind.
const DEBUG_MARKERS: &[(&[&str], &[&str])] = &[
    (
        &["js", "jsx", "ts", "tsx", "mjs", "cjs", "svelte", "vue"],
        &[
            "console.log(",
            "console.debug(",
            "console.trace(",
            "debugger",
        ],
    ),
    (&["rs"], &["dbg!(", "eprintln!(\"DEBUG", "println!(\"DEBUG"]),
    (
        &["py"],
        &["breakpoint()", "pdb.set_trace(", "ipdb.set_trace("],
    ),
    (&["rb"], &["binding.pry", "binding.irb"]),
    (&["go"], &["spew.Dump(", "litter.Dump("]),
    (&["java", "kt"], &["printStackTrace()"]),
    (&["php"], &["var_dump(", "xdebug_break("]),
];

/// What a generated file says about itself. Every generator the repository
/// runs writes one of these into the first lines of what it produces.
const GENERATED_HEADERS: &[&str] = &[
    "@generated",
    "DO NOT EDIT",
    "do not edit",
    "Code generated by",
    "auto-generated",
    "autogenerated",
];
const GENERATED_HEADER_LINES: usize = 8;

fn extension(path: &Path) -> Option<String> {
    path.extension()
        .and_then(|value| value.to_str())
        .map(|value| value.to_ascii_lowercase())
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|value| value.to_str())
        .unwrap_or_default()
        .to_string()
}

fn is_test_path(path: &Path) -> bool {
    let name = file_name(path);
    if TEST_INFIXES.iter().any(|infix| name.contains(infix)) {
        return true;
    }
    if name.starts_with("test_") || name == "conftest.py" {
        return true;
    }
    path.components().any(|component| {
        component
            .as_os_str()
            .to_str()
            .is_some_and(|segment| TEST_DIRECTORIES.contains(&segment))
    })
}

fn debug_markers_for(path: &Path) -> &'static [&'static str] {
    let Some(extension) = extension(path) else {
        return &[];
    };
    DEBUG_MARKERS
        .iter()
        .find(|(extensions, _)| extensions.contains(&extension.as_str()))
        .map(|(_, markers)| *markers)
        .unwrap_or(&[])
}

fn declares_itself_generated(text: &str) -> bool {
    text.lines()
        .take(GENERATED_HEADER_LINES)
        .any(|line| GENERATED_HEADERS.iter().any(|header| line.contains(header)))
}

/// What kind of file this is. A generated file is asked rather than guessed
/// at: the file the generator wrote says so in its own header, and that header
/// is what the change replaced.
pub fn subject_of(path: &Path, before: &str, after: &str) -> FileChangeSubject {
    if LOCKFILES.contains(&file_name(path).as_str()) {
        return FileChangeSubject::Lockfile;
    }
    if MANIFESTS.contains(&file_name(path).as_str()) {
        return FileChangeSubject::Manifest;
    }
    if declares_itself_generated(before) || declares_itself_generated(after) {
        return FileChangeSubject::Generated;
    }
    if is_test_path(path) {
        return FileChangeSubject::Test;
    }
    match extension(path) {
        Some(extension) if DOCUMENTATION_EXTENSIONS.contains(&extension.as_str()) => {
            FileChangeSubject::Documentation
        }
        Some(extension) if CONFIGURATION_EXTENSIONS.contains(&extension.as_str()) => {
            FileChangeSubject::Configuration
        }
        _ => FileChangeSubject::Source,
    }
}

/// A file whose surviving lines are a small share of what it held was replaced
/// wholesale, whatever the tool call was named.
const REWRITE_SURVIVING_LINE_SHARE: f64 = 0.25;
const REWRITE_MINIMUM_LINES: usize = 8;

fn extent_of(before: &str, after: &str) -> ChangeExtent {
    if before.trim().is_empty() {
        return ChangeExtent::Created;
    }
    let before_lines: Vec<&str> = before
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect();
    if before_lines.len() < REWRITE_MINIMUM_LINES {
        return ChangeExtent::Edited;
    }
    let after_lines: HashSet<&str> = after.lines().map(str::trim).collect();
    let surviving = before_lines
        .iter()
        .filter(|line| after_lines.contains(*line))
        .count();
    let share = surviving as f64 / before_lines.len() as f64;
    if share < REWRITE_SURVIVING_LINE_SHARE {
        ChangeExtent::Rewritten
    } else {
        ChangeExtent::Edited
    }
}

fn added_lines<'a>(before: &str, after: &'a str) -> Vec<&'a str> {
    let held: HashSet<&str> = before.lines().map(str::trim).collect();
    after
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !held.contains(line))
        .collect()
}

fn declares_a_dependency(line: &str) -> bool {
    let line = line.trim_start_matches(['-', '+', ' ']);
    if line.starts_with('#') || line.starts_with("//") {
        return false;
    }
    line.contains('=') || line.contains(':') || line.starts_with("require ")
}

/// Everything about this change a person would want told about.
pub fn notices_for(
    path: &Path,
    subject: FileChangeSubject,
    before: &str,
    after: &str,
) -> Vec<FileChangeNotice> {
    let mut notices = Vec::new();
    let added = added_lines(before, after);

    let markers = debug_markers_for(path);
    if added
        .iter()
        .any(|line| markers.iter().any(|marker| line.contains(marker)))
    {
        notices.push(FileChangeNotice::DebugInstrumentation);
    }
    match subject {
        FileChangeSubject::Lockfile => notices.push(FileChangeNotice::LockfileEditedByHand),
        FileChangeSubject::Generated => notices.push(FileChangeNotice::GeneratedFileEdited),
        FileChangeSubject::Manifest => {
            if added.iter().any(|line| declares_a_dependency(line)) {
                notices.push(FileChangeNotice::DependencyAdded);
            }
        }
        FileChangeSubject::Test => {
            if !before.trim().is_empty() {
                notices.push(FileChangeNotice::TestChanged);
            }
        }
        FileChangeSubject::Source
        | FileChangeSubject::Documentation
        | FileChangeSubject::Configuration => {}
    }
    notices
}

/// Why this write happened, from the file it replaced and the file it left.
pub fn classify_change(path: &Path, before: &str, after: &str) -> ChangeReason {
    let subject = subject_of(path, before, after);
    ChangeReason {
        subject,
        extent: extent_of(before, after),
        notices: notices_for(path, subject, before, after),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn a_debugging_aid_the_change_left_behind_is_named() {
        let reason = classify_change(
            &PathBuf::from("src/importer.ts"),
            "export function run() {\n  return 1;\n}\n",
            "export function run() {\n  console.log('here');\n  return 1;\n}\n",
        );
        assert_eq!(reason.subject, FileChangeSubject::Source);
        assert_eq!(reason.extent, ChangeExtent::Edited);
        assert!(reason
            .notices
            .contains(&FileChangeNotice::DebugInstrumentation));
        assert!(reason.describe().contains("debugging"));
    }

    #[test]
    fn a_debugging_marker_that_was_already_there_is_not_this_changes_doing() {
        let held = "export function run() {\n  console.log('here');\n  return 1;\n}\n";
        let reason = classify_change(
            &PathBuf::from("src/importer.ts"),
            held,
            "export function run() {\n  console.log('here');\n  return 2;\n}\n",
        );
        assert!(!reason
            .notices
            .contains(&FileChangeNotice::DebugInstrumentation));
    }

    #[test]
    fn a_marker_from_another_language_is_not_a_debugging_aid_in_this_one() {
        let reason = classify_change(
            &PathBuf::from("src/importer.rs"),
            "fn run() -> u32 {\n    1\n}\n",
            "fn run() -> u32 {\n    // console.log(1)\n    1\n}\n",
        );
        assert!(!reason
            .notices
            .contains(&FileChangeNotice::DebugInstrumentation));

        let rust = classify_change(
            &PathBuf::from("src/importer.rs"),
            "fn run() -> u32 {\n    1\n}\n",
            "fn run() -> u32 {\n    dbg!(1);\n    1\n}\n",
        );
        assert!(rust
            .notices
            .contains(&FileChangeNotice::DebugInstrumentation));
    }

    #[test]
    fn replacing_a_file_wholesale_is_not_recorded_as_an_edit() {
        let before = (0..20)
            .map(|index| format!("let value{index} = {index};"))
            .collect::<Vec<_>>()
            .join("\n");
        let narrow = before.replace("let value7 = 7;", "let value7 = 70;");
        assert_eq!(
            classify_change(&PathBuf::from("src/a.ts"), &before, &narrow).extent,
            ChangeExtent::Edited
        );

        let wholesale = (0..20)
            .map(|index| format!("const other{index} = {index};"))
            .collect::<Vec<_>>()
            .join("\n");
        assert_eq!(
            classify_change(&PathBuf::from("src/a.ts"), &before, &wholesale).extent,
            ChangeExtent::Rewritten
        );
    }

    #[test]
    fn a_new_file_is_created_rather_than_rewritten() {
        let reason = classify_change(&PathBuf::from("src/new.rs"), "", "fn main() {}\n");
        assert_eq!(reason.extent, ChangeExtent::Created);
    }

    #[test]
    fn a_test_file_the_agent_changed_never_changes_silently() {
        let reason = classify_change(
            &PathBuf::from("src/__tests__/importer.test.ts"),
            "it('resumes', () => { expect(run()).toBe(1); });\n",
            "it('resumes', () => { expect(run()).toBeTruthy(); });\n",
        );
        assert_eq!(reason.subject, FileChangeSubject::Test);
        assert!(reason.notices.contains(&FileChangeNotice::TestChanged));

        let fresh = classify_change(
            &PathBuf::from("tests/importer_test.rs"),
            "",
            "#[test]\nfn resumes() {}\n",
        );
        assert_eq!(fresh.subject, FileChangeSubject::Test);
        assert!(!fresh.notices.contains(&FileChangeNotice::TestChanged));
    }

    #[test]
    fn a_dependency_added_to_a_manifest_is_named_and_a_comment_is_not() {
        let added = classify_change(
            &PathBuf::from("Cargo.toml"),
            "[dependencies]\nserde = \"1\"\n",
            "[dependencies]\nserde = \"1\"\nreqwest = \"0.12\"\n",
        );
        assert_eq!(added.subject, FileChangeSubject::Manifest);
        assert!(added.notices.contains(&FileChangeNotice::DependencyAdded));

        let annotated = classify_change(
            &PathBuf::from("Cargo.toml"),
            "[dependencies]\nserde = \"1\"\n",
            "[dependencies]\n# the wire format\nserde = \"1\"\n",
        );
        assert!(!annotated
            .notices
            .contains(&FileChangeNotice::DependencyAdded));
    }

    #[test]
    fn a_lockfile_written_by_hand_is_named_as_that() {
        let reason = classify_change(
            &PathBuf::from("pnpm-lock.yaml"),
            "lockfileVersion: '9.0'\n",
            "lockfileVersion: '9.0'\npackages:\n  reqwest: {}\n",
        );
        assert_eq!(reason.subject, FileChangeSubject::Lockfile);
        assert!(reason
            .notices
            .contains(&FileChangeNotice::LockfileEditedByHand));
    }

    #[test]
    fn a_file_that_says_a_generator_wrote_it_is_not_edited_silently() {
        let generated = "// @generated by the catalog generator\nexport const a = 1;\n";
        let reason = classify_change(
            &PathBuf::from("src/catalog.ts"),
            generated,
            "// @generated by the catalog generator\nexport const a = 2;\n",
        );
        assert_eq!(reason.subject, FileChangeSubject::Generated);
        assert!(reason
            .notices
            .contains(&FileChangeNotice::GeneratedFileEdited));

        let hand_written = classify_change(
            &PathBuf::from("src/catalog.ts"),
            "export const a = 1;\n",
            "export const a = 2;\n",
        );
        assert_eq!(hand_written.subject, FileChangeSubject::Source);
        assert!(hand_written.notices.is_empty());
    }

    #[test]
    fn a_generated_header_below_the_top_of_a_long_file_is_not_a_generator_claim() {
        let body = (0..40)
            .map(|index| format!("export const value{index} = {index};"))
            .collect::<Vec<_>>()
            .join("\n");
        let mentioned = format!("{body}\n// DO NOT EDIT this constant by hand\n");
        assert_eq!(
            subject_of(&PathBuf::from("src/catalog.ts"), &body, &mentioned),
            FileChangeSubject::Source
        );
    }

    #[test]
    fn every_subject_and_notice_says_something_a_person_can_read() {
        for subject in FileChangeSubject::ALL {
            assert!(!subject.label().is_empty(), "{subject:?} has no label");
        }
        for notice in FileChangeNotice::ALL {
            assert!(notice.label().len() > 10, "{notice:?} says too little");
        }
        for extent in [
            ChangeExtent::Created,
            ChangeExtent::Edited,
            ChangeExtent::Rewritten,
        ] {
            assert!(!extent.label().is_empty());
        }
    }
}
