/**
 * @agiworkforce/ui: cross-surface PURE UI: pure-presentation components and
 * plain config/contract data shared by web (apps/web) and desktop (apps/desktop).
 *
 * Boundary rule: ONLY pure presentation (no data/IO, currentColor SVG) and
 * config/contract (plain data) live here. Anything that imports a store, calls
 * invoke()/fetch(), or reads Next/RSC stays per-surface.
 */

export { ProviderMark, hasProviderMark } from './ProviderMark';
export { AgiMark } from './AgiMark';
export { cn } from './cn';
export { useUiTranslation, type UiNamespace, type UiTranslate, type UiTranslation } from './i18n';
export { isApplePlatform, primaryModifierLabel, shortcutLabel } from './platformKeys';
export { lucideToolIcon } from './toolIcon';
export {
  Alert,
  AlertTitle,
  AlertDescription,
  type AlertProps,
  AccessibleDialog,
  type AccessibleDialogProps,
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
  ContextMenu,
  ContextMenuTrigger,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuCheckboxItem,
  ContextMenuRadioItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuGroup,
  ContextMenuPortal,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuRadioGroup,
  HoverCard,
  HoverCardTrigger,
  HoverCardContent,
  Button,
  buttonVariants,
  type ButtonProps,
  LoadingButton,
  type LoadingButtonProps,
  ResizeHandle,
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  SelectScrollUpButton,
  SelectScrollDownButton,
  Spinner,
  spinnerVariants,
  type SpinnerProps,
  Textarea,
  type TextareaProps,
  EmptyState,
  Badge,
  badgeVariants,
  type BadgeProps,
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuRadioGroup,
  Input,
  type InputProps,
  Progress,
  ScrollArea,
  ScrollBar,
  Skeleton,
  SkeletonText,
  SkeletonCard,
  SkeletonListItem,
  SkeletonChatMessage,
  SkeletonTableRow,
  SkeletonFormField,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
  Checkbox,
  Separator,
  Switch,
  ResponsiveContainer,
  type ResponsiveContainerProps,
  ResponsiveGrid,
  type ResponsiveGridProps,
  ResponsiveShow,
  type ResponsiveShowProps,
  TouchTarget,
  type TouchTargetProps,
  useBreakpoint,
  useIsTouchDevice,
  Dialog,
  DialogPortal,
  DialogOverlay,
  DialogClose,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  AlertDialog,
  AlertDialogPortal,
  AlertDialogOverlay,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
  Popover,
  PopoverTrigger,
  PopoverContent,
  Label,
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
  Slider,
  ConfirmDialog,
  useConfirm,
  type ConfirmDialogProps,
  PromptDialog,
  usePrompt,
  type PromptDialogProps,
  FormField,
  type FormFieldProps,
  SectionErrorBoundary,
  type SectionErrorBoundaryProps,
  Avatar,
  AvatarImage,
  AvatarFallback,
  AspectRatio,
  Toggle,
  toggleVariants,
  ToggleGroup,
  ToggleGroupItem,
  RadioGroup,
  RadioGroupItem,
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbSeparator,
  BreadcrumbEllipsis,
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
  InputOTPSeparator,
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetOverlay,
  SheetPortal,
  SheetTitle,
  SheetTrigger,
  Drawer,
  DrawerPortal,
  DrawerOverlay,
  DrawerTrigger,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
  Calendar,
  type CalendarProps,
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandShortcut,
  CommandSeparator,
  Menubar,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarItem,
  MenubarSeparator,
  MenubarLabel,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarPortal,
  MenubarSubContent,
  MenubarSubTrigger,
  MenubarGroup,
  MenubarSub,
  MenubarShortcut,
  navigationMenuTriggerStyle,
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuContent,
  NavigationMenuTrigger,
  NavigationMenuLink,
  NavigationMenuIndicator,
  NavigationMenuViewport,
  type CarouselApi,
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
  SonnerToaster,
  sonnerToast,
  type SonnerToasterProps,
  DataTable,
  createSortableHeader,
  ThemeToggle,
} from './primitives';
export {
  Sidebar,
  type SidebarProps,
  SessionItem,
  type SessionItemProps,
  type SessionItemHandlers,
  SearchOverlay,
  type SearchOverlayProps,
  Menu,
  MenuItem,
  MenuSeparator,
  isMenuPanelOpen,
  keepOpenForMenuEscape,
  type MenuProps,
  type MenuItemProps,
  getTemporalGroup,
  TEMPORAL_LABELS,
  toSafeDate,
  type SidebarSession,
  type SidebarProject,
  type SidebarMode,
  type SidebarTemporalGroup,
  type SidebarNavItem,
  type SidebarIconComponent,
} from './sidebar';
export {
  SETTINGS_NAV,
  isSettingsNavKey,
  SETTINGS_NAV_GROUPS,
  SETTINGS_NAV_GROUPS_WEB,
  SETTINGS_NAV_KEYWORDS,
  type SettingsNavEntry,
  type SettingsNavGroup,
  type SettingsNavGroupResolved,
  type SettingsNavItem,
  type SettingsNavKey,
} from './settings-nav';
export {
  SettingsModal,
  type SettingsModalProps,
  type SettingsNavBadge,
  ConnectorLogo,
  type ConnectorLogoProps,
  type SettingsDataAdapter,
  type SettingsConnector,
  type ConnectedConnector,
  type SettingsSkill,
  type SettingsPlugin,
  type SettingsSectionKey,
  isUnverifiedCustomConnector,
  parseCustomMcpJsonConfig,
  describeCustomMcpJsonImportError,
  type ParsedCustomMcpConfig,
  type CustomMcpJsonImportError,
  type CustomMcpJsonImportResult,
} from './settings-modal';

export { useConfirmAction } from './primitives/ConfirmAction';
export type { ConfirmActionRequest } from './primitives/ConfirmAction';
export { useMenuKeyboard } from './primitives/useMenuKeyboard';

export {
  DirectoryPanel,
  type DirectoryPanelProps,
  DirectoryToolbar,
  DirectoryGrid,
  DirectoryCard,
  SkillDetailView,
  SkillFileTree,
  SkillFileBody,
  CodeBlock,
  highlightLine,
  isCodeFile,
  isTextFile,
  splitLines,
  type HighlightKind,
  type HighlightToken,
  ConnectorDetailView,
  PluginDetailView,
  AddMarketplaceDialog,
  buildFileTree,
  countActiveFilters,
  formatInstallCount,
  matchesDirectoryFilters,
  matchesDirectorySearch,
  matchesDirectorySource,
  selectDirectoryEntries,
  sortDirectoryEntries,
  toggleFilterValue,
  DIRECTORY_SECTION_LABELS,
  DIRECTORY_SOURCE_ALL_ID,
  DIRECTORY_SOURCE_ALL_LABEL,
  INSTALL_COUNT_FLOOR,
  MARKETPLACE_UNAVAILABLE_COPY,
  type DirectoryAdapter,
  type DirectoryBadgeKind,
  type DirectoryConnectorDetail,
  type DirectoryDetail,
  type DirectoryDetailFile,
  type DirectoryEntry,
  type DirectoryFilterGroup,
  type DirectoryFilterOption,
  type DirectoryFilterSelection,
  type DirectoryMarketplaceEntry,
  type DirectoryMarketplaceInput,
  type DirectoryMarketplaceResult,
  type DirectoryPluginDetail,
  type DirectorySection,
  type DirectorySectionKey,
  type DirectorySkillDetail,
  type DirectorySortKey,
  type DirectorySourceChip,
  type DirectoryTreeNode,
} from './directory';
