/**
 * Unified Auth Types
 *
 * Shared authentication types for the AGI Workforce platform.
 * Used across desktop, web, Chrome extension, VS Code extension, and mobile.
 *
 * @module auth
 * @packageDocumentation
 */

// ============================================================================
// User Identity
// ============================================================================

/**
 * Basic user identity from Supabase auth.
 * Minimal info needed for auth checks across all platforms.
 */
export interface AuthUser {
  /** Supabase user ID (UUID). */
  id: string;

  /** User's email address. */
  email: string;

  /** Display name (from profile or OAuth provider). */
  name?: string;

  /** Avatar URL (from profile or OAuth provider). */
  avatar?: string;

  /** User role for RBAC. */
  role?: string;
}

// ============================================================================
// Auth Session
// ============================================================================

/**
 * A Supabase auth session that can be transferred between platforms.
 * Used for desktop-to-extension auth bridging.
 */
export interface AuthSession {
  /** Supabase JWT access token. */
  accessToken: string;

  /** Supabase refresh token for session renewal. */
  refreshToken: string;

  /** User identity associated with this session. */
  user: AuthUser;

  /** Unix timestamp (ms) when the access token expires. */
  expiresAt: number;
}

// ============================================================================
// Desktop Token (Web -> Desktop deep link auth)
// ============================================================================

/**
 * Encrypted token payload for web-to-desktop auth transfer.
 * Generated by the web app's /api/auth/desktop-token endpoint.
 * Consumed by the desktop app via deep link.
 */
export interface DesktopAuthTokenPayload {
  /** The Supabase session to transfer. */
  session: AuthSession;

  /** Unix timestamp (ms) when this token was created. */
  issuedAt: number;

  /** Unix timestamp (ms) when this token expires (60s TTL). */
  expiresAt: number;

  /** One-time-use nonce to prevent replay attacks. */
  nonce: string;
}

// ============================================================================
// Extension Auth Bridge Messages
// ============================================================================

/**
 * Auth session request message — sent from extensions to the desktop app
 * via native messaging (Chrome) or WebSocket bridge (VS Code).
 */
export interface AuthSessionRequest {
  type: 'GET_AUTH_SESSION';
  /** Timestamp of the request for freshness validation. */
  timestamp: number;
}

/**
 * Auth session response — sent from desktop to extensions.
 */
export interface AuthSessionResponse {
  type: 'AUTH_SESSION';
  success: boolean;
  session?: AuthSession;
  error?: string;
}

// ============================================================================
// Connection Status Types
// ============================================================================

/**
 * Connection status for native messaging or WebSocket bridges.
 * Shared between Chrome and VS Code extensions.
 */
export type BridgeConnectionStatus = 'connected' | 'disconnected' | 'connecting' | 'error';
