/**
 * Pairing Types
 *
 * Types for the QR-code pairing flow that links desktop and mobile clients.
 * The desktop app generates a pairing code; the mobile app scans it via QR
 * or manual entry. Once paired, the two communicate over WebRTC via the
 * signaling server.
 *
 * @module pairing
 * @packageDocumentation
 */

// ============================================================================
// Pairing Token
// ============================================================================

/**
 * A pairing token generated by the desktop app for mobile connection.
 *
 * The token is displayed as a QR code on the desktop and scanned by the
 * mobile app. It encodes the signaling server URL, the pairing code,
 * and optional metadata.
 *
 * @example
 * ```typescript
 * const token: PairingToken = {
 *   code: '847293',
 *   signalingUrl: 'wss://signal.agiworkforce.com',
 *   expiresAt: '2026-03-15T10:35:00Z',
 *   deviceInfo: {
 *     deviceId: 'desktop-abc',
 *     deviceName: 'MacBook Pro',
 *     platform: 'macos',
 *     appVersion: '1.2.0',
 *   },
 * };
 * ```
 */
export interface PairingToken {
  /** 6-digit pairing code displayed to the user. */
  code: string;

  /** WebSocket URL of the signaling server. */
  signalingUrl: string;

  /** ISO 8601 timestamp when this token expires (typically 5 minutes). */
  expiresAt: string;

  /** Information about the device that generated the token. */
  deviceInfo?: DeviceInfo;

  /** Arbitrary metadata to include in the pairing payload. */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// Pairing Status
// ============================================================================

/**
 * Status of a pairing session between desktop and mobile.
 *
 * - `generating` -- Token is being created.
 * - `waiting` -- QR code displayed, waiting for mobile to scan.
 * - `connecting` -- Mobile scanned, WebRTC connection being established.
 * - `paired` -- Devices are successfully paired and communicating.
 * - `expired` -- The pairing code has expired without being used.
 * - `failed` -- Pairing attempt failed (network error, invalid code, etc.).
 * - `disconnected` -- Previously paired devices lost connection.
 */
export type PairingStatus =
  | 'generating'
  | 'waiting'
  | 'connecting'
  | 'paired'
  | 'expired'
  | 'failed'
  | 'disconnected';

// ============================================================================
// Device Info
// ============================================================================

/**
 * Information about a device participating in a pairing session.
 *
 * Shared between desktop and mobile during the pairing handshake so each
 * side knows what it is connecting to.
 *
 * @example
 * ```typescript
 * const device: DeviceInfo = {
 *   deviceId: 'mobile-xyz-789',
 *   deviceName: 'iPhone 16 Pro',
 *   platform: 'ios',
 *   appVersion: '1.2.0',
 *   capabilities: ['approve', 'monitor', 'voice'],
 * };
 * ```
 */
export interface DeviceInfo {
  /** Unique device identifier (persisted across sessions). */
  deviceId: string;

  /** Human-readable device name (e.g., `"MacBook Pro"`, `"iPhone 16"`). */
  deviceName: string;

  /** Operating system platform. */
  platform: 'macos' | 'windows' | 'linux' | 'ios' | 'android' | 'web';

  /** Application version string. */
  appVersion: string;

  /** Optional device capabilities for negotiation. */
  capabilities?: string[];

  /** Optional battery level (0-100) for mobile devices. */
  batteryLevel?: number;

  /** Optional network type for mobile devices. */
  networkType?: 'wifi' | 'cellular' | 'ethernet' | 'unknown';
}

// ============================================================================
// Pairing Session
// ============================================================================

/**
 * Full state of an active pairing session.
 *
 * Combines the token, status, and connected device info. Used by the
 * desktop pairing UI and mobile connection screen.
 */
export interface PairingSession {
  /** The pairing token for this session. */
  token: PairingToken;

  /** Current pairing status. */
  status: PairingStatus;

  /** Connected peer device info (available after pairing succeeds). */
  peerDevice?: DeviceInfo;

  /** ISO 8601 timestamp when the session was created. */
  createdAt: string;

  /** ISO 8601 timestamp when pairing completed. Null while pending. */
  pairedAt?: string | null;

  /** Latency to the peer in milliseconds (measured via WebRTC). */
  latencyMs?: number;
}
