import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

export const ARCHIVE_DIR = 'apps/web/content/legal/policy-archive';
export const ARCHIVE_MANIFEST = `${ARCHIVE_DIR}/manifest.json`;
export const ARCHIVE_INDEX = `${ARCHIVE_DIR}/index.ts`;
export const ARCHIVE_COMMAND = 'node scripts/archive-policy-versions.mjs';

export function policySlug(route) {
  return route.replace(/^\/+/, '').replace(/\//g, '-');
}

export function archiveFile(key, date) {
  return `${ARCHIVE_DIR}/${key}/${date}.json`;
}

function identifier(key, date) {
  return `${key}_${date.replace(/-/g, '_')}`;
}

export function lastDigest(document, date) {
  return (document.versions ?? []).findLast((version) => version.date === date)?.digest ?? null;
}

export function readGitObjects(root, names) {
  if (names.length === 0) return [];
  const buffer = execFileSync('git', ['-C', root, 'cat-file', '--batch'], {
    input: `${names.join('\n')}\n`,
    maxBuffer: 1024 * 1024 * 1024,
  });
  const contents = [];
  let offset = 0;
  while (offset < buffer.length) {
    const end = buffer.indexOf(10, offset);
    const header = buffer.subarray(offset, end).toString('utf8');
    offset = end + 1;
    if (header.endsWith(' missing')) {
      contents.push(null);
      continue;
    }
    const size = Number(header.split(' ')[2]);
    contents.push(buffer.subarray(offset, offset + size).toString('utf8'));
    offset += size + 1;
  }
  return contents;
}

export function datedVersions(document) {
  const byDate = new Map();
  for (const version of document.versions ?? []) {
    if (!version.date || byDate.has(version.date)) continue;
    byDate.set(version.date, version);
  }
  return [...byDate.values()];
}

function introducedAfter(version, recordedSince) {
  return typeof recordedSince === 'string' && version.date > recordedSince;
}

export function archiveExpectations(registry, routes, exists) {
  const policies = {};
  for (const [key, document] of Object.entries(registry.documents ?? {})) {
    const route = routes[key];
    if (!route) continue;
    const dated = datedVersions(document);
    if (dated.length === 0) continue;
    if (dated.length < 2 && !introducedAfter(dated[0], registry.recordedSince)) continue;
    const current = dated.at(-1).date;
    policies[key] = {
      route,
      slug: policySlug(route),
      current,
      versions: dated
        .map((version) => ({
          date: version.date,
          summary: typeof version.summary === 'string' ? version.summary : null,
          status:
            version.date === current
              ? 'current'
              : version.archive === 'not-retained'
                ? 'not-retained'
                : exists(key, version.date)
                  ? 'archived'
                  : 'missing',
        }))
        .reverse(),
    };
  }
  return policies;
}

export function renderManifest(policies, recordedSince) {
  return `${JSON.stringify(
    {
      note: `Generated by ${ARCHIVE_COMMAND} from docs/compliance/policy-versions.json. Do not edit by hand.`,
      recordedSince,
      policies,
    },
    null,
    2,
  )}\n`;
}

export function renderIndex(policies) {
  const archived = Object.entries(policies).flatMap(([key, policy]) =>
    policy.versions
      .filter((version) => version.status === 'archived')
      .map((version) => ({ key, date: version.date }))
      .reverse(),
  );
  const imports = archived.map(
    ({ key, date }) => `import ${identifier(key, date)} from './${key}/${date}.json';`,
  );
  const grouped = new Map();
  for (const { key, date } of archived) {
    grouped.set(key, [...(grouped.get(key) ?? []), date]);
  }
  const entries = [...grouped.entries()].map(
    ([key, dates]) =>
      `  ${key}: {\n${dates.map((date) => `    '${date}': ${identifier(key, date)},`).join('\n')}\n  },`,
  );
  return [
    ...imports,
    '',
    'export const ARCHIVED_POLICY_TEXT = {',
    ...entries,
    '} as const;',
    '',
  ].join('\n');
}

export function runPolicyArchiveCheck(root, registry, routes) {
  const failures = [];
  const exists = (key, date) => fs.existsSync(path.join(root, archiveFile(key, date)));
  const policies = archiveExpectations(registry, routes, exists);

  for (const [key, policy] of Object.entries(policies)) {
    for (const [position, version] of policy.versions.entries()) {
      const earliest = position === policy.versions.length - 1;
      const introduced = earliest && introducedAfter(version, registry.recordedSince);
      const described = version.summary !== null && version.summary.trim().length >= 20;
      if (!earliest && !described) {
        failures.push(
          `docs/compliance/policy-versions.json "${key}" ${version.date}: the first entry for this date needs a public "summary" of what changed, shown on ${policy.route}'s version history`,
        );
      }
      if (introduced && !described) {
        failures.push(
          `docs/compliance/policy-versions.json "${key}" ${version.date}: a policy first published after ${registry.recordedSince} needs a public "summary" of what it sets out, which /changelog lists`,
        );
      }
      if (version.status === 'missing') {
        failures.push(
          `${archiveFile(key, version.date)}: ${policy.route} dated ${version.date} was replaced and its text is not archived; run ${ARCHIVE_COMMAND}`,
        );
      }
    }
  }

  const manifestPath = path.join(root, ARCHIVE_MANIFEST);
  const manifest = fs.existsSync(manifestPath) ? fs.readFileSync(manifestPath, 'utf8') : 'null';
  if (!sameJson(manifest, renderManifest(policies, registry.recordedSince))) {
    failures.push(
      `${ARCHIVE_MANIFEST} does not match the policy version history; run ${ARCHIVE_COMMAND}`,
    );
  }
  const indexPath = path.join(root, ARCHIVE_INDEX);
  const index = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, 'utf8') : '';
  if (withoutSpace(index) !== withoutSpace(renderIndex(policies))) {
    failures.push(`${ARCHIVE_INDEX} does not list every archived version; run ${ARCHIVE_COMMAND}`);
  }
  return failures;
}

function sameJson(left, right) {
  try {
    return JSON.stringify(JSON.parse(left)) === JSON.stringify(JSON.parse(right));
  } catch {
    return false;
  }
}

function withoutSpace(text) {
  return text.replace(/\s+/g, '').replace(/,([}\]])/g, '$1');
}
