/**
 * Account-bound chat-persistence transport for the Chrome surface.
 *
 * The single property that makes account-backed mirroring safe: the shared
 * client's `saveMessage` hard-forces `skipLlm: true`
 * (`managed-cloud-chat-client.ts`), so no payload this file can construct will
 * ever trigger inference or bill the user. This is a persistence transport, not
 * a chat transport.
 *
 * This module is the ONLY place in the extension that constructs a Managed
 * Cloud chat client. It lives under `features/cloud-bridge/` because that
 * directory is the cloud-egress gate enforced by
 * `scripts/check-no-cloud-ipc-v1.mjs`.
 *
 * It must only ever be imported from the MV3 service worker. Extension-worker
 * fetches with `host_permissions` are not CORS-enforced (which is why the
 * existing `freeTrialClient` fetches work at all); a content script performing
 * the same request WOULD be CORS-enforced, and `apps/web/lib/cors.ts` has no
 * `chrome-extension://` branch.
 */
import {
  createManagedCloudChatClient,
  MANAGED_CLOUD_CHAT_MAX_METADATA_LENGTH,
  managedCloudMetadataLength,
  type GeneratedFileWire,
  type ManagedCloudChatClient,
} from '@agiworkforce/cloud-contracts';
import type { InteractiveCard } from '@agiworkforce/types';
import { FREE_TRIAL_GATEWAY, getManagedCloudAuthContext } from './freeTrialClient';
import { sameManagedCloudOwner, type ManagedCloudOwner } from './managedCloudAuthority';

/** The signed-in account/session changed while a request was being prepared. */
export class ManagedCloudOwnerChangedError extends Error {
  constructor(message = 'The Managed Cloud account changed while this request was in progress.') {
    super(message);
    this.name = 'ManagedCloudOwnerChangedError';
  }
}

/** No Managed Cloud session is available (signed out, or the session lapsed). */
export class ManagedCloudSignedOutError extends Error {
  constructor(message = 'Managed Cloud session is not available.') {
    super(message);
    this.name = 'ManagedCloudSignedOutError';
  }
}

/**
 * Build an owner-fenced persistence client.
 *
 * `getAuthToken` THROWS on a missing token rather than returning `null`. The
 * shared client omits the Authorization header entirely for a null token, and
 * the server's CSRF bypass requires a cryptographically valid Bearer — so a
 * lapsed Clerk session would otherwise surface as a confusing 403
 * `CSRF_VALIDATION_FAILED` instead of "you are signed out". `apps/web` sidesteps
 * this the same way.
 *
 * The token is re-resolved and the owner re-checked at the transport boundary on
 * every attempt, including the shared client's internal retries. A sign-out or
 * account switch mid-flight therefore fails BEFORE any payload leaves the
 * browser, rather than writing one account's transcript under another's session.
 */
export function createExtensionCloudChatClient(
  expectedOwner: ManagedCloudOwner,
): ManagedCloudChatClient {
  return createManagedCloudChatClient({
    // No trailing slash: the shared client concatenates paths directly.
    baseUrl: FREE_TRIAL_GATEWAY,
    getAuthToken: async () => {
      const context = await getManagedCloudAuthContext();
      if (!context) throw new ManagedCloudSignedOutError();
      if (!sameManagedCloudOwner(context.owner, expectedOwner)) {
        throw new ManagedCloudOwnerChangedError();
      }
      return context.token;
    },
    // Applied to mutations only. The one legacy workspace-recovery GET gets
    // its Bearer and explicit scope from the shared client's read headers; it
    // needs neither a CSRF header nor a surface claim. A valid Clerk Bearer
    // bypasses `requireCsrfToken` for mutations.
    decorateMutationHeaders: (headers) => ({
      ...headers,
      'X-Requested-With': 'XMLHttpRequest',
      'X-AGI-Surface': 'chrome',
    }),
    fetchImpl: (input, init) => fetch(input, init),
  });
}

export interface ExtensionCloudMessageMetadataInput {
  /** The Chrome-local conversation id, so a mirrored row can be traced back. */
  localConversationId: string;
  /** Always 'managed-cloud' — nothing else is eligible to be mirrored. */
  runtime: 'managed-cloud';
  managedQuickMode?: boolean;
  cloudAgentRunId?: string;
  /** Exact catalog route that produced this assistant turn. */
  model?: string;
  /** Canonical provider derived from `model`, never trusted from the wire. */
  provider?: string;
  /** Validated durable descriptors only; generated bytes are never embedded. */
  generatedFiles?: GeneratedFileWire[];
  /** Validated bounded card envelopes emitted for this turn. */
  interactiveCards?: InteractiveCard[];
}

/**
 * Metadata attached to a mirrored message.
 *
 * `agentEvents` are deliberately excluded. They are display-safe but bulky, and
 * a single agentic turn can carry hundreds of them — enough to blow the
 * metadata cap and fail the write. Compare `apps/desktop`'s
 * `buildBoundedCloudMessageMetadata`.
 */
export function buildExtensionCloudMessageMetadata(
  input: ExtensionCloudMessageMetadataInput,
): Record<string, unknown> {
  const metadata: Record<string, unknown> = {
    surface: 'chrome',
    runtime: input.runtime,
    localConversationId: input.localConversationId.slice(0, 200),
    ...(input.managedQuickMode ? { managedQuickMode: true } : {}),
    ...(input.cloudAgentRunId ? { cloudAgentRunId: input.cloudAgentRunId.slice(0, 200) } : {}),
    ...(input.model ? { model: input.model.slice(0, 200) } : {}),
    ...(input.provider ? { provider: input.provider.slice(0, 100) } : {}),
  };

  const appendIfBounded = (
    field: 'generatedFiles' | 'interactiveCards',
    value: unknown,
  ): boolean => {
    const current = Array.isArray(metadata[field]) ? (metadata[field] as unknown[]) : [];
    const candidate = { ...metadata, [field]: [...current, value] };
    if (managedCloudMetadataLength(candidate) > MANAGED_CLOUD_CHAT_MAX_METADATA_LENGTH)
      return false;
    metadata[field] = candidate[field];
    return true;
  };

  for (const file of input.generatedFiles ?? []) {
    if (
      !appendIfBounded('generatedFiles', {
        id: file.id,
        fileName: file.file_name,
        mimeType: file.mime_type,
        uri: file.uri,
        byteCount: file.byte_count,
        kind: file.kind,
        ...(file.checksum_sha256 ? { checksumSha256: file.checksum_sha256 } : {}),
        surface: file.surface,
        previewable: file.previewable,
      })
    ) {
      break;
    }
  }

  for (const card of input.interactiveCards ?? []) {
    if (!appendIfBounded('interactiveCards', card)) break;
  }

  // Core values are tightly bounded above. Rich fields are appended only when
  // the exact serialized contract length still fits, so persistence cannot turn
  // a successful chat into a metadata-validation failure.
  return metadata;
}
