'use client';

import { useCallback, useState } from 'react';
import {
  BarChart3,
  Check,
  Code2,
  Copy,
  Download,
  FileCode,
  FileText,
  Globe,
  Network,
  Table2,
  X,
} from 'lucide-react';
import { toast } from 'sonner';
import { useUnifiedChatStore } from '@/stores/unified/unifiedChatStore';
import { cn } from '@/lib/utils';
import type { Artifact, ArtifactType } from '@/types/chat';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ArtifactPanelProps {
  conversationId?: number;
  onClose: () => void;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getArtifactIcon(type: ArtifactType) {
  switch (type) {
    case 'code':
      return <FileCode className="h-3.5 w-3.5" />;
    case 'chart':
      return <BarChart3 className="h-3.5 w-3.5" />;
    case 'diagram':
    case 'mermaid':
      return <Network className="h-3.5 w-3.5" />;
    case 'html':
      return <Globe className="h-3.5 w-3.5" />;
    case 'table':
    case 'csv':
    case 'spreadsheet':
      return <Table2 className="h-3.5 w-3.5" />;
    case 'markdown':
    case 'document':
      return <FileText className="h-3.5 w-3.5" />;
    default:
      return <Code2 className="h-3.5 w-3.5" />;
  }
}

const LANGUAGE_EXTENSIONS: Record<string, string> = {
  typescript: 'ts',
  javascript: 'js',
  python: 'py',
  rust: 'rs',
  ruby: 'rb',
  csharp: 'cs',
  cpp: 'cpp',
  markdown: 'md',
  html: 'html',
  css: 'css',
  json: 'json',
  csv: 'csv',
};

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function EmptyState() {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-3 px-6 py-16 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-zinc-800/60">
        <Code2 className="h-7 w-7 text-zinc-500" aria-hidden="true" />
      </div>
      <div>
        <p className="text-sm font-semibold text-zinc-200">No artifacts yet</p>
        <p className="mt-1 text-xs text-zinc-500">
          Code and files generated by the AI will appear here
        </p>
      </div>
    </div>
  );
}

interface ArtifactTabProps {
  artifact: Artifact;
  isSelected: boolean;
  onSelect: () => void;
}

function ArtifactTab({ artifact, isSelected, onSelect }: ArtifactTabProps) {
  return (
    <button
      onClick={onSelect}
      title={artifact.title}
      className={cn(
        'flex shrink-0 items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors',
        isSelected
          ? 'bg-teal-500/15 text-teal-300'
          : 'text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200',
      )}
    >
      {getArtifactIcon(artifact.type)}
      <span className="max-w-[110px] truncate">{artifact.title}</span>
    </button>
  );
}

interface ArtifactViewerProps {
  artifact: Artifact;
}

function ArtifactViewer({ artifact }: ArtifactViewerProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(artifact.content);
      setCopied(true);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy to clipboard');
    }
  }, [artifact.content]);

  const handleDownload = useCallback(() => {
    const lang = artifact.language ?? artifact.type;
    const ext = LANGUAGE_EXTENSIONS[lang] ?? lang ?? 'txt';
    const filename = artifact.title.includes('.') ? artifact.title : `${artifact.title}.${ext}`;
    const blob = new Blob([artifact.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`);
  }, [artifact]);

  return (
    <div className="flex flex-1 flex-col overflow-hidden">
      {/* Scrollable code content */}
      <div className="flex-1 overflow-y-auto">
        <pre className="m-0 p-4 text-xs leading-relaxed text-zinc-200 whitespace-pre-wrap break-words font-mono bg-transparent">
          {artifact.content}
        </pre>
      </div>

      {/* Action bar */}
      <div className="flex items-center gap-2 border-t border-zinc-800 px-3 py-2 shrink-0">
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200 transition-colors"
          aria-label="Copy artifact content"
        >
          {copied ? (
            <>
              <Check className="h-3.5 w-3.5 text-green-400" aria-hidden="true" />
              Copied
            </>
          ) : (
            <>
              <Copy className="h-3.5 w-3.5" aria-hidden="true" />
              Copy
            </>
          )}
        </button>
        <button
          onClick={handleDownload}
          className="flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200 transition-colors"
          aria-label="Download artifact"
        >
          <Download className="h-3.5 w-3.5" aria-hidden="true" />
          Download
        </button>
        {artifact.language && (
          <span className="ml-auto text-[10px] uppercase tracking-wider text-zinc-600">
            {artifact.language}
          </span>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function ArtifactPanel({ onClose }: ArtifactPanelProps) {
  const [selectedArtifactId, setSelectedArtifactId] = useState<string | null>(null);

  // Pull artifacts out of the active conversation's messages
  const messagesByConversation = useUnifiedChatStore((state) => state.messagesByConversation);
  const activeConversationId = useUnifiedChatStore((state) => state.activeConversationId);

  // Collect all artifacts from the current conversation
  const artifacts: Artifact[] = [];
  if (activeConversationId) {
    const messages = messagesByConversation[activeConversationId] ?? [];
    for (const msg of messages) {
      if (msg.artifacts) {
        for (const artifact of msg.artifacts) {
          artifacts.push(artifact as Artifact);
        }
      }
    }
  }

  const selectedArtifact =
    artifacts.find((a) => a.id === selectedArtifactId) ?? artifacts[0] ?? null;

  const effectiveSelectedId = selectedArtifact?.id ?? null;

  return (
    <div className="flex flex-col h-full bg-zinc-950 border-l border-zinc-800">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-zinc-800 px-4 py-3 shrink-0">
        <div className="flex items-center gap-2">
          <Code2 className="h-4 w-4 text-zinc-400" aria-hidden="true" />
          <h2 className="text-sm font-semibold text-zinc-200">Artifacts</h2>
          {artifacts.length > 0 && (
            <span className="rounded-full bg-teal-500/15 px-1.5 py-0.5 text-[10px] font-medium text-teal-300">
              {artifacts.length}
            </span>
          )}
        </div>
        <button
          onClick={onClose}
          className="flex h-7 w-7 items-center justify-center rounded-lg text-zinc-500 hover:bg-zinc-800 hover:text-zinc-300 transition-colors"
          aria-label="Close artifacts panel"
        >
          <X className="h-4 w-4" aria-hidden="true" />
        </button>
      </div>

      {artifacts.length === 0 ? (
        <EmptyState />
      ) : (
        <>
          {/* Tab strip */}
          <div className="border-b border-zinc-800 px-3 py-2 shrink-0">
            <div className="flex gap-1 overflow-x-auto scrollbar-none">
              {artifacts.map((artifact) => (
                <ArtifactTab
                  key={artifact.id}
                  artifact={artifact}
                  isSelected={artifact.id === effectiveSelectedId}
                  onSelect={() => setSelectedArtifactId(artifact.id)}
                />
              ))}
            </div>
          </div>

          {/* Viewer */}
          <div className="flex flex-1 flex-col overflow-hidden bg-zinc-900/50">
            {selectedArtifact ? <ArtifactViewer artifact={selectedArtifact} /> : <EmptyState />}
          </div>
        </>
      )}
    </div>
  );
}
