/**
 * ArtifactPanel tests
 *
 * Covers:
 * - Empty state when no artifacts exist
 * - Rendering artifacts from the active conversation
 * - Tab selection
 * - Copy and download interactions
 * - Close button callback
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import type { Artifact } from '@/types/chat';
import { ArtifactPanel } from './ArtifactPanel';

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

// sonner toast
vi.mock('sonner', () => ({
  toast: {
    success: vi.fn(),
    error: vi.fn(),
  },
}));

// Unified chat store — we expose a mutable state to set per-test
let mockMessagesByConversation: Record<string, any[]> = {};
let mockActiveConversationId: string | null = null;

vi.mock('@/stores/unified/unifiedChatStore', () => ({
  useUnifiedChatStore: (selector: (state: any) => any) =>
    selector({
      messagesByConversation: mockMessagesByConversation,
      activeConversationId: mockActiveConversationId,
    }),
}));

// ---------------------------------------------------------------------------
// Factories
// ---------------------------------------------------------------------------

function makeArtifact(overrides: Partial<Artifact> = {}): Artifact {
  return {
    id: 'art-1',
    type: 'code',
    title: 'hello.ts',
    content: 'console.log("hello")',
    language: 'typescript',
    createdAt: new Date('2024-01-01T00:00:00Z'),
    updatedAt: new Date('2024-01-01T00:00:00Z'),
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function renderPanel(onClose = vi.fn()) {
  return render(<ArtifactPanel onClose={onClose} />);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('ArtifactPanel', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockMessagesByConversation = {};
    mockActiveConversationId = null;
  });

  // ============================================================
  // Empty state
  // ============================================================

  describe('empty state', () => {
    it('shows empty state when there are no messages', () => {
      renderPanel();
      expect(screen.getByText('No artifacts yet')).toBeInTheDocument();
    });

    it('shows empty state when active conversation has no artifacts', () => {
      mockActiveConversationId = 'conv-1';
      mockMessagesByConversation = {
        'conv-1': [{ id: 'msg-1', content: 'Hello' }],
      };
      renderPanel();
      expect(screen.getByText('No artifacts yet')).toBeInTheDocument();
    });

    it('shows helper text in empty state', () => {
      renderPanel();
      expect(
        screen.getByText('Code and files generated by the AI will appear here'),
      ).toBeInTheDocument();
    });
  });

  // ============================================================
  // Header
  // ============================================================

  describe('header', () => {
    it('renders the "Artifacts" heading', () => {
      renderPanel();
      expect(screen.getByRole('heading', { name: 'Artifacts' })).toBeInTheDocument();
    });

    it('renders the close button', () => {
      renderPanel();
      expect(screen.getByLabelText('Close artifacts panel')).toBeInTheDocument();
    });

    it('calls onClose when close button is clicked', () => {
      const onClose = vi.fn();
      renderPanel(onClose);
      fireEvent.click(screen.getByLabelText('Close artifacts panel'));
      expect(onClose).toHaveBeenCalledOnce();
    });
  });

  // ============================================================
  // Artifact rendering
  // ============================================================

  describe('artifact rendering', () => {
    beforeEach(() => {
      mockActiveConversationId = 'conv-1';
      mockMessagesByConversation = {
        'conv-1': [
          {
            id: 'msg-1',
            artifacts: [makeArtifact({ id: 'art-1', title: 'index.ts', content: 'const x = 1;' })],
          },
        ],
      };
    });

    it('renders the artifact tab with the title', () => {
      renderPanel();
      expect(screen.getByTitle('index.ts')).toBeInTheDocument();
    });

    it('renders artifact content in viewer', () => {
      renderPanel();
      expect(screen.getByText('const x = 1;')).toBeInTheDocument();
    });

    it('renders the artifact language label', () => {
      renderPanel();
      expect(screen.getByText('typescript')).toBeInTheDocument();
    });

    it('shows artifact count badge', () => {
      renderPanel();
      expect(screen.getByText('1')).toBeInTheDocument();
    });
  });

  // ============================================================
  // Multiple artifacts — tab switching
  // ============================================================

  describe('multiple artifacts — tab switching', () => {
    beforeEach(() => {
      mockActiveConversationId = 'conv-1';
      mockMessagesByConversation = {
        'conv-1': [
          {
            id: 'msg-1',
            artifacts: [
              makeArtifact({
                id: 'art-1',
                title: 'alpha.ts',
                content: 'const alpha = true;',
              }),
              makeArtifact({
                id: 'art-2',
                title: 'beta.py',
                content: 'def beta(): pass',
                language: 'python',
              }),
            ],
          },
        ],
      };
    });

    it('renders a tab for each artifact', () => {
      renderPanel();
      expect(screen.getByTitle('alpha.ts')).toBeInTheDocument();
      expect(screen.getByTitle('beta.py')).toBeInTheDocument();
    });

    it('shows first artifact content by default', () => {
      renderPanel();
      expect(screen.getByText('const alpha = true;')).toBeInTheDocument();
    });

    it('clicking a tab switches the viewed artifact', () => {
      renderPanel();
      fireEvent.click(screen.getByTitle('beta.py'));
      expect(screen.getByText('def beta(): pass')).toBeInTheDocument();
    });

    it('shows badge with total artifact count', () => {
      renderPanel();
      expect(screen.getByText('2')).toBeInTheDocument();
    });
  });

  // ============================================================
  // Copy action
  // ============================================================

  describe('copy action', () => {
    beforeEach(() => {
      mockActiveConversationId = 'conv-1';
      mockMessagesByConversation = {
        'conv-1': [
          {
            id: 'msg-1',
            artifacts: [makeArtifact({ id: 'art-1', title: 'test.ts', content: 'let x = 42;' })],
          },
        ],
      };

      Object.defineProperty(navigator, 'clipboard', {
        value: { writeText: vi.fn().mockResolvedValue(undefined) },
        writable: true,
        configurable: true,
      });
    });

    it('renders the copy button', () => {
      renderPanel();
      expect(screen.getByLabelText('Copy artifact content')).toBeInTheDocument();
    });

    it('copies content to clipboard when copy button is clicked', async () => {
      renderPanel();
      fireEvent.click(screen.getByLabelText('Copy artifact content'));
      await waitFor(() => {
        expect(navigator.clipboard.writeText).toHaveBeenCalledWith('let x = 42;');
      });
    });

    it('shows "Copied" feedback after click', async () => {
      renderPanel();
      fireEvent.click(screen.getByLabelText('Copy artifact content'));
      await waitFor(() => {
        expect(screen.getByText('Copied')).toBeInTheDocument();
      });
    });
  });

  // ============================================================
  // Download action
  // ============================================================

  describe('download action', () => {
    beforeEach(() => {
      mockActiveConversationId = 'conv-1';
      mockMessagesByConversation = {
        'conv-1': [
          {
            id: 'msg-1',
            artifacts: [
              makeArtifact({ id: 'art-1', title: 'snippet', content: 'x = 1', language: 'python' }),
            ],
          },
        ],
      };
    });

    it('renders the download button', () => {
      renderPanel();
      expect(screen.getByLabelText('Download artifact')).toBeInTheDocument();
    });

    it('triggers download when download button is clicked', () => {
      const createObjectURL = vi.fn(() => 'blob:test');
      const revokeObjectURL = vi.fn();
      global.URL.createObjectURL = createObjectURL;
      global.URL.revokeObjectURL = revokeObjectURL;

      // Spy on anchor click
      const clickSpy = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {});

      renderPanel();
      fireEvent.click(screen.getByLabelText('Download artifact'));

      expect(createObjectURL).toHaveBeenCalled();
      expect(clickSpy).toHaveBeenCalled();

      clickSpy.mockRestore();
    });
  });

  // ============================================================
  // Artifact types — icon/label variations
  // ============================================================

  describe('artifact types', () => {
    const types: Array<Artifact['type']> = [
      'code',
      'html',
      'mermaid',
      'chart',
      'table',
      'markdown',
      'json',
    ];

    for (const type of types) {
      it(`renders without error for type="${type}"`, () => {
        mockActiveConversationId = 'conv-1';
        mockMessagesByConversation = {
          'conv-1': [{ id: 'msg-1', artifacts: [makeArtifact({ type })] }],
        };
        expect(() => renderPanel()).not.toThrow();
      });
    }
  });
});
