import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { buildSbom, flattenPnpmTree, parseCargoLock } from './generate-sbom.mjs';

const scriptPath = fileURLToPath(new URL('./generate-sbom.mjs', import.meta.url));
const repositoryRoot = path.dirname(path.dirname(scriptPath));

const CARGO_LOCK_FIXTURE = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "agiworkforce-desktop"
version = "1.2.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5f0e2c6ed6606019b4e29e69dbaba95b11854410e5347d525002456dbbb786b6"
`;

test('parseCargoLock reads every locked crate with its source', () => {
  const packages = parseCargoLock(CARGO_LOCK_FIXTURE);
  assert.deepEqual(packages, [
    { name: 'agiworkforce-desktop', version: '1.2.0' },
    {
      name: 'serde',
      version: '1.0.219',
      source: 'registry+https://github.com/rust-lang/crates.io-index',
    },
  ]);
});

test('flattenPnpmTree collects transitive npm packages and drops workspace links', () => {
  const packages = flattenPnpmTree([
    {
      name: '@agiworkforce/desktop',
      dependencies: {
        '@agiworkforce/types': { version: 'link:../../packages/contracts/types' },
        react: {
          version: '19.2.6',
          dependencies: { 'scheduler-fixture': { version: '0.27.0' } },
        },
      },
    },
  ]);
  assert.deepEqual(
    packages.sort((a, b) => a.name.localeCompare(b.name)),
    [
      { name: 'react', version: '19.2.6' },
      { name: 'scheduler-fixture', version: '0.27.0' },
    ],
  );
});

test('buildSbom emits a CycloneDX document with purls for both ecosystems', () => {
  const sbom = buildSbom({
    component: 'agiworkforce-desktop',
    version: '1.2.0',
    cargoPackages: parseCargoLock(CARGO_LOCK_FIXTURE),
    npmPackages: [{ name: '@agiworkforce/types', version: '1.0.0' }],
  });

  assert.equal(sbom.bomFormat, 'CycloneDX');
  assert.equal(sbom.specVersion, '1.6');
  assert.equal(sbom.metadata.component.version, '1.2.0');
  const purls = sbom.components.map((entry) => entry.purl);
  assert.ok(purls.includes('pkg:cargo/serde@1.0.219'));
  assert.ok(purls.includes('pkg:npm/%40agiworkforce/types@1.0.0'));
  assert.deepEqual(
    purls,
    [...purls].sort((a, b) => a.localeCompare(b)),
  );
});

test('the CLI writes an SBOM covering the real workspace Cargo.lock', () => {
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), 'agi-sbom-'));
  const outputPath = path.join(outputDir, 'desktop.cdx.json');
  try {
    execFileSync(
      process.execPath,
      [
        scriptPath,
        '--component',
        'agiworkforce-desktop',
        '--version',
        '1.2.0',
        '--cargo-lock',
        path.join(repositoryRoot, 'Cargo.lock'),
        '--out',
        outputPath,
      ],
      { stdio: 'pipe' },
    );
    const sbom = JSON.parse(fs.readFileSync(outputPath, 'utf8'));
    assert.equal(sbom.bomFormat, 'CycloneDX');
    assert.ok(sbom.components.length > 100);
    assert.ok(sbom.components.every((entry) => entry.purl.startsWith('pkg:')));
  } finally {
    fs.rmSync(outputDir, { recursive: true, force: true });
  }
});

test('the CLI refuses to write an SBOM with no components', () => {
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), 'agi-sbom-empty-'));
  try {
    assert.throws(
      () =>
        execFileSync(
          process.execPath,
          [
            scriptPath,
            '--component',
            'agiworkforce-desktop',
            '--version',
            '1.2.0',
            '--out',
            path.join(outputDir, 'empty.cdx.json'),
          ],
          { stdio: 'pipe' },
        ),
      /refusing to write an empty SBOM/u,
    );
  } finally {
    fs.rmSync(outputDir, { recursive: true, force: true });
  }
});
