#!/usr/bin/env bash
# scripts/update-homebrew-tap.sh — Updates the Homebrew tap with v-cli-X.Y.Z release artifacts.
#
# Prerequisites:
#   - GitHub release v-cli-$VERSION exists with darwin-arm64/x64 + linux-arm64/x64 .tar.gz assets
#   - You have push access to https://github.com/siddharthanagula3/homebrew-tap
#   - HOMEBREW_TAP_DIR env var points to a local clone of the tap repo (default: ~/code/homebrew-tap)
#
# Usage:
#   ./scripts/update-homebrew-tap.sh 1.0.0

set -euo pipefail

VERSION="${1:?usage: $0 <version>}"
TAP_DIR="${HOMEBREW_TAP_DIR:-$HOME/code/homebrew-tap}"
RELEASE_BASE="https://github.com/siddharthanagula3/agiworkforce/releases/download/v-cli-$VERSION"

if [ ! -d "$TAP_DIR" ]; then
  echo "ERROR: $TAP_DIR doesn't exist."
  echo "  git clone git@github.com:siddharthanagula3/homebrew-tap.git $TAP_DIR"
  exit 1
fi

echo "→ Computing sha256 for each platform binary..."
declare -A SHAS
for platform in darwin-arm64 darwin-x64 linux-arm64 linux-x64; do
  url="$RELEASE_BASE/agiworkforce-$platform.tar.gz"
  echo "  fetching $url"
  sha=$(curl -fsSL "$url" | sha256sum | cut -d' ' -f1)
  SHAS[$platform]="$sha"
  echo "    sha256: $sha"
done

echo ""
echo "→ Generating $TAP_DIR/Formula/agiworkforce.rb..."
mkdir -p "$TAP_DIR/Formula"
cat > "$TAP_DIR/Formula/agiworkforce.rb" <<EOF
# Auto-generated by scripts/update-homebrew-tap.sh — DO NOT EDIT BY HAND.
# Source: https://github.com/siddharthanagula3/agiworkforce/blob/main/scripts/homebrew/agiworkforce.rb

class Agiworkforce < Formula
  desc "Multi-model AI agent for your terminal — BYOK, 25 providers, MCP, computer-use"
  homepage "https://agiworkforce.com"
  license "Proprietary"
  version "$VERSION"

  on_macos do
    if Hardware::CPU.arm?
      url "$RELEASE_BASE/agiworkforce-darwin-arm64.tar.gz"
      sha256 "${SHAS[darwin-arm64]}"
    else
      url "$RELEASE_BASE/agiworkforce-darwin-x64.tar.gz"
      sha256 "${SHAS[darwin-x64]}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "$RELEASE_BASE/agiworkforce-linux-arm64.tar.gz"
      sha256 "${SHAS[linux-arm64]}"
    else
      url "$RELEASE_BASE/agiworkforce-linux-x64.tar.gz"
      sha256 "${SHAS[linux-x64]}"
    end
  end

  def install
    bin.install "agiworkforce"
  end

  test do
    assert_match "agiworkforce", shell_output("#{bin}/agiworkforce --version")
    assert_match "ANTHROPIC", shell_output("#{bin}/agiworkforce --list-models")
  end
end
EOF

echo ""
echo "→ Committing + pushing tap update..."
(
  cd "$TAP_DIR"
  git add Formula/agiworkforce.rb
  git commit -m "agiworkforce $VERSION

Auto-published by agiworkforce/scripts/update-homebrew-tap.sh.
"
  git push origin main
)

echo ""
echo "✓ Tap updated. Users can now:"
echo "  brew install siddharthanagula3/tap/agiworkforce"
echo "  brew upgrade siddharthanagula3/tap/agiworkforce"
