#!/usr/bin/env bash
# scripts/update-homebrew-tap.sh — Updates the Homebrew tap with v-cli-X.Y.Z release artifacts.
#
# Prerequisites:
#   - GitHub release v-cli-$VERSION exists with darwin-arm64/x64 + linux-arm64/x64 .tar.gz assets
#   - You have push access to https://github.com/siddharthanagula3/homebrew-tap
#   - HOMEBREW_TAP_DIR env var points to a local clone of the tap repo (default: ~/code/homebrew-tap)
#
# Usage:
#   ./scripts/update-homebrew-tap.sh 1.0.0

set -euo pipefail

VERSION="${1:?usage: $0 <version>}"
TAP_DIR="${HOMEBREW_TAP_DIR:-$HOME/code/homebrew-tap}"
RELEASE_BASE="https://github.com/siddharthanagula3/agiworkforce/releases/download/v-cli-$VERSION"

if [ ! -d "$TAP_DIR" ]; then
  echo "ERROR: $TAP_DIR doesn't exist."
  echo "  git clone git@github.com:siddharthanagula3/homebrew-tap.git $TAP_DIR"
  exit 1
fi

echo "→ Computing sha256 for each platform binary..."
# Use plain variables instead of `declare -A` — macOS ships bash 3.2 which
# lacks associative arrays. linux-arm64 was dropped from the v1.0 matrix
# (cross-compile openssl issue); add it back here when v1.1 ships.
fetch_sha() {
  local platform="$1"
  local url="$RELEASE_BASE/agiworkforce-$platform.tar.gz"
  echo "  fetching $url" >&2
  curl -fsSL "$url" | shasum -a 256 | cut -d' ' -f1
}

SHA_DARWIN_ARM64=$(fetch_sha darwin-arm64)
echo "    darwin-arm64: $SHA_DARWIN_ARM64"
SHA_DARWIN_X64=$(fetch_sha darwin-x64)
echo "    darwin-x64:   $SHA_DARWIN_X64"
SHA_LINUX_X64=$(fetch_sha linux-x64)
echo "    linux-x64:    $SHA_LINUX_X64"

echo ""
echo "→ Generating $TAP_DIR/Formula/agiworkforce.rb..."
mkdir -p "$TAP_DIR/Formula"
cat > "$TAP_DIR/Formula/agiworkforce.rb" <<EOF
# Auto-generated by scripts/update-homebrew-tap.sh — DO NOT EDIT BY HAND.
# Source: https://github.com/siddharthanagula3/agiworkforce/blob/main/scripts/homebrew/agiworkforce.rb

class Agiworkforce < Formula
  desc "Multi-model AI agent for your terminal — BYOK, 25 providers, MCP, computer-use"
  homepage "https://agiworkforce.com"
  license "Proprietary"
  version "$VERSION"

  on_macos do
    if Hardware::CPU.arm?
      url "$RELEASE_BASE/agiworkforce-darwin-arm64.tar.gz"
      sha256 "$SHA_DARWIN_ARM64"
    else
      url "$RELEASE_BASE/agiworkforce-darwin-x64.tar.gz"
      sha256 "$SHA_DARWIN_X64"
    end
  end

  # linux-arm64 omitted in v1.0 (cross-compile openssl-sys not yet wired —
  # users on arm64 Linux can run: cargo install --git
  # https://github.com/siddharthanagula3/agiworkforce agiworkforce-cli)
  on_linux do
    url "$RELEASE_BASE/agiworkforce-linux-x64.tar.gz"
    sha256 "$SHA_LINUX_X64"
  end

  def install
    bin.install "agiworkforce"
  end

  test do
    assert_match "agiworkforce", shell_output("#{bin}/agiworkforce --version")
    assert_match "ANTHROPIC", shell_output("#{bin}/agiworkforce --list-models")
  end
end
EOF

echo ""
echo "→ Committing + pushing tap update..."
(
  cd "$TAP_DIR"
  git add Formula/agiworkforce.rb
  git commit -m "agiworkforce $VERSION

Auto-published by agiworkforce/scripts/update-homebrew-tap.sh.
"
  git push origin main
)

echo ""
echo "✓ Tap updated. Users can now:"
echo "  brew install siddharthanagula3/tap/agiworkforce"
echo "  brew upgrade siddharthanagula3/tap/agiworkforce"
