/**
 * Legal directory index. Currently routes users to the Article 50 reference;
 * future legal screens (DPA, GDPR DSAR, CCPA) land here without changing the
 * drawer entry point.
 */
import { Redirect, type Href } from 'expo-router';

export default function LegalIndex() {
  // `.expo/types/router.d.ts` is regenerated by the dev server and lags
  // newly-added route files. Same `as Href` escape used elsewhere in the app.
  return <Redirect href={'/legal/article-50' as Href} />;
}
