import 'server-only';

import { createHash } from 'crypto';
import { storeMedia, isMediaStorageConfigured } from '@/lib/server/media-storage';
import { insertMediaAsset, type MediaKind } from '@/lib/server/media-assets';
import { logger } from '@/lib/logger';

/**
 * Shared persistence core for the generated-file byte pipeline (managed cloud
 * only). EVERY source of model-generated bytes feeds this one function:
 *
 *   - E2B sandbox files harvested at turn end            (lib/e2b/generated-files.ts)
 *   - E2B runCode rich results (matplotlib chart PNGs)   (tool-loop.ts)
 *   - OpenAI Code Interpreter container files            (lib/server/container-files.ts)
 *   - Anthropic code-execution Files API outputs         (lib/server/container-files.ts)
 *
 * It stores the bytes durably (R2 via storeMedia), catalogs them in
 * `media_assets`, and returns the wire descriptor emitted to clients in the
 * `x_generated_files` SSE delta. The descriptor's `uri` is a SAME-ORIGIN path
 * (`/api/files/{assetId}`) — the only kind of URL the web renderer gates
 * (PDF viewer, inline image, spreadsheet fetch) accept for inline rendering.
 *
 * Contract consumed by web today and mobile/desktop cloud later:
 *   uri: same-origin path on the web app origin; fetch with the user's Clerk
 *        session cookie (browser) or `Authorization: Bearer <jwt>` (native).
 *   checksum_sha256: hash of the exact stored bytes, so any surface can verify
 *        byte round-trip integrity end-to-end.
 */

/** Max bytes per persisted generated file (matches the E2B harvest cap). */
export const MAX_GENERATED_FILE_BYTES = 20 * 1024 * 1024;

/** Wire shape of one generated file in the `x_generated_files` SSE delta. */
export interface GeneratedFileWire {
  id: string;
  file_name: string;
  mime_type: string;
  /** Durable download URL. Same-origin `/api/files/{id}` when cataloged. */
  uri: string;
  byte_count: number;
  /** Coarse kind for client icons: pdf | docx | xlsx | pptx | csv | json | markdown | html | image | archive | other */
  kind: string;
  /** SHA-256 of the stored bytes (hash in == hash out verification). */
  checksum_sha256: string;
}

// Compile-time drift anchor: the emitted wire shape must stay assignable to
// the shared cloud contract (`packages/services/src/cloud-contracts/
// generated-files.ts`) that mobile/desktop validate stream deltas against.
const _generatedFileWireContractCheck: (
  file: GeneratedFileWire,
) => import('@agiworkforce/services').GeneratedFileWire = (file) => file;
void _generatedFileWireContractCheck;

export type PersistGeneratedFileOutcome =
  | { ok: true; file: GeneratedFileWire }
  | { ok: false; reason: 'not_configured' | 'too_large' | 'storage_error' };

/** Coarse client-icon kind for a filename+mime (shared across all sources). */
export function generatedFileKind(fileName: string, mime: string): string {
  const ext = fileName.toLowerCase().split('.').pop() ?? '';
  if (['pdf', 'docx', 'xlsx', 'pptx', 'csv', 'json', 'html'].includes(ext)) return ext;
  if (ext === 'md' || ext === 'markdown') return 'markdown';
  if (mime.startsWith('image/')) return 'image';
  if (ext === 'zip' || ext === 'tar' || ext === 'gz') return 'archive';
  return 'other';
}

function mediaKindFor(mime: string): MediaKind {
  if (mime.startsWith('image/')) return 'image';
  if (mime.startsWith('video/')) return 'video';
  return 'file';
}

/**
 * Persist one generated file's raw bytes and return its wire descriptor.
 * Never throws: failures return a typed reason so callers can keep today's
 * "skipping" warn AND surface an honest inline note instead of silence.
 */
export async function persistGeneratedFileBytes(params: {
  userId: string;
  data: Buffer;
  mimeType: string;
  filename: string;
  /** Byte source for provenance: 'e2b' | 'openai' | 'anthropic' | ... */
  provider: string;
  /** Provenance detail stored in metadata.origin, e.g. 'e2b-execution'. */
  origin: string;
  model?: string;
  prompt?: string;
  extraMetadata?: Record<string, unknown>;
}): Promise<PersistGeneratedFileOutcome> {
  const { userId, data, mimeType, filename, provider, origin, model, prompt } = params;

  if (!isMediaStorageConfigured()) return { ok: false, reason: 'not_configured' };
  if (data.byteLength > MAX_GENERATED_FILE_BYTES) {
    logger.warn(
      { filename, size: data.byteLength, cap: MAX_GENERATED_FILE_BYTES, provider },
      'Generated file exceeds persistence cap; skipping',
    );
    return { ok: false, reason: 'too_large' };
  }

  try {
    const kind = mediaKindFor(mimeType);
    const checksum = createHash('sha256').update(data).digest('hex');
    const stored = await storeMedia({ userId, kind, data, contentType: mimeType });
    const assetId = await insertMediaAsset({
      userId,
      kind,
      mimeType,
      byteSize: stored.byteSize,
      storageUrl: stored.url,
      storagePathname: stored.pathname,
      prompt,
      provider,
      model,
      sourceSurface: 'web',
      metadata: {
        filename,
        origin,
        checksumSha256: checksum,
        ...(params.extraMetadata ?? {}),
      },
    });

    return {
      ok: true,
      file: {
        id: assetId ?? crypto.randomUUID(),
        file_name: filename,
        mime_type: mimeType,
        // Same-origin serve path when cataloged (renderer gates accept it);
        // the raw R2 public URL is only a download-fallback when the catalog
        // row could not be written (pre-migration deploys).
        uri: assetId ? `/api/files/${assetId}` : stored.url,
        byte_count: stored.byteSize,
        kind: generatedFileKind(filename, mimeType),
        checksum_sha256: checksum,
      },
    };
  } catch (err) {
    logger.warn(
      { err: err instanceof Error ? err.message : String(err), filename, provider, userId },
      'Failed to persist generated file bytes; skipping',
    );
    return { ok: false, reason: 'storage_error' };
  }
}
