/**
 * @file An `OAuthClientProvider` that makes MCP connectors connectable without
 * the operator holding a relationship with the vendor.
 *
 * THE PROBLEM THIS SOLVES
 * ----------------------
 * `oauth-registry.ts` connects a user to a provider whose OAuth application the
 * operator registered by hand. That is correct, and it ships with zero
 * providers on purpose. The cost is that every one of the 83
 * `operator-configurable` entries in `catalog.ts` renders a Connect button that
 * cannot complete, because completing it requires a human to go and register
 * with that specific vendor first.
 *
 * MCP's authorization spec is designed to remove that step, and this module is
 * where the removal happens. Everything the flow needs is discovered from the
 * MCP server itself at connect time:
 *
 *   1. An unauthenticated request to the MCP endpoint answers `401` with a
 *      `WWW-Authenticate` challenge naming its protected-resource metadata.
 *   2. That metadata (RFC 9728) names the authorization server and the scopes
 *      the resource understands.
 *   3. The authorization server's metadata (RFC 8414) names its authorize,
 *      token, and registration endpoints, and states which client
 *      authentication and registration mechanisms it supports.
 *   4. A `client_id` is obtained WITHOUT a human, in the order MCP prescribes —
 *      see `clientInformation()` below.
 *
 * WHY THE SDK'S `auth()` DRIVES IT
 * --------------------------------
 * The orchestration is delegated to `auth()` from `@modelcontextprotocol/client`
 * rather than re-implemented here. Three of the steps it performs are ones a
 * hand-rolled broker gets subtly wrong:
 *
 *   - **Authorization-server mix-up defense.** RFC 9207: the `iss` returned on
 *     the callback is validated against the issuer discovery reported, BEFORE
 *     the code is redeemed.
 *   - **Issuer binding (SEP-2352).** Stored credentials carry the issuer they
 *     were minted under. If the MCP server later points at a DIFFERENT
 *     authorization server, the mismatch is detected and the credential is
 *     discarded instead of being replayed at a server that is no longer the
 *     right audience for it.
 *   - **Resource binding.** RFC 8707: the token is requested for a specific
 *     `resource`, so a token minted for one MCP server is not accepted by
 *     another.
 *
 * This class supplies the storage and the redirect seam; `auth()` supplies the
 * protocol.
 *
 * REQUEST SHAPE
 * -------------
 * The broker spans two HTTP requests — start and callback — so this provider is
 * built twice per flow and carries no in-process state between them. The start
 * leg accumulates what discovery produced and persists it in one row when the
 * authorization URL is finally known; the callback leg is constructed FROM that
 * row. Pinning the endpoints at start time is deliberate: it means a discovery
 * response that changes between the two legs cannot steer the code exchange
 * somewhere else.
 */

import 'server-only';

import type {
  OAuthClientMetadata,
  OAuthClientProvider,
  OAuthDiscoveryState,
  StoredOAuthClientInformation,
  StoredOAuthTokens,
} from '@modelcontextprotocol/client';

import { logger } from '@/lib/logger';
import {
  buildMcpClientMetadataDocument,
  resolveClientMetadataUrl,
  resolveClientRedirectUri,
} from '@/lib/connectors/mcp-client-metadata';
import {
  getMcpOAuthClient,
  saveMcpOAuthClient,
  type McpClientRegistrationMethod,
} from '@/lib/connectors/mcp-oauth-clients';

/**
 * What the start leg produced, ready to be written to the pending-authorization
 * row by the route. Assembled here because this class is what `auth()` hands
 * each piece to, at the moment it becomes known.
 */
export interface McpPendingAuthorizationDraft {
  authorizationUrl: string;
  state: string;
  codeVerifier: string;
  issuer: string | null;
  authorizationEndpoint: string | null;
  tokenEndpoint: string | null;
  resourceUrl: string | null;
  clientId: string | null;
}

/** Seed values the callback leg replays from the persisted pending row. */
export interface McpOAuthProviderSeed {
  state?: string;
  codeVerifier?: string;
  issuer?: string | null;
  tokens?: StoredOAuthTokens | undefined;
}

export interface McpOAuthProviderOptions {
  /** The MCP endpoint being authorized. Identifies the protected resource. */
  mcpUrl: string;
  /** Opaque `state` for this flow. Generated by the caller so it can hash it. */
  state: string;
  /** Present on the callback leg only. */
  seed?: McpOAuthProviderSeed;
}

/**
 * Raised when this deployment cannot host a client identity AND the
 * authorization server does not offer dynamic registration — the one case
 * where discovery genuinely cannot produce a `client_id`.
 */
export class McpClientIdentityUnavailableError extends Error {
  constructor(readonly issuer: string) {
    super(
      `No client identity is available for ${issuer}: this deployment publishes no client ` +
        `metadata document (set CONNECTOR_OAUTH_REDIRECT_BASE_URL to an HTTPS origin) and the ` +
        `authorization server does not support dynamic client registration.`,
    );
    this.name = 'McpClientIdentityUnavailableError';
  }
}

export class McpOAuthClientProvider implements OAuthClientProvider {
  /** Set by `redirectToAuthorization`; read by the start route. */
  private _authorizationUrl: string | null = null;
  private _codeVerifier: string | null;
  private _discovery: OAuthDiscoveryState | null = null;
  private _clientInformation: StoredOAuthClientInformation | undefined;
  private _tokens: StoredOAuthTokens | undefined;
  private _resourceUrl: string | null = null;
  private _authorizationServerUrl: string | null;
  /** How the client_id was obtained, for the audit line and the store. */
  private _registrationMethod: McpClientRegistrationMethod | null = null;

  constructor(private readonly options: McpOAuthProviderOptions) {
    this._codeVerifier = options.seed?.codeVerifier ?? null;
    this._authorizationServerUrl = options.seed?.issuer ?? null;
    this._tokens = options.seed?.tokens;
  }

  // ── Identity ──────────────────────────────────────────────────────────────

  get redirectUrl(): string | undefined {
    return resolveClientRedirectUri() ?? undefined;
  }

  /**
   * The CIMD URL. `auth()` uses it as the `client_id` when — and only when —
   * the authorization server advertises `client_id_metadata_document_supported`.
   * Returning it unconditionally is therefore safe: a server that does not
   * support CIMD ignores it and the dynamic-registration branch runs instead.
   */
  get clientMetadataUrl(): string | undefined {
    return resolveClientMetadataUrl() ?? undefined;
  }

  get clientMetadata(): OAuthClientMetadata {
    const document = buildMcpClientMetadataDocument();
    if (document) {
      // Strip `client_id`: this getter describes what we are REGISTERING, and a
      // registration request that names an id it does not yet hold is invalid.
      const { client_id: _clientId, ...metadata } = document;
      return metadata as unknown as OAuthClientMetadata;
    }
    // No hosted origin — the dynamic-registration path still needs metadata,
    // and a relative redirect is not acceptable to any authorization server, so
    // this branch only ever reaches a server in a misconfigured deployment. It
    // fails there with a clear `invalid_redirect_uri` rather than silently.
    return {
      client_name: 'AGI Workforce',
      redirect_uris: [this.redirectUrl ?? ''],
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
      token_endpoint_auth_method: 'none',
    } as unknown as OAuthClientMetadata;
  }

  state(): string {
    return this.options.state;
  }

  // ── Client registration ───────────────────────────────────────────────────

  /**
   * Resolve the client we present to this authorization server.
   *
   * Returning `undefined` is what tells `auth()` to acquire one, and the order
   * it then follows is the order MCP's client-registration guidance prescribes:
   * CIMD when the server advertises support for it, otherwise dynamic client
   * registration (RFC 7591 — deprecated for this purpose, but still what most
   * deployed authorization servers offer today).
   *
   * The pre-registered rung of that ladder sits ABOVE this module entirely: a
   * connector the operator has registered an OAuth app for is served by
   * `oauth-registry.ts` and never reaches discovery at all.
   */
  async clientInformation(ctx?: {
    issuer: string;
  }): Promise<StoredOAuthClientInformation | undefined> {
    if (this._clientInformation) return this._clientInformation;
    const issuer = ctx?.issuer ?? this._authorizationServerUrl;
    if (!issuer) return undefined;

    const record = await getMcpOAuthClient(issuer);
    if (!record) return undefined;

    this._registrationMethod = record.registrationMethod;
    this._clientInformation = {
      client_id: record.clientId,
      ...(record.clientSecret ? { client_secret: record.clientSecret } : {}),
      issuer: record.issuer,
    } as StoredOAuthClientInformation;
    return this._clientInformation;
  }

  async saveClientInformation(
    clientInformation: StoredOAuthClientInformation,
    ctx?: { issuer: string },
  ): Promise<void> {
    this._clientInformation = clientInformation;
    const issuer = clientInformation.issuer ?? ctx?.issuer ?? this._authorizationServerUrl;
    if (!issuer) {
      // Without an issuer there is no correct key to store under, and storing
      // under the MCP URL would let one server's registration be handed to
      // another. Keeping it in memory for this flow only is the safe loss.
      logger.warn(
        { mcpUrl: this.options.mcpUrl },
        '[mcp-oauth] client registration has no issuer; not persisting',
      );
      return;
    }

    const info = clientInformation as unknown as {
      client_id: string;
      client_secret?: string;
      client_secret_expires_at?: number;
    };

    // A `client_id` that IS our metadata URL means `auth()` took the CIMD
    // branch — nothing was registered anywhere, and there is no secret.
    const metadataUrl = resolveClientMetadataUrl();
    const method: McpClientRegistrationMethod =
      metadataUrl && info.client_id === metadataUrl ? 'cimd' : 'dynamic';
    this._registrationMethod = method;

    await saveMcpOAuthClient({
      issuer,
      clientId: info.client_id,
      clientSecret: method === 'cimd' ? null : (info.client_secret ?? null),
      registrationMethod: method,
      clientMetadataUrl: method === 'cimd' ? metadataUrl : null,
      // RFC 7591 expresses the expiry as seconds since the epoch, with 0
      // meaning "never expires".
      clientSecretExpiresAt:
        info.client_secret_expires_at && info.client_secret_expires_at > 0
          ? new Date(info.client_secret_expires_at * 1000)
          : null,
    });

    logger.info(
      { issuer, method },
      '[mcp-oauth] client identity established without operator registration',
    );
  }

  // ── Tokens ────────────────────────────────────────────────────────────────

  tokens(): StoredOAuthTokens | undefined {
    return this._tokens;
  }

  /**
   * `auth()` calls this the moment tokens exist. Persisting to
   * `connector_oauth_grants` is the ROUTE's job, not this class's, because the
   * route owns the user identity and the connector id; this class is scoped to
   * one MCP server and deliberately knows neither. Holding them here lets the
   * route read the result out after `auth()` returns.
   */
  saveTokens(tokens: StoredOAuthTokens): void {
    this._tokens = tokens;
  }

  // ── PKCE ──────────────────────────────────────────────────────────────────

  saveCodeVerifier(codeVerifier: string): void {
    this._codeVerifier = codeVerifier;
  }

  codeVerifier(): string {
    if (!this._codeVerifier) {
      // Reaching here on the callback leg means the pending row did not carry a
      // verifier — a replayed or forged callback. Failing loudly is correct:
      // a PKCE exchange without the verifier must never be attempted.
      throw new Error('No PKCE code verifier is available for this authorization');
    }
    return this._codeVerifier;
  }

  // ── Redirect seam ─────────────────────────────────────────────────────────

  redirectToAuthorization(authorizationUrl: URL): void {
    this._authorizationUrl = authorizationUrl.toString();
  }

  // ── Discovery state (SEP-2352 inputs) ─────────────────────────────────────

  saveDiscoveryState(state: OAuthDiscoveryState): void {
    this._discovery = state;
  }

  discoveryState(): OAuthDiscoveryState | undefined {
    return this._discovery ?? undefined;
  }

  saveAuthorizationServerUrl(authorizationServerUrl: string): void {
    this._authorizationServerUrl = authorizationServerUrl;
  }

  authorizationServerUrl(): string | undefined {
    return this._authorizationServerUrl ?? undefined;
  }

  saveResourceUrl(resourceUrl: string): void {
    this._resourceUrl = resourceUrl;
  }

  resourceUrl(): string | undefined {
    return this._resourceUrl ?? undefined;
  }

  // ── Readouts for the routes ───────────────────────────────────────────────

  /** The issuer discovery settled on, or null when discovery did not run. */
  get issuer(): string | null {
    return (
      this._discovery?.authorizationServerMetadata?.issuer ?? this._authorizationServerUrl ?? null
    );
  }

  get registrationMethod(): McpClientRegistrationMethod | null {
    return this._registrationMethod;
  }

  get resolvedTokens(): StoredOAuthTokens | undefined {
    return this._tokens;
  }

  /**
   * Everything the pending-authorization row needs, or null when `auth()`
   * completed without needing a redirect (an existing token was still good).
   */
  get pendingDraft(): McpPendingAuthorizationDraft | null {
    if (!this._authorizationUrl || !this._codeVerifier) return null;
    const metadata = this._discovery?.authorizationServerMetadata;
    return {
      authorizationUrl: this._authorizationUrl,
      state: this.options.state,
      codeVerifier: this._codeVerifier,
      issuer: this.issuer,
      authorizationEndpoint: metadata?.authorization_endpoint ?? null,
      tokenEndpoint: metadata?.token_endpoint ?? null,
      resourceUrl: this._resourceUrl,
      clientId:
        (this._clientInformation as unknown as { client_id?: string } | undefined)?.client_id ??
        null,
    };
  }
}
