//! Modular Command Registration
//!
//! This module provides a structured way to organize and register Tauri commands
//! by domain, making the codebase more maintainable and easier to navigate.
//!
//! Commands are grouped into logical categories:
//! - `sys_commands`: System-level operations (window, tray, settings, etc.)
//! - `core_commands`: Core AGI/AI functionality (agents, orchestration, etc.)
//! - `data_commands`: Data operations (chat, database, files, etc.)
//! - `automation_commands`: Automation features (browser, terminal, workflows)
//! - `integration_commands`: Third-party integrations (cloud, email, calendar, etc.)

/// Macro to generate the command handler registration
///
/// This macro takes command paths and generates the `tauri::generate_handler![]`
/// invocation, making it easier to organize commands by category.
#[macro_export]
macro_rules! register_commands {
    ($($cmd:path),* $(,)?) => {
        tauri::generate_handler![
            $($cmd),*
        ]
    };
}

/// System-level commands for window management, settings, and core app functionality
#[macro_export]
macro_rules! sys_command_handlers {
    () => {
        [
            // Window management
            $crate::sys::commands::window_get_state,
            $crate::sys::commands::window_set_pinned,
            $crate::sys::commands::window_set_always_on_top,
            $crate::sys::commands::window_set_visibility,
            $crate::sys::commands::window_dock,
            $crate::sys::commands::window_is_maximized,
            $crate::sys::commands::window_maximize,
            $crate::sys::commands::window_unmaximize,
            $crate::sys::commands::window_toggle_maximize,
            $crate::sys::commands::window_set_fullscreen,
            $crate::sys::commands::window_is_fullscreen,
            $crate::sys::commands::window_toggle_floating,
            $crate::sys::commands::window_open_floating,
            $crate::sys::commands::window_close_floating,
            $crate::sys::commands::window_is_floating_visible,
            $crate::sys::commands::tray_set_unread_badge,
            // Settings
            $crate::sys::commands::settings_load,
            $crate::sys::commands::settings_save,
            $crate::sys::commands::settings_load_from_disk,
            $crate::sys::commands::settings_v2_get,
            $crate::sys::commands::settings_v2_set,
            $crate::sys::commands::settings_v2_get_batch,
            $crate::sys::commands::settings_v2_delete,
            $crate::sys::commands::settings_v2_get_category,
            $crate::sys::commands::settings_v2_load_app_settings,
            $crate::sys::commands::settings_v2_save_app_settings,
            $crate::sys::commands::settings_v2_clear_cache,
            $crate::sys::commands::settings_v2_list_all,
            // Custom Instructions
            $crate::sys::commands::save_custom_instructions,
            $crate::sys::commands::load_custom_instructions,
            // Shortcuts
            $crate::sys::commands::shortcuts_register,
            $crate::sys::commands::shortcuts_unregister,
            $crate::sys::commands::shortcuts_list,
            $crate::sys::commands::shortcuts_update,
            $crate::sys::commands::shortcuts_trigger,
            $crate::sys::commands::shortcuts_reset,
            $crate::sys::commands::shortcuts_check_key,
            $crate::sys::commands::shortcuts_get_defaults,
            $crate::sys::commands::shortcuts_register_global,
            $crate::sys::commands::shortcuts_unregister_global,
            // Authentication
            $crate::sys::commands::auth_store_session,
            $crate::sys::commands::auth_retrieve_session,
            $crate::sys::commands::auth_remove_session,
            $crate::sys::commands::security::auth_login,
            // Error reporting
            $crate::sys::commands::error_report,
            $crate::sys::commands::error_report_batch,
            $crate::sys::commands::error_get_logs,
            $crate::sys::commands::error_clear_logs,
            $crate::sys::commands::error_get_stats,
            $crate::sys::commands::error_export_logs,
            // Onboarding
            $crate::sys::commands::get_onboarding_status,
            $crate::sys::commands::complete_onboarding_step,
            $crate::sys::commands::skip_onboarding_step,
            $crate::sys::commands::reset_onboarding,
            $crate::sys::commands::export_user_data,
            $crate::sys::commands::check_connectivity,
            $crate::sys::commands::get_session_info,
            $crate::sys::commands::update_session_activity,
            $crate::sys::commands::get_user_preference,
            $crate::sys::commands::set_user_preference,
            $crate::sys::commands::select_demo,
            $crate::sys::commands::record_demo_results,
            $crate::sys::commands::mark_setup_completed,
            $crate::sys::commands::complete_first_run,
            $crate::sys::commands::get_first_run_session,
            $crate::sys::commands::get_first_run_statistics,
            $crate::sys::commands::skip_first_run,
            $crate::sys::commands::start_first_run_experience,
            $crate::sys::commands::has_completed_first_run,
            $crate::sys::commands::update_first_run_step,
            // System resources
            $crate::sys::commands::get_system_resources,
            // Feedback
            $crate::sys::commands::feedback::submit_feedback,
            // Privacy
            $crate::sys::commands::privacy::privacy_delete_account,
            $crate::sys::commands::privacy::privacy_export_data,
            $crate::sys::commands::privacy::settings_update_privacy,
        ]
    };
}

/// Core AGI/AI commands for agent management and orchestration
#[macro_export]
macro_rules! core_command_handlers {
    () => {
        [
            // AGI Core
            $crate::sys::commands::agi_init,
            $crate::sys::commands::agi_submit_goal,
            $crate::sys::commands::agi_submit_goal_parallel,
            $crate::sys::commands::agi_get_goal_status,
            $crate::sys::commands::agi_list_goals,
            $crate::sys::commands::agi_stop,
            $crate::sys::commands::agi_cancel_goal,
            $crate::sys::commands::start_agent_task,
            // Reflection Engine
            $crate::sys::commands::agi_get_reflection_insights,
            $crate::sys::commands::agi_get_failure_patterns,
            $crate::sys::commands::agi_get_suggested_corrections,
            $crate::sys::commands::agi_get_sub_goals,
            $crate::sys::commands::agi_get_recommendations,
            // Orchestrator
            $crate::sys::commands::orchestrator_init,
            $crate::sys::commands::orchestrator_init_default,
            $crate::sys::commands::orchestrator_spawn_agent,
            $crate::sys::commands::orchestrator_spawn_parallel,
            $crate::sys::commands::orchestrator_get_agent_status,
            $crate::sys::commands::orchestrator_list_agents,
            $crate::sys::commands::orchestrator_cancel_agent,
            $crate::sys::commands::orchestrator_cancel_all,
            $crate::sys::commands::orchestrator_wait_all,
            $crate::sys::commands::orchestrator_cleanup,
            // Agent control
            $crate::sys::commands::pause_agent,
            $crate::sys::commands::resume_agent,
            $crate::sys::commands::cancel_agent,
            $crate::sys::commands::refresh_agent_status,
            $crate::sys::commands::list_active_agents,
            // Agent subsystem
            $crate::sys::commands::agent::agent_init,
            $crate::sys::commands::agent::agent_submit_task,
            $crate::sys::commands::agent::agent_get_task_status,
            $crate::sys::commands::agent::agent_list_tasks,
            $crate::sys::commands::agent::agent_stop,
            // Approvals
            $crate::sys::commands::approve_operation,
            $crate::sys::commands::reject_operation,
            $crate::sys::commands::agent_resolve_approval,
            $crate::sys::commands::agent_set_workflow_hash,
            $crate::sys::commands::agent_list_trusted_workflows,
            // LLM
            $crate::sys::commands::llm_send_message,
            $crate::sys::commands::llm_configure_provider,
            $crate::sys::commands::llm_set_default_provider,
            $crate::sys::commands::llm_ensure_managed_cloud,
            $crate::sys::commands::llm_get_available_models,
            $crate::sys::commands::llm_check_provider_status,
            $crate::sys::commands::llm_get_usage_stats,
            $crate::sys::commands::router_suggestions,
            // Knowledge
            $crate::sys::commands::query_knowledge,
            $crate::sys::commands::get_recent_knowledge,
            $crate::sys::commands::get_knowledge_by_category,
            // AI Native
            $crate::sys::commands::ai_analyze_project,
            $crate::sys::commands::ai_add_constraint,
            $crate::sys::commands::ai_generate_code,
            $crate::sys::commands::ai_refactor_code,
            $crate::sys::commands::ai_generate_tests,
            $crate::sys::commands::ai_get_project_context,
            $crate::sys::commands::ai_generate_context_prompt,
            $crate::sys::commands::ai_access_file,
            // Completion / Ghost Text
            $crate::sys::commands::get_code_completion,
            $crate::sys::commands::get_inline_completion,
            $crate::sys::commands::get_prompt_completion,
            // Vision
            $crate::sys::commands::vision_send_message,
            $crate::sys::commands::vision_analyze_screenshot,
            $crate::sys::commands::vision_extract_text,
            $crate::sys::commands::vision_compare_images,
            $crate::sys::commands::vision_locate_element,
            $crate::sys::commands::vision_describe_ui_elements,
            $crate::sys::commands::vision_answer_question,
            // Voice
            $crate::sys::commands::voice_transcribe_file,
            $crate::sys::commands::voice_transcribe_blob,
            $crate::sys::commands::voice_configure,
            $crate::sys::commands::voice_get_settings,
            $crate::sys::commands::voice_check_local_whisper,
            // Deepgram Streaming STT
            $crate::sys::commands::voice_deepgram_configure,
            $crate::sys::commands::voice_start_deepgram_stream,
            $crate::sys::commands::voice_stop_deepgram_stream,
            $crate::sys::commands::voice_deepgram_send_audio,
            $crate::sys::commands::voice_deepgram_status,
            $crate::sys::commands::voice_convert_audio_to_pcm,
            // Prompt enhancement
            $crate::sys::commands::detect_use_case,
            $crate::sys::commands::enhance_prompt,
            $crate::sys::commands::route_to_best_api,
            $crate::sys::commands::enhance_and_route_prompt,
            $crate::sys::commands::get_prompt_enhancement_config,
            $crate::sys::commands::set_prompt_enhancement_config,
            $crate::sys::commands::get_suggested_provider,
            $crate::sys::commands::get_available_use_cases,
            $crate::sys::commands::get_available_providers,
            // Debug
            $crate::sys::commands::debug_parse_error,
            $crate::sys::commands::debug_suggest_fixes,
            $crate::sys::commands::debug_analyze_stack_trace,
        ]
    };
}

/// Data-related commands for chat, files, database operations
#[macro_export]
macro_rules! data_command_handlers {
    () => {
        [
            // Chat
            $crate::sys::commands::chat_create_conversation,
            $crate::sys::commands::chat_get_conversations,
            $crate::sys::commands::chat_get_conversation,
            $crate::sys::commands::chat_update_conversation,
            $crate::sys::commands::chat_delete_conversation,
            $crate::sys::commands::chat_create_message,
            $crate::sys::commands::chat_get_messages,
            $crate::sys::commands::chat_update_message,
            $crate::sys::commands::chat_delete_message,
            $crate::sys::commands::chat_send_message,
            $crate::sys::commands::chat_stop_generation,
            $crate::sys::commands::cancel_tool_execution,
            $crate::sys::commands::chat_add_pending_message,
            $crate::sys::commands::chat_get_pending_messages,
            $crate::sys::commands::chat_clear_pending_messages,
            $crate::sys::commands::chat_pop_pending_message,
            $crate::sys::commands::chat_get_conversation_stats,
            $crate::sys::commands::chat_get_cost_overview,
            $crate::sys::commands::chat_get_cost_analytics,
            $crate::sys::commands::chat_set_monthly_budget,
            $crate::sys::commands::chat::clear_local_database,
            // Checkpoints
            $crate::sys::commands::checkpoint_create,
            $crate::sys::commands::checkpoint_restore,
            $crate::sys::commands::checkpoint_list,
            $crate::sys::commands::checkpoint_delete,
            // Files
            $crate::sys::commands::file_read,
            $crate::sys::commands::file_write,
            $crate::sys::commands::file_delete,
            $crate::sys::commands::file_rename,
            $crate::sys::commands::file_copy,
            $crate::sys::commands::file_move,
            $crate::sys::commands::file_exists,
            $crate::sys::commands::file_metadata,
            $crate::sys::commands::undo_file_operation,
            $crate::sys::commands::dir_create,
            $crate::sys::commands::dir_list,
            $crate::sys::commands::dir_delete,
            $crate::sys::commands::dir_traverse,
            $crate::sys::filesystem::fs_search_files,
            $crate::sys::filesystem::fs_search_folders,
            $crate::sys::commands::fs_read_file_content,
            $crate::sys::commands::fs_get_workspace_files,
            $crate::sys::commands::file_watch_start,
            $crate::sys::commands::file_watch_stop,
            $crate::sys::commands::file_watch_list,
            $crate::sys::commands::file_watch_stop_all,
            $crate::sys::commands::file_read_text,
            $crate::sys::commands::file_write_text,
            $crate::sys::commands::file_read_binary,
            $crate::sys::commands::file_write_binary,
            $crate::sys::commands::file_get_metadata,
            // Database
            $crate::sys::commands::db_create_pool,
            $crate::sys::commands::db_execute_query,
            $crate::sys::commands::db_execute_prepared,
            $crate::sys::commands::db_execute_batch,
            $crate::sys::commands::db_close_pool,
            $crate::sys::commands::db_list_pools,
            $crate::sys::commands::db_get_pool_stats,
            $crate::sys::commands::db_build_select,
            $crate::sys::commands::db_build_insert,
            $crate::sys::commands::db_build_update,
            $crate::sys::commands::db_build_delete,
            $crate::sys::commands::db_mongo_connect,
            $crate::sys::commands::db_mongo_find,
            $crate::sys::commands::db_mongo_find_one,
            $crate::sys::commands::db_mongo_insert_one,
            $crate::sys::commands::db_mongo_insert_many,
            $crate::sys::commands::db_mongo_update_many,
            $crate::sys::commands::db_mongo_delete_many,
            $crate::sys::commands::db_mongo_disconnect,
            $crate::sys::commands::db_redis_connect,
            $crate::sys::commands::db_redis_get,
            $crate::sys::commands::db_redis_set,
            $crate::sys::commands::db_redis_del,
            $crate::sys::commands::db_redis_exists,
            $crate::sys::commands::db_redis_expire,
            $crate::sys::commands::db_redis_hget,
            $crate::sys::commands::db_redis_hset,
            $crate::sys::commands::db_redis_hgetall,
            $crate::sys::commands::db_redis_disconnect,
            // Cache
            $crate::sys::commands::cache_get_stats,
            $crate::sys::commands::cache_clear_all,
            $crate::sys::commands::cache_clear_by_type,
            $crate::sys::commands::cache_clear_by_provider,
            $crate::sys::commands::cache_get_size,
            $crate::sys::commands::cache_configure,
            $crate::sys::commands::cache_warmup,
            $crate::sys::commands::cache_export,
            $crate::sys::commands::cache_get_analytics,
            $crate::sys::commands::cache_prune_expired,
            // Codebase cache
            $crate::sys::commands::codebase_cache_get_stats,
            $crate::sys::commands::codebase_cache_clear_project,
            $crate::sys::commands::codebase_cache_clear_file,
            $crate::sys::commands::codebase_cache_clear_all,
            $crate::sys::commands::codebase_cache_clear_expired,
            $crate::sys::commands::codebase_cache_get_file_tree,
            $crate::sys::commands::codebase_cache_set_file_tree,
            $crate::sys::commands::codebase_cache_get_symbols,
            $crate::sys::commands::codebase_cache_set_symbols,
            $crate::sys::commands::codebase_cache_get_dependencies,
            $crate::sys::commands::codebase_cache_set_dependencies,
            $crate::sys::commands::codebase_cache_calculate_hash,
            // Embeddings
            $crate::sys::commands::generate_code_embeddings,
            $crate::sys::commands::semantic_search_codebase,
            $crate::sys::commands::get_embedding_stats,
            $crate::sys::commands::index_workspace,
            $crate::sys::commands::index_file,
            $crate::sys::commands::get_indexing_progress,
            $crate::sys::commands::on_file_changed,
            $crate::sys::commands::on_file_deleted,
            // Documents
            $crate::sys::commands::document_read,
            $crate::sys::commands::document_extract_text,
            $crate::sys::commands::document_get_metadata,
            $crate::sys::commands::document_search,
            $crate::sys::commands::document_detect_type,
            $crate::sys::commands::document_create_word,
            $crate::sys::commands::document_create_word_simple,
            $crate::sys::commands::document_create_excel,
            $crate::sys::commands::document_create_excel_simple,
            $crate::sys::commands::document_create_excel_numbers,
            $crate::sys::commands::document_create_pdf,
            $crate::sys::commands::document_create_pdf_simple,
            // Analytics
            $crate::sys::commands::analytics_track_event,
            $crate::sys::commands::analytics_flush_events,
            $crate::sys::commands::analytics_get_session_id,
            $crate::sys::commands::analytics_set_user_property,
            $crate::sys::commands::metrics_get_system,
            $crate::sys::commands::metrics_get_app,
            $crate::sys::commands::feature_flag_get,
            $crate::sys::commands::feature_flag_get_all,
            $crate::sys::commands::analytics_delete_all_data,
            $crate::sys::commands::metrics_increment_automations,
            $crate::sys::commands::metrics_increment_goals,
            $crate::sys::commands::metrics_set_mcp_servers,
            $crate::sys::commands::metrics_set_cache_hit_rate,
            $crate::sys::commands::analytics_calculate_roi,
            $crate::sys::commands::analytics_get_process_metrics,
            $crate::sys::commands::analytics_get_user_metrics,
            $crate::sys::commands::analytics_get_tool_metrics,
            $crate::sys::commands::analytics_get_metric_trends,
            $crate::sys::commands::analytics_export_report,
            $crate::sys::commands::analytics_generate_weekly_report,
            $crate::sys::commands::analytics_generate_monthly_report,
            $crate::sys::commands::analytics_get_top_processes,
            $crate::sys::commands::analytics_save_snapshot,
            $crate::sys::commands::analytics_get_usage_stats,
            $crate::sys::commands::analytics_get_feature_usage,
        ]
    };
}

/// Automation commands for browser, terminal, and workflow automation
#[macro_export]
macro_rules! automation_command_handlers {
    () => {
        [
            // Terminal
            $crate::sys::commands::execute_terminal_command,
            $crate::sys::commands::terminal_detect_shells,
            $crate::sys::commands::terminal_create_session,
            $crate::sys::commands::terminal_send_input,
            $crate::sys::commands::terminal_resize,
            $crate::sys::commands::terminal_kill,
            $crate::sys::commands::terminal_list_sessions,
            $crate::sys::commands::terminal_get_history,
            $crate::sys::commands::terminal_ai_suggest_command,
            $crate::sys::commands::terminal_ai_explain_error,
            $crate::sys::commands::terminal_smart_commit,
            $crate::sys::commands::terminal_ai_suggest_improvements,
            // Browser
            $crate::sys::commands::browser_init,
            $crate::sys::commands::browser_check_status,
            $crate::sys::commands::browser_launch,
            $crate::sys::commands::browser_open_tab,
            $crate::sys::commands::browser_close_tab,
            $crate::sys::commands::browser_list_tabs,
            $crate::sys::commands::browser_navigate,
            $crate::sys::commands::browser_go_back,
            $crate::sys::commands::browser_go_forward,
            $crate::sys::commands::browser_reload,
            $crate::sys::commands::browser_get_url,
            $crate::sys::commands::browser_get_title,
            $crate::sys::commands::browser_click,
            $crate::sys::commands::browser_type,
            $crate::sys::commands::browser_get_text,
            $crate::sys::commands::browser_get_attribute,
            $crate::sys::commands::browser_wait_for_selector,
            $crate::sys::commands::browser_select_option,
            $crate::sys::commands::browser_check,
            $crate::sys::commands::browser_uncheck,
            $crate::sys::commands::browser_screenshot,
            $crate::sys::commands::browser_evaluate,
            $crate::sys::commands::browser_hover,
            $crate::sys::commands::browser_focus,
            $crate::sys::commands::browser_query_all,
            $crate::sys::commands::browser_scroll_into_view,
            $crate::sys::commands::browser_execute_async_js,
            $crate::sys::commands::browser_get_element_state,
            $crate::sys::commands::browser_wait_for_interactive,
            $crate::sys::commands::browser_fill_form,
            $crate::sys::commands::browser_drag_and_drop,
            $crate::sys::commands::browser_upload_file,
            $crate::sys::commands::browser_get_cookies,
            $crate::sys::commands::browser_set_cookie,
            $crate::sys::commands::browser_clear_cookies,
            $crate::sys::commands::browser_get_performance_metrics,
            $crate::sys::commands::browser_wait_for_navigation,
            $crate::sys::commands::browser_get_frames,
            $crate::sys::commands::browser_execute_in_frame,
            $crate::sys::commands::browser_call_function,
            $crate::sys::commands::browser_enable_request_interception,
            $crate::sys::commands::browser_get_screenshot_stream,
            $crate::sys::commands::browser_highlight_element,
            $crate::sys::commands::browser_get_dom_snapshot,
            $crate::sys::commands::browser_get_console_logs,
            $crate::sys::commands::browser_get_network_activity,
            // Semantic browser
            $crate::sys::commands::find_element_semantic,
            $crate::sys::commands::find_all_elements_semantic,
            $crate::sys::commands::click_semantic,
            $crate::sys::commands::type_semantic,
            $crate::sys::commands::get_accessibility_tree,
            $crate::sys::commands::test_selector_strategies,
            $crate::sys::commands::get_dom_semantic_graph,
            $crate::sys::commands::get_interactive_elements,
            $crate::sys::commands::find_by_role,
            // Desktop automation
            $crate::sys::commands::automation_list_windows,
            $crate::sys::commands::automation_find_elements,
            $crate::sys::commands::automation_invoke,
            $crate::sys::commands::automation_set_value,
            $crate::sys::commands::automation_get_value,
            $crate::sys::commands::automation_toggle,
            $crate::sys::commands::automation_focus_window,
            $crate::sys::commands::automation_send_keys,
            $crate::sys::commands::automation_hotkey,
            $crate::sys::commands::automation_click,
            $crate::sys::commands::automation_clipboard_get,
            $crate::sys::commands::automation_clipboard_set,
            $crate::sys::commands::automation_record_start,
            $crate::sys::commands::automation_record_stop,
            $crate::sys::commands::automation_record_action_click,
            $crate::sys::commands::automation_record_action_type,
            $crate::sys::commands::automation_record_action_screenshot,
            $crate::sys::commands::automation_record_action_wait,
            $crate::sys::commands::automation_record_is_recording,
            $crate::sys::commands::automation_save_script,
            $crate::sys::commands::automation_load_script,
            $crate::sys::commands::automation_list_scripts,
            $crate::sys::commands::automation_delete_script,
            $crate::sys::commands::automation_execute_script,
            $crate::sys::commands::automation_record_get_session,
            $crate::sys::commands::automation_inspect_element_at_point,
            $crate::sys::commands::automation_inspect_element_by_id,
            $crate::sys::commands::automation_find_element_by_selector,
            $crate::sys::commands::automation_generate_selector,
            $crate::sys::commands::automation_get_element_tree,
            $crate::sys::commands::automation_save_recording_as_script,
            $crate::sys::commands::automation_generate_code,
            $crate::sys::commands::overlay_emit_click,
            $crate::sys::commands::overlay_emit_type,
            $crate::sys::commands::overlay_emit_region,
            $crate::sys::commands::overlay_replay_recent,
            $crate::sys::commands::automation_drag_drop,
            $crate::sys::commands::automation_ocr,
            $crate::sys::commands::automation_type,
            $crate::sys::commands::automation_screenshot,
            // Workflows
            $crate::sys::commands::create_workflow,
            $crate::sys::commands::update_workflow,
            $crate::sys::commands::delete_workflow,
            $crate::sys::commands::get_workflow,
            $crate::sys::commands::get_user_workflows,
            $crate::sys::commands::execute_workflow,
            $crate::sys::commands::pause_workflow,
            $crate::sys::commands::resume_workflow,
            $crate::sys::commands::cancel_workflow,
            $crate::sys::commands::get_workflow_status,
            $crate::sys::commands::get_execution_logs,
            $crate::sys::commands::schedule_workflow,
            $crate::sys::commands::trigger_workflow_on_event,
            $crate::sys::commands::get_next_execution_time,
            // Tasks
            $crate::sys::commands::task_create,
            $crate::sys::commands::task_get_status,
            $crate::sys::commands::task_update_progress,
            $crate::sys::commands::task_pause,
            $crate::sys::commands::task_resume,
            $crate::sys::commands::task_cancel,
            $crate::sys::commands::task_list,
            $crate::sys::commands::task_list_by_status,
            $crate::sys::commands::task_complete,
            $crate::sys::commands::task_save_context,
            $crate::sys::commands::task_get_resumable,
            $crate::sys::commands::coord_update_app_state,
            $crate::sys::commands::coord_request_approval,
            $crate::sys::commands::coord_get_pending_approvals,
            // Background tasks
            $crate::sys::commands::cancel_background_task,
            $crate::sys::commands::pause_background_task,
            $crate::sys::commands::resume_background_task,
            $crate::sys::commands::list_background_tasks,
            $crate::sys::commands::bg_submit_task,
            $crate::sys::commands::bg_cancel_task,
            $crate::sys::commands::bg_pause_task,
            $crate::sys::commands::bg_resume_task,
            $crate::sys::commands::bg_get_task_status,
            $crate::sys::commands::bg_list_tasks,
            $crate::sys::commands::bg_get_task_stats,
            // Computer use
            $crate::sys::commands::computer_use_start_session,
            $crate::sys::commands::computer_use_capture_screen,
            $crate::sys::commands::computer_use_click,
            $crate::sys::commands::computer_use_move_mouse,
            $crate::sys::commands::computer_use_type_text,
            $crate::sys::commands::computer_use_get_session,
            $crate::sys::commands::computer_use_list_sessions,
            $crate::sys::commands::computer_use_execute_tool,
            // Code editing
            $crate::sys::commands::code_generate_edit,
            $crate::sys::commands::code_apply_edit,
            $crate::sys::commands::code_reject_edit,
            $crate::sys::commands::code_list_pending_edits,
            $crate::sys::commands::composer_start_session,
            $crate::sys::commands::composer_apply_session,
            $crate::sys::commands::composer_get_session,
            $crate::sys::commands::get_file_diff,
            $crate::sys::commands::apply_changes,
            $crate::sys::commands::revert_changes,
            // Capture
            $crate::sys::commands::capture_screen_full,
            $crate::sys::commands::capture_screen_region,
            $crate::sys::commands::capture_get_windows,
            $crate::sys::commands::capture_get_history,
            $crate::sys::commands::capture_delete,
            $crate::sys::commands::capture_save_to_clipboard,
            $crate::sys::commands::capture::capture_screen_window,
            $crate::sys::commands::capture::capture_from_clipboard,
            // OCR
            $crate::sys::commands::ocr_process_image,
            $crate::sys::commands::ocr_process_region,
            $crate::sys::commands::ocr_get_languages,
            $crate::sys::commands::ocr_get_result,
            $crate::sys::commands::ocr_process_with_boxes,
            $crate::sys::commands::ocr_detect_languages,
            $crate::sys::commands::ocr_process_multi_language,
            $crate::sys::commands::ocr_preprocess_image,
        ]
    };
}

/// Integration commands for third-party services
#[macro_export]
macro_rules! integration_command_handlers {
    () => {
        [
            // Cloud
            $crate::sys::commands::cloud_connect,
            $crate::sys::commands::cloud_complete_oauth,
            $crate::sys::commands::cloud_disconnect,
            $crate::sys::commands::cloud_list_accounts,
            $crate::sys::commands::cloud_list,
            $crate::sys::commands::cloud_upload,
            $crate::sys::commands::cloud_download,
            $crate::sys::commands::cloud_delete,
            $crate::sys::commands::cloud_create_folder,
            $crate::sys::commands::cloud_share,
            // Email
            $crate::sys::commands::email_connect,
            $crate::sys::commands::email_list_accounts,
            $crate::sys::commands::email_remove_account,
            $crate::sys::commands::email_list_folders,
            $crate::sys::commands::email_fetch_inbox,
            $crate::sys::commands::email_mark_read,
            $crate::sys::commands::email_delete,
            $crate::sys::commands::email_download_attachment,
            $crate::sys::commands::email_send,
            $crate::sys::commands::contact_create,
            $crate::sys::commands::contact_get,
            $crate::sys::commands::contact_list,
            $crate::sys::commands::contact_search,
            $crate::sys::commands::contact_update,
            $crate::sys::commands::contact_delete,
            $crate::sys::commands::contact_import_vcard,
            $crate::sys::commands::contact_export_vcard,
            // Email Keyring Migration
            $crate::sys::commands::email_check_keyring_status,
            $crate::sys::commands::email_migrate_credentials,
            // Gmail OAuth
            $crate::sys::commands::gmail_oauth_start,
            $crate::sys::commands::gmail_oauth_complete,
            $crate::sys::commands::gmail_oauth_refresh,
            $crate::sys::commands::gmail_oauth_list_accounts,
            $crate::sys::commands::gmail_oauth_disconnect,
            $crate::sys::commands::gmail_oauth_get_account,
            // Calendar
            $crate::sys::commands::calendar_connect,
            $crate::sys::commands::calendar_complete_oauth,
            $crate::sys::commands::calendar_disconnect,
            $crate::sys::commands::calendar_list_accounts,
            $crate::sys::commands::calendar_list_calendars,
            $crate::sys::commands::calendar_list_events,
            $crate::sys::commands::calendar_create_event,
            $crate::sys::commands::calendar_update_event,
            $crate::sys::commands::calendar_delete_event,
            $crate::sys::commands::calendar_get_system_timezone,
            // Productivity
            $crate::sys::commands::productivity_connect,
            $crate::sys::commands::productivity_list_tasks,
            $crate::sys::commands::productivity_create_task,
            $crate::sys::commands::productivity_notion_list_pages,
            $crate::sys::commands::productivity_notion_query_database,
            $crate::sys::commands::productivity_notion_create_database_row,
            $crate::sys::commands::productivity_trello_list_boards,
            $crate::sys::commands::productivity_trello_list_cards,
            $crate::sys::commands::productivity_trello_create_card,
            $crate::sys::commands::productivity_trello_move_card,
            $crate::sys::commands::productivity_trello_add_comment,
            $crate::sys::commands::productivity_asana_list_projects,
            $crate::sys::commands::productivity_asana_list_project_tasks,
            $crate::sys::commands::productivity_asana_create_task,
            $crate::sys::commands::productivity_asana_assign_task,
            $crate::sys::commands::productivity_asana_mark_complete,
            // Git
            $crate::sys::commands::git_init,
            $crate::sys::commands::git_status,
            $crate::sys::commands::git_add,
            $crate::sys::commands::git_commit,
            $crate::sys::commands::git_push,
            $crate::sys::commands::git_pull,
            $crate::sys::commands::git_create_branch,
            $crate::sys::commands::git_checkout,
            $crate::sys::commands::git_checkout_new_branch,
            $crate::sys::commands::git_list_branches,
            $crate::sys::commands::git_delete_branch,
            $crate::sys::commands::git_merge,
            $crate::sys::commands::git_log,
            $crate::sys::commands::git_diff,
            $crate::sys::commands::git_clone,
            $crate::sys::commands::git_fetch,
            $crate::sys::commands::git_stash,
            $crate::sys::commands::git_stash_pop,
            $crate::sys::commands::git_reset,
            $crate::sys::commands::git_list_remotes,
            $crate::sys::commands::git_add_remote,
            // GitHub
            $crate::sys::commands::github_clone_repo,
            $crate::sys::commands::github_get_repo_context,
            $crate::sys::commands::github_search_files,
            $crate::sys::commands::github_read_file,
            $crate::sys::commands::github_get_file_tree,
            $crate::sys::commands::github_list_repos,
            // Design
            $crate::sys::commands::design_generate_css,
            $crate::sys::commands::design_apply_css,
            $crate::sys::commands::design_get_element_styles,
            $crate::sys::commands::design_generate_color_scheme,
            $crate::sys::commands::design_suggest_improvements,
            $crate::sys::commands::design_tokens_to_css,
            $crate::sys::commands::design_check_accessibility,
            // Media
            $crate::sys::commands::media_generate_image,
            $crate::sys::commands::media_generate_video,
            $crate::sys::commands::media_get_history,
            // MCP
            $crate::sys::commands::mcp_initialize,
            $crate::sys::commands::mcp_list_servers,
            $crate::sys::commands::mcp_get_registry,
            $crate::sys::commands::mcp_connect_server,
            $crate::sys::commands::mcp_disconnect_server,
            $crate::sys::commands::mcp_list_tools,
            $crate::sys::commands::mcp_search_tools,
            $crate::sys::commands::mcp_call_tool,
            $crate::sys::commands::mcp_get_config,
            $crate::sys::commands::mcp_update_config,
            $crate::sys::commands::mcp_enable_server,
            $crate::sys::commands::mcp_disable_server,
            $crate::sys::commands::mcp_get_stats,
            $crate::sys::commands::mcp_get_server_logs,
            $crate::sys::commands::mcp_store_credential,
            $crate::sys::commands::mcp_get_tool_schemas,
            $crate::sys::commands::mcp_get_health,
            $crate::sys::commands::mcp_check_server_health,
            $crate::sys::commands::mcp_set_credential,
            $crate::sys::commands::mcp_delete_credential,
            // MCP OAuth
            $crate::sys::commands::mcp_oauth_start,
            $crate::sys::commands::mcp_oauth_callback,
            $crate::sys::commands::mcp_oauth_status,
            $crate::sys::commands::mcp_oauth_disconnect,
            $crate::sys::commands::mcp_oauth_refresh,
            $crate::sys::commands::mcp_oauth_set_credentials,
            // MCPB (MCP Bundles)
            $crate::sys::commands::mcpb_fetch_registry,
            $crate::sys::commands::mcpb_search_bundles,
            $crate::sys::commands::mcpb_get_bundle_details,
            $crate::sys::commands::mcpb_install_bundle,
            $crate::sys::commands::mcpb_uninstall_bundle,
            $crate::sys::commands::mcpb_get_installed_bundles,
            $crate::sys::commands::mcpb_check_updates,
            $crate::sys::commands::mcpb_update_bundle,
            $crate::sys::commands::mcpb_get_categories,
            $crate::sys::commands::mcpb_get_featured,
            // API
            $crate::sys::commands::api_request,
            $crate::sys::commands::api_get,
            $crate::sys::commands::api_post_json,
            $crate::sys::commands::api_put_json,
            $crate::sys::commands::api_delete,
            $crate::sys::commands::api_parse_response,
            $crate::sys::commands::api_extract_json_path,
            $crate::sys::commands::api_oauth_create_client,
            $crate::sys::commands::api_oauth_get_auth_url,
            $crate::sys::commands::api_oauth_exchange_code,
            $crate::sys::commands::api_oauth_refresh_token,
            $crate::sys::commands::api_oauth_client_credentials,
            $crate::sys::commands::api_render_template,
            $crate::sys::commands::api_extract_template_variables,
            $crate::sys::commands::api_validate_template,
            // Ollama
            $crate::sys::commands::ollama_check_status,
            $crate::sys::commands::ollama_list_models,
            $crate::sys::commands::ollama_get_model_info,
            $crate::sys::commands::ollama_pull_model,
            $crate::sys::commands::ollama_delete_model,
            // Native Messaging
            $crate::sys::commands::native_messaging_check_status,
            $crate::sys::commands::native_messaging_install,
            $crate::sys::commands::native_messaging_uninstall,
            $crate::sys::commands::native_messaging_set_extension_id,
            $crate::sys::commands::native_messaging_get_connection_state,
            // Workspace indexing
            $crate::sys::commands::workspace_index,
            $crate::sys::commands::workspace_search_symbols,
            $crate::sys::commands::workspace_find_definition,
            $crate::sys::commands::workspace_find_references,
            $crate::sys::commands::workspace_get_dependencies,
            $crate::sys::commands::workspace_get_file_symbols,
            $crate::sys::commands::workspace_get_stats,
            // LSP
            $crate::sys::commands::lsp_start_server,
            $crate::sys::commands::lsp_stop_server,
            $crate::sys::commands::lsp_did_open,
            $crate::sys::commands::lsp_did_change,
            $crate::sys::commands::lsp_did_close,
            $crate::sys::commands::lsp_completion,
            $crate::sys::commands::lsp_hover,
            $crate::sys::commands::lsp_definition,
            $crate::sys::commands::lsp_references,
            $crate::sys::commands::lsp_rename,
            $crate::sys::commands::lsp_formatting,
            $crate::sys::commands::lsp_workspace_symbol,
            $crate::sys::commands::lsp_code_action,
            $crate::sys::commands::lsp_get_diagnostics,
            $crate::sys::commands::lsp_get_all_diagnostics,
            $crate::sys::commands::lsp_list_servers,
            $crate::sys::commands::lsp_detect_language,
            // Migration
            $crate::sys::commands::migration_test_lovable_connection,
            $crate::sys::commands::migration_list_lovable_workflows,
            $crate::sys::commands::migration_launch_lovable,
            // Messaging
            $crate::sys::commands::messaging::connect_slack,
            $crate::sys::commands::messaging::connect_whatsapp,
            $crate::sys::commands::messaging::connect_teams,
            $crate::sys::commands::messaging::get_messaging_history,
            $crate::sys::commands::messaging::disconnect_platform,
            $crate::sys::commands::messaging::list_messaging_connections,
            $crate::sys::commands::messaging::send_message,
            // Realtime
            $crate::sys::commands::realtime::connect_websocket,
            $crate::sys::commands::realtime::get_team_presence,
            $crate::sys::commands::realtime::get_user_presence,
            $crate::sys::commands::realtime::set_user_online,
            $crate::sys::commands::realtime::set_user_offline,
            $crate::sys::commands::realtime::update_user_activity,
            // Account
            $crate::sys::account::device_link_initiate,
            $crate::sys::account::device_link_poll,
            $crate::sys::account::fetch_user_profile,
            $crate::sys::account::oauth_refresh,
            $crate::sys::account::fetch_credit_balance,
            $crate::sys::account::report_llm_usage,
            $crate::sys::account::account_store_api_base_url,
            $crate::sys::account::account_store_access_token,
            $crate::sys::account::account_store_refresh_token,
            $crate::sys::account::account_clear_tokens,
            // Billing
            $crate::sys::billing::billing_initialize,
            $crate::sys::billing::stripe_create_customer,
            $crate::sys::billing::stripe_get_customer_by_email,
            $crate::sys::billing::stripe_create_subscription,
            $crate::sys::billing::stripe_get_subscription,
            $crate::sys::billing::stripe_update_subscription,
            $crate::sys::billing::stripe_cancel_subscription,
            $crate::sys::billing::stripe_get_invoices,
            $crate::sys::billing::stripe_get_usage,
            $crate::sys::billing::stripe_track_usage,
            $crate::sys::billing::stripe_create_portal_session,
            $crate::sys::billing::stripe_get_active_subscription,
            $crate::sys::billing::stripe_process_webhook,
            $crate::sys::billing::stripe_get_payment_methods,
            $crate::sys::billing::stripe_create_setup_intent,
            $crate::sys::billing::stripe_attach_payment_method,
            $crate::sys::billing::stripe_set_default_payment_method,
            $crate::sys::billing::stripe_delete_payment_method,
            $crate::sys::billing::send_invoice_email,
            $crate::sys::commands::subscribe_to_plan,
            $crate::sys::commands::upgrade_plan,
            $crate::sys::commands::cancel_subscription,
            $crate::sys::commands::get_pricing_plans,
            $crate::sys::commands::get_current_plan,
            // Teams
            $crate::sys::commands::create_team,
            $crate::sys::commands::get_team,
            $crate::sys::commands::update_team,
            $crate::sys::commands::delete_team,
            $crate::sys::commands::get_user_teams,
            $crate::sys::commands::invite_member,
            $crate::sys::commands::accept_invitation,
            $crate::sys::commands::remove_member,
            $crate::sys::commands::update_member_role,
            $crate::sys::commands::get_team_members,
            $crate::sys::commands::get_team_invitations,
            $crate::sys::commands::share_resource,
            $crate::sys::commands::unshare_resource,
            $crate::sys::commands::get_team_resources,
            $crate::sys::commands::get_team_resources_by_type,
            $crate::sys::commands::get_team_activity,
            $crate::sys::commands::get_user_team_activity,
            $crate::sys::commands::get_team_billing,
            $crate::sys::commands::initialize_team_billing,
            $crate::sys::commands::update_team_plan,
            $crate::sys::commands::add_team_seats,
            $crate::sys::commands::remove_team_seats,
            $crate::sys::commands::calculate_team_cost,
            $crate::sys::commands::update_team_usage,
            $crate::sys::commands::transfer_team_ownership,
            // Projects
            $crate::sys::commands::project_create,
            $crate::sys::commands::project_list,
            $crate::sys::commands::project_get,
            $crate::sys::commands::project_update,
            $crate::sys::commands::project_delete,
            $crate::sys::commands::project_get_settings,
            $crate::sys::commands::project_update_settings,
            // Marketplace
            $crate::sys::commands::publish_workflow_to_marketplace,
            $crate::sys::commands::unpublish_workflow,
            $crate::sys::commands::get_featured_workflows,
            $crate::sys::commands::get_trending_workflows,
            $crate::sys::commands::search_marketplace_workflows,
            $crate::sys::commands::get_workflow_by_share_url,
            $crate::sys::commands::get_creator_workflows,
            $crate::sys::commands::get_my_published_workflows,
            $crate::sys::commands::get_workflows_by_category,
            $crate::sys::commands::get_category_counts,
            $crate::sys::commands::get_popular_tags,
            $crate::sys::commands::clone_marketplace_workflow,
            $crate::sys::commands::fork_marketplace_workflow,
            $crate::sys::commands::rate_workflow,
            $crate::sys::commands::get_user_workflow_rating,
            $crate::sys::commands::comment_on_workflow,
            $crate::sys::commands::get_workflow_comments,
            $crate::sys::commands::delete_workflow_comment,
            $crate::sys::commands::favorite_workflow,
            $crate::sys::commands::unfavorite_workflow,
            $crate::sys::commands::is_workflow_favorited,
            $crate::sys::commands::get_user_favorites,
            $crate::sys::commands::get_user_clones,
            $crate::sys::commands::share_workflow,
            $crate::sys::commands::get_workflow_stats,
            $crate::sys::commands::get_workflow_templates,
            $crate::sys::commands::get_workflow_templates_by_category,
            $crate::sys::commands::search_workflow_templates,
            // Process reasoning
            $crate::sys::commands::get_process_templates,
            $crate::sys::commands::get_outcome_tracking,
            $crate::sys::commands::get_process_success_rates,
            $crate::sys::commands::get_best_practices,
            $crate::sys::commands::get_process_statistics,
            // Templates
            $crate::sys::commands::get_all_templates,
            $crate::sys::commands::get_template_by_id,
            $crate::sys::commands::get_templates_by_category,
            $crate::sys::commands::install_template,
            $crate::sys::commands::get_installed_templates,
            $crate::sys::commands::search_templates,
            $crate::sys::commands::execute_template,
            $crate::sys::commands::uninstall_template,
            $crate::sys::commands::get_template_categories,
            // Realtime metrics
            $crate::sys::commands::get_realtime_stats,
            $crate::sys::commands::record_automation_metrics,
            $crate::sys::commands::get_metrics_history,
            $crate::sys::commands::compare_to_manual,
            $crate::sys::commands::compare_to_previous_period,
            $crate::sys::commands::compare_to_industry_benchmark,
            $crate::sys::commands::get_milestones,
            $crate::sys::commands::share_milestone,
            $crate::sys::commands::track_workflow_view,
            $crate::sys::commands::acknowledge_milestone,
            // Hooks
            $crate::sys::commands::hooks_initialize,
            $crate::sys::commands::hooks_list,
            $crate::sys::commands::hooks_add,
            $crate::sys::commands::hooks_remove,
            $crate::sys::commands::hooks_toggle,
            $crate::sys::commands::hooks_update,
            $crate::sys::commands::hooks_get_config_path,
            $crate::sys::commands::hooks_create_example,
            $crate::sys::commands::hooks_export,
            $crate::sys::commands::hooks_import,
            $crate::sys::commands::hooks_reload,
            $crate::sys::commands::hooks_get_event_types,
            $crate::sys::commands::hooks_get_stats,
            // Governance
            $crate::sys::commands::governance::get_audit_events,
            $crate::sys::commands::governance::verify_audit_event,
            $crate::sys::commands::governance::verify_audit_integrity,
            $crate::sys::commands::governance::log_tool_execution,
            $crate::sys::commands::governance::log_workflow_execution,
            $crate::sys::commands::governance::create_approval_request,
            $crate::sys::commands::governance::get_pending_approvals,
            $crate::sys::commands::governance::get_approval_request,
            $crate::sys::commands::governance::approve_request,
            $crate::sys::commands::governance::reject_request,
            $crate::sys::commands::governance::requires_approval,
            $crate::sys::commands::governance::calculate_risk_level,
            $crate::sys::commands::governance::get_approval_statistics,
            $crate::sys::commands::governance::expire_timed_out_requests,
            // Tutorials
            $crate::sys::commands::tutorials::get_user_credits,
        ]
    };
}

/// Helper to get all command handlers
///
/// This can be used for reference but the actual registration must use
/// the individual macros due to how `generate_handler!` works
pub fn list_command_categories() -> Vec<&'static str> {
    vec![
        "sys_commands",
        "core_commands",
        "data_commands",
        "automation_commands",
        "integration_commands",
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_command_categories() {
        let categories = list_command_categories();
        assert_eq!(categories.len(), 5);
        assert!(categories.contains(&"sys_commands"));
        assert!(categories.contains(&"core_commands"));
        assert!(categories.contains(&"data_commands"));
        assert!(categories.contains(&"automation_commands"));
        assert!(categories.contains(&"integration_commands"));
    }
}
