//! Stream observation events and the assembled per-turn outcome.
//!
//! The dialect runners in [`crate::stream`] emit a [`StreamEvent`] at every
//! point where the legacy CLI implementation mutated its accumulation state,
//! then return the authoritative [`ChatOutcome`]. Consumers that only render
//! deltas (the CLI facade) listen for `TextDelta`; richer consumers (desktop
//! IPC bridging, stage c2+) can mirror the full event stream.

use serde::{Deserialize, Serialize};

use crate::wire::ToolCall;

/// Token usage for a single streamed completion.
///
/// Field semantics follow the CLI's historical accumulation rules per dialect
/// (e.g. Anthropic cache counters take the max across `message_start` /
/// `message_delta`; `reasoning_output_tokens` is a character-count estimate
/// until the provider reports a real value).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Usage {
    pub input_tokens: u32,
    pub output_tokens: u32,
    /// Tokens read from prompt cache (Anthropic only). 0 when no cache hit or
    /// the provider doesn't support caching.
    pub cache_read_input_tokens: u32,
    /// Tokens written to prompt cache (Anthropic only).
    pub cache_creation_input_tokens: u32,
    /// Tokens generated by the model's internal reasoning pass. 0 for
    /// non-reasoning models or when the provider does not report this field.
    pub reasoning_output_tokens: u32,
}

/// One observation from a provider stream.
///
/// Serialized form (used by the conformance fixtures) is tagged with `type`:
/// `{"type":"text_delta","text":"…"}`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum StreamEvent {
    /// User-visible assistant text.
    TextDelta { text: String },
    /// Extended-thinking / chain-of-thought text. Never merged into the
    /// user-visible answer.
    ReasoningDelta { text: String },
    /// A tool call started (or was first observed) at `index`. `id`/`name`
    /// carry whatever the wire delivered at that point and may be empty for
    /// pathological streams; [`crate::ToolCallAssembler`] output is
    /// authoritative.
    ToolCallStart { index: usize, id: String, name: String },
    /// A fragment of the JSON arguments for the call at `index`.
    ToolCallArgsDelta { index: usize, fragment: String },
    /// Usage snapshot as of this point in the stream (cumulative, not delta).
    Usage { usage: Usage },
    /// SSE comment line or provider ping — connection is alive, no payload.
    Keepalive,
    /// Provider-specific event this crate does not interpret (e.g. Anthropic
    /// `message_stop`, managed-cloud billing frames). `event` is the vendor's
    /// event/type label; `data` is the raw JSON payload.
    Vendor { event: String, data: serde_json::Value },
    /// Stream finished. Carries the final stop reason, if any was reported.
    End { stop_reason: Option<String> },
}

/// The assembled result of one streamed completion.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ChatOutcome {
    /// Concatenated user-visible text (exactly the `TextDelta` payloads).
    pub text: String,
    /// Fully-assembled tool calls in provider order.
    pub tool_calls: Vec<ToolCall>,
    pub usage: Usage,
    /// The reason the model stopped generating (e.g. "end_turn", "tool_use",
    /// "stop", "tool_calls").
    pub stop_reason: Option<String>,
}
