export type VideoTranscript =
  | { status: 'ok'; text: string; languageCode: string; autoGenerated: boolean }
  | { status: 'none' }
  | { status: 'error'; message: string };

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  autoGenerated: boolean;
}

interface WatchPageData {
  playerResponse: unknown;
  initialData: unknown;
  config: unknown;
}

const REQUEST_TIMEOUT_MS = 15_000;
const MAX_WATCH_PAGE_CHARS = 8_000_000;
const PLAYER_RESPONSE_MARKER = 'ytInitialPlayerResponse = ';
const INITIAL_DATA_MARKER = 'ytInitialData = ';
const CONFIG_MARKER = 'ytcfg.set({';

function record(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function path(value: unknown, keys: readonly (string | number)[]): unknown {
  let current = value;
  for (const key of keys) {
    if (typeof key === 'number') {
      if (!Array.isArray(current)) return undefined;
      current = current[key];
    } else {
      current = record(current)?.[key];
    }
  }
  return current;
}

export function youtubeVideoId(url: string): string | null {
  try {
    const parsed = new URL(url);
    const id = parsed.searchParams.get('v');
    return id && /^[A-Za-z0-9_-]{6,20}$/.test(id) ? id : null;
  } catch {
    return null;
  }
}

function objectEnd(source: string, start: number): number {
  let depth = 0;
  let inString = false;
  for (let index = start; index < source.length; index += 1) {
    const char = source[index];
    if (inString) {
      if (char === '\\') index += 1;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === '{') depth += 1;
    else if (char === '}') {
      depth -= 1;
      if (depth === 0) return index + 1;
    }
  }
  return -1;
}

export function jsonAfterMarker(source: string, marker: string, from = 0): unknown {
  const at = source.indexOf(marker, from);
  if (at < 0) return undefined;
  let start = at + marker.length - (marker.endsWith('{') ? 1 : 0);
  while (source[start] === ' ') start += 1;
  if (source[start] !== '{') return undefined;
  const end = objectEnd(source, start);
  if (end < 0) return undefined;
  try {
    return JSON.parse(source.slice(start, end));
  } catch {
    return undefined;
  }
}

function innertubeConfig(source: string): unknown {
  for (
    let at = source.indexOf(CONFIG_MARKER);
    at >= 0;
    at = source.indexOf(CONFIG_MARKER, at + 1)
  ) {
    const config = jsonAfterMarker(source, CONFIG_MARKER, at);
    if (record(config)?.['INNERTUBE_API_KEY']) return config;
  }
  return undefined;
}

function watchPageData(source: string): WatchPageData {
  return {
    playerResponse: jsonAfterMarker(source, PLAYER_RESPONSE_MARKER),
    initialData: jsonAfterMarker(source, INITIAL_DATA_MARKER),
    config: innertubeConfig(source),
  };
}

function inlineScripts(): string {
  return Array.from(document.scripts, (script) => (script.src ? '' : (script.textContent ?? '')))
    .filter(
      (text) =>
        text.includes(PLAYER_RESPONSE_MARKER) ||
        text.includes(INITIAL_DATA_MARKER) ||
        text.includes(CONFIG_MARKER),
    )
    .join('\n');
}

async function fetchText(url: string, init: RequestInit = {}): Promise<string> {
  const response = await fetch(url, {
    credentials: 'same-origin',
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
    ...init,
  });
  if (!response.ok) throw new Error(`YouTube answered HTTP ${response.status}.`);
  const text = await response.text();
  if (text.length > MAX_WATCH_PAGE_CHARS)
    throw new Error('The YouTube page was too large to read.');
  return text;
}

async function loadWatchPage(videoId: string): Promise<WatchPageData> {
  const inline = watchPageData(inlineScripts());
  if (path(inline.playerResponse, ['videoDetails', 'videoId']) === videoId) return inline;
  return watchPageData(await fetchText(`/watch?v=${encodeURIComponent(videoId)}`));
}

export function captionTracks(playerResponse: unknown): {
  tracks: CaptionTrack[];
  defaultIndex: number | null;
} {
  const renderer = path(playerResponse, ['captions', 'playerCaptionsTracklistRenderer']);
  const rawTracks = path(renderer, ['captionTracks']);
  const tracks = (Array.isArray(rawTracks) ? rawTracks : []).flatMap((raw): CaptionTrack[] => {
    const track = record(raw);
    const baseUrl = track?.['baseUrl'];
    const languageCode = track?.['languageCode'];
    if (typeof baseUrl !== 'string' || typeof languageCode !== 'string') return [];
    return [{ baseUrl, languageCode, autoGenerated: track?.['kind'] === 'asr' }];
  });
  const audioIndex = path(renderer, ['defaultAudioTrackIndex']);
  const defaultIndex = path(renderer, [
    'audioTracks',
    typeof audioIndex === 'number' ? audioIndex : 0,
    'defaultCaptionTrackIndex',
  ]);
  return {
    tracks,
    defaultIndex:
      typeof defaultIndex === 'number' && tracks[defaultIndex] !== undefined ? defaultIndex : null,
  };
}

export function chooseCaptionTrack(
  tracks: readonly CaptionTrack[],
  defaultIndex: number | null,
): CaptionTrack | null {
  const spokenLanguage = tracks.find((track) => track.autoGenerated)?.languageCode;
  const defaultTrack = defaultIndex === null ? undefined : tracks[defaultIndex];
  return (
    tracks.find((track) => !track.autoGenerated && track.languageCode === spokenLanguage) ??
    (defaultTrack && !defaultTrack.autoGenerated ? defaultTrack : undefined) ??
    tracks.find((track) => track.autoGenerated) ??
    defaultTrack ??
    tracks[0] ??
    null
  );
}

function timestamp(milliseconds: number): string {
  const totalSeconds = Math.max(0, Math.floor(milliseconds / 1_000));
  const hours = Math.floor(totalSeconds / 3_600);
  const minutes = Math.floor((totalSeconds % 3_600) / 60);
  const seconds = String(totalSeconds % 60).padStart(2, '0');
  return hours > 0
    ? `${hours}:${String(minutes).padStart(2, '0')}:${seconds}`
    : `${minutes}:${seconds}`;
}

function transcriptLine(startMs: number, text: string): string | null {
  const cleaned = text.replace(/\s+/g, ' ').trim();
  return cleaned ? `[${timestamp(startMs)}] ${cleaned}` : null;
}

export function timedTextTranscript(body: unknown): string {
  const events = path(body, ['events']);
  return (Array.isArray(events) ? events : [])
    .flatMap((event) => {
      const segments = path(event, ['segs']);
      const start = path(event, ['tStartMs']);
      if (!Array.isArray(segments) || typeof start !== 'number') return [];
      const text = segments
        .map((segment) => path(segment, ['utf8']))
        .filter((value): value is string => typeof value === 'string')
        .join('');
      const line = transcriptLine(start, text);
      return line ? [line] : [];
    })
    .join('\n');
}

export function panelTranscript(body: unknown): string {
  const segments = path(body, [
    'actions',
    0,
    'updateEngagementPanelAction',
    'content',
    'transcriptRenderer',
    'content',
    'transcriptSearchPanelRenderer',
    'body',
    'transcriptSegmentListRenderer',
    'initialSegments',
  ]);
  return (Array.isArray(segments) ? segments : [])
    .flatMap((segment) => {
      const renderer = path(segment, ['transcriptSegmentRenderer']);
      const start = Number(path(renderer, ['startMs']));
      const runs = path(renderer, ['snippet', 'runs']);
      if (!Number.isFinite(start) || !Array.isArray(runs)) return [];
      const text = runs
        .map((run) => path(run, ['text']))
        .filter((value): value is string => typeof value === 'string')
        .join('');
      const line = transcriptLine(start, text);
      return line ? [line] : [];
    })
    .join('\n');
}

function transcriptPanelParams(initialData: unknown): string | null {
  const panels = path(initialData, ['engagementPanels']);
  for (const panel of Array.isArray(panels) ? panels : []) {
    const params = path(panel, [
      'engagementPanelSectionListRenderer',
      'content',
      'continuationItemRenderer',
      'continuationEndpoint',
      'getTranscriptEndpoint',
      'params',
    ]);
    if (typeof params === 'string' && params) return params;
  }
  return null;
}

async function readTimedText(track: CaptionTrack): Promise<string> {
  const url = new URL(track.baseUrl, window.location.origin);
  if (url.origin !== window.location.origin) return '';
  url.searchParams.set('fmt', 'json3');
  const body = await fetchText(url.toString());
  if (!body.trim()) return '';
  try {
    return timedTextTranscript(JSON.parse(body));
  } catch {
    return '';
  }
}

async function readTranscriptPanel(data: WatchPageData): Promise<string> {
  const params = transcriptPanelParams(data.initialData);
  const apiKey = path(data.config, ['INNERTUBE_API_KEY']);
  const context = path(data.config, ['INNERTUBE_CONTEXT']);
  if (!params || typeof apiKey !== 'string' || !record(context)) return '';
  const body = await fetchText(
    `/youtubei/v1/get_transcript?key=${encodeURIComponent(apiKey)}&prettyPrint=false`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ context, params }),
    },
  );
  try {
    return panelTranscript(JSON.parse(body));
  } catch {
    return '';
  }
}

export async function readYouTubeTranscript(pageUrl: string): Promise<VideoTranscript> {
  const videoId = youtubeVideoId(pageUrl);
  if (!videoId) return { status: 'none' };
  try {
    const data = await loadWatchPage(videoId);
    const { tracks, defaultIndex } = captionTracks(data.playerResponse);
    const track = chooseCaptionTrack(tracks, defaultIndex);
    if (!track) return { status: 'none' };
    const text = (await readTimedText(track).catch(() => '')) || (await readTranscriptPanel(data));
    return text
      ? {
          status: 'ok',
          text,
          languageCode: track.languageCode,
          autoGenerated: track.autoGenerated,
        }
      : { status: 'error', message: 'YouTube did not return the captions for this video.' };
  } catch (error) {
    return {
      status: 'error',
      message: error instanceof Error ? error.message : 'The captions could not be read.',
    };
  }
}
