
import * as vscode from 'vscode';
import { MODEL_COST_RATES } from '../features/model-picker/modelConstants';
import { isAutoRoutingModel } from '../integrations/routingTask';

export class TokenCounter implements vscode.Disposable {
  private _promptTokens = 0;
  private _completionTokens = 0;
  private _requestCount = 0;
  private _unpricedRequestCount = 0;
  private _estimatedCostUsd = 0;
  private readonly _statusBarItem: vscode.StatusBarItem;

  constructor() {
    this._statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 80);
    this._statusBarItem.command = 'agi-workforce.showTokenBreakdown';
    this._updateDisplay();
  }

  get totalTokens(): number {
    return this._promptTokens + this._completionTokens;
  }

  get promptTokens(): number {
    return this._promptTokens;
  }

  get completionTokens(): number {
    return this._completionTokens;
  }

  get requestCount(): number {
    return this._requestCount;
  }

  get unpricedRequestCount(): number {
    return this._unpricedRequestCount;
  }

  get estimatedCostUsd(): number {
    return this._estimatedCostUsd;
  }

  addMeasuredUsage(model: string, promptTokens: number, completionTokens: number): void {
    this._promptTokens += promptTokens;
    this._completionTokens += completionTokens;
    this._requestCount += 1;

    const rates = isAutoRoutingModel(model) ? undefined : MODEL_COST_RATES[model];
    if (rates === undefined) {
      this._unpricedRequestCount += 1;
    } else {
      this._estimatedCostUsd +=
        (promptTokens / 1_000_000) * rates.input + (completionTokens / 1_000_000) * rates.output;
    }

    this._updateDisplay();
  }

  reset(): void {
    this._promptTokens = 0;
    this._completionTokens = 0;
    this._requestCount = 0;
    this._unpricedRequestCount = 0;
    this._estimatedCostUsd = 0;
    this._updateDisplay();
  }

  private _updateDisplay(): void {
    if (this._requestCount === 0) {
      this._statusBarItem.hide();
      return;
    }

    this._statusBarItem.text = `$(pulse) Tokens: ${formatTokenCount(this.totalTokens)}`;
    this._statusBarItem.tooltip =
      `AGI Workforce -- Session Token Usage\n` +
      `Measured this session, across every model used.\n\n` +
      `Input: ${formatTokenCount(this._promptTokens)}\n` +
      `Output: ${formatTokenCount(this._completionTokens)}\n` +
      `Total: ${formatTokenCount(this.totalTokens)}\n` +
      `Turns: ${this._requestCount}\n` +
      `Est. cost: ${costLabel(this)}\n\n` +
      `Click for detailed breakdown`;
    this._statusBarItem.show();
  }

  dispose(): void {
    this._statusBarItem.dispose();
  }
}

function formatTokenCount(count: number): string {
  if (count < 1_000) return String(count);
  if (count < 1_000_000) return `${(count / 1_000).toFixed(1)}k`;
  return `${(count / 1_000_000).toFixed(2)}M`;
}

let _instance: TokenCounter | undefined;

export function getTokenCounter(): TokenCounter {
  if (_instance === undefined) {
    _instance = new TokenCounter();
  }
  return _instance;
}

export function activateTokenCounter(context: vscode.ExtensionContext): void {
  const counter = getTokenCounter();
  context.subscriptions.push(counter);

  context.subscriptions.push(
    vscode.commands.registerCommand('agi-workforce.resetTokenCounter', () => {
      counter.reset();
      vscode.window.showInformationMessage('AGI Workforce: Token counter reset.');
    }),
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('agi-workforce.showTokenBreakdown', async () => {
      if (counter.requestCount === 0) {
        vscode.window.showInformationMessage(
          'AGI Workforce: No measured token usage yet this session.',
        );
        return;
      }

      const items: vscode.QuickPickItem[] = [
        {
          label: `$(arrow-up) Input Tokens`,
          description: formatTokenCount(counter.promptTokens),
          detail: 'Tokens sent to the model (prompts, context, system messages)',
        },
        {
          label: `$(arrow-down) Output Tokens`,
          description: formatTokenCount(counter.completionTokens),
          detail: 'Tokens generated by the model (completions)',
        },
        {
          label: `$(graph) Total Tokens`,
          description: formatTokenCount(counter.totalTokens),
          detail: 'Combined input + output usage this session, across every model used',
        },
        {
          label: `$(credit-card) Estimated Cost`,
          description: costLabel(counter),
          detail: 'Published rates applied to measured tokens — not an invoice or provider bill',
        },
        {
          label: `$(request-changes) Turns`,
          description: `${counter.requestCount}`,
          detail: 'Completed turns that reported measured token usage',
        },
        { label: '', kind: vscode.QuickPickItemKind.Separator },
        {
          label: '$(trash) Reset Counter',
          description: 'Clear all session metrics',
        },
      ];

      const picked = await vscode.window.showQuickPick(items, {
        title: 'AGI Workforce -- Token Usage Breakdown',
        placeHolder: 'Session token usage details',
      });

      if (picked?.label.includes('Reset Counter')) {
        counter.reset();
        vscode.window.showInformationMessage('AGI Workforce: Token counter reset.');
      }
    }),
  );
}

function costLabel(counter: TokenCounter): string {
  if (counter.unpricedRequestCount === counter.requestCount) return 'no published rate';
  const amount = `$${counter.estimatedCostUsd.toFixed(4)}`;
  return counter.unpricedRequestCount === 0
    ? amount
    : `${amount} (excludes ${counter.unpricedRequestCount} turn(s) with no published rate)`;
}
